### ISSUE TITLE
--appId / --appIdSuffix options no longer working in React Native 0.62.0-rc.3

### ISSUE THREAD

**Issue by mjmasn** [react-native-community/cli#1028]
## Environment

```
System:
    OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 874.14 MB / 15.51 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.11.1 - ~/.nvm/versions/node/v12.11.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom_64
  npmPackages:
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.0-rc.3 => 0.62.0-rc.3 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Description

After upgrading to react-native@0.62-rc.3, the --appIdSuffix option no longer works (and prevents `react-native run-android` from working). Removing the option causes the Play Store version of the app to open, not the local debug version.

The command I'm running is: `react-native run-android --appIdSuffix=debug`

Weirdly looking at the code it looks like support was removed then reverted, but for some reason no longer works, see: https://github.com/react-native-community/cli/commit/d74bd88f52faa5e4c74e8cd307df8a57e3b08c09.

## Reproducible Demo

Run these commands:
```
npx react-native init CliIssue --version=0.62.0-rc.3
cd CliIssue
npx react-native run-android --appIdSuffix=debug
```
=>
```
error: unknown option `--appIdSuffix'
```

**Comment by mjmasn** [comment]
I think ca4a0aeb788ad7e85b9ca5d54001004ddacf4b0b needs to be reverted :+1:

**Comment by thymikee** [comment]
cc @grabbou isn't this something that should be done on `next` instead of `4.x`?

**Comment by grabbou** [comment]
Yes, we should also revert this commit. We have reverted the underlying commit introducing `--flavor`, so we need these options back.

I am going to spend some time on clearing this up. 

@thymikee, this change is what made `4.x` in first place. Rather than that, all the changes are backwards compatible.

**Comment by thymikee** [comment]
Should be fixed by https://github.com/react-native-community/cli/commit/a70064bfbe8837bbd114e4ea492b1a9df026af0b

**Comment by mjmasn** [comment]
Thanks both! :)
