### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by Esemesek** [react-native-community/cli#103]
Create `cli` documentation. Official `react-native` docs don't provider enough information about all commands, functionalities and examples.

**Comment by Kielan** [comment]
We need a website, i hope I can be the one to find time to make the react-native-cli docs ^^ that would be cool, or someone else.

**Comment by cito125** [comment]
I agree, docs would be super useful.

**Comment by morenoh149** [comment]
Are you open to using GitHub pages? At least add installation instruction in the readme. How do you install this?
