### ISSUE TITLE
"Cannot read property 'find' of undefined" with command unlink (iOS dependency)

### ISSUE THREAD

**Issue by psam44** [react-native-community/cli#1030]
## Environment

System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
    Memory: 1.62 GB / 7.93 GB
  Binaries:
    Node: 12.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.7 - C:\Users\Patrick\AppData\Roaming\npm\npm.CMD
    Watchman: 4.9.0 - C:\WINDOWS\watchman.EXE
  SDKs:
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 28
      Build Tools: 23.0.1, 23.0.3, 24.0.2, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 27.0.3, 28.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  npmPackages:
    react: ^16.9.0 => 16.9.0
    react-native: ^0.61.5 => 0.61.5

## Description

I try to unlink a package (doesn't matter which one).

>npx react-native unlink react-native-screens
info Unlinking "react-native-screens" iOS dependency
error Something went wrong while unlinking. Reason Cannot read property 'find' of undefined. Run CLI with --verbose flag for more details.
TypeError: Cannot read property 'find' of undefined
    at removeFromProjectReferences (D:\<snip>\node_modules\@react-native-community\cli-platform-ios\build\link\removeFromProjectReferences.js:30:53)
    at removeProjectFromProject (D:\<snip>\node_modules\@react-native-community\cli-platform-ios\build\link\removeProjectFromProject.js:45:63)
    at unregisterNativeModule (D:\<snip>\node_modules\@react-native-community\cli-platform-ios\build\link\unregisterNativeModule.js:99:54)
    at Object.unregisterNativeModule [as unregister] (D:\<snip>\node_modules\@react-native-community\cli-platform-ios\build\link\common\unregisterNativeModule.js:42:41)
    at D:\<snip>\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\unlink.js:65:16
    at Array.forEach (<anonymous>)
    at unlinkDependency (D:\<snip>\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\unlink.js:41:32)
    at Object.unlink [as func] (D:\<snip>\node_modules\react-native\node_modules\@react-native-community\cli\build\commands\link\unlink.js:110:5)
    at Command.handleAction (D:\<snip>\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:182:23)
    at Command.listener (D:\<snip>\node_modules\commander\index.js:315:8)

The problem is in removeFromProjectReferences.js :
... = firstProject.projectReferences.find(...

My project.pbxproj doesn't have any projectReferences in PBXProject section.
Neither in https://github.com/react-native-community/rn-diff-purge/blob/release/0.61.5/RnDiffApp/ios/RnDiffApp.xcodeproj/project.pbxproj

I suppose the absence of this attribute is valid and should be supported.

**Comment by thymikee** [comment]
Unlink (and alike) is deprecated and won't be patched anymore. It will soon be removed. Please rely on [autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) instead.

**Comment by psam44** [comment]
Precisely, on the way to autolinking, I followed instructions in https://github.com/react-native-community/cli/blob/master/docs/autolinking.md:
"If you have been using React Native before version 0.60, please unlink native dependencies if you have any from a previous install."

My project was 0.59.10, with some linked packages. If the unlink command was supposed to be run *before* the RN upgrade, it should be stated clearly.

**Comment by thymikee** [comment]
> If the unlink command was supposed to be run before the RN upgrade, it should be stated clearly.

It shouldn't matter really. Linking/unlinking is known to be error prone and fragile, that's why we're dropping it. I'd advise unlinking manually through native tooling like Xcode and Android Studio.

**Comment by psam44** [comment]
A dirty hack to workaround the issue:
- impose "return null;" in removeFromProjectReferences.js
- impose "return;" in removeFromPbxReferenceProxySection.js

Finally, the expected result:
```
>npx react-native unlink react-native-screens
info Unlinking "react-native-screens" iOS dependency
info iOS module "react-native-screens" has been successfully unlinked
info Unlinking "react-native-screens" Android dependency
info Android module "react-native-screens" has been successfully unlinked
```

**Comment by thymikee** [comment]
@psam44 feel free to create a diff one would need to apply, e.g. using `patch-package` project, as it would also store information about the version of the CLI used :)
