### ISSUE TITLE
Support renaming android/ios folders within a React Native project

### ISSUE THREAD

**Issue by dpux** [react-native-community/cli#1034]
## Describe the Feature
Currently` run-android` and `run-ios` commands are looking for 'android' and 'ios' folders in the project folder. There are no options to override these folder names, which is helpful when integrating with existing projects. The existing options of `root` and `appFolder` do not solve this problem.
[Relevant source for android](https://github.com/react-native-community/cli/blob/a70064bfbe8837bbd114e4ea492b1a9df026af0b/packages/platform-android/src/commands/runAndroid/index.ts#L131)

## Possible Implementations
Add a new option to override the hardcoded 'android' and 'ios' folder names in runAndroid and runiOS scripts.

**Comment by thymikee** [comment]
There is sourceDir for Android https://github.com/react-native-community/cli/blob/master/docs/projects.md#project-1
iOS is searched based on grepping for xcode project or workspace

**Comment by dpux** [comment]
@thymikee Perhaps I am misunderstanding the role of each:
1. `--root` from run-android
2. `--appFolder` from run-android
3. `sourceDir` from cli/projects
I assumed `root` should be the top level folder which holds android/ios sub-folders. `sourceDir` is relative to `root` and can be used to override default folder name such as android. `appFolder` is for specifying the main app module in case of multi-modular android projects.

But `sourceDir` seems to work only after `android` folder has been resolved. Unless I change the folder name to `android`, none of the `sourceDir` values work.
