### ISSUE TITLE
version parameter on init command not treated as semver correctly

### ISSUE THREAD

**Issue by acoates-ms** [react-native-community/cli#1039]
## Environment

I am on a windows box, but in this case that seems unlikely to affect things.

## Description

Steps:
`npx react-native init myproj --version ^0.60.0`

The package.json created has a dependency:
`"react-native": "0.60.0"`

I would expect the package.json to have a version dependency of ^0.60.0, and hopefully to have 0.60.6 installed.

According to this, the --version parameter should accept a semver:
https://github.com/react-native-community/cli/blob/master/docs/commands.md#--version-string

## Reproducible Demo
Just run:
`npx react-native init myproj --version ^0.60.0`

**Comment by thymikee** [comment]
I think that's a reasonable thing to do. We use version to fetch a specific version of the react-native template, which has all the versions hardcoded. We could add a behavior to modify the resulting package.json.

cc @Esemesek

**Comment by grabbou** [comment]
Labelling this as a feature request.

**Comment by acoates-ms** [comment]
`npx react-native init myproj --template react-native@^0.60.0` is a good work around.

**Comment by thymikee** [comment]
Now that I think about it, how about killing `--version` and leaving it forever with a deprecation notice to use `--template` instead? We should strive for simplicity and clearly `--version` brings confusion because of previous init implementation, where a lot of stuff was undocumented

**Comment by Esemesek** [comment]
`npx @react-native-community/cli init XD --version ^0.60.0` seems to work just fine on my machine.

But I agree with @thymikee , we should drop `--version` flag since `--template` gives us much more flexibility in terms of what we can do.
