### ISSUE TITLE
[Umbrella] Refactor and standardise error handling 

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#1062]
We have `CLIError` that we use in most of the places and global try/catch that prints the error message or stack trace (when in `debug` mode).

Some places use `Error` directly and log error message themselves, which is a bit confusing (e.g. `installPods`).

We should unify error handling and consider refactoring `CLIError` so that it doesn't inline messages. I think that the fact we inline multiline error messages (that are nice and verbose) into a single string makes them harder to read.

Opening this issue as an umbrella, let's do a proper investigation of places that need to be cleaned up and update this text.

**Comment by Esemesek** [comment]
I think we can close this issue in favor of https://github.com/react-native-community/cli/issues/1101.
