### ISSUE TITLE
`npx react-native init AwesomeProject` not working

### ISSUE THREAD

**Issue by peterp** [react-native-community/cli#1063]
```bash
➜ npx react-native init AwesomeProject2

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn once, write anywhere

✔ Downloading template
✖ Copying template
error Error: Couldn't find the "/var/folders/w5/bsw5vt490q78cyx2_h42ldtw0000gn/T/rncli-init-template-nzsCCY/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template
```

I'm on Mac OS and don't have the `react-native` cli installed globally.

**Comment by thymikee** [comment]
Maybe it's something with permissions? We've seen a few users having similar issues and reasons were varying. We can't really reproduce it ourselves. If you could debug this (clone this repo and follow CONTRIBUTING.md instructions), we'd be thankful for your help

**Comment by peterp** [comment]
Running `sudo npx react-native init AwesomeProject2` made it work. The download too way longer than before, so I'm guessing that it could not stream the download into the destination correctly.

**Comment by thymikee** [comment]
Awesome, that's something! I suspect we swallow an important error, which should surface earlier. Also, ideas why you would need sudo to make it work? Do you have Node.js installed globally (with sudo) and not as a user?

**Comment by peterp** [comment]
I can't really think of a reason why this would fail, most `npx`/ `yarn create` scripts don't.

```bash
~/Personal/cli (master)
➜ which node
/usr/local/bin/node

~/Personal/cli (master)
➜ ll /usr/local/bin/node
lrwxr-xr-x  1 peterp  admin    30B Feb 24 14:19 /usr/local/bin/node -> ../Cellar/node/13.8.0/bin/node

```

**Comment by peterp** [comment]
It appears to have something to do with both yarn and npm not wanting to run in the `os.tmpdir()`,

as an example:

```bash
➜ pwd
/var/folders/w5/bsw5vt490q78cyx2_h42ldtw0000gn/T/x

/var/folders/w5/bsw5vt490q78cyx2_h42ldtw0000gn/T/x
➜ ll .
total 0
drwxr-xr-x     2 peterp  staff    64B Mar 19 15:55 .
drwx------@ 3838 peterp  staff   120K Mar 19 16:11 ..

/var/folders/w5/bsw5vt490q78cyx2_h42ldtw0000gn/T/x
➜ yarn add react-native@latest
yarn add v1.22.0
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-native > metro-react-native-babel-transformer@0.56.4" has unmet peer dependency "@babel/core@*".
warning " > react-native@0.61.5" has unmet peer dependency "react@16.9.0".
[4/4] 🔨  Building fresh packages...

warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ react-native@0.61.5
info All dependencies
└─ react-native@0.61.5
✨  Done in 1.90s.

/var/folders/w5/bsw5vt490q78cyx2_h42ldtw0000gn/T/x
➜ ll .
total 0
drwxr-xr-x     2 peterp  staff    64B Mar 19 15:55 .
drwx------@ 3838 peterp  staff   120K Mar 19 16:11 ..
```

Bone dry!

**Comment by thymikee** [comment]
Um, but did you create a package.json? And a directory inside $TMP? 
What if you try:
```
mkdir rncli-tmp
cd rncli-tmp
yarn init -y
yarn add react-native
ls -al
```
This succeeds on my end and creates 
```
drwxr-xr-x    5 thymikee  x     160 Mar 19 16:39 .
drwx------@ 275 thymikee  x    8800 Mar 19 16:39 ..
drwxr-xr-x  467 thymikee  x   14944 Mar 19 16:39 node_modules
-rw-r--r--    1 thymikee  x     145 Mar 19 16:39 package.json
-rw-r--r--    1 thymikee  x  204778 Mar 19 16:39 yarn.lock
```

**Comment by peterp** [comment]
I'm tracing the commands that react-native's cli executes, I did not create a package.json, since the cli doesn't do that and I created a directory within the same temporary folder that the cli uses.

https://github.com/react-native-community/cli/blob/4dbfc7751aee90c5e9c78286b3825796a4d332ab/packages/cli/src/commands/init/init.ts#L100

**Comment by thymikee** [comment]
Yea, CLI doesn't "create" a package.json, it's copied over from the template

**Comment by peterp** [comment]
The step I'm referencing is run before the `package.json` is copied. The package.json is copied afterward `yarn add react-native@latest`

I believe that `yarn init -y` needs to be run before running `yarn add`

Would you want to jump on a call, or something, so that I can show you?

**Comment by peterp** [comment]
The line that is failing is the step that creates the template. The step that creates the template runs: `yarn add react-native@latest`

**Comment by thymikee** [comment]
On my end it `yarn add` works with or without package.json in a temporary directory. Does it work in any case for you, without sudo? 

I can see that you have the same permissions set on tmp dir as mine, so that seems fine.

Another thing that comes to my mind is that this call
https://github.com/react-native-community/cli/blob/4dbfc7751aee90c5e9c78286b3825796a4d332ab/packages/cli/src/commands/init/init.ts#L92-L94
creates a directory with permissions that prevent you from installing. But even so, Yarn would throw EACCES then. Let me know if you find out more about it

**Comment by peterp** [comment]
> On my end it yarn add works with or without package.json in a temporary directory. Does it work in any case for you, without sudo?

It works in other directories, just not in the temporary directory.

https://github.com/react-native-community/cli/blob/4dbfc7751aee90c5e9c78286b3825796a4d332ab/packages/cli/src/commands/init/init.ts#L92-L94

This line creates the directory with the correct permissions, running `yarn add` does not work in a temporary directory created by the cli, or manually created by myself.

**Comment by peterp** [comment]
Steps that do work in the temporary folders is to run `yarn init -y` before running `yarn add react-native`

**Comment by thymikee** [comment]
> Steps that do work in the temporary folders is to run `yarn init -y` before running `yarn add react-native`

Cc @Esemesek. I think we could do init, just need to figure out something that works with yarn and npm :)

**Comment by mdgilene** [comment]
So is there a temporary workaround here? Can this be avoided by just using a different version of the cli?

**Comment by wtrocki** [comment]
Basically I got similar issues when using npm. This depends on how node.js is installed. When using NVM it is using the home directory to cache npx stuff. With system installation I got into the same problem as above. As my target was to design workshops I always tell people to install yarn as there are numerous issues that are related to the way that packages are installed with npm that introduce strange errors while for yarn all things work.

I guess if npm is supported it will be cool to add some integration test to CI process to see if the project is created successfully for each PR

**Comment by wtrocki** [comment]
The alternative is to follow NPM create-x to get templates. This is very common and I found some people trying to do it without checking if that is actually supported. 

https://github.com/react-native-community/cli/issues/343

**Comment by wtrocki** [comment]
To add also I found people doing also trying `npx react-native-cli create`

**Comment by thymikee** [comment]
I honestly have no idea where people get these from. Official docs are clear:

https://reactnative.dev/docs/environment-setup:
![image](https://user-images.githubusercontent.com/5106466/77574537-74ccfc80-6ed2-11ea-92fd-8edfe2ca9a70.png)

**Comment by wtrocki** [comment]
Since I already have been using cli extensively I have tested it on mac:

`npx react-native init AwesomeProject`
MacOS Catalina
Nvm versions:
```
lts/dubnium -> v10.19.0 
lts/erbium -> v12.16.1
```

In all cases finished successfully:
```
Downloading template
✔ Copying template
✔ Processing template
✔ Installing CocoaPods dependencies (this may take a few minutes)

  Run instructions for iOS:
    • cd "/Users/wtrocki/Projects/sync/offix/examples/react-native/MyApp" && npx react-native run-ios
    - or -
    • Open MyApp/ios/MyApp.xcworkspace in Xcode or run "xed -b ios"
    • Hit the Run button

  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/wtrocki/Projects/sync/offix/examples/react-native/MyApp" && npx react-native run-android
```

**Comment by victorwpbastos** [comment]
In Windows 10 doesn't work.

![image](https://user-images.githubusercontent.com/1017515/77783587-e4103100-7037-11ea-957c-e35a81557b30.png)

**Comment by thymikee** [comment]
@victorwpbastos Does it work with `sudo`?

**Comment by victorwpbastos** [comment]
> @victorwpbastos Does it work with `sudo`?

I'm on a Windows 10 machine. I don't have `sudo`. I did try with Powershell in administrator mode but it doesn't work either.

**Comment by thymikee** [comment]
Right, made a shortcut, sorry about that. Can I ask you to try debugging it? There's an instruction in CONTRIBUTING.md on how to use the CLI locally. You could comment out this line:
https://github.com/react-native-community/cli/blob/d21c21ee133e2b03489414051cccf84d6d470003/packages/cli/src/commands/init/init.ts#L137
`cd` into this tmp directory and see what's there, why is there no `template.config.js` in `node_modules/react-native`

**Comment by victorwpbastos** [comment]
The folder is empty:

![image](https://user-images.githubusercontent.com/1017515/77786626-e32dce00-703c-11ea-8503-625e5ad28287.png)

**Comment by thymikee** [comment]
What happens if you run `yarn add react-native` there? Or `npm install --save react-native`? Does it work? If not, does it work if you run `yarn init -y` / create package.json first? Maybe you run into the same issue as https://github.com/react-native-community/cli/issues/1063#issuecomment-601320363 ?

**Comment by victorwpbastos** [comment]
`yarn add react-native` did nothing. But `yarn init -y` and `yarn add react-native` works.

**Comment by thymikee** [comment]
Then we need to run `yarn init -y`/`npm init -y` prior that. Do you fancy contribute this change and make a PR? 🙂

**Comment by victorwpbastos** [comment]
Done. PR #1077. It's my first PR to this project! I'm very happy to contribute.

**Comment by badarshahzad** [comment]
Well in my case it was not working today with all latest version of npm and node. I uninstalled the node and npm. Then I install the nvm and using nvm I install node. After this I use `npx react-native init MyApp` it works.

**Comment by cyphire** [comment]
I found a great work around for this frustrating and soul crushing problem with initializing for react-native.

I'm a windows user (of course the documentation is Mac centric another problem which keeps so many windows users frustrated with the complex react-native learning curve).

I do have both Yarn and NPM and didn't want to start the terrible consequences of removing one or both and reinstalling.  THIS IS A PROBLEM WITH THE TEMP DIRECTORIES!!! (As stated above).

I edited my windows environment variables for my self as the user....

TEMP = C:\Users\bcanin01\tmp  was changed to TEMP = d:\tmp  (make sure to create the directory!)
TMP was changed to d:\temp2.

ran npx react-native init Test99

and.... FOR THE FIRST TIME EVER I was able to create a react-native project without an hour of manual labor and headaches!!!

THIS WORKS!  Just change your temp directories, it affects nothing (that I can see) and worked.

p.s. don't know if it was important (probably not) but when i opened my command shell in windows make sure to open it with admin permissions...

**Comment by thymikee** [comment]
@cyphire So the problem seems is with lack of permissions, I don't think we can do anything about it. Maybe throw a better error if we have enough information?

**Comment by cyphire** [comment]
That make sense, but instead of using the temp directories, couldn't
react-native init create temp directories in the newly created directory
and then just erase them??? Maybe take the environment out of the picture?
_________________________________________
Brian B. Canin    brian.canin@gmail.com

858-945-5601 (cell)

**Comment by thymikee** [comment]
Worth exploring that path

**Comment by marshetamare** [comment]
all answers are not working

**Comment by chenweigh** [comment]
chen@chen ~ % npx react-native init AwesomeProject

Need to install the following packages:
  react-native
Ok to proceed? (y) y
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/chen/.npm/_npx/7930a8670f922cdb/node_modules/react-native
npm ERR! dest /Users/chen/.npm/_npx/7930a8670f922cdb/node_modules/.react-native-JAoXw5Fv
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/chen/.npm/_npx/7930a8670f922cdb/node_modules/react-native' -> '/Users/chen/.npm/_npx/7930a8670f922cdb/node_modules/.react-native-JAoXw5Fv'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chen/.npm/_logs/2022-01-26T10_18_02_465Z-debug.log

----

How to fix ?

**Comment by deantek** [comment]
I installed android studio, prepared the environment, the queue came before the project was initialized, the following error occurs:

`alfagenesis@alfagenesis-MS-7817:/opt/lampp/htdocs/react-Native$ npx react-native init AwesomeTSProject --template react-native-template-typescript
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'to-fast-properties'
Require stack:
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/definitions/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/validators/validate.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/builders/validateNode.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/builders/generated/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/utils/react/cleanJSXElementLiteralChild.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/builders/react/buildChildren.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/template/lib/formatters.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/template/lib/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/Bundler/util.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/Assets.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/Server.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/shared/output/bundle.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/bundle.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js
- /home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/definitions/index.js:68:25)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/definitions/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/validators/validate.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/builders/validateNode.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/builders/generated/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/utils/react/cleanJSXElementLiteralChild.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/builders/react/buildChildren.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/types/lib/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/template/lib/formatters.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@babel/template/lib/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/Bundler/util.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/Assets.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/Server.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/metro/src/shared/output/bundle.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/buildBundle.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/bundle.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/bundle/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/commands/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli-plugin-metro/build/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/commands/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/index.js',
    '/home/alfagenesis/.npm/_npx/7930a8670f922cdb/node_modules/@react-native-community/cli/build/bin.js'
  ]
}`

i have already updated node, npm to latest version, even installed 'to-fast-properties' via npm, nothing helps, how can i make it work?

**Comment by SufianBabri** [comment]
I was receiving the following error when running `npx react-native init SocialMediaDownloader --template react-native-template-typescript`:
```
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/sufian/.npm/_npx/7930a8670f922cdb/node_modules/babel-plugin-polyfill-regenerator
npm ERR! dest /Users/sufian/.npm/_npx/7930a8670f922cdb/node_modules/.babel-plugin-polyfill-regenerator-1PdlkCQk
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/sufian/.npm/_npx/7930a8670f922cdb/node_modules/babel-plugin-polyfill-regenerator' -> '/Users/sufian/.npm/_npx/7930a8670f922cdb/node_modules/.babel-plugin-polyfill-regenerator-1PdlkCQk'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sufian/.npm/_logs/2022-10-04T14_18_11_578Z-debug-0.log
```

Replacing `npx react-native` with `npx react-native@latest` solved it for me.

**Comment by abdallahshaban557** [comment]
That fixed the problem for me as well @SufianBabri !
