### ISSUE TITLE
npx react-native run-android never finish

### ISSUE THREAD

**Issue by paulequilibrio** [react-native-community/cli#1066]
## Environment
```
System:
    OS: Linux 5.5 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
    Memory: 133.47 MB / 7.64 GB
    Shell: 3.1.0 - /usr/bin/fish
  Binaries:
    Node: 13.11.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.3 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

## Description
This problem is the same related here: https://github.com/facebook/react-native/issues/26097

<img src="https://user-images.githubusercontent.com/23743072/63273612-ae6ec280-c274-11e9-91fe-ebe2f728441c.png" />

It seems that the solution was already suggested here: https://github.com/facebook/react-native/issues/26097#issuecomment-575859723

## Reproducible Demo

1. Start a new project with `npx react-native init Project`
2. Enter the directory `cd Project`
3. Try the command `npx react-native run-android`

**Comment by thymikee** [comment]
JS server may open in another Terminal tab and it may take a while for Metro to finish. Does it work if you run `start` manually before `run-android`?

**Comment by paulequilibrio** [comment]
@thymikee, yes in that case works.

**Comment by Esemesek** [comment]
It seems like we were not using the correct terminal program. Last year we replaced the default `TERM` with `TERM_PROGRAM` which is specific to OSX. It caused to open the `metro` in the current terminal without any visible output. Gonna create a PR soon.

**Comment by thymikee** [comment]
Closed via #1099

**Comment by ShivamJoker** [comment]
Hey I am still facing this issue it not launching or building the app please help. I in mac os

**Comment by Esemesek** [comment]
@ShivamJoker fix is available in the latest version of the CLI. If you use `linux` make sure to have `TERM` env variable exported correctly.

**Comment by Esemesek** [comment]
On `OSX`, similar to `linux`, you need to have `TERM_PROGRAM` variable exported.
