### ISSUE TITLE
Could not create reasonml React native app.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [react-native-community/cli#1074]
## The problem
` npx @react-native-community/cli init --template @reason-react-native/template 
`

## How to reproduce
Steps to reproduce:

1.` npx @react-native-community/cli init --template @reason-react-native/template App`
## Expected behavior
An app with reasonml has to be generated.

## Actual behavior
Error

```
npm ERR! Unexpected end of JSON input while parsing near '...694+ZW1QWXWVftSGVTjim'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/a-c-sreedhar-reddy/.npm/_logs/2020-03-26T15_36_21_099Z-debug.log
Install for @react-native-community/cli@latest failed with code 1
```

**Comment by a-c-sreedhar-reddy** [comment]
https://github.com/reason-react-native/reason-react-native/issues/651

**Comment by thymikee** [comment]
Please don't duplicate issues. It belongs to `reason-react-native` for now. If they can point out there's a bug in the CLI, then feel free to open a new issue with the findings

**Comment by MoOx** [comment]
This is totally not helping.

First look say that some JSON was broken. Can be network issue etc.

https://github.com/reason-react-native/reason-react-native/issues/651#issuecomment-604507214
