### ISSUE TITLE
Error: Cannot find module @react-native-community/cli/build/index.js

### ISSUE THREAD

**Issue by Fausto95** [react-native-community/cli#1076]
## Environment
MacOS Catalina

## Description

Cannot find module @react-native-community/cli/build/index.js

This happens when I try to run `react-native start`

## Reproducible Demo

Just bootstrap a new RN project and I'm getting this error.
I checked my `node_modules/@ @react-native-community/cli/` folder and there is no build folder

**Comment by thymikee** [comment]
Sounds like an issue with the package manager you use. Likely nothing we can do about, since it's environmental. Please try once again
