### ISSUE TITLE
Wrong paths for android ProjectConfig

### ISSUE THREAD

**Issue by yoerivdm** [react-native-community/cli#1083]
## Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 16.34 GB / 31.95 GB
  Binaries:
    Node: 13.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Python: 2.7.17 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.0 => 0.62.0
  npmGlobalPackages:
    *react-native*: Not Found

## Description
react-native link not working because of wrong paths for project.android.stringsPath and mainFilePath

See [ReactNative issue report](https://github.com/facebook/react-native/issues/28426) for additional info.

## Reproducible Demo
Create new project (RN0.62) and link a library

**Comment by thymikee** [comment]
Likely fixed by https://github.com/react-native-community/cli/pull/1080. Can you verify?

**Comment by yoerivdm** [comment]
Looks good ... kind of misleading variable name: appName in the pull request.
I wasn't sure but after looking into the getAppName function it looks ok, it should return 'app' in most cases :-).

Thanks!

**Comment by thymikee** [comment]
Published v4.5 with a fix
