### ISSUE TITLE
How should I modify the project entry file

### ISSUE THREAD

**Issue by Elderkly** [react-native-community/cli#1089]
![image](https://user-images.githubusercontent.com/32736776/78221044-35676700-74f5-11ea-92d1-b418797e77e6.png)

I moved the index.js file to the src directory and caused the error.

```
error: bundling failed: src/index.js: Cannot find module '/Users/admin/Desktop/Git/pigletrn/Piglet/babel.config.js' from '/Users/admin/Desktop/Git/pigletrn/Piglet'
```

**Comment by Esemesek** [comment]
Your project setup is faulty and won't work. Configuration files like: `react-native.config.js`, `tsconfig.json`, `metro.config.js`, `babel.config.js` etc should be in the same directory as `package.json` and `node_modules`.
