### ISSUE TITLE
Manual links showing up as errors despite being commented out

### ISSUE THREAD

**Issue by personjerry** [react-native-community/cli#1091]
## Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz
    Memory: 19.83 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.60.0
```

## Description

Despite being commented out, any `include`/`project` or `implementation` in `settings.gradle` or `build.gradle` will trigger complaints about being manually linked. `react-native unlink` does not do anything about it (and fails silently!).

## Reproducible Demo

1. Add this to a RN android app you're working on in `android/settings.gradle` (yes it's a comment):

```
// include ':react-native-camera'
// project(':react-native-camera').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-camera/android')
```

2. `react-native run-android` (it might be that you actually need to have the manually linked package as a dependency in your `package.json`, I haven't tested it, but the problem isn't exclusive to `react-native-camera` I'm just using it as an example)

3. Observe this in the log:
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-camera (to unlink run: "react-native unlink react-native-camera")
```

**Comment by thymikee** [comment]
The error comes from legacy `link` logic, which will be removed in next release major release, hence the error will be gone. Commenting out won't work, because legacy `link` doesn't parse Gradle scripts, but uses regular expressions to find matching strings. Closing.
