### ISSUE TITLE
Split the `download` and `yarn install` part when `init`-ing.

### ISSUE THREAD

**Issue by pvinis** [react-native-community/cli#1092]
Running `npx @react-native-community/cli init Bla`, the loader stays on `Downloading template` for a long long time, and then skips to `Copying template`. I think we should split this and update the loader text to `Downloading template`, `Running <package manager> install`, then `Copying template` etc. At least that way there is a bit more feedback on what's happening, especially when yarn takes a while to install.

**Comment by Esemesek** [comment]
`Downloading` step is just installing the template into `tmp` directory. I don't think we can split it in any additional way. I think it might have been improved in the latest version tho. https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/init/template.ts#L17-L35
cc. @thymikee

**Comment by thymikee** [comment]
Would changing the test to `Downloading and installing template` help here? We could also run yarn with `--json` flag to get information about progress and display it somehow. Not sure how npm handles that though. Seems like a fun feature to add to our PackageManager :)

**Comment by Esemesek** [comment]
@thymikee What about `npm`? Is there any way to inherit the progress from `npm` subprocess?

**Comment by pvinis** [comment]
Changing the text would be fine, but I think some progress would be even better!

**Comment by jamesgeorge007** [comment]
I assume you're looking forward to see a spinner showing up prior to this process over here: https://github.com/react-native-community/cli/blob/cbcdf20d704fe4624e003e472d0134c28e354c1c/packages/cli/src/commands/init/init.ts#L99
