### ISSUE TITLE
[!] Invalid `Podfile` file: 785: unexpected token at ''.

### ISSUE THREAD

**Issue by mfazekas** [react-native-community/cli#1094]
## Environment
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Memory: 1.24 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /Users/boga/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 28.0.3
      System Images: android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-Q | Intel x86 Atom_64, android-Q | Google APIs Intel x86 Atom_64, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 11.4/11E146 - /usr/bin/xcodebuild
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

We have a library `react-native-mapbox-gl` inside the library we have a react native example.
See: https://github.com/react-native-mapbox-gl/maps

If I upgrade the example to RN 0.62.1 then pod install will fail.

The problem seems to be because the parent directory of the example is the library and it has an older RN installed where '@react-native-community/cli' is accessible. When [cocopods tries to calculate the path](https://github.com/react-native-community/cli/blob/master/packages/platform-ios/native_modules.rb#L19-L20) it uses the following expression: 
```sh
node -e "try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}"
```
But since parent has `@react-native-community/cli` the first part will not railse an exception, but will just return undefined.

This seems to be caused by the fact that node `require` does search in parent directories node_modules as well.

https://nodejs.org/api/modules.html#modules_all_together

## Reproducible Demo

```sh
mkdir -p library
cd library
npm init -y

react-native init example
edit package.json  # add those to package.json
  "peerDependencies": {
    "react": "^16.6.1",
    "react-native": ">=0.59.9"
  },
  "devDependencies": {
    "react-native": "0.59.10"
  },

npm install
cd example
rm -rf node_modules ; yarn.lock
npm install
cd ios
pod install
```

```sh
/Users/boga/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/executable.rb:93: warning: Insecure world writable dir /usr/local/Cellar in PATH, mode 040777
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/private/tmp/rn-cli-issue-demo/library/example/ios/undefined'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[!] Invalid `Podfile` file: 785: unexpected token at ''.

 #  from /private/tmp/rn-cli-issue-demo/library/example/ios/Podfile:62
 #  -------------------------------------------
 #  
 >    use_native_modules!
 #  
 #  -------------------------------------------
```

**Comment by Esemesek** [comment]
It is not working due to `CLI`'s compatibility with different versions of react-native. Please look up the compatibility table: https://github.com/react-native-community/cli#compatibility

**Comment by mfazekas** [comment]
@Esemesek thanks, would you be open for a PR improving developer experience here?!

My understanding is that unlike node, RN module resolver does not look into parent's `node_modules` so far we haven't seen any issue if the library itself had different RN constraints than the example app.

It takes a bit of digging to figure out that now cocoapods calls node. And since node searches upwards, it's an issue if the library in parent folder has different RN installed in it's node_modules than the example app.

**Comment by Esemesek** [comment]
@mfazekas good idea. Created a new issue for that.

**Comment by fabellonnoe** [comment]
delete yarn.lock
then run yarn
