### ISSUE TITLE
react-native init should have a folder option in addition to the current ProjectName one

### ISSUE THREAD

**Issue by zabojad** [react-native-community/cli#110]
As written in the title, a `folder` option would be very welcome. It should allow to give a different location to the default one it currently uses.

We should be able to do:
```console
foo@bar:~$ react-native init AwesomeProject .
```
or 
```console
foo@bar:~$ react-native init AwesomeProject awesome05
```

**Comment by thymikee** [comment]
I think that makes sense

**Comment by thymikee** [comment]
@zabojad ping, would you like to take a stab at it? :) We've rewritten `init` to be a local command, so it's way easier to test now.

**Comment by lucasbento** [comment]
Is anyone working on this? If not I would like to do it.

**Comment by garretteklof** [comment]
Is there a manual workaround for this? If I init a react-native project with an app name, then change the folder name (not app name) it will no longer build. I'm guessing there a few other things I need to change in some configs. The name of my folder can differ from the name of the app itself, correct? Any help would be greatly appreciated.

**Comment by lucasbento** [comment]
@garretteklof: changing just the folder should work fine, if you have a unix-like OS just do `mv MyProject my-new-project-folder` and that should be it.

**Comment by garretteklof** [comment]
Yeah every time I do that (just change the folder name, or `mv`) it won't build.
<img width="773" alt="Screen Shot 2019-05-16 at 9 06 42 AM" src="https://user-images.githubusercontent.com/4140229/57860165-f4ba0e80-77b9-11e9-9715-3d115d9a4626.png">

**Comment by thymikee** [comment]
@garretteklof this issue and @lucasbento response is about chaning the _root_ directory of your React Native project, not the Xcode or Android project name. Please mind the difference. The later is not supported automatically.

**Comment by garretteklof** [comment]
@thymikee I'm aware. I definitely just want to change the root folder (I know there's a separate process for the project name). For me, what worked was deleting the `ios/build` folder, and then re-running `react-native run-ios`. Without doing that, build errors like the one I pasted above kept occurring. Hopefully this is of some help to someone. Thanks.

**Comment by garretteklof** [comment]
@thymikee I'm aware. I definitely just wanted to change the root folder (I know there's a separate process for the project name). Apologies if I didn't spell that out well enough. For me, what worked was deleting the `ios/build` folder, and then re-running `react-native run-ios`. Without doing that, various build errors like the one I pasted above kept occurring. Hopefully this is of some help to someone. Thanks for the responses!
