### ISSUE TITLE
Doctor: showing download progress

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/cli#1108]
## Describe the Feature

Doctor is able to download some missing tools like JDK automatically. it would be great if it can showing the downloading progress. (like 100MB/176MB)

so we can know how much time left to complete the download task .

## Possible Implementations
-

## Related Issues
I can't find any issue related to this feature request. is it needed to create one myself?

**update**: it seems there is one related issue #976 according to @molant's [comment](https://github.com/react-native-community/cli/issues/1108#issuecomment-612186082)

**Comment by molant** [comment]
As a related issue you can probably point to #976 where I mentioned having a progress bar for that 😊

**Comment by SaeedZhiany** [comment]
@molant 

It's done
