### ISSUE TITLE
Check CocoaPods version in doctor

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/cli#1112]
## Describe the Feature

Currently we are only checking if CocoaPods is installed, it would be useful to check the version.

As seem in react-native-community/upgrade-support#20 there may be errors tied to a CocoaPods version which can possibly be fixed by having a minimum supported version.

## Possible Implementations

Check that CocoaPods is installed and has a version `>= 1.9.1` somewhere around [here](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/doctor/healthchecks/cocoaPods.ts#L17), [Node.js health check](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/doctor/healthchecks/nodeJS.ts) can be used as a reference on how to implement this.

**Comment by molant** [comment]
`envinfo` seems to look for the CocoaPods version if [I'm reading this correctly](https://github.com/tabrindle/envinfo/blob/26c5e528acec4548f131bfea8ae7ff3374eface2/src/helpers/managers.js#L22).
We could update [`versionRanges.ts`](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/doctor/versionRanges.ts) with the version you are proposing and [`cocoaPods.ts` as you proposed](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/doctor/healthchecks/cocoaPods.ts#L17) with something like the following (this is based on the Python check so some changes might be needed):

```ts
 getDiagnostics: async ({Managers}) => ({
    needsToBeFixed: doesSoftwareNeedToBeFixed({
      version:
        typeof Managers.CocoaPods === 'string'
          ? Managers.CocoaPods
          : Managers.CocoaPods.version,
      versionRange: versionRanges.COCOAPODS,
    }),

    version:
      typeof Managers.CocoaPods === 'string'
        ? Managers.CocoaPods
        : Managers.CocoaPods.version,
    versionRange: versionRanges.COCOAPODS,
  }),
```

What do you think?

**Comment by lucasbento** [comment]
Yep, that seems to be it!

We already have CocoaPods [listed here](https://github.com/react-native-community/cli/blob/6c72d03bbc8aab3d5735634c5f92e73ddec4d2c1/packages/cli/src/tools/envinfo.ts#L24) so it's just a matter of putting a few pieces together 🙂
