### ISSUE TITLE
Flags to skip launching the emulator for `run-android`

### ISSUE THREAD

**Issue by peteroid** [react-native-community/cli#1128]
## Describe the Feature
In the current version, an emulator will be launched when we run `react-native run-android ...` and there is no way to skip launching it.

In my project, the use case of `run-android` is to run different gradle tasks like the following which doesn't need the emulator at all.
```
$ react-native run-android --tasks clean,assembleRelease,uploadRelease
```

However, the emulator will be launched for every run of `run-android` and I have to close it again and again.

This is actually a dilemma that we can definitely use the original gradle cli. In this case, we need to run the `jetifier` on our own and this is not the optimal scenario.

## Possible Implementations
Support a new flag, e.g. `--no-emulator` and add a condition at https://github.com/react-native-community/cli/blob/a5d837543dad8b3f40b4d2449963542e5d3abefe/packages/platform-android/src/commands/runAndroid/runOnAllDevices.ts#L39

## Related Issues
n/a

**Comment by thymikee** [comment]
Fair call. We already have an ongoing effort to add the `--emulator` flag here: https://github.com/react-native-community/cli/issues/1038. We could first introduce the `--no-emulator` though.

**Comment by jayu** [comment]
In my opinion, `run-android` should be used for running the app, so the emulator is needed there. If you want to execute other Gradle tasks you should write the additional script. Using `run-android` to execute some scripts does not look like a good practice.

`Jetifier `is not a big deal, you can run `npx jetify` right before Gradle script. Or you can run `jetifier` on `post-install` as mentioned in it's [readme in point 5.](https://github.com/mikehardy/jetifier#to-jetify--convert-node_modules-dependencies-to-androidx)

**Comment by thymikee** [comment]
@jayu I'd disagree. Why do we require users to "write the additional script" when we could provide a command to do so? It's a shortcoming of the CLI that we don't provide proper commands for building. This problem was briefly discussed here: #179. 

What I think we need is having `build-android` and `build-ios` that share their backend with `run-*` commands, but without starting Metro instance and booting up a simulator. We also need the `--mode` flag mentioned in #179.

**Comment by mauscoelho** [comment]
This can also help some CI like Bitrise, today when you run with the purpose of generating an apk you will get an error
```
$ react-native run-android --variant=release
```

```
Execution failed for task ':app:installRelease'.
> com.android.builder.testing.api.DeviceException: No connected devices!
```

We could avoid it using
```
$ react-native build-android --variant=release
```

**Comment by rbarman** [comment]
If anyone has an android device plugged in, you can run `npx react-native run-android --active-arch-only` to skip the emulator step.

**Comment by cortinico** [comment]
> If anyone has an android device plugged in

That's a workaround. The solution to this issue can't be just "plug an android device".

> What I think we need is having `build-android` and `build-ios` that share their backend with `run-*` commands, but without starting Metro instance and booting up a simulator. We also need the `--mode` flag mentioned in #179.

+1 for this approach
