### ISSUE TITLE
Migrate to kleur

### ISSUE THREAD

**Issue by jamesgeorge007** [react-native-community/cli#1135]
## Describe the Feature
[kleur](https://github.com/lukeed/kleur) is a lightweight alternative to [chalk](https://github.com/chalk/chalk) with a comparable API.

## Possible Implementations
Refactor the codebase to onboard `kleur` for colored prompts.

## Related Issues
N/A

**Comment by thymikee** [comment]
`chalk` is battle-tested, widely used and comes with decent performance, while being only 20kB bigger. Install size is of course larger, but our deps co-depend on the biggest one, being `ansi-styles`. Sorry, but I don't see a point in this change, it's better to use this time and resources on fixing actual bugs.
