### ISSUE TITLE
skip dependencies install in init

### ISSUE THREAD

**Issue by FedericoMorrone** [react-native-community/cli#1142]
When running react-native init all the dependencies are automatically installed, is it possible to skip the install step and just create the project where I can later manually install the dependencies?

**Comment by thymikee** [comment]
No, it's not currently possible. You can however stop the process (Ctrl + C) and still end up with working setup, just not installed. Is this sufficient to close? We would like to avoid adding extra flags, unless they provide a good DX improvement affecting more than 1 special use case if possible.

**Comment by FedericoMorrone** [comment]
Stopping the process doesn't help me, what I'm trying to achieve is the ability to create multiple react-native projects just by running command (without any human interaction) but obviously I  don't want to install the dependencies for each one of them unless I'm using it or they'll end up using multiple Gb of space.

**Comment by thymikee** [comment]
Yup doesn't seem too much of a hassle. Wanna tackle it? :)
