### ISSUE TITLE
Add command to regenerate android and ios folders

### ISSUE THREAD

**Issue by morr0ne** [react-native-community/cli#1144]
## Describe the Feature

Right now it's not possible to regenerate missing android and ios folders in an already existing project.
Right now the workaround is this but it's creating another project with the same name and settings and copying over the folders, this is clearly not ideal
I suggest adding a generate command which has the job to generate those folders 

## Possible Implementations

This new command could use the same method of the init command (copying the template and replacing what's necessary) but just copying over those folders.
It should also accept two options:

-  --project-name which should default to the folder name
- --template which should default to the default template

Since all this functionally is already present in the init command another possible implementation would be a --regenerate flag for the init command that copies just the missing folders

This command could also be used by "doctor" to fix the missing folders

## Related Issues

https://github.com/react-native-community/cli/issues/808#issuecomment-543207588

**Comment by thymikee** [comment]
This will most likely come back in a way better form in 2023 as a part of our DX improvements around upgrading experience in React Native. Stay tuned. For now, it's ok to keep this closed.
