### ISSUE TITLE
platforms.android.appName not working

### ISSUE THREAD

**Issue by stephan-wolf-ais** [react-native-community/cli#1154]
## Environment

info Fetching system and libraries information...
System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 63.35 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 27.0.2, 27.0.3, 28.0.0, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom_64
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_131 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: ^0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
## Description

We are using the same code for different applicationId's. As of the parameter --appId is working but deprecated we want to switch to react-native.config.js.

When we implement the property paltforms.android.appName as suggested from the deprecation warning the cli ant never start and does not recognised the folder as a react-native project. Using the --verbose parameter the cli gives the following error message. This is the case in every cli call and not special for run-android

$ react-native info --verbose
debug Unknown option platforms.android.appName with value ""com.app.Name"" was found. This is either a typing error or a user mistake. Fixing it will remove this message.
debug Failed to load configuration of your project. Only a subset of commands will be available.
error Unrecognized command "info".
info Run "react-native --help" to see a list of all available commands.

## Reproducible Demo

we use the following react-native.config.js

module.exports = {
  assets: ["./app/theme/fonts/"],
  platforms: {
    android: {
        appName: "com.app.Name"
    }
  }
}

**Comment by thymikee** [comment]
It should be `projects.android.appName`:
```js
module.exports = {
  assets: ["./app/theme/fonts/"],
  project: {
    android: {
      appName: "com.app.Name"
    }
  }
}
```
Can you try it once again? :)

**Comment by stephan-wolf-ais** [comment]
The error message is gone but the property is ignored and it seems that the applicationId is taken from the package name.

**Comment by thymikee** [comment]
We failed at documenting this beetter. Here's what `appName` does:

> A name of the app in the Android `sourceDir`, equivalent to Gradle project name. By default it's `app`. 

What you're looking for is `--appIdSuffix` flag:

> Specify an `applicationIdSuffix` to launch after build.

So in the case you provided it should be enough to run `run-android --appIdSuffix Name`

**Comment by stephan-wolf-ais** [comment]
Ok. but than the appName is a equivalent for the --appFolder parameter.

And of course We dont need an applicationidsuffix. We require to set the whole applicationId so for now the deprecation for --appId is wrong. there is no other way to set the applicationId to launch.

Regards,
Stephan

**Comment by thymikee** [comment]
The `applicationId` should be inferred from the `sourceDir` and `appName` (e.g. default `android/app/**/AndroidManifest.xml`, you don't need any flag for it. 
Can you point me to a minimal repro and describe what exactly are you trying to achieve please, so we can understand your use case better?

**Comment by stephan-wolf-ais** [comment]
The applicationId is defined in build.gradle as described here [https://developer.android.com/studio/build/application-id](url). AndroidManifest.xml contains the package name which is not the applicationId.

At the moment we got it to work setting the application display name and applicationId/product bundle identifier from environment variables during the build process. The last point is the launch on developer machines on different platforms. 

From my point of view the right way is to create a new option project.android.appId and everything is fine or remove the deprecation from `--appId` because the parameter itself works.

I will setup a test repo.

**Comment by thymikee** [comment]
Thanks! It makes sense to rethink some stuff we do. Until then we'll remove the deprecation.
