### ISSUE TITLE
Template option in format username/repo

### ISSUE THREAD

**Issue by victorwpbastos** [react-native-community/cli#1163]
## Describe the Feature
Init command doesn't accept github repo as  `--template` argument, nnly npm packages and local folders. Would be great to pass a repo as argument:

```sh
npx react-native init AwesomeProject --template username/repo
```

## Possible Implementations
??

## Related Issues
??

**Comment by thymikee** [comment]
`--template` supports anything that Yarn/npm does, so you can pass a whole github address, like `https://github.com/facebook/react-native`

**Comment by victorwpbastos** [comment]
yarn/npm supports the syntax `username/repo`, RN CLI doesn't.

**Comment by thymikee** [comment]
Then let's implement it :)
