### ISSUE TITLE
Init command doesn't work with yarn dlx

### ISSUE THREAD

**Issue by morr0ne** [react-native-community/cli#1169]
## Description

Trying to run init command with new yarn dlx commands fails

## Reproducible Demo

Create a new folder and install yarn v2
```bash
mkdir project && cd project && yarn set version berry
```
Try creating a new react-native project using yarn dlx

```bash
yarn dlx react-native init app
```
This fails because setup_env.sh can't be found and the temp folder for the template is not generated

Here is the full output of running the command with verbose flag on

<details>
  <summary>Terminal output</summary>
federico@federico-X510UQR:~/Documents/projects/rcli-tst$ yarn dlx react-native init app --verbose

➤ YN0000: ┌ Resolution step
➤ YN0032: │ nan@npm:2.14.1: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ root-workspace-0b6124@workspace:. doesn't provide react@16.11.0 requested by react-native@npm:0.62.2
➤ YN0000: └ Completed in 5.95s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.66s
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:2.6.11 must be built because it never did before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=495457 must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 5.61s
➤ YN0000: Done with warnings in 12.32s

warn Failed to run environment setup script "setup_env.sh"

Error: spawnSync /tmp/xfs-03eca821/dlx-5586/.yarn/$$virtual/@react-native-community-cli-virtual-d0de6136d1/4/home/federico/.yarn/berry/cache/@react-native-community-cli-npm-4.8.0-405aac3c2d-3.zip/node_modules/@react-native-community/cli/setup_env.sh ENOENT                                                                                                                              
info React Native CLI will continue to run if your local environment matches what React Native expects. If it does fail, check out "/tmp/xfs-03eca821/dlx-5586/.yarn/$$virtual/@react-native-community-cli-virtual-d0de6136d1/4/home/federico/.yarn/berry/cache/@react-native-community-cli-npm-4.8.0-405aac3c2d-3.zip/node_modules/@react-native-community/cli/setup_env.sh" and adjust your environment to match it.
debug We couldn't find a package.json in your project. Are you sure you are running it inside a React Native project?
debug Failed to load configuration of your project. Only a subset of commands will be available.
debug Initializing new project

                ######                ######               
              ###     ####        ####     ###             
             ##          ###    ###          ##            
             ##             ####             ##            
             ##             ####             ##            
             ##           ##    ##           ##            
             ##         ###      ###         ##            
              ##  ########################  ##             
           ######    ###            ###    ######          
       ###     ##    ##              ##    ##     ###      
    ###         ## ###      ####      ### ##         ###   
   ##           ####      ########      ####           ##  
  ##             ###     ##########     ###             ## 
   ##           ####      ########      ####           ##  
    ###         ## ###      ####      ### ##         ###   
       ###     ##    ##              ##    ##     ###      
           ######    ###            ###    ######          
              ##  ########################  ##             
             ##         ###      ###         ##            
             ##           ##    ##           ##            
             ##             ####             ##            
             ##             ####             ##            
             ##          ###    ###          ##            
              ###     ####        ####     ###             
                ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

debug Installing template from react-native@latest
{
  name: 'rncli-init-template-vAgdFr'
}
➤ YN0000: ┌ Resolution step
➤ YN0032: │ nan@npm:2.14.1: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ rncli-init-template-vAgdFr@workspace:. doesn't provide react@16.11.0 requested by react-native@npm:0.62.2
➤ YN0000: └ Completed in 6.61s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yallist@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:11.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:15.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:12.0.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:14.2.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 2.85s
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:2.6.11 must be built because it never did before or the last one failed
➤ YN0007: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=495457 must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 9.46s
➤ YN0000: Done with warnings in 19.05s
debug Getting config from /tmp/rncli-init-template-vAgdFr/node_modules/react-native/template.config.js
error Error: Couldn't find the "/tmp/rncli-init-template-vAgdFr/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

</details>

**Comment by thymikee** [comment]
Help in fixing that appreciated :)

**Comment by itfarrier** [comment]
The same problem with the `yarn dlx react-native start`, `yarn dlx react-native link`, `yarn dlx react-native run` etc.

**Comment by TMisiukiewicz** [comment]
@thymikee is there  any update in CLI on using v2 of yarn?

**Comment by adamTrz** [comment]
@TMisiukiewicz can confirm issue is valid

**Comment by TMisiukiewicz** [comment]
> The same problem with the `yarn dlx react-native start`, `yarn dlx react-native link`, `yarn dlx react-native run` etc.

When using yarn berry, adding this line to `.yarnrc.yml`  should do the trick:
```
nodeLinker: node-modules
```

**Comment by adamTrz** [comment]
Hi @itfarrier @morr0ne  - could you please try the solution proposed by @TMisiukiewicz ? 
Closing the issue for now but more than happy to reopen if proposed solution fails 🙂

**Comment by eurobob** [comment]
@adamTrz the proposed solution is not working for me
