### ISSUE TITLE
Work closely with Expo for better CLI

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#117]
This is an umbrella issue. Opening so that we can track all the tasks. 

## Description:

Expo CLI is great. It's stable, consistent and fast. There's a lot of things we could learn from it. Expo itself is also known for many great and important contributions to the React Native ecosystem. Expo team reached out to us and offered their help in boosting React Native CLI experience. 

Over the past few weeks we have been thinking about the areas where we could worked together. We have came to a conclusion that we should identify common areas of functionality and work towards sharing as much of them as possible.

The plan can be divided into two parts:
- Creating a "@react-native-community/cli-tools" utility package. It should contain some of the code that is already present in "xdl" package that is not Expo-specific and can be useful for both CLIs
- Providing a programatic API to some of the existing React Native CLI functionalities, so that other tools can work on top of it. For example, Expo starts "react-native start" and has to parse "stdout" in order to provide feedback to its users. This should not be needed

Sharing utilities with Expo has a lot of benefits, such as:
- Expo users use React Native CLI once they eject from Expo. It makes a lot of sense to ensure same quality across the CLIs to make the experience for the developers as pleasant as possible
- Expo already solved a lot of UX issues we are struggling right now with, such as being able to spawn an iOS simulator and check the project for being correct at the same time. It doesn't make sense to re-invent the logic in React Native CLI by writing the same code once again
- Our teams can work together on the same set of tools. The tools can be actually useful for authors of other tools, such as Ignite

## Issues

To be filled in soon.

**Comment by fson** [comment]
> Creating a "@react-native-community/cli-tools" utility package. It should contain some of the code that is already present in "xdl" package that is not Expo-specific and can be useful for both CLIs

I would go a bit further in splitting out the functionality: we have a monorepo with Expo CLI related packages at https://github.com/expo/expo-cli/tree/master/packages. I think it would make sense to create smaller packages like `open-simulator` or `react-native-doctor` in this monorepo.

Creating small, focused packages makes it easier to decide what should go in it, both projects can mix and match them as necessary, and if they're still in the same repo as before, there's very little overhead (in terms of versioning etc) compared to having the functionality in xdl.
