### ISSUE TITLE
How can i make a debug build that does not use metro?

### ISSUE THREAD

**Issue by patchthecode** [react-native-community/cli#1191]
## Ask your Question

Hi, we need to run debug builds on simulators for automation testing purposes.
However, it looks like metro is always needed to load the source code correctly for each build we run. For production apps however, this is not an issue because all the source is bundled within the production build.

How can we get a debug build (which runs in simulators) to have all the source code bundled so that, just like a production build, it will not need metro to run?

**Comment by SConaway** [comment]
For which platform? 

For android, just use the debug variant. So, for example, I use `cd android && rm -rf 'app/build/' && ./gradlew bundleDebug` to create a debug app bundle.

For iOS, you can set the `FORCE_BUNDLING` to true to force the JS to be bundled. So just prefix it to the command you're running, like this: `FORCE_BUNDLING=true yarn run:ios` to deploy to the default simulator.

**Comment by patchthecode** [comment]
thank you
