### ISSUE TITLE
pod install failure with glog

### ISSUE THREAD

**Issue by genk1** [react-native-community/cli#1194]
## Ask your Question

I have been trying to start with `npx react-native init AwesomeProject` but having failure with glog.
Is there any way to overcome this problems??

### What I have tried

1. `sudo xcode-select --switch /Applications/Xcode.app`
2. uninstall and install xcode, cocoapods
3. re-creating new projects

is there any solution ??

```ios $pod install
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.62.2)
Installing FBReactNativeSpec (0.62.2)
Installing Flipper (0.33.1)
Installing Flipper-DoubleConversion (1.1.7)
Installing Flipper-Folly (2.2.0)
Installing Flipper-Glog (0.3.6)
[!] /bin/bash -c
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h
/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif
/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif
/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk
checking whether the C compiler works... no
/Users/genkiamagata/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing: Unknown `--is-lightweight' option
Try `/Users/genkiamagata/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/genkiamagata/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by thymikee** [comment]
This is not a CLI issue. Please report this in main React Native repo.

**Comment by genk1** [comment]
@thymikee https://github.com/facebook/react-native/issues/29101
Thanks I post it there :)

**Comment by smecnarowski** [comment]
what helped me:
`sudo xcode-select --switch /Applications/Xcode.app`

**Comment by ayushag99** [comment]
@smecnarowski your suggested solution worked for me. 
Thanks.

**Comment by ntgnst** [comment]
sudo xcode-select --switch /Applications/Xcode.app

it didn't work for me.. Still fails after Flipper-Glog

`Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Downloading dependencies
Installing CocoaAsyncSocket (7.6.4)
Installing CocoaLibEvent (1.0.0)
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.63.4)
Installing FBReactNativeSpec (0.63.4)
Installing Flipper (0.54.0)
Installing Flipper-DoubleConversion (1.1.7)
Installing Flipper-Folly (2.3.0)
Installing Flipper-Glog (0.3.6)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h
/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif
/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif
/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

/bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory`

**Comment by cbnsndwch** [comment]
> what helped me:
> `sudo xcode-select --switch /Applications/Xcode.app`

For anyone coming from Google and banging their heads (and for future-me 😉):

 I tried this and many other similar solutions and they didn't work for me. Then I restarted my Mac (unchecked re-open windows), ran pod install, and it worked.

**Comment by lancejpollard** [comment]
@cbnsndwch for a second I thought your solution was working for me, but alas, restarting my computer didn't help :/

**Comment by humodev** [comment]
@smecnarowski you solution worked for me thanks!!

**Comment by akshaykrsharma** [comment]
Hello @genk1 , 

Just follow the screenshots and select Xcode. 



<img width="455" alt="Screenshot 2021-03-23 at 6 34 15 PM" src="https://user-images.githubusercontent.com/4579085/112150821-8987c180-8c06-11eb-99a0-ad2dd3d226a5.png">
<img width="834" alt="Screenshot 2021-03-23 at 6 34 42 PM" src="https://user-images.githubusercontent.com/4579085/112150892-9d332800-8c06-11eb-8e9e-8f0248af3899.png">

**Comment by genk1** [comment]
Thanks!! Will try it!!

**Comment by revfanc** [comment]
> llow the screenshots an

thanks,work for me!

**Comment by hugouraga** [comment]
> what helped me:
> `sudo xcode-select --switch /Applications/Xcode.app`

Thanks!

**Comment by cybersasi** [comment]
> what helped me:
> `sudo xcode-select --switch /Applications/Xcode.app`

Thanks it works

**Comment by alexanderblackh** [comment]
For those who find this with issues on MacOS Monterrey developer beta, do `sudo xcode-select --switch /Applications/Xcode-beta.app`and then restart the computer. This worked for me.

**Comment by BayraaKaspersky** [comment]
> what helped me:
> `sudo xcode-select --switch /Applications/Xcode.app`

Thanks

**Comment by MuhammadAbdullah54321** [comment]
> what helped me:
> `sudo xcode-select --switch /Applications/Xcode.app`

this helped me

**Comment by kymani20100** [comment]
none of the above solutions seem to be working for me. Any other suggestion guys?

**Comment by fighter520** [comment]
> sudo xcode-select --switch /Applications/Xcode.app
> 
> it didn't work for me.. Still fails after Flipper-Glog
> 
> Analyzing dependencies
> Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
> Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
> Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
> Downloading dependencies
> Installing CocoaAsyncSocket (7.6.4)
> Installing CocoaLibEvent (1.0.0)
> Installing DoubleConversion (1.1.6)
> Installing FBLazyVector (0.63.4)
> Installing FBReactNativeSpec (0.63.4)
> Installing Flipper (0.54.0)
> Installing Flipper-DoubleConversion (1.1.7)
> Installing Flipper-Folly (2.3.0)
> Installing Flipper-Glog (0.3.6)
> [!] /bin/bash -c
> set -e
> #!/bin/bash
> 
> # Copyright (c) Facebook, Inc. and its affiliates.
> # This source code is licensed under the MIT license found in the
> # LICENSE file in the root directory of this source tree.
> set -e
> 
> PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
> CURRENT_ARCH="${CURRENT_ARCH}"
> 
> if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
> # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
> # it's better to rely on platform name as fallback because architecture differs between simulator and device
> 
> ```
> if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
>     CURRENT_ARCH="x86_64"
> else
>     CURRENT_ARCH="armv7"
> fi
> ```
> 
> fi
> 
> export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
> export CXX="$CC"
> 
> # Remove automake symlink if it exists
> if [ -h "test-driver" ]; then
> rm test-driver
> fi
> 
> ./configure --host arm-apple-darwin
> 
> # Fix build for tvOS
> cat << EOF >> src/config.h
> /* Add in so we have Apple Target Conditionals _/ #ifdef **APPLE** #include <TargetConditionals.h> #include <Availability.h> #endif /_ Special configuration for AppleTVOS _/ #if TARGET_OS_TV #undef HAVE_SYSCALL_H #undef HAVE_SYS_SYSCALL_H #undef OS_MACOSX #endif /_ Special configuration for ucontext */
> #undef HAVE_UCONTEXT_H
> #undef PC_FROM_UCONTEXT
> #if defined(**x86_64**)
> #define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
> #elif defined(**i386**)
> #define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
> #endif
> EOF
> 
> # Prepare exported header include
> EXPORTED_INCLUDE_DIR="exported/glog"
> mkdir -p exported/glog
> cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
> cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
> cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
> cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
> cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"
> 
> /bin/bash: ./configure: /bin/sh^M: bad interpreter: No such file or directory

git config --global core.autocrlf false 
fix this bug
see https://github.com/facebook/react-native/issues/29101

**Comment by victorcbr** [comment]
for me work removing ios/Pods ios/Podfile.lock and reinstall with npx pod-install on root project.

**Comment by ctoxyz** [comment]
FAILS - npx pod-install

RETURNS - see below

Installing Flipper-Glog (0.3.6)
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h
/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif
/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif
/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.2.sdk
checking whether the C compiler works... no
/Users/n8Dog/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing: Unknown `--is-lightweight' option
Try `/Users/n8Dog/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/Users/n8Dog/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6':
configure: error: C compiler cannot create executables
See `config.log' for more details


Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: Command `pod install` failed.
└─ Cause: pod exited with non-zero code: 1
    at CocoaPodsPackageManager._installAsync (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:92213)
    at async CocoaPodsPackageManager.installAsync (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90176)
    at async runAsync (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106198)
    at async /Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106284 {
  code: 'COMMAND_FAILED',
  cause: Error: pod exited with non-zero code: 1
      at ChildProcess.h (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:1073)
      at Object.onceWrapper (node:events:510:26)
      at ChildProcess.emit (node:events:390:28)
      at maybeClose (node:internal/child_process:1062:16)
      at Socket.<anonymous> (node:internal/child_process:448:11)
      at Socket.emit (node:events:390:28)
      at Pipe.<anonymous> (node:net:687:12)
      ...
      at Object.spawnAsync [as default] (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:558)
      at CocoaPodsPackageManager._runAsync (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:92995)
      at CocoaPodsPackageManager._installAsync (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90499)
      at CocoaPodsPackageManager.installAsync (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:90187)
      at runAsync (/Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106206)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /Users/n8Dog/.npm/_npx/7cf525d1e16b4e35/node_modules/pod-install/build/index.js:2:106284 {
    pid: 83640,
    output: [ '', '' ],
    stdout: '',
    stderr: '',
    status: 1,
    signal: null
  },
  isPackageManagerError: true
}

**Comment by dhruvasagar** [comment]
For me the root of the problem was having `coreutils`, `moreutils` and `gnu-sed` installed and set up to override mac osx counter parts.

**Comment by uciadonis** [comment]
> what helped me:
> `sudo xcode-select --switch /Applications/Xcode.app`

Thanks a lot

**Comment by jrhe** [comment]
None of the above worked for me. Crossposting as this potential fix has not been mentioned yet.

For me the issue was that I had set `LDFLAGS` and `CPPFLAGS` in my `~/.zshrc` following installation of `llvm` by homebrew. Unsetting them / uncommenting them and then re-running the install command fixed the issue.

More details here: https://github.com/facebook/react-native/issues/32291

**Comment by orchetect** [comment]
In case it helps anyone:

I was getting the same errors as OP. Turns out the glog script wasn't using escaping paths when testing "checking whether the C compiler works" and I had renamed my `Xcode.app` to `Xcode 13.4.1.app` which contained a space character. Renaming it back to `Xcode.app` and running `xcode-select` resolved the issue and glog was able to install successfully.

**Comment by mangjuned** [comment]
this is worked for me https://github.com/facebook/react-native/issues/34443#issuecomment-1219525104

**Comment by trozdol** [comment]
> In case it helps anyone:
> 
> I was getting the same errors as OP. Turns out the glog script wasn't using escaping paths when testing "checking whether the C compiler works" and I had renamed my `Xcode.app` to `Xcode 13.4.1.app` which contained a space character. Renaming it back to `Xcode.app` and running `xcode-select` resolved the issue and glog was able to install successfully.

I found removing any white space character from the name fixed it for me.

**Comment by kyutneryan** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

Thanks !  this is worked for me

**Comment by davelsan** [comment]
> this is worked for me [facebook/react-native#34443 (comment)](https://github.com/facebook/react-native/issues/34443#issuecomment-1219525104)

I know this is an old issue, but I just wanted to emphasize the solution provided by @mangjuned, as it may be a little harder to find for others browsing this issue (and all other related threads). This was a tricky problem because I only noticed the error when re-cloning the repo and trying to install the pods from scratch. 

The issue was indeed installing Anaconda (or Miniconda in my case). Unsetting the compiler flags resolved it. I cannot thank you enough @mangjuned, I was going crazy with this.

**Comment by babarbahadur** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

Thanks! 🙏

**Comment by nscribble** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

thx!!

**Comment by torabian** [comment]
For anyone expericing this:

git config --global core.autocrlf false 

Would solve the problem.

**Comment by bxtendit** [comment]
> For anyone expericing this:
> 
> git config --global core.autocrlf false
> 
> Would solve the problem.

@torabian, thanks!
Worked perfectly.

**Comment by dagdanmo** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

Solved it for me. Thanks!

**Comment by staciax** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

Thanks <3

**Comment by macksal** [comment]
I found this error when not installing Xcode beforehand. The error could be a lot clearer... it's caused by these lines in glog.podspec:

https://github.com/facebook/react-native/blob/v0.73.2/packages/react-native/third-party-podspecs/glog.podspec#L33-L39

However, these have been removed for unrelated reasons as of https://github.com/facebook/react-native/pull/43949 so there's nothing left to do.

**Comment by divyansh432** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

Thanks , it worked for me.

**Comment by kunal-j10** [comment]
> Hello [@genk1](https://github.com/genk1) ,
> 
> Just follow the screenshots and select Xcode.
> 
> <img alt="Screenshot 2021-03-23 at 6 34 15 PM" width="455" src="https://user-images.githubusercontent.com/4579085/112150821-8987c180-8c06-11eb-99a0-ad2dd3d226a5.png">
> 
> <img alt="Screenshot 2021-03-23 at 6 34 42 PM" width="834" src="https://user-images.githubusercontent.com/4579085/112150892-9d332800-8c06-11eb-8e9e-8f0248af3899.png">

This works for me, I recently updated my Xcode and few of my projects stills points to the location where previous Xcode version was installed, and therefor getting the xcode version as empty string. So, after you select the Xcode for your project, its position gets updated and you are able to successfully install your pods.

**Comment by kjgetcarnera** [comment]
Simple solution is: 

My Xcode name is like **Xcode 2.app**

Step 1:  Remove any white space character from the name of Xcode solved the issue. **(update the name Xcode.app)**

Step 2: sudo xcode-select --switch /Applications/Xcode.app

Step 3: Restart the system

Step 4: Try below command again : 
```
a. npx create-expo-app@latest
b. npx expo start
c. npx expo prebuild
```

**Comment by kjgetcarnera** [comment]
Simple solution is: 

My Xcode name is like **Xcode 2.app**

Step 1:  Remove any white space character from the name of Xcode solved the issue. **(update the name Xcode.app)**

Step 2: sudo xcode-select --switch /Applications/Xcode.app

Step 3: Restart the system

Step 4: Try below command again : 
```
a. npx create-expo-app@latest
b. npx expo start
c. npx expo prebuild
```

**Comment by anggaip** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

worked for me. Thanks dude

**Comment by sandeepa91** [comment]
> what helped me: `sudo xcode-select --switch /Applications/Xcode.app`

Thanks!

**Comment by phallguy** [comment]
For anyone else stuck on an older version of Xcode....make sure there are no spaces in the path. I had to rename it to 'Xcode-16.2'

**Comment by managementsucks** [comment]
> For anyone else stuck on an older version of Xcode....make sure there are no spaces in the path. I had to rename it to 'Xcode-16.2'

This did it for me. Thank you!

**Comment by developerdesigner18** [comment]
I have tried the above all the verified solution but its got the same error.

Please someone help me with the solve this error.

Project:

react native version : 0.63.3
node version : 14

glob version which shows 0.3.5

**Comment by MohammadKanaan** [comment]
> Hello [@genk1](https://github.com/genk1) ,
> 
> Just follow the screenshots and select Xcode.
> 
> <img alt="Screenshot 2021-03-23 at 6 34 15 PM" width="455" src="https://user-images.githubusercontent.com/4579085/112150821-8987c180-8c06-11eb-99a0-ad2dd3d226a5.png">
> 
> <img alt="Screenshot 2021-03-23 at 6 34 42 PM" width="834" src="https://user-images.githubusercontent.com/4579085/112150892-9d332800-8c06-11eb-8e9e-8f0248af3899.png">

This works! Thanks!

**Comment by MaxSandulsky** [comment]
I encountered the same error message as OP while installing pods for project with outdated dependencies and built for different architecture.
`CURRENT_ARCH=arm64 pod install --repo-update`
This allowed me to install pods correctly.

**Comment by parthkanani93** [comment]
If you still getting issue non of solution worked then try this i solved by using this solution for my M2 Macbook

Try this solution on Stackoverflow :- https://stackoverflow.com/a/79766838/11264971
