### ISSUE TITLE
Autolinking assets without pods

### ISSUE THREAD

**Issue by maxkomarychev** [react-native-community/cli#1206]
Hi, 

I am working on a package whose sole sole purpose is to provide some fonts. I have created `react-native.config.js` in the package but native projects are not modified unless I do `react-native link <packagename>`.

Considering the fact that `react-native link` will soon be removed what's the right way to do this kind of stuff?

Only thing that comes to my mind so far is to provide empty navite code so that pods/gradle code can link it up (haven't tried that yet though).

Is there a better way?

Thanks.

**Comment by thymikee** [comment]
We need a story around linking assets without changing native code. Reopening

**Comment by rborn** [comment]
I'm exactly in this position right now, thanks for reopening

**Comment by finnp** [comment]
Any ideas how this would work?

**Comment by szymonrybczak** [comment]
Autolinking assets was implemented with new [`link-assets`](https://github.com/react-native-community/cli/pull/2276) command! 🙌
