### ISSUE TITLE
unable to remove react-native-cli

### ISSUE THREAD

**Issue by xgqfrms** [react-native-community/cli#1210]
# Question

> how to remove react-native-cli?

## not work at all

```sh

# yarn global remove
$ yarn global remove react-native-cli

```

![](https://user-images.githubusercontent.com/7291672/86080180-d948ba80-bac4-11ea-9aff-add54e96ad5d.png)

**Comment by thymikee** [comment]
You may still have it installed with npm, so you can run `npm uninstall -g react-native-cli`. Run `which react-native-cli` to see if it's installed anywhere else and act accordingly. Closing, because this is not related to the development of the CLI.
