### ISSUE TITLE
Autolinker for specific build variant

### ISSUE THREAD

**Issue by b3coded** [react-native-community/cli#1211]
## Ask your Question

Is it possible to use Autolinker for a specific dependency only in some build variant (eg. Debug)?

**Comment by thymikee** [comment]
It's only possible on iOS through Podfile, but as far as I can tell that's not easily doable on Android.

**Comment by b3coded** [comment]
@thymikee I'm not sure if it will be a problem but we can make this line optional, so autolinker will not add the devDependencies on Release build
