### ISSUE TITLE
"Open developer menu" command doesn't work from the terminal for iOS and RNW

### ISSUE THREAD

**Issue by RedMickey** [react-native-community/cli#1213]
## Environment

- MacOS:
System:
    OS: macOS 10.15.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 1.11 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 25, 27, 28, 29
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 27.0.3, 28.0.3, 29.0.0, 29.0.1
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

- Windows
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 7.62 GB / 15.94 GB
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6241897
  Languages:
    Java: 1.8.0_212-release - C:\Program Files\Android\Android Studio\jre\bin\javac.EXE
    Python: 3.7.6 - C:\Python37\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: ^0.62.0-0 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
## Description
Please see [the original issue](https://github.com/facebook/flipper/issues/1309).

I created a plain React Native v0.62.2 project.
I tried to open dev menu on an iOS simulator from the terminal by pressing "d", but it didn't open. At the same time the `Reload` command works fine.

![image](https://user-images.githubusercontent.com/33267199/86346293-6296f300-bc65-11ea-8cb9-04c086981cb5.png)

I also faced the same problem on a [React Native Windows](https://github.com/microsoft/react-native-windows) application.
It seems that "Open developer menu" command works incorrectly from the terminal.

**Comment by RedMickey** [comment]
Hi, are there any updates on this?

**Comment by alpha0010** [comment]
Definitely annoying.  My workaround for iOS was to use AssistiveTouch to put a button on screen that triggers the shake gesture.  Frequently shaking a device during development is *not* good (difficult for tablets, and damaging to cables/ports).

**Comment by EzioLi01** [comment]
This issue is still repro. Could you please help on this?

**Comment by TMisiukiewicz** [comment]
to be checked again with newer version of RN

**Comment by adamTrz** [comment]
> 

Can confirm that issue is still present

**Comment by TMisiukiewicz** [comment]
@adamTrz I tried to investigate that, but cannot find where exactly the websocket messages are received - do you have any knowledge about it? Reloading the app works as excepted

**Comment by adamTrz** [comment]
Well, the message is definitely being sent here:
https://github.com/react-native-community/cli/blob/e590149a71db3253e5f118de457b31e8a130a993/packages/cli-server-api/src/websocket/createMessageSocketEndpoint.ts#L108
but then somehow it's got lost 🤷

**Comment by TMisiukiewicz** [comment]
seems to work correctly on Android 🤷 any help with discovering what's going on there is highly appreciated

**Comment by EzioLi01** [comment]
Checking it still repro on 0.71.1.

**Comment by TMisiukiewicz** [comment]
@szymonrybczak assigning you to remember closing it once your [PR](https://github.com/facebook/react-native/pull/36115) is merged. Awesome job 👏

**Comment by szymonrybczak** [comment]
Closing since it's done by https://github.com/facebook/react-native/pull/36115 😄
