### ISSUE TITLE
Error: Cannot find module @react-native-community\cli\build\bin.js

### ISSUE THREAD

**Issue by JangoCG** [react-native-community/cli#1214]
## Environment

info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 2.42 GB / 15.94 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: Not Found
    Python: 3.8.3 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: ^4.10.1 => 4.10.1
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
## Description

  When I try to run my project with react-native run-android it won't build the project and cancel with a error.

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:969  throw err;  ^Error: Cannot find module 'C:\Users\CengizGÃ¼rtusgil\dev_win\test2\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)    at Function.Module._load (internal/modules/cjs/loader.js:842:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

However that files exists for sure the folder is created and I can manually locate bin.js

## Reproducible Demo

1. Initialize my project with react-native init projectName
2. try to run my project with react-native run-android

**Comment by HaydenJayAylor** [comment]
I have encountered the same problem and nothing I try will fix it. 

`[dax@host ios]$ pod install
Installing unimodules:
 expo-app-loader-provider@8.0.0 from ../node_modules/expo-app-loader-provider/ios
 expo-constants@8.0.0 from ../node_modules/expo-constants/ios
 expo-contacts@8.2.1 from ../node_modules/expo-contacts/ios
 expo-file-system@8.0.0 from ../node_modules/expo-file-system/ios
 expo-local-authentication@8.0.0 from ../node_modules/expo-local-authentication/ios
 expo-permissions@8.0.0 from ../node_modules/expo-permissions/ios
 unimodules-barcode-scanner-interface@5.0.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
 unimodules-camera-interface@5.0.0 from ../node_modules/unimodules-camera-interface/ios
 unimodules-constants-interface@5.0.0 from ../node_modules/unimodules-constants-interface/ios
 unimodules-core@5.0.0 from ../node_modules/@unimodules/core/ios
 unimodules-face-detector-interface@5.0.0 from ../node_modules/unimodules-face-detector-interface/ios
 unimodules-file-system-interface@5.0.0 from ../node_modules/unimodules-file-system-interface/ios
 unimodules-font-interface@5.0.0 from ../node_modules/unimodules-font-interface/ios
 unimodules-image-loader-interface@5.0.0 from ../node_modules/unimodules-image-loader-interface/ios
 unimodules-permissions-interface@5.0.0 from ../node_modules/unimodules-permissions-interface/ios
 unimodules-react-native-adapter@5.0.0 from ../node_modules/@unimodules/react-native-adapter/ios
 unimodules-sensors-interface@5.0.0 from ../node_modules/unimodules-sensors-interface/ios
 unimodules-task-manager-interface@5.0.0 from ../node_modules/unimodules-task-manager-interface/ios

Debugger attached.
Waiting for the debugger to disconnect...
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/home/dax/Code/*********/<ProjectFile>/node_modules/@react-native-community/cli/build/bin.js
Debugger attached.
Waiting for the debugger to disconnect...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[!] Invalid `Podfile` file: 783: unexpected token at ''.

 #  from /home/dax/Code/*****/<ProjectFile>/ios/Podfile:73
 #  -------------------------------------------
 #    use_unimodules!
 >    use_native_modules!
 #  end
 #  -------------------------------------------`

**Comment by anthowm** [comment]
Just turn off debugger if you are running the commands in visual studio code

**Comment by IbrahimTahaSanli** [comment]
I was have same problem. in my case, reason root path was has non-ascii character(CengizG**Ã¼**rtusgil like this character). I moved my root folder from my desktop to C:\ and error gone. It's a little late but it maybe help someone else.
