### ISSUE TITLE
[!] Invalid `Podfile` file: cannot infer basepath.

### ISSUE THREAD

**Issue by atifgulzar** [react-native-community/cli#1225]
## Environment

react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Memory: 597.02 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/wison/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 28, 29
      Build Tools: 26.0.2, 28.0.3, 29.0.2, 30.0.0
      System Images: android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_101 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found

## Description

Hello Everyone
I'm new on React Native I followed the all dependencies setup describe in react native official website. 

Created new project using below commend.

 > npx react-native init AwesomeProject

Everything went just fine execpt CocoaPods dependencies installation

error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./AwesomeProject/ios && pod install".
CocoaPods documentation: https://cocoapods.org/

So when I run pod install command manually in ios directy I got this error. 

> pod install

[!] Invalid `Podfile` file: cannot infer basepath.

 #  from /Applications/XAMPP/xamppfiles/htdocs/PersonalHelpingCode/

AwesomeProject/ios/Podfile:1
 #  -------------------------------------------
 >  require_relative '../node_modules/react-native/scripts/react_native_pods'
 #  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  -------------------------------------------

## Reproducible Demo

package.json file screenshot is attached. 

![Screenshot 2020-07-19 at 12 42 33 PM](https://user-images.githubusercontent.com/572680/87869955-5c22ae00-c9bd-11ea-8439-d63ba95ec858.png)

**Comment by gwmccull** [comment]
I was getting that same error but it was due to an npm package failing to install prior to the pod install running
