### ISSUE TITLE
Auto-linking with 0.60 and custom maven url 

### ISSUE THREAD

**Issue by lucaspiressimao** [react-native-community/cli#1228]
## Ask your Question

Hi,
My lib includes a custom maven repository in build.gradle like:

repositories {
...
maven { url 'https://github.com/.../raw/master' }
}

I need to Autolink this lib and add this Maven repo to project Gradle. I already tried 
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
and 
https://github.com/react-native-community/cli/blob/master/docs/dependencies.md
I don`t  know how to configure this maven repo in react-native.config.js. Should I use this param  **platforms.android.packageImportPath** ?

I was wondering if there is a config for android like scriptPhases source from IOS.

**Comment by thymikee** [comment]
You need to include this URL in the build.gradle, there's no automating that.

**Comment by lucaspiressimao** [comment]
Tks.

**Comment by fr33z3** [comment]
@thymikee @lucaspiressimao Sorry I didn't get it. I can not ship the npm package within the custom maven repository? I need to add it in the app project repo?
