### ISSUE TITLE
How to recover IOS & Android folder in react native.?

### ISSUE THREAD

**Issue by Aftab-farooq** [react-native-community/cli#1239]
I am new to react-native I am facing an error that my IOS and Android folder are deleted by using this command (rm -rf node_modules ios android). Now I am trying to recover the IOS and Android folder by using these commands npm install--> react-native upgrade -->react-native run-ios.But no success and facing same issue error iOS project folder not found. Are you sure this is a React Native project?. Please help me.

**Comment by pedrohram** [comment]
The command `rm -rf` will forcefully delete the folder and it's contents and you're explicitly deleting both three folders. They will not be sent to the Trash Bin, but will be permanently deleted.

If there is some dependency issue, delete **only** node_modules with `rm -rf node_modules` and re-install the dependencies with `npm install`.

I recommend you read the command docs for `react-native upgrade`:
https://github.com/react-native-community/cli/blob/master/docs/commands.md#upgrade

**Comment by pedrohram** [comment]
May you please specify the output of the logs?

**Comment by pedrohram** [comment]
The command `rm -rf` will forcefully delete the folder and its contents and you're explicitly deleting both three folders. They will not be sent to the Trash Bin, but will be permanently deleted.

I'm afraid that the only way to recover the native folders is by creating a new project.

**Comment by abhinavk9757** [comment]
@Aftab-farooq You can use react-native-eject (https://www.npmjs.com/package/react-native-eject) and run it to get back the ios and android folders.
