### ISSUE TITLE
Shorter binary alias

### ISSUE THREAD

**Issue by Kjens93** [react-native-community/cli#1247]
## Describe the Feature
When I'm working quickly, typing `react-native start && react-native run-ios` takes a lot of keystrokes. It would be great if the cli package included a shorter binary alias, (i.e. `rn`), to make working with the cli just a little bit smoother. After the change, the above command would look like this: `rn start && rn run-ios` and starting a new project would look like this: `npx rn init`. I do use NPM/Yarn scripts to help with this, but even those could benefit from this improvement. I'm happy to submit a PR for this as well, but I wanted to open up the conversation here in case there was something I'm not aware of.

## Possible Implementations
```diff
diff --git packages/cli/package.json
{
  "bin": {
+   "rn": "build/bin.js",
    "react-native": "build/bin.js"
  },
}
```

**Comment by safaiyeh** [comment]
You should be able to do this locally. I feel like adding another alias might be conflicting with say another binary named "rn". "react-native" is unique and owned by here. It is up to your own dev environment to alias things.

**Comment by Kjens93** [comment]
Closing this issue because the corresponding PR was rejected by @thymikee.
