### ISSUE TITLE
Text Scroll Issue in TVOS

### ISSUE THREAD

**Issue by jasmeet447** [react-native-community/cli#1249]
Hii, I've been trying to make a scrollable text component for tvos like the one we see in terms and conditions box in a lot of applications. The code works fine for android tv but the text doesn't scroll down in tvos.
The code snippet is as follows:

<ScrollView style={
{
flex: 1,
paddingTop: getScaledValue(50)
}}
contentContainerStyle={{
alignItems: 'center',
justifyContent: 'center'
}}
removeClippedSubviews={false}

< Text style={styles.textH2} >
This is the text portion that needs to be scrolled .............

< /Text >
< /ScrollView >

Any Help will be appreciated

**Comment by thymikee** [comment]
Please report this in React Native core repository. This is a CLI it's not related to React, nor ScrollView components.
