### ISSUE TITLE
RFC: use logkitty for `log-android` command

### ISSUE THREAD

**Issue by zamotany** [react-native-community/cli#125]
## Describe the Feature

This is a proposal to use 3rd party tool for `log-android` for prettier messages and more flexible interface: https://github.com/zamotany/logkitty

![logkitty](https://user-images.githubusercontent.com/17573635/51744070-f6db4e80-209e-11e9-9c49-7fb46d2b5823.gif)

logkitty currently supports only Android (iOS in the future if requested) with better syntax for common tasks like filtering by tags (`logkitty tag myTag otherTag`, `logkitty tag myTag otherTag -W`), filtering by application (`logkitty app com.expample.myApp`, `logkitty app com.expample.myApp -E`) and custom patters (`logkitty custom *:S ReactNativeJS:D`).

Let me know what do you think. Any feedback appreciated.

## Possible Implementations

Spawn `logkitty` process when running `react-native log-android`.

**Comment by grabbou** [comment]
Given the amount of +1 on @zamotany issue, I think we can say this is a good proposal and should be implemented.

@zamotany, would you be willing to contribute this?
