### ISSUE TITLE
Template only copying the package files

### ISSUE THREAD

**Issue by ThallyssonKlein** [react-native-community/cli#1251]
Hello,

I was trying to create a react-native template to use with this CLI. I followed a tutorial that guided me to delete everything that comes by default in the projects, I did that and started a new project with the flag template pointing to the package of my template, which is here:

https://github.com/ThallyssonKlein/react-native-template-tk-email-app/packages/357150

But something strange happened. My package files were simply copied to the new project folder but nothing was created (node_modules, android folder, ios folder). This is normal? Should I include the android and ios folder in the template?

**Comment by thymikee** [comment]
Please refer to this doc: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template and see a sample custom template provided. Yes, you need to provided ios/android/whatever folders that you want to be copied.
