### ISSUE TITLE
Errors during `npx react-native init NameOfProject`

### ISSUE THREAD

**Issue by SeasonLeee** [react-native-community/cli#1256]
## Environment

no... I am following the recommendation from the official doc and you guys suggest we should use `npx react-native init` instead of install cli locally, remember????

![image](https://user-images.githubusercontent.com/13610283/91199063-f352f200-e72f-11ea-8e54-f8f946076927.png)

## Description

You can see the error from the screenshot:
![image](https://user-images.githubusercontent.com/13610283/91199182-167da180-e730-11ea-826e-18ebf7383c89.png)

Oh, I have googled the issue and I tried someone else's method, to uninstall npm and node and reinstall, yes, nothing works!!!!! GOD!!!!!! wtf???

Anyone has the same issue????

## Reproducible Demo

You try run the command yourself, yes, go!

---
fine, I am so frustrated by this RN thing, no offense and anyone is offended I apologize here, I love react.js, but react native? well, 'great too' 🙃

oh, incase any info about my device:
OS: macOS 10.15.6
node: v12.18.3
npm: 6.14.6

Thanks in advance! 

You guys did a great job for all these tools, really, thank you.

**Comment by thymikee** [comment]
Have you tried with different version of Node.js?

**Comment by SeasonLeee** [comment]
@thymikee hi, thanks for response, no, still not working... besides, I ask someone else to run the command, they have some whole different kind of error......................................

**Comment by thymikee** [comment]
This is fsevents and node-gyp related, likely nothing we can do about it. Try running with Node 10 or Node 14 (switch versions with `nvm` or `n`), it worked for me with the same environment.
