### ISSUE TITLE
In react-player, How can we add codec to support .mkv, 4k Videos and live stream URLs for tvOS?

### ISSUE THREAD

**Issue by tanujttn** [react-native-community/cli#1263]
**Current Behaviour:**
I am unable to play .mkv, 4K & live URLs on tvOS as these URLs are working on other platforms.

**Environment:**
URL attempting to play: http://tivix.eu:8000/movie/demo4/1SVHifcnbO/88814.mkv

**Comment by thymikee** [comment]
Ask on react-player, this is React Native CLI, which is unrelated to user code.
