### ISSUE TITLE
Launching on multiple devices at once

### ISSUE THREAD

**Issue by kevmo314** [react-native-community/cli#1265]
## Describe the Feature
I have a few iOS devices connected to my machine and I'd like to deploy an app to all of them at the same time. Currently, the CLI only picks the first available device which basically means I have to sequentially unplug and then run-ios. Could it be changed or a flag be added to launch on all of them at once so the app doesn't need to be rebuilt every time?

## Possible Implementations
Flag or change default.

**Comment by thymikee** [comment]
Sounds good, anybody willing to implement this? :)

**Comment by gsevla** [comment]
Agree with you!

As temporary solution, I add into package.json something like: `run-ios:multiple: react-native run-ios --udid XXX && react-native run-ios --udid YYY && ...`

But when we call run-android the application is installed on all available android devices and I think it should be similar on ios.

**Comment by Pirsanth** [comment]
I could do this.

> Agree with you!
> 
> As temporary solution, I add into package.json something like: `"run-ios:multiple": "react-native run-ios --udid XXX && react-native run-ios --udid YYY && ..."`
> 
> But when we call run-android the application is installed on all available android devices and I think it should be similar on ios.

I remember this mentioned elsewhere (making run-android and run-ios behave the same way with regards to installing on all devices when ran without any options). If I can find that issue I will post it below

Which should we go for then? Making run-ios install on all devices by default or a flag that makes run-ios install on all devices?
