### ISSUE TITLE
Error when archiving from XCode: EMFILE

### ISSUE THREAD

**Issue by TheRealNate** [react-native-community/cli#1268]
This error has been reported before, but the solution did not help me.

## Description
I am seeing this error when archiving from XCode. I have not encountered this issue before and have tried reverting my code:
````
node /.../node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output ... --assets-dest ...

warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (/Users/.../node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:311:20)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:133:12) {
  errno: -24,
  syscall: 'watch',
  code: 'EMFILE',
  filename: null
}
````

The error seems to be from `NodeWatcher`, does that mean that it is not using Watchman? On running `npx react-native doctor` and there is a ✅ next to Watchman

I have tried the following steps to fix:
- Reinstall Watchman (`sudo port uninstall watchman`, `sudo port install watchman`, reboot) (this has been the solution on similar issues but has not helped me)
- Reset Cocoapods (Deintegrate, rm Pods/, reinstall etc)
- Reset Watchman Cache (watchman watch-del-all)
- Clean Build Folder in XCode

If I run the bundle command manually from terminal it succeeds, it only seems to have a problem when archiving from XCode.

## Versions:
Environment: macOS Catalina
React Native CLI Version: 4.10.1
Node Version 12.16.1
React Native Version: 0.63.2
Watchman Version: 4.9.0

**Comment by TheRealNate** [comment]
Interesting development. If I manually run the xcodebuild command the archive succeeds:
````
xcodebuild -workspace ... -scheme ... archive
````

**Comment by joe06102** [comment]
hi, is there any progress on the issue? I've been bothered by the `too many open files`error  for couple of days.
I'm using the cli in a programmatic way:

```typescript
require('@react-native-community/cli/build/tools/gracefulifyFs')

const loadConfig = require('@react-native-community/cli/build/tools/config').default
const runServer = require('@react-native-community/cli/build/commands/start/runServer').default

async function run(options) {
    try {
        const config = await loadConfig()
        const server = await runServer([], config, options)
    } catch(err) {}
}
```

in low-end devices like macbook air or some macbookpro, the error occurs always. But if I change to `spawn('npx, ['react-native', 'start'])`, it works as expected.
