### ISSUE TITLE
Support for bundleid/packagename when initializing a new app

### ISSUE THREAD

**Issue by allyraza** [react-native-community/cli#1269]
## Describe the Feature
Add package name and bundle id support to init command

## Possible Implementations
Add `--package` options to `init` command which allows the user to specify bundleid/packagename

**Comment by thymikee** [comment]
Is it this hard changing it yourself after the project is initialized?

**Comment by aliraza-noon** [comment]
Not stale

**Comment by thymikee** [comment]
@aliraza-noon maybe you'd like to tackle this feature? 🚀
