### ISSUE TITLE
`bundle` ignores path alias if ran from `./ios` folder

### ISSUE THREAD

**Issue by sidferreira** [react-native-community/cli#1271]
I just finished updating to `rn 0.63.2`, but since that, our builds for release fails.
After a lot of digging, I found out that the problem is related to the `bundle` failing to resolve the path aliases if it is running from the `ios` folder.
This happens because we use Fastlane to assist the releases.

I tried both `node ... bundle` and `npx ... bundle` with the same results (running from command line).

(still digging for more details, but feels like a regression)

adding `cd ..` and `cd ios` on `Bundle React Native code and images` step fixes the issue, but it isn't the optimal solution...

**Comment by sidferreira** [comment]
So far, the only thing I managed to pinpoint is that at `metro/src/DeltaBundler/traverseDependencies.js: resolveDependencies` the aliased path is already resolved then running on project root, but not when running from `ios` folder.

**Comment by ajp8164** [comment]
As I understand, changes to the rn 0.63.2 (at least) include removing the use of PROJECT_ROOT and defaulting to PWD. It seems that cli is supposed to traverse up the dir tree until it finds package.json and set that directory. Seems this traversal is not working? See [Allow changing the project path in react-native-xcode.sh](https://github.com/facebook/react-native/commit/9ccde378b6e6379df61f9d968be6346ca6be7ead#commitcomment-37914902)

I followed the example in the above PR by adding `export PROJECT_ROOT=$PWD/..` to the build phase script.

**Comment by thymikee** [comment]
@grabbou can you weigh in?
