### ISSUE TITLE
Couldn't find template.config.js file inside "react-native" template

### ISSUE THREAD

**Issue by TerrerSandman** [react-native-community/cli#1274]
Creating a new project with v0.59.10 failed with error
> error Error: Couldn't find the "C:\Users\User\AppData\Local\Temp\rncli-init-template-hUh3Bm\node_modules\react-native\template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

But creating RN project with version 0.60.0 and above is working without errors.

**Steps to reproduce**
run cmd
`npx react-native init rn_example --version 0.59.10`

**Environment**
npm v6.14.1
node v12.14.1

**Comment by grabbou** [comment]
New `init` supports 0.60 and newer. Here's how you can init old version: https://github.com/react-native-community/cli/blob/master/docs/init.md#for-older-react-native-versions

**Comment by Murtala-1** [comment]
npx react-native init YourAwesomeProject --npm


you can also uninstall yarn globally
npm uninstall yarn
