### ISSUE TITLE
variant build with auto link work ? as we are maintain for GMS and HMS. 

### ISSUE THREAD

**Issue by arul-prasad** [react-native-community/cli#1275]
I have a question for auto linking with variant build

I have android app sources as below:

app/src/gms/java/MainApplication.java --> google mobile service main app
app/src/hms/java/MainApplication.java --> huawei service main app

if we use some react-native modules for example react-native-image-picker will it do auto-link correctly?

**Comment by thymikee** [comment]
You'll need to use `project.android.appName` or `--appFolder` to tell the CLI where your project is. See this issue: https://github.com/react-native-community/cli/issues/1292 and documentation: https://github.com/react-native-community/cli/blob/master/docs/platforms.md#projectconfig
