### ISSUE TITLE
[platform-ios] findProject heuristic is not good enougth

### ISSUE THREAD

**Issue by chrmod** [react-native-community/cli#1276]
`react-native config` will may detect wrong project if there are multiple `.xcodeproj` files present.

There are few issues here https://github.com/react-native-community/cli/blob/be37d6414ae26b81e2400ed6963230e93fbd8346/packages/platform-ios/src/config/findProject.ts#L40

1. `glob` sort order varies between versions and operating systems
2. current sorting is optimized for vanilla react-native project by flavoring `ios` folder. Brownfield projects typically don't have `ios` folder.

Those approaches may improve the situation:
* better heuristic: choose least nested `.xcodeproj` file 
* specify project file in `rn-cli.config.js`

**Comment by thymikee** [comment]
Project can be specified in the config already: https://github.com/react-native-community/cli/blob/master/docs/projects.md#how-does-it-work

**Comment by chrmod** [comment]
@michalchudziak thanks for the link. I've read it before but as I've understood it is being used for libraries, not for application project. When creating `react-native.config.js` the `react-native config` command stops working for me completely (I assume due to insufficient details in the config file).

Or am I doing it wrong?

**Comment by chrmod** [comment]
Well, I've tried it again and it seems to work. I'm guessing this is sufficient to close this issue. Thanks!
