### ISSUE TITLE
Incorrect bundle output location in documentation

### ISSUE THREAD

**Issue by nikdo** [react-native-community/cli#1284]
## Environment

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Memory: 310.12 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.12.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^4.13.0 => 4.13.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

```
Gradle 6.3
```

## Description

Suggested bundle output location for `./gradlew assembleDebug` in [`bundle` command `--bundle-output` parameter documentation](https://github.com/react-native-community/cli/blob/83ef4678452fb23cde6454f59122804c8dade056/docs/commands.md#--bundle-output-string) is incorrect.

The file produced by setting `bundleInDebug: true` and invoking `bundleDebugJsAndAssets` gradle taks is [`android/app/build/generated/assets/react/debug/index.android.bundle`](https://github.com/facebook/react-native/blob/7100756bb8b0b1ac85ccaa32c0ce5c1cc70d524f/react.gradle#L45).

And even this location is not sufficient for including bundle into APK. To do that, `copyDebugBundledJs` gradle task, which is enabled by setting `bundleInDebug: true`, [copies this file to 3 locations](https://github.com/facebook/react-native/blob/7100756bb8b0b1ac85ccaa32c0ce5c1cc70d524f/react.gradle#L274): 

```
app/build/intermediates/merged_assets/debug/out/index.android.bundle
app/build/intermediates/merged_assets/debug/mergeDebugAssets/out/index.android.bundle
app/build/intermediates/assets/debug/index.android.bundle
```

Only after that, the bundle is part of the APK.

I am not sure what is the correct approach how to use `bundle` command to successfully include the resulting bundle into APK, but the current documentation is misleading, unfortunately.

## Reproducible Demo

```sh
react-native init App
cd App
react-native bundle\
  --platform android --dev false --entry-file index.js\
  --bundle output android/app/build/generated/assets/react/debug/index.android.js
cd android
./gradlew assembleDebug
cd app/build/outputs/apk/debug
unzip app-debug.apk
find . -name "*index.android*"
```

**Comment by thymikee** [comment]
Right, would you like to send a PR improving the documentation? :)

**Comment by TMisiukiewicz** [comment]
@thymikee is there still an error in the docs?

**Comment by thymikee** [comment]
@adamTrz would be the best to tell now, as he worked on build-android command recently
