### ISSUE TITLE
Allow run-ios to accept an xcconfig to be used in xcodebuild

### ISSUE THREAD

**Issue by dathorntonsbg** [react-native-community/cli#1293]
## Describe the Feature
I would love to see the ability to pass in an xcconfig file to run-ios so that configs can be used to customize the build process with xcodebuild.  This is a very important feature for whitelabeled applications that use xcconfig, scheme and configuration for different versions of an app.  I was able to make a 2 line change to pass in the xcconfig locally and it worked without issue.

## Possible Implementations
**File**
https://github.com/react-native-community/cli/blob/master/packages/platform-ios/src/commands/runIOS/index.ts#L570
**Change**
Add a new option
**Implementation**
```javascript
{
  name: '--xcconfig [string]',
  description: 'Explicitly set xcconfig to use',
}
```

**File**
https://github.com/react-native-community/cli/blob/master/packages/platform-ios/src/commands/runIOS/index.ts#L414
**Change**
Pass xcconfig to xcodebuildArgs
**Implementation**
```javascript
const xcodebuildArgs = [
  xcodeProject.isWorkspace ? '-workspace' : '-project',
  xcodeProject.name,
  ... args.xcconfig ? ['-xcconfig', args.xcconfig] : [],
  '-configuration',
  args.configuration,
  '-scheme',
  scheme,
  '-destination',
  `id=${udid}`,
];
```
## Related Issues
N/A

**Comment by thymikee** [comment]
Can you contribute this feature? :)

**Comment by mdaj06** [comment]
@thymikee  ill take a look at this

**Comment by ShaswatPrabhat** [comment]
Hi @thymikee is this issue still open ?

**Comment by adamTrz** [comment]
> Hi @thymikee is this issue still open ?

@ShaswatPrabhat we would welcome your contribution here if you want to pick up the task :)

**Comment by ShaswatPrabhat** [comment]
Will share a PR for the same ASAP

**Comment by ShaswatPrabhat** [comment]
[PR](https://github.com/react-native-community/cli/pull/1722) for the issue
