### ISSUE TITLE
Use real device for ios as default as well

### ISSUE THREAD

**Issue by DomiR** [react-native-community/cli#1296]
## Describe the Feature
Android uses the first plugged in device per default.

## Possible Implementations
Do this for `run-ios` as well. We can either add a flag `--prefer-real-device` or just do this by default.

I'll start a PR for this, if someone can decide on this.

**Comment by grabbou** [comment]
You can do `react-native run-ios --device` and first device will be used. Does that satisfy your use case?

**Comment by grabbou** [comment]
(I do agree we should keep it more or less the same between run-ios/run-android)

**Comment by DomiR** [comment]
Okay, thanks! I don't know how I missed, that the first device will be used, when no argument is passed 🙈
