### ISSUE TITLE
Reset cache independently

### ISSUE THREAD

**Issue by sonicdoe** [react-native-community/cli#1299]
## Describe the Feature

Currently, it’s only possible to remove cached files using the `--reset-cache` option of the `bundle` and `start` commands. I’d like to suggest the possibility of resetting the cache without having to run the bundler.

## Possible Implementations

Providing a new command, `reset-cache`.

**Comment by thymikee** [comment]
Use `jest --clearCache`

**Comment by sonicdoe** [comment]
What if the project doesn’t use Jest?

**Comment by thymikee** [comment]
Oh, right. You'll need to go to [Metro issue tracker](https://github.com/facebook/metro/issues) and suggest that, since that's the tool used to bundle and serve js in RN apps.

**Comment by sonicdoe** [comment]
Thanks, I’ve opened https://github.com/facebook/metro/issues/598.

Out of curiosity, why does resetting Jest’s cache reset Metro’s cache? Do they both use the same cache directory?

**Comment by thymikee** [comment]
I confused this repo with Jest when opening an email notification, that's it :). And Metro uses some packages from Jest monorepo e.g. for its file system abstraction. Unfortunately they don't share cache but with some effort they likely could.
