### ISSUE TITLE
sourceMappingURL included in released builds but map files missing.

### ISSUE THREAD

**Issue by rod-salazar** [react-native-community/cli#1304]
## Environment

```
System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 19.01 GB / 31.85 GB
  Binaries:
    Node: 12.18.1 - ~\AppData\Local\Temp\yarn--1604300537415-0.21860973668823203\node.CMD
    Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1604300537415-0.21860973668823203\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20201003.030026 - C:\tools\watchman\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
    Visual Studio: 15.9.28307.1177 (Visual Studio Professional 2017), 16.7.30621.155 (Visual Studio Professional 2019)
  Languages:
    Java: 14.0.1 - /c/Program Files/Java/jdk-14.0.1/bin/javac
    Python: 2.7.14 - /c/Python27/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
    react-native-windows: ^0.63.0-0 => 0.63.5
  npmGlobalPackages:
    *react-native*: Not Found
Done in 2.01s.
```

## Description
When using debugger-ui, there are warnings in the chrome console about missing source map files.

`DevTools failed to load SourceMap: Could not load content for http://localhost:8081/debugger-ui/ui.bcd3f9d1.js.map: HTTP error: status code 500, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

This appears to be due to the fact that we inject sourceMappingUrl into each file during the build: https://github.com/react-native-community/cli/blob/master/scripts/build.js#L104

But, we exclude .map files when installing cli as a dependency: https://github.com/react-native-community/cli/blob/master/packages/debugger-ui/package.json#L14

To avoid this some change has to be made to exclude the sourceMappingUrl at the bottom of each built file when we are in some sort of 'release' mode.

**Comment by thymikee** [comment]
Good call. Would you like to help fixing that? :)
