### ISSUE TITLE
`react-native run-ios` build failure "x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler "

### ISSUE THREAD

**Issue by vorousjames** [react-native-community/cli#1311]
I just updated to RN v0.63.3, although im not sure this related to the upgrade. I was having issues with react-native run-ios on previous react-native version after changing the name of the app, and the project/schemes had different names, never got that issue solved, everyone said to just upgrade.

now on v0.63.3 there is still an issue with failing build after react-native run-ios. this time the error is:

> ** BUILD FAILED **
> 
> The following build commands failed: 
> 
> CompileC /Users/vorousjames/Library/Developer/Xcode/DerivedData/<OLD_NAME>-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/<NEW_NAME>.build/Debug-iphonesimulator/<NEW_NAME>.build/Objects-normal/x86_64/AppDelegate.o /Users/Desktop/Development/App/iOS/<OLD_NAME>/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure)

There is NO issue building/running from inside Xcode. ONLY with react-native run-ios

EDIT: I thought maybe there was an issue with the fact that I had the cli globally installed since I was just calling react-native run-ios. I believe that uses the global installation. so since its outdated, I uninstalled globally and tried to use the community package with npx react-native run-ios. now its giving another compileC error, but different.

> ** BUILD FAILED **
> 
> The following build commands failed: 
> 
> CompileC /Users/Library/Developer/Xcode/DerivedData/App-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseMessaging.o /Users/Desktop/Development/App/node_modules/react-native-firebase/ios/RNFirebase/messaging/RNFirebaseMessaging.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler 
> 
> CompileC /Users/Library/Developer/Xcode/DerivedData/App-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseFirestore.o /Users/Desktop/Development/App/node_modules/react-native-firebase/ios/RNFirebase/firestore/RNFirebaseFirestore.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (2 failures)

This is completely killing my ability to iterate quickly, any advice is welcomed

react-native: 0.63.3 react-native-cli (global): 2.0.1 react-native-community/cli: ^4.8.0 Xcode: 12.0.1 iOS: 14.0.1

**Comment by thymikee** [comment]
Use a local version of the CLI like `yarn react-native run-ios` or `npm run react-native run-ios`. The `npx` command may still pick up global version on some occasions :<

**Comment by AlphaJuliettOmega** [comment]
? what do you mean @thymikee 
The error is the same regardless which of the three commands I use. npx / yarn / npm run

```

The following build commands failed:
        CompileC /Users/x/Library/Developer/Xcode/DerivedData/x-x/Build/Intermediates.noindex/x.build/Debug-iphonesimulator/x.build/Objects-normal/x86_64/AppDelegate.o /Users/x/code/x-mobile/x/ios/x/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

error Command failed with exit code 1.```

Why was this issue closed?
What do you mean about the Global Version?

I don't have React Native global installed because the docs recommend running through npx, at least how I understand it.

**Comment by hackrx** [comment]
@AlphaJuliettOmega are you able to solve this error? I am also facing the same [issue](https://github.com/razorpay/react-native-razorpay/issues/310).

**Comment by RusherK** [comment]
are you able to solve this error? I am also facing the same issue

**Comment by hackrx** [comment]
@RusherK I solved this issue, so please follow the below steps to solve it
1.Make sure every package which you have installed is linked properly.
2.Find if you imported a package in a file and now you don't have that package installed.
3. Open xxx.xcworkspace instead of xxx.codeproj with xCode and try to run from there.

These steps worked for me.I hope this will help you.

**Comment by Rolando-Barbella** [comment]
Any updates on this one?

**Comment by omarTrigui20** [comment]
any update ?

**Comment by marian-galik** [comment]
https://stackoverflow.com/questions/66118122/lexical-or-preprocessor-issue-event2-event-config-h-file-not-found

this worked for me

**Comment by daniel1up** [comment]
@marian-galik I tried the solution on that question but that gives me this error message: 
[!] There are duplicate dependencies on `FlipperKit` in `Podfile`:

Any suggestion?

**Comment by daniel1up** [comment]
@marian-galik I fixed It :)

**Comment by MintakanValerie** [comment]
By updating the latest Flipper SDK, the issue got resolved:
iOS:

Call `use_flipper` with a specific version in `ios/Podfile`, for example: `use_flipper!({ 'Flipper' => '0.78.0' })`.
Run `pod install` in the ios directory.

https://fbflipper.com/docs/getting-started/react-native/

**Comment by ArturCherkanov** [comment]
It's really weird, but after the last xcode update, updating the Flipper SDK has become useless for me. 

You can try to comment `use_flipper!({ 'Flipper' => '...' })` or `use_flipper` line

**Comment by AlexHooperDev** [comment]
Updating to xcode 14.5 has also broken my build too, `flipper-folly` seems to be the culprit, it fails when trying to `CompileC` on the `flipper-folly` pod. So far neither `useFlipper!` or `use_flipper!({ 'Flipper-Folly' => '2.5.1' })` works.

**Comment by mqueiroz1995** [comment]
> Updating to xcode 14.5 has also broken my build too, `flipper-folly` seems to be the culprit, it fails when trying to `CompileC` on the `flipper-folly` pod. So far neither `useFlipper!` or `use_flipper!({ 'Flipper-Folly' => '2.5.1' })` works.

Downgrading `Flipper-Folly` to v2.3.0 fixed the issue:
- `use_flipper!({ 'Flipper-Folly' => '2.3.0' })`

**Comment by oleksandr-dziuban** [comment]
> > Updating to xcode 14.5 has also broken my build too, `flipper-folly` seems to be the culprit, it fails when trying to `CompileC` on the `flipper-folly` pod. So far neither `useFlipper!` or `use_flipper!({ 'Flipper-Folly' => '2.5.1' })` works.
> 
> Downgrading `Flipper-Folly` to v2.3.0 fixed the issue:
> 
> * `use_flipper!({ 'Flipper-Folly' => '2.3.0' })`

use_flipper!({ 'Flipper-Folly' => '2.3.0' }) or use_flipper!({ 'Flipper-Folly' => '2.5.1' }) doesnt work after upgrade to xcode 14.5
Do I need to reinstall pods, update somethiong or cleanup pod repo?

**Comment by oleksandr-dziuban** [comment]
https://github.com/facebook/react-native/issues/31179

https://github.com/facebook/react-native/issues/31441

**Comment by thangpq** [comment]
There are several way to suddenly your project building failure. I dont know and dont care, I just know how to fix.! I will show you all of them:
=> ios/podfile: comment:    
        #  use_flipper!()
        
        #  post_install do |installer|
        #    react_native_post_install(installer)
        #  end

=> Open Xcode by file in ios foulder (yourProject.xcworkspace) then right click to your project add swift file then ok. (dont think too much, just do it =_=).

=> one of 2 ways below cant make your project building success, but it still bulding failure just do last way I know:
because you installed react-native-navigator then you install "react-native-reanimated" that make your project build failure so fix it:
npm install react-native-reanimated@2.3.0-beta.2

If 3 ways below cant fix ??? so you should carefull by testing all package that you installed by testing them:
- create new project, install step by step pakage then: react-native run-ios => what pakage cause failure that problem => search: "....failure-pakage + bulding failure + react native"

I JUST MADESS AFTER LEAN REACT-NATIVE SO I DONT WANNA ANYONE ELSE MAD LIKE ME +____+
GOODLUCK

**Comment by ccraig09** [comment]
> Use a local version of the CLI like `yarn react-native run-ios` or `npm run react-native run-ios`. The `npx` command may still pick up global version on some occasions :<

this worked for me

**Comment by yilmar0309** [comment]
it worked for me
platform :ios, '10.0' to platform :ios, '11.0'

**Comment by SnowLew** [comment]
Please checkout our podfiles, check if all versions off plataform :ios.
This need be:
platform :ios, '11.0'

Common problem using onesignal.

**Comment by harryt04** [comment]
> Use a local version of the CLI like `yarn react-native run-ios` or `npm run react-native run-ios`. The `npx` command may still pick up global version on some occasions :<

it is outrageous that you closed this issue after a half-assed response like that.

**Comment by TienRyo** [comment]
> https://stackoverflow.com/questions/66118122/lexical-or-preprocessor-issue-event2-event-config-h-file-not-found
'Flipper' => '0.95.0'  work for me

**Comment by evangrim** [comment]
> @RusherK I solved this issue, so please follow the below steps to solve it 1.Make sure every package which you have installed is linked properly. 2.Find if you imported a package in a file and now you don't have that package installed. 3. Open xxx.xcworkspace instead of xxx.codeproj with xCode and try to run from there.
> 
> These steps worked for me.I hope this will help you.

Based on my experience, if you break your react-native-cli and use xcode as a workaround, you'll eventually pay for not dealing with the issue properly (whatever it is).

**Comment by gulshanAI** [comment]
Occur due to some mismatch of packages, search for a package which shows the error and remove the package

After that

delete ios folder install react native eject package

`npm i react-native-eject`


**re-create ios folder**
`npx react-native eject`


**install pod**
```
cd ios
pod install
```

**Comment by sanoofrahiman960** [comment]
> [facebook/react-native#31179](https://github.com/facebook/react-native/issues/31179)
> 
> [facebook/react-native#31441](https://github.com/facebook/react-native/issues/31441)



> There are several way to suddenly your project building failure. I dont know and dont care, I just know how to fix.! I will show you all of them: => ios/podfile: comment: # use_flipper!()
> 
> ```
>     #  post_install do |installer|
>     #    react_native_post_install(installer)
>     #  end
> ```
> 
> => Open Xcode by file in ios foulder (yourProject.xcworkspace) then right click to your project add swift file then ok. (dont think too much, just do it =_=).
> 
> => one of 2 ways below cant make your project building success, but it still bulding failure just do last way I know: because you installed react-native-navigator then you install "react-native-reanimated" that make your project build failure so fix it: npm install react-native-reanimated@2.3.0-beta.2
> 
> If 3 ways below cant fix ??? so you should carefull by testing all package that you installed by testing them:
> 
> * create new project, install step by step pakage then: react-native run-ios => what pakage cause failure that problem => search: "....failure-pakage + bulding failure + react native"
> 
> I JUST MADESS AFTER LEAN REACT-NATIVE SO I DONT WANNA ANYONE ELSE MAD LIKE ME +____+ GOODLUCK

i got this error"require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# platform :ios, '11.0'
 
# target 'milmaDataEntry' do
#   config = use_native_modules!

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # to enable hermes on iOS, change `false` to `true` and then install pods
#     :hermes_enabled => false
#   )


$RNFirebaseAsStaticFramework = true

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

#flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end


target 'milmaDataEntry' do
  config = use_native_modules!

  # use_frameworks!    # added by developer

  use_frameworks! :linkage => :static # added by developer

  # $static_framework = ['FlipperKit', 'Flipper', 'Flipper-Folly',
  #    'CocoaAsyncSocket', 'ComponentKit', 'DoubleConversion',
  #    'glog', 'Flipper-PeerTalk', 'Flipper-RSocket', 'Yoga', 'YogaKit',
  #    'CocoaLibEvent', 'OpenSSL-Universal', 'boost-for-react-native']
  
  #  pre_install do |installer|
  #    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  #    installer.pod_targets.each do |pod|
  #        if $static_framework.include?(pod.name)
  #          def pod.build_type;
  #            Pod::BuildType.static_library
  #          end
  #        end
  #      end
  # end

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled, needed commented by developer
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseMessaging',  :modular_headers => true
  pod 'React-Core',path: "../node_modules/react-native/",:modular_headers => true
  #pod 'RNReanimated',path: "../node_modules/RNReanimated/",:modular_headers => true
  
  target 'milmaDataEntryTests' do
    inherit! :complete
    # Pods for testing
  end
end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
   __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
#end

"
how too solve

**Comment by sanoofrahiman960** [comment]
> I just updated to RN v0.63.3, although im not sure this related to the upgrade. I was having issues with react-native run-ios on previous react-native version after changing the name of the app, and the project/schemes had different names, never got that issue solved, everyone said to just upgrade.
> 
> now on v0.63.3 there is still an issue with failing build after react-native run-ios. this time the error is:
> 
> > ** BUILD FAILED **
> > The following build commands failed:
> > CompileC /Users/vorousjames/Library/Developer/Xcode/DerivedData/<OLD_NAME>-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/<NEW_NAME>.build/Debug-iphonesimulator/<NEW_NAME>.build/Objects-normal/x86_64/AppDelegate.o /Users/Desktop/Development/App/iOS/<OLD_NAME>/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure)
> 
> There is NO issue building/running from inside Xcode. ONLY with react-native run-ios
> 
> EDIT: I thought maybe there was an issue with the fact that I had the cli globally installed since I was just calling react-native run-ios. I believe that uses the global installation. so since its outdated, I uninstalled globally and tried to use the community package with npx react-native run-ios. now its giving another compileC error, but different.
> 
> > ** BUILD FAILED **
> > The following build commands failed:
> > CompileC /Users/Library/Developer/Xcode/DerivedData/App-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseMessaging.o /Users/Desktop/Development/App/node_modules/react-native-firebase/ios/RNFirebase/messaging/RNFirebaseMessaging.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> > CompileC /Users/Library/Developer/Xcode/DerivedData/App-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseFirestore.o /Users/Desktop/Development/App/node_modules/react-native-firebase/ios/RNFirebase/firestore/RNFirebaseFirestore.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (2 failures)
> 
> This is completely killing my ability to iterate quickly, any advice is welcomed
> 
> react-native: 0.63.3 react-native-cli (global): 2.0.1 react-native-community/cli: ^4.8.0 Xcode: 12.0.1 iOS: 14.0.1

i got error like this "/AppDelegate.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'milmaDataEntry' from project 'milmaDataEntry')
(1 failure)"
<img width="953" alt="Screenshot 2023-07-07 at 11 07 42 AM" src="https://github.com/react-native-community/cli/assets/81160871/a25555cd-f3bf-4396-bdec-e938bc0c6dc6">

my pod file attached below please help

**Comment by hamzakashifCL** [comment]
> > I just updated to RN v0.63.3, although im not sure this related to the upgrade. I was having issues with react-native run-ios on previous react-native version after changing the name of the app, and the project/schemes had different names, never got that issue solved, everyone said to just upgrade.
> > now on v0.63.3 there is still an issue with failing build after react-native run-ios. this time the error is:
> > > ** BUILD FAILED **
> > > The following build commands failed:
> > > CompileC /Users/vorousjames/Library/Developer/Xcode/DerivedData/<OLD_NAME>-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/<NEW_NAME>.build/Debug-iphonesimulator/<NEW_NAME>.build/Objects-normal/x86_64/AppDelegate.o /Users/Desktop/Development/App/iOS/<OLD_NAME>/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (1 failure)
> > 
> > 
> > There is NO issue building/running from inside Xcode. ONLY with react-native run-ios
> > EDIT: I thought maybe there was an issue with the fact that I had the cli globally installed since I was just calling react-native run-ios. I believe that uses the global installation. so since its outdated, I uninstalled globally and tried to use the community package with npx react-native run-ios. now its giving another compileC error, but different.
> > > ** BUILD FAILED **
> > > The following build commands failed:
> > > CompileC /Users/Library/Developer/Xcode/DerivedData/App-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseMessaging.o /Users/Desktop/Development/App/node_modules/react-native-firebase/ios/RNFirebase/messaging/RNFirebaseMessaging.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> > > CompileC /Users/Library/Developer/Xcode/DerivedData/App-gdmnlxiprekjqhfiueouiidqhqnl/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNFirebase.build/Objects-normal/x86_64/RNFirebaseFirestore.o /Users/Desktop/Development/App/node_modules/react-native-firebase/ios/RNFirebase/firestore/RNFirebaseFirestore.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (2 failures)
> > 
> > 
> > This is completely killing my ability to iterate quickly, any advice is welcomed
> > react-native: 0.63.3 react-native-cli (global): 2.0.1 react-native-community/cli: ^4.8.0 Xcode: 12.0.1 iOS: 14.0.1
> 
> i got error like this "/AppDelegate.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'milmaDataEntry' from project 'milmaDataEntry') (1 failure)" <img alt="Screenshot 2023-07-07 at 11 07 42 AM" width="953" src="https://user-images.githubusercontent.com/81160871/251647190-a25555cd-f3bf-4396-bdec-e938bc0c6dc6.png">
> 
> my pod file attached below please help

you able to resolve this?

**Comment by hamzakashifCL** [comment]
I am getting this error whenever I build npx reaxct-native run-ios
I have attached my pod file along with command line error and error I gets when I build directly from XCode
<img width="739" alt="Screenshot 2023-07-25 at 12 26 20 PM" src="https://github.com/react-native-community/cli/assets/111490054/8d66c017-78bc-43b9-8147-7678be2732b7">
<img width="554" alt="Screenshot 2023-07-25 at 12 25 59 PM" src="https://github.com/react-native-community/cli/assets/111490054/80ad37df-b0c9-45e8-a015-3eb90dbbe7fb">
<img width="1512" alt="Screenshot 2023-07-25 at 12 25 07 PM" src="https://github.com/react-native-community/cli/assets/111490054/e55dc9f3-7cf1-4ffb-8ede-f590186828d1">

**Comment by stnrd** [comment]
I was struggling with this issue last week and it kind of disappeared. I cleared all my cache `yarn cache clean` and `pod cache clean --all` and `rm -rf "$(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache"` my clang cache. 

After that, I was able to rebuild the app using Xcode. I can't really pinpoint what exactly solved my issue which is quite concerning...

**Comment by hamzakashifCL** [comment]
Yes, I updated my React native version to 0.71.6, it keeps on giving this error

**Comment by facuescobar** [comment]
I've upgraded my project from "0.70.8" to  "0.72.3", and still getting the error.

I've tried everything mentioned above, but didn't work.
Any suggestions? 

```
    "react": "18.2.0",
    "react-native": "0.72.3",
```

**Comment by hamzakashifCL** [comment]
I resolved the error after commenting out  below command in my pod file

`    # :flipper_configuration => FlipperConfiguration.enabled,
`

and used the solution provided here https://mrdevgeek.com/xcode-14-3-simulator-16-4-build-failure-how-to-fix-value-is-unavailable-introduced-in-ios-12-0-error-with-react-native-0-71-5/

**Comment by MuhammadAbdullah54321** [comment]
I am facing this issues after I tried to upgrade react-native version from 0.63.4 to 0.71.3 and made changes to podfile according to react native upgrade helper

**Comment by MuhammadAbdullah54321** [comment]
I am facing this issues after I tried to upgrade react-native version from 0.63.4 to 0.71.3 and made changes to podfile according to react native upgrade helper

**Comment by AmilaJJ** [comment]
> https://stackoverflow.com/questions/66118122/lexical-or-preprocessor-issue-event2-event-config-h-file-not-found
> 
> this worked for me

If you re working with a m1 chip,  Downgrade @react-native-community/datetimepicker to version 7.6.2
