### ISSUE TITLE
Error in installing react native app

### ISSUE THREAD

**Issue by swanand246** [react-native-community/cli#1312]
error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version

This error is thrown whenever I try to run my react native app.I have done every other thing found on github to solve this issue but it doesn't worked for me.I even tried to create local.properties and inserted the Sdk path in it but still it doesn't work and consistently this error is thrown.Please anyone has solution or some kind of trick to avoid this and run the app,can you please tell me.Thanking in advance!

**Comment by thymikee** [comment]
Configure your $JAVA_HOME env var to point to Java 8. See: https://stackoverflow.com/questions/50824789/why-am-i-getting-received-fatal-alert-protocol-version-or-peer-not-authentic
