### ISSUE TITLE
[Plugin] Inject project commands with config sent to plugin commands

### ISSUE THREAD

**Issue by cbrevik** [react-native-community/cli#1313]
## Describe the Feature
I'm trying to build a plugin for the CLI which will need to interact with other commands, specifically the `bundle` command. According to the [plugin docs](https://github.com/react-native-community/cli/blob/master/docs/plugins.md#command-interface) the `func` property which my plugin config would have to expose, will be invoked with a `Config` object. This object has a [`commands`-property](https://github.com/react-native-community/cli/blob/f94673c3d972c227f2942ff8bb42a60b8f6e6f45/packages/cli-types/src/index.ts#L248), with the command definitions.

I thought I'd be able to nab the `bundle` command off there, and invoke it inside my plugin. But it turns out that the `commands`-property only contains commands defined by dependency config files. Like the one in the [`react-native` dependency](https://github.com/facebook/react-native/blob/752e7ab1f9b787090abdc2f1b0debe0113efd04d/react-native.config.js#L12), or my own plugin.

This seems to be because the `config` sent in [when attaching the commands](https://github.com/react-native-community/cli/blob/f94673c3d972c227f2942ff8bb42a60b8f6e6f45/packages/cli/src/index.ts#L220-L225) is resolved from the config files. I'd like some way to reach the "project commands" as well, which are not defined by the config files.

## Possible Implementations
A naive solution seems to be to merge the `projectCommands` into the `config.commands` when [the CLI-setup is run](https://github.com/react-native-community/cli/blob/f94673c3d972c227f2942ff8bb42a60b8f6e6f45/packages/cli/src/index.ts#L220-L225):

```ts
const config = loadConfig();

const mergedConfig = {
  ...config,
  commands: [...config.commands, ...projectCommands],
};

logger.enable();

for (const command of mergedConfig.commands) {
  attachCommand(command, mergedConfig);
}
```

Which works in a way, I can do the following from my plugin:

```ts
function func(argv: any, config: Config, opts: any) {
  const bundle = config.commands.find(
    (c) => c.name === 'bundle'
  );
  if (bundle) {
    const bundleFunc = bundle.func as any;
    bundleFunc([], config, {
      entryFile: config.root + '/index.js',
      dev: false,
      resetCache: true,
      platform: 'ios',
      resetGlobalCache: false,
      bundleOutput: config.root + '/main.jsbundle',
      sourcemapUseAbsolutePath: false,
      verbose: false,
    });
  }
}
```

If this seems like a good idea I'd love to submit a PR.

## Discussion
This might not be an ideal solution though, since a lot of the sane defaults in the [bundle command line args](https://github.com/react-native-community/cli/blob/f94673c3d972c227f2942ff8bb42a60b8f6e6f45/packages/cli/src/commands/bundle/bundleCommandLineArgs.ts#L30) are lost by invoking `bundle` in this way.

Also I must search through the commands array, and find the command definiton by name. And some command names are strings like `'link [packageName]'`. Which might be a fragile long-term. 

Another way is if I could reach the `commander` instance in some way, and invoke the command by name there. So I didn't have to search an array for the command, and I'd get the default args. But I've not found a good way to do that. Or I could probably do that indirectly by invoking the CLI through `execa`. Both those options seems a bit unnecessary/roundabout though, since the plugin is invoked directly by the CLI-code - but I'd have to indirectly invoke CLI-code from the plugin.

Am I thinking about this the wrong way? Is there some other sane way to do this?

**Comment by thymikee** [comment]
cc @grabbou
