### ISSUE TITLE
A failed event should return with an exit code of 1

### ISSUE THREAD

**Issue by jamesgeorge007** [react-native-community/cli#1333]
## Description

A case of failure should ideally return with an exit code of 1, this isn't the case currently.

- https://github.com/react-native-community/cli/tree/master/packages/cli/src/commands/init/errors
- https://github.com/react-native-community/cli/blob/master/packages/tools/src/errors.ts

## Reproducible Demo

```bash
# A directory named `app` already exists in path
$ react-native init app

error Cannot initialize new project because directory "TestInit" already exists.

$ echo $?
0
```

cc @thymikee

**Comment by jamesgeorge007** [comment]
https://github.com/react-native-community/cli/blob/fa73dd1c30ff60da87717ae3c2043ffdd7d12257/packages/cli/src/commands/init/errors/DirectoryAlreadyExistsError.ts#L6

```js
process.exitCode = 1;
```

**Comment by thymikee** [comment]
We can't just put `process.exitCode` here and there. The errors should bubble to the top-level error handler here: https://github.com/react-native-community/cli/blob/b52fc00b168786dabfbdebbe02c04215786adb47/packages/cli/src/index.ts#L26-L48 
If it doesn't do that, let's figure out what's silencing it and fix that instead, as it may silence more scenarios.

**Comment by grabbou** [comment]
BTW, why do we need a special file for every kind of Error as a subclass? Wouldn't `new CLIError`... just do it?

**Comment by grabbou** [comment]
Fix would be rather simple - let's just remove `try/catch` from `init` https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/init/init.ts#L217-L219 and the error will hit the master handler.

(not sure why this was done in first place).

**Comment by thymikee** [comment]
@grabbou we don't need to subclass errors. This was introduced by @Esemesek for readability and I didn't mind :)
