### ISSUE TITLE
--template is not working

### ISSUE THREAD

**Issue by lbnlrnt** [react-native-community/cli#1335]
## Environment

Not relevant at this point
## Description

Using `npx react-native init MyApp --template typescript` (I guess any template actually) is not working. 

It seems that a step is missing like "apply the template" 

We can see in the folder after init process finish that a `./template` folder is here, containing what we would expect to be at root `./`

## Reproducible Demo
`npx react-native init MyApp --template typescript`

<img width="1268" alt="Screen Shot 2020-12-09 at 1 36 29 PM" src="https://user-images.githubusercontent.com/7923050/101558545-0f9b4600-3a24-11eb-8a18-f4da853b3bae.png">

**Comment by lbnlrnt** [comment]
By the way, I was creating a new project with the will to create a template myself. Maybe the process has changed? 

I found [this article from 2017](https://medium.com/dailyjs/the-1-2-3s-of-react-native-templates-1f5dda037e11), that doesn't seem up to date when comparing what lives in [the typescript template](https://github.com/react-native-community/react-native-template-typescript).

If you have any advises at the time really interested :)

**Comment by thymikee** [comment]
CLI doesn't supports shortcuts anymore, but full module names or absolute file paths. Check the `docs/` directory in this repository :) 
```
npx react-native init MyApp --template react-native-template-typescript
```

**Comment by lbnlrnt** [comment]
Okay thanks will check that

**Comment by lbnlrnt** [comment]
@thymikee Doesn't seems to be better, I don't know if it a display error, but it seems to try to fetch `react-native-template-react-native-template-typescript`

![Screen Shot 2020-12-10 at 9 05 59 AM](https://user-images.githubusercontent.com/7923050/101681556-3199d480-3ac7-11eb-9465-9d898b39d884.png)

**Comment by lbnlrnt** [comment]
@thymikee Sorry for the noise, all good, it came from the fact that I still had a react-native-cli installed locally and it was using it instead of the right cli :)

**Comment by thymikee** [comment]
> @thymikee Sorry for the noise, all good, it came from the fact that I still had a react-native-cli installed locally and it was using it instead of the right cli :)

Happens to the best :) Glad it works for you now!
