### ISSUE TITLE
CLI location Gradle file - Run Gradle outside of Javascript hierarchy always fail

### ISSUE THREAD

**Issue by Yassabio** [react-native-community/cli#1349]
## cliResolveScript = "console.log(require('react-native/cli').bin);"
Hi,

I'm using the following module @react-native-community/cli-platform-android for react-native project.
I'm trying to build my project with fastlane in Gitlab CI. However when it comes to run fastlane command, it always fails with this following error : 

> ReactNative:Unexpected empty result of running '[node, -e, console.log(require('react-native/cli').bin);]' command.
> :ReactNative:Running '[node, -e, console.log(require('react-native/cli').bin);]' command failed.
> FAILURE: Build failed with an exception.
> * Where:
> Script '/builds/leested1/tablette-app/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 195
> * What went wrong:
> A problem occurred evaluating script.
> internal/modules/cjs/loader.js:883  throw err;  ^Error: Cannot find module

In fact, I've seen this comment in the native_modules.gradle : 

` /**
     * Resolve the CLI location from Gradle file
     *
     * @todo: Sometimes Gradle can be called outside of the JavaScript hierarchy (-p flag) which
     * will fail to resolve the script and the dependencies. We should resolve this soon.
     *
     * @todo: fastlane has been reported to not work too.
     */`

So, my question is when this issue will be fixed ? 
In the meantime, is there a way for me to workaround this issue ?

Thanks a lot for your answer.

**Comment by tingtien** [comment]
Having the same issue. Gradle can be called outside of the JavaScript hierarchy,  when can the script and the dependencies be resolve.

**Comment by bombillazo** [comment]
Updates on this issue? Break fastlane on monorepos
