### ISSUE TITLE
Can not change the react-native-community/cli version according to the guidlines

### ISSUE THREAD

**Issue by httol** [react-native-community/cli#1357]
## Ask your Question
My environment is 
macOs Big Sur
react: 16.9.0
react-native: 0.61.2

I have done according to the guidline https://github.com/react-native-community/cli#updating-the-cli
But the react-native-community/cli version has no changes
![image](https://user-images.githubusercontent.com/4971746/106581641-0939ce00-657e-11eb-8e68-e0746a3ab88f.png)

What's the problem? Can anyone have some suggestions

**Comment by Joao360** [comment]
Same issue when using react-native 0.61.5, cli remains on version "^3.0.0"

**Comment by thymikee** [comment]
It's working as expected. `react-native@0.61` requires CLI `^3.0.0`, which means it will fetch the latest 3.x version of the CLI, but no higher, because that's how semver works.
