### ISSUE TITLE
adb: error: cannot bind listener: Operation not permitted

### ISSUE THREAD

**Issue by skippy130** [react-native-community/cli#1368]
Hi I'm trying to get the basic [React Native tutorial here][1] set up, under the CLI quickstart tab, but I keep running into issues.

Here are the specifics of my set up:

 - Mac OS: Mojave  10.14.5
 - Node:           14.15.5
 - npx:            6.14.11
 - gem:            3.2.3
 - watchman:       4.9.0
 - Android Studio: 3.5.3
 - JRE:            1.8

Running the command "react-native start" opens up Metro, shows this, but it never says "Done." 

[![Metro in terminal not showing "done"][2]][2]

Running the command "npx react-native run android" causes this message on the terminal

    BUILD SUCCESSFUL in 25s
    27 actionable tasks: 5 executed, 22 up-to-date
    info Connecting to the development server...
    adb: error: cannot bind listener: Operation not permitted
    warn Failed to connect to development server using "adb reverse": Command failed: /Users/Library/Android/sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
    info Starting the app on "emulator-5554"...
    Starting: Intent { cmp=com.awesomeproject/.MainActivity }

On the emulator, this is what I see

[![Android Emulator Error][3]][3]

I've hit the reload button, and gotten this screen on the emulator 
[![enter image description here][4]][4]

[then followed instructions detailed here][5] and set up the IP address but still no luck. I've tried using the command "react-native run android" and it gives the same results as above. 

This is the most basic project I can set up and I've followed the instructions listed on the tutorial to the letter multiple times with many fresh projects. I'm really not sure what more I can do or where I could've messed up. I've seen similar issues posted on other forums but they've all been closed without proper resolution. 

Does anyone how I can resolve this? What could the issue be here? Should I be running "npm install" at some point? Running the app directly in Android Studio results in the same issues too. 

I've been trying to make this work for about a week now so I appreciate any help people can offer. Thanks.

I've found [this answer](https://github.com/react-native-community/cli/issues/437)  but when I run adb root I just get the following message "adbd cannot run as root in production builds". Meanwhile running adb reverse tcp:8081 tcp:8081
yields "adb: error: cannot bind listener: Operation not permitted". I'm really not sure what to do.

  [1]: https://reactnative.dev/docs/environment-setup
  [2]: https://i.stack.imgur.com/pPppP.png
  [3]: https://i.stack.imgur.com/F69qr.png
  [4]: https://i.stack.imgur.com/REdQE.png
  [5]: https://stackoverflow.com/questions/42064283/could-not-connect-to-react-native-development-server-on-android

**Comment by raimonkh** [comment]
This sounds related to https://github.com/microsoft/vscode-react-native/issues/1028
