### ISSUE TITLE
README is missing for multiple packages

### ISSUE THREAD

**Issue by trivikr** [react-native-community/cli#1382]
## Describe the Feature
README is missing in multiple packages, so no information is displayed on npmjs homepage for those packages.
* [@react-native-community/cli-types](https://www.npmjs.com/package/@react-native-community/cli-types)
* [@react-native-community/cli-debugger-ui](https://www.npmjs.com/package/@react-native-community/cli-debugger-ui)
* [@react-native-community/cli-server-api](https://www.npmjs.com/package/@react-native-community/cli-server-api)
* [@react-native-community/cli-platform-ios](https://www.npmjs.com/package/@react-native-community/cli-platform-ios)
* [@react-native-community/cli-platform-android](https://www.npmjs.com/package/@react-native-community/cli-platform-android)
* [@react-native-community/cli-tools](https://www.npmjs.com/package/@react-native-community/cli-tools)
* [@react-native-community/cli-hermes](https://www.npmjs.com/package/@react-native-community/cli-hermes)

## Possible Implementations
Add README with details on what individual package does.

## Related Issues
https://github.com/react-native-community/cli/issues/1380

**Comment by trivikr** [comment]
The package.json field `description` can also be added as part of this issue.

**Comment by thymikee** [comment]
Definitely worth to add these. Would you like to volunteer? Happy to help if needed. We can start with brief descriptions

**Comment by liamjones** [comment]
On a related note, CONTRIBUTING.md still states this repo has two packages; `cli` and `global-cli`. Once the new package descriptions are decided on it'd be good to update that too.

**Comment by trivikr** [comment]
The issue is still valid.

**Comment by adamTrz** [comment]
Thanks @trivikr , removing stale label. 💪 

Would you like to give us a helping hand here and do a PR with some readme's? 🙏
