### ISSUE TITLE
React Native create new project not working iOS

### ISSUE THREAD

**Issue by qaisershehzad** [react-native-community/cli#1389]
**iOS Not working** with basic steps https://reactnative.dev/docs/environment-setup using React native CLI Quick Start
When I try to create new Project using 
`npx react-native init AwesomeProject`

Commands ends successfully.
 but when I try to run Xcode project from Xcode directly or using terminal command 
 
 run successfully  `npx react-native start`
 But below commands gives error
 `npx react-native run-ios`
 
 `The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/qaiser/Library/Developer/Xcode/DerivedData/AwesomeProject-duuqfagzadnhhofgitlmhzimmznn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FBReactNativeSpec.build/Script-F6C9470D63916EDD9D283A9330288482.sh
(1 failure)
`
Xcode error :` Command PhaseScriptExecution failed with a nonzero exit code`

I tried multiple time creating new projects. No global installation of react-native-cli.
tried this `npm uninstall -g react-native-cli` as well before creating new project . 

**Working fine on Android.**

Environment Details
=========================

mac OS : 10.15.7
Xcode Version : 12.4 
tried on Xcode 11.3.1 as well
 node -v :  v14.12.0
gem which cocoapods:  `/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods.rb`
 pod --version: 1.10.1

**Xcode Screenshot:**
<img width="874" alt="Screenshot 2021-03-29 at 6 53 07 PM" src="https://user-images.githubusercontent.com/11673425/112847161-38714500-90c0-11eb-9266-792625b3feaf.png">

**Comment by jianwen612** [comment]
Same issue on my Mac..

**Comment by hanselabreu** [comment]
Try doing `pod install` inside the `ios` directory.

**Comment by qaisershehzad** [comment]
Yes I tried installing pods directly but no luck.

**Comment by ovbm** [comment]
Same issue. Tried everything here: https://github.com/facebook/react-native/issues/31259 . Still no success. Anyone found a workaround?

**Comment by jianwen612** [comment]
Hi everyone. I searched on Google and someone fixed this issue by making sure that no space characters are in the project's full path. If there is a space character, the script will become broken.  Hope this can help.
