### ISSUE TITLE
TypeError: An error was thrown when attempting to render log messages via LogBox.

### ISSUE THREAD

**Issue by N1colasVega** [react-native-community/cli#1402]
what it can be? I can see boxes sometimes, some times this error. I could close it and continue testing. This started to happen after the transition to 0.62. Right now i have 0.64 and problem still exist

<img width="346" alt="Screenshot 2021-04-28 at 10 11 52" src="https://user-images.githubusercontent.com/11300153/116361893-280cd100-a80a-11eb-8ec1-9b4d3c11c497.png">

**Comment by saravanakumarColan** [comment]
Are you solve it.. I am also facing the same issue

**Comment by Sherry112** [comment]
Facing the same issue.

**Comment by mitjnextt** [comment]
hey! anyone found any solution?

**Comment by winnyDiese** [comment]
j'ai le meme probleme, quelqu'un a t il trouvait la solution

**Comment by GuillaumeHemmen** [comment]
I have the same problem when I set `inlineRequires: true` in my `metro.config.js` file.

**Comment by BBID** [comment]
Hi, I'm also facing this issue. any body found a solution?

**Comment by Shahista96** [comment]
I am also facing the same issue.. Can someone please update on this.. thank you..

**Comment by cavaalex** [comment]
+1

**Comment by aminhdev** [comment]
+ 1

**Comment by gastonirby** [comment]
SAME

**Comment by serhiiharbo** [comment]
same

**Comment by shivakumarbdoddamani** [comment]
Any update or solution yet?

**Comment by symclouds** [comment]
Hello, I'm getting this issue in React Native 0.75.2. Any update on this?!

**Comment by szymonrybczak** [comment]
@symclouds could you please create a new issue with related reproductions steps and all informations about your environment? :pray:

**Comment by symclouds** [comment]
@szymonrybczak I did take another look at this issue and in this original thread it was thrown by console.log due to the fact that the rendered log message exceeded some finite setting. I actually received the exact same error message but in console.error due to a massive stack exception. That was my initial oversight of the issue but this issue is also present in console.error. I’m not certain whether or not it’s that way per design but I think it should be fixed given the common stack depth in react native. I can verify that the issue is indeed fixed in console.log because that’s how I was able to dump the stack so that I could troubleshoot the problem. Hope it helps.

**Comment by MHKCoder** [comment]
I am having the same issue not sure how to fix it but I do have the code if anyone can help it would be much appreciated =)  also im using expo on a development server : import * as BackgroundFetch from "expo-background-fetch";
import * as TaskManager from "expo-task-manager";
import { useState, useEffect } from "react";
import { fetchPrayerTimesFunction } from "../utils/FetchPrayerTimes";

const BACKGROUND_FETCH_TASK = "background-fetch";

TaskManager.defineTask(BACKGROUND_FETCH_TASK, async () => {
  try {
    const receivedNewData = await fetchPrayerTimesFunction();
  
    return receivedNewData
      ? BackgroundFetch.BackgroundFetchResult.NewData
      : BackgroundFetch.BackgroundFetchResult.NoData;
  } catch (error) {
    return BackgroundFetch.BackgroundFetchResult.Failed;
  }
});

export default function BackgroundFetchFunction() {
  const [isRegistered, setIsRegistered] = useState(false);
  const [status, setStatus] =
    useState<BackgroundFetch.BackgroundFetchStatus | null>(null);
    
    async function registerBackgroundFetchAsync() {
      return BackgroundFetch.registerTaskAsync(BACKGROUND_FETCH_TASK, {
      minimumInterval: 60 * 15, // 15 minutes
      stopOnTerminate: false, // android only,
      startOnBoot: true, // android only
    });
  }
  
  const checkStatusAsync = async () => {
    const status = await BackgroundFetch.getStatusAsync();
    const isRegistered = await TaskManager.isTaskRegisteredAsync(
      BACKGROUND_FETCH_TASK
    );
    setStatus(status);
    setIsRegistered(isRegistered);
  };
  
    useEffect(() => {
      registerBackgroundFetchAsync();
      checkStatusAsync();
      toggleFetchTask();
    }, []);
  
  const toggleFetchTask = async () => {
    if (!isRegistered) {
      await registerBackgroundFetchAsync();
    }
    
    checkStatusAsync();
  };
}

**Comment by MHKCoder** [comment]
Hello @symclouds - Thank you for the detailed response  - I will give that a try - Thank you again. =)

**Comment by MHKCoder** [comment]
Thank you @symclouds - I was able to successfully track down and fix the bug - It was a fault of mine where I was calling the background fetch as a function in my main **index.tsx file** when it was supposed to be called as a react native component. Thanks for the help =)
