### ISSUE TITLE
react-native run-ios --device not working with XCode 12.5 CLI tools

### ISSUE THREAD

**Issue by cbargren** [react-native-community/cli#1404]
## Environment

```
System:
    OS: macOS 11.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 626.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /var/folders/34/_v0h6lqn0x17yx6pppvqrnbmcjbc20/T/yarn--1619714124765-0.3284344217580091/node
    Yarn: 1.22.10 - /var/folders/34/_v0h6lqn0x17yx6pppvqrnbmcjbc20/T/yarn--1619714124765-0.3284344217580091/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.2.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      System Images: android-28 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

After upgrading to the latest version of Xcode (12.5), I can no longer run my react-native project on a physical device. Running `react-native run-ios --device=X` always results in an error and a message that there are no available devices to run on:

![image](https://user-images.githubusercontent.com/1050712/116590665-e300a180-a8d2-11eb-82ac-a02d417cee29.png)

I've tracked the issue down to [this line](https://github.com/react-native-community/cli/blob/641b21f583c97e3d48ce87d5fe804f42db92fa5c/packages/platform-ios/src/commands/runIOS/index.ts#L91). It seems that `xcrun xctrace list devices` no longer outputs to stderr:

![image](https://user-images.githubusercontent.com/1050712/116591416-a5504880-a8d3-11eb-9a40-a8a061b88784.png)

`tail error` => empty, `tail out` => list of devices. Changing the above line to `stdout` instead of `stderr` fixes the issue locally for me.

## Reproducible Demo

This _should_ be reproducible on any react-native project when running XCode 12.5, but if I'm mistaken, let me know and I'll try to put together a minimal demo.

**Comment by dburdan** [comment]
I ran into the same issue, and found the same solution as you. Temporarily fixing with the following [patch-package](https://www.npmjs.com/package/patch-package) patch:
`@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch`
```diff
diff --git a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
index ac4cd9f..ce330d8 100644
--- a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
+++ b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
@@ -128,7 +128,7 @@ function runIOS(_, ctx, args) {
   let devices;
 
   try {
-    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stderr);
+    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stdout);
   } catch (e) {
     _cliTools().logger.warn('Support for Xcode 11 and older is deprecated. Please upgrade to Xcode 12.');
 

```

**Comment by thymikee** [comment]
@dburdan mind sending a PR? :)

**Comment by thang2162** [comment]
I submitted a pull request for this. Ran into this issue after updating to Xcode 12.5.

**Comment by fredefl** [comment]
> I ran into the same issue, and found the same solution as you. Temporarily fixing with the following [patch-package](https://www.npmjs.com/package/patch-package) patch:
> `@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch`
> 
> ```diff
> diff --git a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> index ac4cd9f..ce330d8 100644
> --- a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> +++ b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> @@ -128,7 +128,7 @@ function runIOS(_, ctx, args) {
>    let devices;
>  
>    try {
> -    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stderr);
> +    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stdout);
>    } catch (e) {
>      _cliTools().logger.warn('Support for Xcode 11 and older is deprecated. Please upgrade to Xcode 12.');
>  
> ```

For others waiting for this fix in a new release of the cli, apply the above patch by placing it in a file called `@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch` in your project folder, and running:
`patch -p1 < @react-native-community+cli-platform-ios+5.0.1-alpha.2.patch`

**Comment by aryanm5** [comment]
> > I ran into the same issue, and found the same solution as you. Temporarily fixing with the following [patch-package](https://www.npmjs.com/package/patch-package) patch:
> > `@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch`
> > ```diff
> > diff --git a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> > index ac4cd9f..ce330d8 100644
> > --- a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> > +++ b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> > @@ -128,7 +128,7 @@ function runIOS(_, ctx, args) {
> >    let devices;
> >  
> >    try {
> > -    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stderr);
> > +    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stdout);
> >    } catch (e) {
> >      _cliTools().logger.warn('Support for Xcode 11 and older is deprecated. Please upgrade to Xcode 12.');
> >  
> > ```
> 
> For others waiting for this fix in a new release of the cli, apply the above patch by placing it in a file called `@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch` in your project folder, and running:
> 
> ```
> patch -p1 < @react-native-community+cli-platform-ios+5.0.1-alpha.2.patch
> ```

I'm getting `patch unexpectedly ends in middle of line` after running the command. I pasted the diff into the new file with no changes. Anyone know why?

**Comment by MBach** [comment]
Hello,
Not working for me:
- Latest release: 5.0.1-alpha.2
- iOS: 12.5

**Comment by brodybits** [comment]
5.0.1-alpha.2 was published before PR #1407 was merged.

I recommend you consider trying the 6.0.0-rc.0
or @***@***.*** version which *should* include the
bugfix.

>

**Comment by minyoung-jun** [comment]
Hello,
6.0.0-rc.0 was not working for me ;)

**Comment by RogerParis** [comment]
> > > I ran into the same issue, and found the same solution as you. Temporarily fixing with the following [patch-package](https://www.npmjs.com/package/patch-package) patch:
> > > `@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch`
> > > ```diff
> > > diff --git a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> > > index ac4cd9f..ce330d8 100644
> > > --- a/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> > > +++ b/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js
> > > @@ -128,7 +128,7 @@ function runIOS(_, ctx, args) {
> > >    let devices;
> > >  
> > >    try {
> > > -    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stderr);
> > > +    devices = (0, _parseXctraceIOSDevicesList.default)(_execa().default.sync('xcrun', ['xctrace', 'list', 'devices']).stdout);
> > >    } catch (e) {
> > >      _cliTools().logger.warn('Support for Xcode 11 and older is deprecated. Please upgrade to Xcode 12.');
> > >  
> > > ```
> > 
> > 
> > For others waiting for this fix in a new release of the cli, apply the above patch by placing it in a file called `@react-native-community+cli-platform-ios+5.0.1-alpha.2.patch` in your project folder, and running:
> > ```
> > patch -p1 < @react-native-community+cli-platform-ios+5.0.1-alpha.2.patch
> > ```
> 
> I'm getting `patch unexpectedly ends in middle of line` after running the command. I pasted the diff into the new file with no changes. Anyone know why?

Just delete the line 13 if you copy paste from above and get an empty line (13) at the end.

**Comment by ghasemikasra39** [comment]
`5.0.1-alpha.2` not working for me

**Comment by kortbyoussama** [comment]
not working `5.0.1-alpha.2
`
i'm building with xcode

**Comment by f4z3k4s** [comment]
> 5.0.1-alpha.2 was published before PR #1407 was merged. I recommend you consider trying the 6.0.0-rc.0 or @react-native-community/cli@next version from npm which *should* include the bugfix.

Sadly it doesn't fix the issue.

**Comment by lundjrl** [comment]
Worked for me but ran into a small newline warning with my linter. 
Solution is to run `echo -e "\n" >> @react-native-community+cli-platform-ios+5.0.1-alpha.2.patch`

**Comment by amma-dev** [comment]
just update cli-platform-ios inside  @react-native-community/
try this
npm i @react-native-community/cli-platform-ios

**Comment by xRiot** [comment]
We were able to solve this by upgrading `react-native` package to latest release: https://reactnative.dev/docs/upgrading

`react-native` package seems to be using CLI tools from its peer dependencies (which in our case was `@react-native-community/cli-platform-ios@5.0.1-alpha.2` with `react-native@0.64.1`). Seems like this behavior is counterintuitive, here's a separate issue report for that: https://github.com/facebook/react-native/issues/32002

**Comment by Keatooon** [comment]
After upgrading to the latest version of Xcode 13.2.1 was hitting "error No iOS devices connected." as well after running react-native run-ios --device. Tried to upgrade my react-native version from 0.62 to 0.64.2 and still doesn't work.

In the end it's due to my iPhone name is having brackets! (e.g. iPhone (2)).  This bracket two was added automatically to the phone name after migrating from old iphone to new iphone (2)

So everything doesn't work for you just remove the brackets!

**Comment by pprotas** [comment]
> 

This patch worked for me, why is this not merged into the NPM package?
