### ISSUE TITLE
Post warning that jetifier is deprecated and won't be called automatically in the future

### ISSUE THREAD

**Issue by mikehardy** [react-native-community/cli#1409]
## Describe the Feature

I regret not having a link to the discussion but at some point recently we decided AndroidX transition should be done and we should sunset jetifier as an automatic thing.

I've added a deprecation notice to jetifier and now warn any time a file is translated, suggesting the user post a PR to do the AndroidX transition in the repo

https://github.com/mikehardy/jetifier/releases/tag/v1.6.7

## Possible Implementations
Just a deprecation notice at first, that jetifier will no longer be automatically called in the future.
Then later, remove the jetifier functionality here.

**Comment by carlosmen-hrbl** [comment]
This just broke appcenter...

**Comment by mikehardy** [comment]
The addition of console warnings (not errors) with output pointing directly at modules with stale code, in a tool no one should be using any more that people may feel free to patch locally or pin to an earlier version broke something? How's that?

**Comment by mikehardy** [comment]
how does app center handle deprecation notices generally? How's it handle peer dependencies in npm 7? Seems like madness if it can't tolerate console warnings...

**Comment by carlosmen-hrbl** [comment]
To be honest, I am totally agree with you. Things like this should be gracefully handled and/or not affect this at all, but happened...

**Comment by carlosmen-hrbl** [comment]
:V
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /Users/runner/work/_temp/bceef46f-3b81-4a2f-a236-d45339757822.sh
Jetifier is deprecated. Future versions of react-native CLI may not run it by default.
Jetifier found 1477 file(s) to forward-jetify. Using 3 workers...
##[error]Bash wrote one or more lines to the standard error stream.
##[error]Jetifier is deprecated. Future versions of react-native CLI may not run it by default.

**Comment by mikehardy** [comment]
if there were no actual dependencies that were stale, run the android build with `--no-jetifier` I think ?

**Comment by carlosmen-hrbl** [comment]
Yeah, I will try that. But as a short term fix, need appcenter to manage this meanwhile we fix those.
Appreciate your replies.

**Comment by mikehardy** [comment]
also - these were console.warn - now sure how appcenter maps that to stderr? That seems like a bad mapping - here's the actual change for reference: https://github.com/mikehardy/jetifier/commit/a027dd065c62e19af29afe19e500391b62d39847

**Comment by stefoid** [comment]
Heya all, how do I tell react-native cli to use a previous version of jettifier so I can do what I need to do right now?

**Comment by mikehardy** [comment]
Probably a resolutionStrategy block in your package.json is most explicit? I'm mobile and don't have the exact syntax but react-native-firebase or its test subdir has an example I'll try to link later

**Comment by mikehardy** [comment]
nevermind went to a terminal - I don't intend for this to blow people up but we have to sunset somehow sometime...so to pin a dependency (even in sub modules) of a package at a version you want a "resolutions" element in your package.json

react-native-firebase pins react typescript types this way because it's docs package sometimes slips version boundaries and things get ugly. It looks like:

https://github.com/invertase/react-native-firebase/blob/0b62d5ac9a31f4d840c45ea41aeb89a7c2ecbaf3/package.json#L70-L72

`package.json`:
```json
  "resolutions": {
    "@types/react": "^17.0.3"
  },
```

That is tested and working code. What you want for this problem is untested so please report back but should be this in `package.json`

```json
  "resolutions: {
    "jetifier": "1.6.6"
  },
```

Try it and report? 🤞

**Comment by stefoid** [comment]
Heya, didnt work, still grabbing 1.6.7

Ill look further and report back

**Comment by stefoid** [comment]
I feel like I need to put some sort of dependency override into my build.gradle

**Comment by mikehardy** [comment]
build.gradle won't have anything to do with this one. The console.warns are - as I linked to the commit above - at the javascript level. The resolutions should force it, so that's odd.

**Comment by mikehardy** [comment]
For reference to CLI folks - the deprecation warnings are in jetifier@2
