### ISSUE TITLE
Why doesn't this CLI let me create a new project in an existing, empty directory?

### ISSUE THREAD

**Issue by Pika-Pool** [react-native-community/cli#1418]
## Ask your Question

When i run this command: `npx react-native init --directory . --skip-install awesomeproject`, I get the error `error Error occurred while trying to create project directory.` Note that the '.' directory is completely empty

I checked the code and it seems the cli only checks if the directory already exists, and if it does,  error is thrown [here](https://github.com/react-native-community/cli/blob/121916fca2d85d808862d10b75b787a82f683d62/packages/cli/src/commands/init/init.ts#L44)

But in create-react-app, you can just specify the directory, the command works, as long as package.json does not exist, even if the directory does.

Is there are particular reason react-native does this? If not, I think the CRA way is better and I would love to implement it in this CLI

**Comment by Pika-Pool** [comment]
ok, I'll work on this then. It'll be great if you could clarify a few things for me

- whats the diff between `/package/cli/src/commands/init.ts` and `/package/cli/src/commands/initCompat.ts`?
- in what order are these files executed?
- and which file do i make the changes for this issue?

This is the workflow in my mind. 
- There are 3 scenarios for the command line arguments:
	 - `projectName` is given, `--directory` is not:
		- treat `projectName` as a directory path, so something like this:
		```js
		const projectDirectory = path.resolve(projectName);
		projectName = path.basename(root);
		```

	- `projectName` and `--directory` both are given:
		```js
		const projectDirectory = path.resolve(directory);
		// projectName remains same as the command line argument passed
		// projectName is also already validated against a regex in the existing code
		```
	- `projectName` is not given:
		- this already throws an error, so no changes

- Now,  to check if the `projectDirectory` is valid, CRA uses [function `isSafeToCreateProjectIn`](https://github.com/facebook/create-react-app/blob/7bdeced8495370b683c08b86bc84b66af83f2f0a/packages/create-react-app/createReactApp.js#L934), which uses a list of valid files that could be already present in the directory.
	- i couldn't find any other conflicting files for the react-native cli, please mention them if there are any

**Comment by thymikee** [comment]
Create a PR please :)

**Comment by Pika-Pool** [comment]
I'm stuck at writing tests for this. To validate a directory, the code checks the local file system. So should I use something like [mock-fs](https://github.com/tschaub/mock-fs) for this?
