### ISSUE TITLE
Build issue when using typescript numeric separator

### ISSUE THREAD

**Issue by pesekviktor** [react-native-community/cli#1419]
## Bundle command fails when using typescript numeric separators

Hi, 

when I use numeric separator such as `const a = 60_000;` the bundle command fails:

```
Error: Unexpected token name «_000», expected punc «,» in file YYY.ts at 27:33
    at XXX/node_modules/metro-transform-worker/src/index.js:279:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (XXX/node_modules/metro-transform-worker/src/index.js:146:24)
    at _next (XXX/node_modules/metro-transform-worker/src/index.js:168:9)
    at XXX/node_modules/metro-transform-worker/src/index.js:175:7
    at new Promise (<anonymous>)
    at XXX/node_modules/metro-transform-worker/src/index.js:164:12
    at minifyCode (XXX/node_modules/metro-transform-worker/src/index.js:289:17)
    at Object.<anonymous> (XXX/node_modules/metro-transform-worker/src/index.js:569:40)
```

While I can live without them, could you suggest a best way to fix it?

My tsconfig:

    "target": "esnext",
    "module": "esnext",
    "lib": [
      "es2017",
      "dom"
    ],

**Comment by liamjones** [comment]
Assuming you're getting babel to process your TS (rather than using react-native-typescript-transformer);

TS understands the separator but babel doesn't out of the box, you need to add https://babeljs.io/docs/en/babel-plugin-proposal-numeric-separator to your project & babel config.

**Comment by pesekviktor** [comment]
Indeed, I've added the plugin and it is woking now. Thanks
