### ISSUE TITLE
The `--appId`  parameter may configurable in react-native.config.js

### ISSUE THREAD

**Issue by goodjun** [react-native-community/cli#1422]
## Describe the Feature

When ApplicationId was different from PackageName, an `--appId` parameter should be add in `react-native run-android`, the `--appId`  parameter may configurable in react-native.config.js.

If function above was needed, I can submit a PR for it.

**Comment by liamjones** [comment]
It already has this: https://github.com/react-native-community/cli/blob/master/packages/platform-android/src/commands/runAndroid/index.ts#L337 or are you looking for something slightly different?

**Comment by goodjun** [comment]
> It already has this: https://github.com/react-native-community/cli/blob/master/packages/platform-android/src/commands/runAndroid/index.ts#L337 or are you looking for something slightly different?

yes, but the `--appId` here can not be config in react-native.config.js .

**Comment by liamjones** [comment]
Ah, gotcha.
