### ISSUE TITLE
react-native crashes immediately when I run it

### ISSUE THREAD

**Issue by lilshebeary** [react-native-community/cli#1429]
## Ask your Question
after resetting my computer,  I can't get watchman to work.  

Warning: Problem checking watchman version. Invalid Version: 2021.06.07.00

**Comment by alexwmidas** [comment]
Same issue on my side

**Comment by lc3t35** [comment]
When I run `npx @react-native-community/cli doctor` on osx 11.4, I have this strange return : 

```
Common
 ✓ Node.js
 ✓ yarn
 ✖ Watchman - Used for watching changes in the filesystem when in development mode
   - Version found: 2021.06.07.00
   - Version supported: 4.x
```

watchman is already at latest version : 
```
% brew install watchman
Warning: watchman 2021.06.07.00 is already installed and up-to-date.
To reinstall 2021.06.07.00, run:
  brew reinstall watchman
```

**Comment by lilshebeary** [comment]
it now works, but I don't remember what I did to fix it. I think I reinstalled it.

**Comment by iboxgithub** [comment]
same here, is it possible to share how you fixed this?

**Comment by lilshebeary** [comment]
I think in my case, I had just purchased a new computer and I had not installed watchman yet. It is only the second time I had set up as I am fairly new.

________________________________
