### ISSUE TITLE
run-android|run-ios do not support RNTester out of the box

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#143]
Instructions to run RNTester recommend running Gradle / opening Xcode in order to run the app. We should add support for using the CLI, which will make it faster and easier to run RNTester and check when releasing new versions.

The biggest issue is in the detection mechanism that are inside `run-android` and `run-ios` (that are quite dumb).

**Comment by grabbou** [comment]
While doing it, rename `--root` in `run-android` to be less confusing (ideally, make it like the `run-ios`)

**Comment by grabbou** [comment]
iOS part is being worked on in #287

**Comment by grabbou** [comment]
@dulmandakh would you be able to explain why some Android projects have `android/gradlew` and others have `android/app/gradle` (RNTester)? Trying to handle both cases when doing `run-android` and I am a bit lost here.

**Comment by thymikee** [comment]
AFAIK this is done.
