### ISSUE TITLE
RN 0.64 eventually fails to load from Metro on iOS device

### ISSUE THREAD

**Issue by lindboe** [react-native-community/cli#1450]
## Environment

```
yarn run v1.22.10
$ /Users/lizzilindboe/dev/TestProject/node_modules/.bin/react-native info
info Fetching system and libraries information...
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 693.71 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /var/folders/t3/qdr7x1_x6kq3zhmlmd9_1kt80000gq/T/yarn--1626373443556-0.32661718408266616/node
    Yarn: 1.22.10 - /var/folders/t3/qdr7x1_x6kq3zhmlmd9_1kt80000gq/T/yarn--1626373443556-0.32661718408266616/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/lizzilindboe/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 29.0.2, 30.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.2 => 0.64.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
✨  Done in 3.80s.
```

## Description

Filed an issue with Metro [here](https://github.com/facebook/metro/issues/686), but I'm not sure where the source of this bug is, so also filing here.

When running a React Native 0.64 app on a physical iOS device, I eventually hit an error while trying to load the app JS, which says `Expected MIME-Type to be 'application/javascript' or 'text/javascript', but got '(null)'`.

Restarting the server with `--reset-cache` does fix the issue, but it doesn't take long to occur again. It's inconsistent, but I've even seen it fail on the first refresh after a reset-cache launch.

I haven't seen this on an Android device, or on an iOS simulator. Android continues to be able to load JS from metro after this happens.

## Reproducible Demo

Create a project with `react-native init`, and then run it on a physical iOS device using the steps from https://reactnative.dev/docs/running-on-device. Refresh the app a few times until you hit the error.

**Comment by dkarter** [comment]
Here's a video replicating the issue, it is only happening to us on real devices during subsequent reloads (after force-closing the app and reopening it with the same metro server):
https://cln.sh/ywHK3NsqxippkbUWqkp1

Would really appreciate any help or direction! :) This issue has been plaguing our team ever since we upgraded react native to 0.64.2 more details posted here: https://github.com/facebook/metro/issues/686#issuecomment-880291288

**Comment by jimmyfortinx** [comment]
Good news, we have found a workaround and posted more details about the issue itself on https://github.com/facebook/metro/issues/686#issuecomment-902113158

Spoiler alert: you just need to upgrade your Mac OS!
