### ISSUE TITLE
run-ios command does not look for the default build configuration when --scheme is specified

### ISSUE THREAD

**Issue by boliveira** [react-native-community/cli#1454]
## Describe the Feature
Currently, when we use the flag --scheme to specify a scheme to be run while invoking the react-native run-ios command, the cli is not looking for the build configuration that is associated with the specified scheme and uses the 'Debug' configuration by default.

As we can specify a default build configuration for each scheme in Xcode, the cli should use that configuration as the default instead of using the 'Debug' configuration.

## Possible Implementations
Take a look at fastlane's implementation in gym action source code (file code_signing_mapping.rb, function 'detect_configuration_for_archive'). What it does is, if a configuration is not specified by the user on the command-line, then it will find the corresponding build configuration for the archive action of the specified scheme. The cli could use the build configuration used for the Run action of the specified scheme.

**Comment by adamTrz** [comment]
Not stale

**Comment by TMisiukiewicz** [comment]
gonna take a look on that one 👀
