### ISSUE TITLE
Gradle sync stop working with  "Cannot run program "node" message

### ISSUE THREAD

**Issue by zinoviev** [react-native-community/cli#1457]
## Environment

System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 123.39 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.19.1 - /opt/homebrew/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 31
      Build Tools: 29.0.2, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

Hey, everyone. Surprisingly for me launching project with android studio stopped to work with gradle sync error. But I still can run project with ```npx react-native run-android```

```
Caused by: java.io.IOException: Cannot run program "node" (in directory "/Users/zigi/Temp/droidSuck/android"): error=2, No such file or directory
	at java_lang_Runtime$exec$0.call(Unknown Source)
	at ReactNativeModules.getCommandOutput(/Users/zigi/Temp/droidSuck/node_modules/@react-native-community/cli-platform-android/native_modules.gradle:189)
	at ReactNativeModules$getCommandOutput$0.callCurrent(Unknown Source)
	at ReactNativeModules.getReactNativeConfig(/Users/zigi/Temp/droidSuck/node_modules/@react-native-community/cli-platform-android/native_modules.gradle:233)
	at ReactNativeModules$getReactNativeConfig.callCurrent(Unknown Source)
	at ReactNativeModules.<init>(/Users/zigi/Temp/droidSuck/node_modules/@react-native-community/cli-platform-android/native_modules.gradle:84)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at native_modules_btdx1fw5o90mtgvk8m0ztnv6f.run(/Users/zigi/Temp/droidSuck/node_modules/@react-native-community/cli-platform-android/native_modules.gradle:287)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 159 more
Caused by: java.io.IOException: error=2, No such file or directory
```

I found a workaround - I can launch the android studio from the terminal and error is gone, so my bet it's doesn't see node binary from brew folder, but I have no idea why this is happening and why it works before and suddenly stops

**Comment by zinoviev** [comment]
Still no idea why it's happening, but was fixed with node symlink ```sudo ln -s $(which node) /usr/local/bin/node```

due https://stackoverflow.com/questions/67337836/new-rn-project-in-m1-mbp-built-failed-could-not-find-node-make-sure-it-is-in

**Comment by leotm** [comment]
maybe had it in `/opt/homebrew/bin/node` so above created symlink to it, xcode should now find _node_ too

**Comment by hexboy** [comment]
I am using "Android Studio Bumblebee | 2021.1.1".
it works for me `sudo chmod +x /Applications/Android\ Studio.app/Contents/bin/printenv`

more info: https://stackoverflow.com/a/70891538/2558451

**Comment by NileshRathore** [comment]
> I am using "Android Studio Bumblebee | 2021.1.1". it works for me `sudo chmod +x /Applications/Android\ Studio.app/Contents/bin/printenv`
> 
> more info: https://stackoverflow.com/a/70891538/2558451

Thank you so much, you saved a lot of my time.

**Comment by hntddt123** [comment]
> I am using "Android Studio Bumblebee | 2021.1.1". it works for me `sudo chmod +x /Applications/Android\ Studio.app/Contents/bin/printenv`
> 
> more info: https://stackoverflow.com/a/70891538/2558451

Also need to restart the Android Studio after the above comment

**Comment by xgenem** [comment]
The above solution doesn't work on my case. I am on chipmunk right now.

**Comment by artmerlop** [comment]
@xgenem how did you fixed it?

**Comment by kunalsolanki1992** [comment]
I have android studio chipmunk too and the above solution didn't work for me. My system is apple macbook pro with m1 pro chip.

**Comment by caricbrown** [comment]
I don't think this has anything to do with the version of Android Studio or Gradle. Try fixing your Node setup: https://benscheer.medium.com/how-to-install-nvm-and-node-on-macos-m1-silicon-in-2022-172fba82d92f

**Comment by xgenem** [comment]
Hi all, I was able to resolve the issue by updating my Gradle version used. `File > Project Structure > Project` then under Gradle Version I chose 6.9-rc-1 

You can also update it in `android/gradle/wrapper/gradle-wrapper.properties` file.

**Comment by zain-khalid** [comment]
Follow this, it worked for me.

For Mac users, use the following command:
open -a /Applications/Android\ Studio.app /path/to/my_android_project

For Windows users, use the following command:

start "" "C:\Program Files\Android\Android Studio\bin\studio64.exe" "X:\path\to\my_android_project"

reference https://stackoverflow.com/questions/35363546/open-androidstudio-project-from-command-line-on-osx

**Comment by sryze** [comment]
Anyone knows how to fix this in Dolphin? The above solutions didn't help me unfortunately 😞

**Comment by maxweb4u** [comment]
@sryze I have the same problem in the same android studio, only second variant that you mentioned is working for me: run this from CL:

`/Applications/Android\ Studio.app/Contents/MacOS/studio`

other variants are not working.

**Comment by ez-tech-global** [comment]
> @sryze I have the same problem in the same android studio, only second variant that you mentioned is working for me: run this from CL:
> 
> `/Applications/Android\ Studio.app/Contents/MacOS/studio`
> 
> other variants are not working.

thanks! It work for me

**Comment by jcdhlzq** [comment]
Change the default JDK version from Android studio embeded JDK11 to JDK1.8. That works for me.
This changed the gradle scripts running env PATH, after which node can be found. But I don't know why this change affect env.

**Comment by siliconsocket** [comment]
### 1. Edit `build.gradle` in the `android` Directory
Add the following configuration to dynamically set the `nodeExecutableAndArgs` property:

```gradle
import groovy.json.JsonSlurper

project.ext.react = [
    nodeExecutableAndArgs: [getNodePath()]
]

def getNodePath() {
    def process = "which node".execute()
    process.waitFor()
    def nodePath = process.in.text.trim()
    if (!nodePath) {
        throw new GradleException("Node.js executable not found in PATH. Please ensure Node.js is installed and accessible.")
    }
    return nodePath
}
```

### 2. What This Does
- The `getNodePath()` function executes the `which node` command to dynamically find the path to the `node` executable in your system's `PATH`.
- If `node` is not found, it throws a `GradleException` with a helpful error message.
- This ensures that the correct `node` executable is used, even if you're using tools like `nvm`.

### 3. Save the File and Rebuild
Clean and rebuild your project to apply the changes:

```bash
cd android
./gradlew clean
./gradlew assembleDebug
```

## Why This Works
When using `nvm` or similar tools, `node` is often installed in a user-specific directory, and its path might not be accessible to Gradle. This solution ensures that Gradle dynamically retrieves the correct path to `node` during the build process.

**Comment by erkie** [comment]
@siliconsocket this amazing. 

This is exactly what was needed to get build running using [FNM](https://github.com/Schniz/fnm) without setting a highly unstable symlink to `/usr/local/bin/node`. Given how FNM installs node it would just invite further issues down the road.

This is a lot safer as well than just relying on the correct `$PATH` being loaded in Android Studio. 

```
$ which node
/Users/erik/Library/Caches/fnm_multishells/9909_1735404813791/bin/node 
```

**Comment by yuriy-dobryi** [comment]
> Change the default JDK version from Android studio embeded JDK11 to JDK zulu version. That works for me on Apple M2. This changed the gradle scripts running env PATH, after which node can be found. But I don't know why this change affect env.

This worked for me with Expo 52 and 53 on **Android Studio Narwhal** (2025.1.3). To make this the default for any project and build, I went to `File` → `New Projects Setup` → `Settings for New Projects` → `Default Gradle JDK` and selected **Zulu 17**.

After that, the same value should automatically apply under `New Projects Setup` → `Default Project Structure` → `Default Gradle JDK` as well.

**Comment by tejas238** [comment]
@yuriy-dobryi Thank you,  this was the solution after upgrading to expo v52. Needs to be in the expo changelog honestly...
