### ISSUE TITLE
Feature request: support Apple TV

### ISSUE THREAD

**Issue by douglowder** [react-native-community/cli#1476]
## Describe the Feature

I'm the maintainer for the Apple TV and Android TV RN repo (https://github.com/react-native-tvos/react-native-tvos).  I'd like to implement better CLI support for Apple TV with two features:

- New command `react-native run-tvos` (this can be done with the right flags to `run-ios`, but it would be convenient to have a separate command)
- Make `react-native upgrade` work with the `react-native-tvos` fork

## Possible Implementations

I plan on implementing these, but wanted to find out your preference on the approach I should take.

For `run-tvos`, should I make changes to the existing `platform-ios` package, or do it in a separate package (which means a lot of duplicate code)?

For `upgrade`, it seems to me the right way is to have `upgrade.ts` detect that the project uses `react-native-tvos` and use the `react-native-tvos` diffs (I have already created a repo for the diffs).  But if you prefer a separate command or package for this, that's ok.

**Comment by thymikee** [comment]
CLI has a plugin subscription mechanism that allows npm packages to expose their own plugins. This way `react-native-tvos` can expose a `run-tvos` plugin, that uses platform-ios under the hood (any changes to make it more generic so it fits tvos needs better are welcome!). Check this doc: https://github.com/react-native-community/cli/blob/master/docs/plugins.md.

Regarding `upgrade`, it's not super reliable for the default template. If the change would be a simple switch to change the source of the diff, then I think we can put this in for now. And later figure out something similar to CLI plugins so this repo doesn't have to maintain too many templates.

**Comment by douglowder** [comment]
Thanks for the tips, I'll do `run-tvos` inside the RN TV repo, and see if the change for `upgrade` can be done here in a not too intrusive way.

**Comment by douglowder** [comment]
Fixed in release 6.1.0
