### ISSUE TITLE
Support checking against CalVer for dependencies in the `doctor` command

### ISSUE THREAD

**Issue by tywayne** [react-native-community/cli#1485]
## Describe the Feature
The `doctor` tool only supports version checking with SemVer. Watchman has switched from using SemVer to CalVer in their versioning, so it always shows as failing even when it is correctly installed to the latest version. 

It would be great if the `doctor` command would support checking against both SemVer and CalVer so that Watchman would report correctly.

## Possible Implementations
Update the `doesSoftwareNeedToBeFixed` function to support checking against SemVer as well as CalVer versioning systems.

**Comment by thymikee** [comment]
Thanks for noting that! Makes sense to update the logic for Watchman then 👍🏼 cc @adamTrz

**Comment by adamTrz** [comment]
Closing the issue since Watchman version check was resolved with #1700
