### ISSUE TITLE
Command failed: yarn install

### ISSUE THREAD

**Issue by gurbela** [react-native-community/cli#1486]
Command:  npx --ignore-existing react-native init TestApp --template react-native-template-typescript
Error: Command failed: yarn install
warning react-native > @react-native-community/cli-platform-ios > xcode > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

I have latest version of react-native and react-native-cli

**Comment by jerry-inc** [comment]
I am also facing this issue

`√ Downloading template
√ Copying template
√ Processing template
× Installing dependencies
error Error: Command failed: yarn install
warning react-native > @react-native-community/cli-platform-ios > xcode > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @react-native-community/eslint-config > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
error @typescript-eslint/eslint-plugin@5.7.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "15.9.0"
error Found incompatible module.
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by jerry-inc** [comment]
> I am also facing this issue
> 
> > √ Downloading template
> > √ Copying template
> > √ Processing template
> > × Installing dependencies
> > error Error: Command failed: yarn install
> > warning react-native > @react-native-community/cli-platform-ios > xcode > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> > warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro-core > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
> > warning react-native > @react-native-community/cli > @react-native-community/cli-plugin-metro > metro > metro-minify-uglify > uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
> > warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> > warning react-native > react-native-codegen > jscodeshift > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> > warning @react-native-community/eslint-config > babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
> > error @typescript-eslint/eslint-plugin@5.7.0: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "15.9.0"
> > error Found incompatible module.
> > yarn install v1.22.17
> > info No lockfile found.
> > [1/4] Resolving packages...
> > [2/4] Fetching packages...
> > info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> I am trying this on windows...

Nevermind. Solved this by installing the latest version of Node

**Comment by Ledenwifi** [comment]
You just need to install the latest version of Nodejs, it worked in my case.
