### ISSUE TITLE
Cannot invoke method isEmpty() on null object

### ISSUE THREAD

**Issue by kukuandroid** [react-native-community/cli#1489]
## Environment

RN : 0.63
MacOS : BigSur

## Description
Cannot invoke method isEmpty() on null object

Cannot invoke method isEmpty() on null object

**Comment by Flam3rboy** [comment]
I've found a workaround by editing ``/node_modules/@react-native-community/cli-platform-android/native_modules.gradle`` Line 275
```diff
-         if (!androidConfig["buildTypes"].isEmpty()) {
+         if (androidConfig["buildTypes"] && !androidConfig["buildTypes"].isEmpty()) {
```

**Comment by DevAnatolii** [comment]
Unfortunately, we faced with the same issue in Version 6.2.0. The problem is in line 275. 

Environment:
Android Studio: Artic Fox 2020| 3.1.0 Patch 3
**ANDROID GRADLE PLUGIN:** 7.0+
 minSdk             : 21
 targetSdk         : 30,
 compileSdk      : 30

**Comment by i-petro** [comment]
@Flam3rboy your workaround works, but it would be great if we had this line updated in the library

FYI @thymikee @DevAnatolii

**Comment by thymikee** [comment]
@i-petro PR welcome! :)

**Comment by DevAnatolii** [comment]
When this fix will be released?
