### ISSUE TITLE
'MODULE_NOT_FOUND', @react-native-community/cli

### ISSUE THREAD

**Issue by yunyami0605** [react-native-community/cli#1491]
## Ask your Question

I have a trouble with react-native-community/cli when command 'pod install' on ios folder

how to solve these problem?

[my react native project package version]
"@react-native-community/cli": "6.1.0",
"react": "17.0.2",
"react-native": "0.66.0"

[version]
xcode : 12.5.1
node: 16.11.0
cocoapods: 1.11.2 

<img width="1098" alt="스크린샷 2021-10-28 오후 12 09 19" src="https://user-images.githubusercontent.com/81840364/139179679-c46e3829-6748-4a5e-b88d-cc71d2560836.png">

**Comment by liamjones** [comment]
@yunyami0605 It _might_ be caused by your project living under the directory name containing Hangul(?) characters. Maybe try moving to to somewhere only using ASCII characters in the parent directory names and see if that fixes the issue?

**Comment by codydaig** [comment]
I have the exact same issue and I'm using a directory that I've been using for months to develop on react native without issues. `/Users/codydaig/dev/ioverlander/ioverlander-client-react` 

[version]
xcode: Xcode 13.1. Build version 13A1030d
node v14.18.0
pods: 1.11.2
Mac 11.6 (Intel)

**Comment by codydaig** [comment]
This works when I run it in terminal, but not in the terminal in VSCODE. (So annoying). It's consistently working in Terminal but not VScode.

**Comment by kesha-antonov** [comment]
I started to get this error after upgrading from RN 0.66.4 to 0.67.2

**Comment by yunyami0605** [comment]
Sorry to answer late.
i can solve this problem to install '@react-native-community/cli '
> @react-native-community/cli => 6.1.0
> react-native => 0.66.3

**Comment by kesha-antonov** [comment]
I solved it chaning like this in `android/app/build.gradle`
```
 project.ext.react = [
     enableHermes: true,  // clean and rebuild if changing
-    cliPath: new File(["node", "--print", "require.resolve('react-native/package.json')"].execute().text.trim(), "../cli.js"),
+    cliPath: "../../node_modules/react-native/cli.js"
 ]
```

**Comment by krmao** [comment]
still not work on mac m1 follow https://reactnative.dev/docs/integration-with-existing-apps

**Comment by lillian56** [comment]
> This works when I run it in terminal, but not in the terminal in VSCODE. (So annoying). It's consistently working in Terminal but not VScode.

me too, Have you solved the problem yet?

**Comment by krmao** [comment]
@kesha-antonov cliPath is not found in

```
   "@react-native-community/cli" "^7.0.3"
    "@react-native-community/cli-platform-android" "^7.0.1"
    "@react-native-community/cli-platform-ios" "^7.0.1"
```

please see (https://github.com/react-native-community/cli/issues/1600#issuecomment-1229240714)[https://github.com/react-native-community/cli/issues/1600#issuecomment-1229240714]

**Comment by kesha-antonov** [comment]
> @kesha-antonov cliPath is not found in
> 
> 
> 
> ```
> 
>    "@react-native-community/cli" "^7.0.3"
> 
>     "@react-native-community/cli-platform-android" "^7.0.1"
> 
>     "@react-native-community/cli-platform-ios" "^7.0.1"
> 
> ```
> 
> what is your version ?
> 
> 
> 
> 
> 
> please see (https://github.com/react-native-community/cli/issues/1600#issuecomment-1229240714)[https://github.com/react-native-community/cli/issues/1600#issuecomment-1229240714]

Sorry bro
I'm on the higher rn version and everything works

**Comment by krmao** [comment]
ok, we should be different problem, my android project is outter rn js project,[ latest code is same](https://github.com/react-native-community/cli/blob/main/packages/cli-platform-android/native_modules.gradle)
