### ISSUE TITLE
Update strip-ansi due to security vulnerability about ansi-regex(v4.1.0)

### ISSUE THREAD

**Issue by jcoyne** [react-native-community/cli#1506]
## Description
The cli package specifies strip-ansi 5.2.0.  This version pulls in a vulnerable version of ansi-regex.  Can strip-ansi be upgraded to 6.x or 7.x? 

https://github.com/react-native-community/cli/blob/master/packages/cli/package.json#L55

See:
* https://github.com/jest-community/jest-junit/pull/188
* https://github.com/chalk/strip-ansi/issues/40

**Comment by thymikee** [comment]
Feel free to submit a PR with a fix. I'd be happy to merge it :)

**Comment by jcoyne** [comment]
@thymikee I don't actually use react-native, it only ended up in my bundle by way of a indirect dependency (https://github.com/aws-amplify/amplify-js/issues/9119). So, while I can make this change. I have no way of testing that it still works.

**Comment by tex0l** [comment]
This is due to https://github.com/zamotany/logkitty/issues/32

**Comment by Brma1048** [comment]
Any updates on this? It's still using 4.1.0 with security vulnerability

**Comment by Brma1048** [comment]
and ora must also be updatet to a newer version
