### ISSUE TITLE
Upgrade ora in cli-types

### ISSUE THREAD

**Issue by jcoyne** [react-native-community/cli#1507]
## Description

ora version 3 pulls in a vulnerable version of strip-ansi (v4).  
https://github.com/react-native-community/cli/blob/master/packages/cli-types/package.json#L9

This dependency is fixed in ora version 6: https://github.com/sindresorhus/ora/commit/090860b50257f75f02dd5cd76b76025ca95311f0

**Comment by djc** [comment]
Note that ora is used in all of cli, cli-types and platform-ios.

I looked at upgrading it in cli, but it seems the `ora.Ora` class used here is no longer exported, so I'm not sure how that should be solved (I'm not that experienced with the Node ecosystem/TypeScript). If anyone has a pointer how that should be done, I'm happy to try and fix that.

**Comment by stianjensen** [comment]
I believe I've fixed most of that here, but I still have a few test failures to figure out:
https://github.com/react-native-community/cli/pull/1522
