### ISSUE TITLE
Project has flowconfig but no flow-bin

### ISSUE THREAD

**Issue by Brianzchen** [react-native-community/cli#1518]
## Description
So first time running `react-native init name` and process went well but I kept getting errors that flow couldn't be booted, took me a quick minute to check output and it turns out flow-bin doesn't get installed. Seems like it might be a quick one to just add [here](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/init/initCompat.ts#L76).

## Reproducible Demo
- Have `Flow Language Support` installed on vscode
- init a new project
- See flow fail to start over and over again

**Comment by grabbou** [comment]
Please go to React Native repository and open up an issue there. The template doesn't have the dependency here: https://github.com/facebook/react-native/blob/main/template/package.json
