### ISSUE TITLE
Gradle error - "task with that name already exists" native_modules.gradle

### ISSUE THREAD

**Issue by bensig** [react-native-community/cli#1528]
Perhaps someone has experienced this before or can point me in the right direction to debug.

I'm unable to build with any gradle commands. Any idea how to debug this duplicate gradle task? 

```
Script '<redacted>/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 296

* What went wrong:
A problem occurred evaluating project ':app'.
> Cannot add task 'generatePackageList' as a task with that name already exists.
```

Same failure in Android Studio:

```
Caused by: org.gradle.api.internal.tasks.DefaultTaskContainer$DuplicateTaskException: Cannot add task 'generatePackageList' as a task with that name already exists.
```

Thanks 🙏

**Comment by mitchellmcm27** [comment]
Hi @bensig check your `android/settings.gradle` and `android/app/build.gradle` files to make sure things aren't duplicated there. Specifically, lines that begin with `apply from:`. I somehow ended up with some of these being duplicated, which pulled in `task generatePackageList` more than once.

**Comment by addyaddy22** [comment]
go to android->app->build. graddle not android->graddle, in my case I found comment one of those. In my case, it worked. apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

**Comment by maksudkhan7706** [comment]
In my case to solve this simply go to android>build.gradle and search "react-native-vector-icons". If you found this twice then remove that line.

Thank You!

**Comment by mianaamirshehzad** [comment]
The is duplication of `apply from: file("../../node_modules/react-native-vector-icons/fonts.gradle")
` in the code. Step into **android/app/build.gradle** and search this line, you find the duplicates, remove one and rebuild your project.
