### ISSUE TITLE
[Security Warning] Cli-Doctor: Inefficient Regular Expression Complexity 

### ISSUE THREAD

**Issue by zizhang5** [react-native-community/cli#1547]
Cli-Doctor package uses strip-ansi@5.2.0 which uses ansi-regex@4.1.0 which contains to [a moderate severity vulnerability](https://github.com/advisories/GHSA-93q8-gq69-wqmw).

It should be updated to [strip-ansi@^6.0.1](https://github.com/chalk/strip-ansi/releases/tag/v6.0.1) or [strip-ansi@^7.0.1](https://github.com/chalk/strip-ansi/releases/tag/v7.0.1)

**Comment by Brma1048** [comment]
Please update
