### ISSUE TITLE
doctor: combo check for android gradle plugin < 7.1 iff react-native <= 0.68

### ISSUE THREAD

**Issue by mikehardy** [react-native-community/cli#1566]
## Describe the Feature
Doctor should determine the installed version of react-native (if one is installed), and if react-native is <= 0.68, it should verify that android gradle plugin is < 7.1

## Possible Implementations
Unknown, need to experiment

## Related Issues
#1554 - discussion of how to handle incompatibilities discovered after a react-native release
https://github.com/facebook/react-native/pull/33057 - PR where issue will be resolved

**Comment by mikehardy** [comment]
Needs a more fine-grained test if possible, even because of https://issuetracker.google.com/issues/159411906

If new architecture is enabled, android gradle plugin 7.2 will be needed or clean build fails, but plugin > 7.0 is not okay until react-native 0.69+ so there is a version range + feature set that simply has a known incompatibility, that can be communicated to users though

Noticed in https://github.com/reactwg/react-native-releases/discussions/13#discussioncomment-2255906

**Comment by cortinico** [comment]
> clean build fails

To clarify, calling `gradle clean` will fail. Not a clean build (i.e. building from a clean repo). But yeah, worth to address

**Comment by mikehardy** [comment]
sorry! exactly correct, imprecise wording on my part. I'm going to edit the comment to take this in to account, good catch
