### ISSUE TITLE
doctor: check for required catalyst build tweaks

### ISSUE THREAD

**Issue by mikehardy** [react-native-community/cli#1573]
## Describe the Feature

Building for catalyst is very difficult - if the user has SUPPORTS_MACCATALYST as YES -

Tweaks to check:
- dead code stipping is on (https://github.com/react-native-community/cli/issues/1572#issuecomment-1067177507)
- you have a development team set https://github.com/mikehardy/rnfbdemo/blob/cca01dd3f6209aed03c4ff80e590d57280f58257/make-demo.sh#L230
- you have the Podfile tweak that turns on adhoc signing for cocoapods resources (https://github.com/CocoaPods/CocoaPods/issues/8891#issuecomment-573301570)
- you have a fancy library path addition https://github.com/mikehardy/rnfbdemo/blob/cca01dd3f6209aed03c4ff80e590d57280f58257/make-demo.sh#L242-L243
- you have an entitlements file https://github.com/mikehardy/rnfbdemo/blob/cca01dd3f6209aed03c4ff80e590d57280f58257/make-demo.sh#L223-L226

## Possible Implementations
Mostly pbxproj verification with exception of the postinstall Podfile thing, not sure how to check Podfile contents other than a grep?

## Related Issues

https://github.com/facebook/flipper/issues/3117#issuecomment-1067136387

**Comment by cortinico** [comment]
As a side note: should those requirements be documented somewhere?

**Comment by mikehardy** [comment]
Almost certainly? :sweat_smile: This is not *really* the place to discuss it but I can make a website PR that adds (or edits?) a macCatalyst section and documents it, as well as the limitations. Probably shouldn't merge that until 68 since it'll build-break for a lot of people until 0.68 is out with the fixes for things that broke from 0.65-0.67. Good thought though, right now there's exactly one mention of catalyst and it's just an announcement

![image](https://user-images.githubusercontent.com/782704/158800443-4c7fa6ad-4ab5-42c5-acf8-f32a3e63668e.png)

Ironically for 0.65, which will not compile if people try to use flutter :-). A tangled web we weave

**Comment by cortinico** [comment]
I think that we can have a page under the iOS guides here:

![Screenshot 2022-03-17 at 18 17 44](https://user-images.githubusercontent.com/3001957/158869457-a7df61c8-8131-4789-a3cd-85b66b8f1442.png)
