### ISSUE TITLE
Package react-native-webview has been ignored because it contains invalid configuration

### ISSUE THREAD

**Issue by gonglixin980926** [react-native-community/cli#1581]
## Ask your Question

I am trying to use  react-native-webview and following step. But it doesn't work.

yarn add react-native-webview
cd ios && pod install && cd .. # CocoaPods on iOS needs this extra step
# run
yarn react-native run-ios

There is my problem.
![image](https://user-images.githubusercontent.com/40887236/161053152-25bfb438-c150-4d28-8fcb-88d4d8aabcbc.png)

I also tried other methods, such as: re-' npm i ', but nothing happened

**Comment by thymikee** [comment]
Which version of the `@react-native-community/cli` you're using?

**Comment by gonglixin980926** [comment]
"react-native": "0.67.4", 
"@react-native-community/cli": "^7.0.3",

**Comment by gonglixin980926** [comment]
> Which version of the `@react-native-community/cli` you're using?

"react-native": "0.67.4",
"@react-native-community/cli": "^7.0.3",

**Comment by thymikee** [comment]
Interesting. Please file this ticket in the react-native-webview repo, ok? Closing this for now

**Comment by gonglixin980926** [comment]
OK

**Comment by gonglixin980926** [comment]
> Interesting. Please file this ticket in the react-native-webview repo, ok? Closing this for now

ok

**Comment by gonglixin980926** [comment]
> Interesting. Please file this ticket in the react-native-webview repo, ok? Closing this for now

![image](https://user-images.githubusercontent.com/40887236/161055271-c21abfb4-0d30-47e7-a910-bc96b4f1c01b.png)
The version of `@react-native-community/cli` in `react-native` is 6.0
