### ISSUE TITLE
Android Gradle SDK Changes

### ISSUE THREAD

**Issue by cyb3rsalih** [react-native-community/cli#159]
## Describe the Feature
Each time I build a RN project in Android. I am getting same
warnings during build phase. It says
`Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.`
`Configuration 'testCompile' is obsolete and has been replaced with 'testİmplementation'.`
etc.

Some of these warnings will appear until March 2019. After this date builds may fail.

## Possible Implementations
This replacements can applied during `react native init`

**Comment by thymikee** [comment]
This is now fixed in default template and in most 3rd party libraries out there. Not actionable on our side. Closing.
