### ISSUE TITLE
react native upgrade command need proxy support

### ISSUE THREAD

**Issue by biaji** [react-native-community/cli#1593]
## Describe the Feature
`npx react native upgrade` command does not support proxy, and throw error like:

```
info Fetching diff between v0.66.4 and v0.68.1...
error request to https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.66.4..0.68.1.diff failed, reason: connect ENETUNREACH 185.199.111.133:443
error Failed to fetch diff for react-native@0.68.1. Maybe it's not released yet?
```

## Possible Implementations
Maybe we can detect proxy from env and use [node-http-proxy-agent](https://github.com/TooTallNate/node-http-proxy-agent) as fetch implement?

**Comment by youniaogu** [comment]
you can set proxy in terminal like [this](https://askubuntu.com/questions/583797/how-to-set-a-proxy-for-terminal)

**Comment by biaji** [comment]
> you can set proxy in terminal like [this](https://askubuntu.com/questions/583797/how-to-set-a-proxy-for-terminal)

I'm not sure about this.  As I practiced,  It doesn't work.

**Comment by M45ter** [comment]
same problem

**Comment by hgsantana** [comment]
Same problem here.

My terminal is all set up with proxy variables and everything works fine, but react-native cli.

**Comment by cnhuz** [comment]
same problem
