### ISSUE TITLE
yarn ios --device: No iOS devices found

### ISSUE THREAD

**Issue by jakerieger** [react-native-community/cli#1597]
We're not sure if this is a bug with RN CLI or something with Xcode, but as of April 17th, we can no longer run any RN projects on our iPhone as the command `yarn ios --device` returns `No iOS devices found`. Running `ios-deploy -c` lists our device but `xcrun xctrace list devices` does not. Finder also shows the phone is connected and so does the Xcode app. We've tried reinstalling Xcode devtools to no avail. We found this article from a year ago describing the exact same issue: [https://lifesaver.codes/answer/react-native-run-ios-device-not-working-with-xcode-12-5-cli-tools-1404](https://lifesaver.codes/answer/react-native-run-ios-device-not-working-with-xcode-12-5-cli-tools-1404) however the patch described has been fixed since Xcode 12.5 came out so it doesn't apply to us.

Wondering if anyone has had a similar issue or has any ideas on how to resolve it. At the moment we can use the simulator without issue but it's really slowed down our development workflow.

We're running the latest version of Xcode, iOS and macOS along with RN CLI 6.2.0

**Comment by liamjones** [comment]
Have you tried Xcode 13.3.1? `xcrun xctrace list devices` lists my iOS 15.4.1 device with that version of Xcode.

**Comment by jakerieger** [comment]
@liamjones Thanks, I guess we were using 13.2 and I failed to notice.
