### ISSUE TITLE
Migrate off lerna

### ISSUE THREAD

**Issue by thymikee** [react-native-community/cli#1599]
## Describe the Feature

Lerna is currently unmaintained. Even though it may likely change for better, I think it's a nice opportunity to try something different.
My favorite so far I guess: https://github.com/vercel/turborepo/tree/main/examples/with-changesets. Let's give it a shot. cc @kbieganowski

**Comment by TMisiukiewicz** [comment]
not stale

**Comment by TMisiukiewicz** [comment]
@thymikee what's the status here? As i can see Lerna is being maintained again, so it could be eventually upgraded, or do you still want to move to sth else?

**Comment by szymonrybczak** [comment]
After internal conversation, Lerna is still maintained so we'll stay with it in the CLI.
