### ISSUE TITLE
No longer possible to disable autolinking for specific platforms

### ISSUE THREAD

**Issue by tido64** [react-native-community/cli#1612]
## Environment

```
System:
    OS: macOS 11.6.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 23.41 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - /private/var/folders/qc/zygl93h53zb3ctbyw0f0jbzm0000gn/T/xfs-ac3821f8/node
    Yarn: 3.1.1 - /private/var/folders/qc/zygl93h53zb3ctbyw0f0jbzm0000gn/T/xfs-ac3821f8/yarn
    npm: 8.6.0 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: ^0.66.4 => 0.66.4
    react-native-macos: ^0.66.14 => 0.66.55
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

According to the docs, it is possible to disable autolinking for certain platforms:

https://github.com/react-native-community/cli/blob/c4179d8c0d956fe226d839c85b9887ec3c8c6892/docs/autolinking.md?plain=1#L73-L86

However, this seems to no longer work.

This is what `react-native config` looks normally:

```json
{
  "root": "/~/example",
  "reactNativePath": "/~/example/node_modules/react-native",
  "dependencies": {
    "react-native-test-app": {
      "root": "/~",
      "name": "react-native-test-app",
      "platforms": {
        "ios": {
          "sourceDir": "/~/example/ios",
          "folder": "/~",
          "pbxprojPath": "/~/ios/ReactTestApp.xcodeproj/project.pbxproj",
          "podfile": "/~/example/ios/Podfile",
          "podspecPath": "/~/ReactTestApp-DevSupport.podspec",
          "projectPath": "/~/ios/ReactTestApp.xcodeproj",
          "projectName": "ReactTestApp.xcodeproj",
          "libraryFolder": "Libraries",
          "sharedLibraries": [],
          "plist": [],
          "scriptPhases": [],
          "configurations": []
        },
        "android": null,
        "macos": null,
        "windows": null
      },
      "assets": [],
      "hooks": {},
      "params": []
    }
  }
}
```

If I change `react-native.config.js` to:

```js
module.exports = {
  dependency: {
    platforms: {
      android: null,
    },
  },
};
```

The output becomes:

```json
{
  "root": "/~/example",
  "reactNativePath": "/~/example/node_modules/react-native",
  "dependencies": {}
}
```

## Reproducible Demo

```
git clone https://github.com/microsoft/react-native-test-app.git
cd react-native-test-app
yarn

# open react-native.config.js and add `android: null`

cd example
yarn react-native config
```

**Comment by tido64** [comment]
cc @thymikee

**Comment by thymikee** [comment]
I've noticed you're using RN 0.66 and yarn v3 with workspace setup. Does it also happen on RN 0.68? Would be great if you'd be able to check with the latest version of the CLI (v8), although I don't recall changes in this space. Did it work before some changes/upgrades?

**Comment by tido64** [comment]
I wonder if this has ever worked since the introduction of `joi`. Modifying the [schema](https://github.com/react-native-community/cli/blob/9402009aed42439e3f1d4645939df039439a3812/packages/cli-config/src/schema.ts#L76) lets me continue, but it crashes inside the platform packages since it expects `userConfig` to be nonnull.

Do we consider this a regression, bug in docs, or a new feature to be implemented?

**Comment by thymikee** [comment]
Hm, I guess we documented a case that never actually worked, or haven't in a really long time. There's no test case for that as well. It should be supported though.

Btw, we also allow overwriting from the app/project level, if you need to get unblocked:
```js
module.exports = {
  dependencies: {
    "react-native-test-app": {
      platforms: {
        ios: null,
      },
    },
  },
}
```
If all platforms are nulled it won't show the dependency at all

**Comment by tido64** [comment]
I kinda worked around it with [`typealias`es](https://github.com/microsoft/react-native-test-app/pull/843/files#diff-b9ce41f42536997921d6c5302b7d6eb07c695553a184d84a092f38b2e68d4176) 😛 

In any case, I can probably take a look at this later. It works for `macos` and `windows`, so it's kinda weird that it would fail for `android`/`ios`.
