### ISSUE TITLE
Autolinking silently ignored for projects not following new schema

### ISSUE THREAD

**Issue by oblador** [react-native-community/cli#1619]
## Environment

<details>
<pre>
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 572.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /var/folders/71/_l5989nn5pbfkmj5_fym3xn00000gp/T/yarn--1653987108916-0.9631595489427285/node
    Yarn: 1.22.10 - /var/folders/71/_l5989nn5pbfkmj5_fym3xn00000gp/T/yarn--1653987108916-0.9631595489427285/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
    Watchman: 2022.02.14.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/joel.arvidsson/.asdf/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 30, 31, 32
      Build Tools: 30.0.2, 31.0.0, 32.0.0, 32.1.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.0-rc.3 => 0.69.0-rc.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
</pre>
</details>

## Description

With PR https://github.com/react-native-community/cli/pull/1537 the schema for `react-native.config.js` change quite dramatically. Several libraries I use are now silently ignored and it took me a while to figure out that for example having an empty `assets` definition caused the config to be rejected and thus not autolinked. I propose that the CLI should throw with an error message instead of just ignoring it. 

## Reproducible Demo

Create a new vanilla project with 0.69, add `react-native-navigation` and observe it not being autolinked on ios.

**Comment by thymikee** [comment]
This hit me in one of the sample projects when I was debugging some autolinking issues, so fully support this. We currently log these as "errors" but don't halt the execution. Additionally when only running `config` command, we disable the console output, so the errors are silenced. They're only visible once you build or run the app.
