### ISSUE TITLE
`config` traversing the entire project paths and reading every single file

### ISSUE THREAD

**Issue by f0o** [react-native-community/cli#1621]
## Ask your Question

Hi,

I noticed `config` being called by gradle and it being seemingly stuck so I issued the command through `strace` and saw that it opens _EVERY SINGLE FILE_ that exists in the repo (regardless of type) which obviously takes a very very very very very very very very long time in some cases (specially when using gradle's `--build-cache `).

So the Question is: Why?
Why is it doing that to construct an object that lists perhaps 20 paths?

Is there no way to filter this and make it more optimized? it seems to only post things starting with `react-native-*` yet accesses every single module and project file in existence for that.

The sheer amount of statx() calls isnt even the issue but the fact that it opens and reads from them makes it particularly fun when it opens binary files or APK artifacts...

Is this really by design??

**Comment by thymikee** [comment]
It's just unoptimized. We'll welcome any kind of improvements, like caching or better resolution strategy as a PR :)

**Comment by f0o** [comment]
Happy to, just trying to find the culprit here. Right now I'm "solving" it by nuking node_modules after every build and reinstalling things
