### ISSUE TITLE
add support for `react-native run-ios --simulator booted`

### ISSUE THREAD

**Issue by pvinis** [react-native-community/cli#1624]
## Describe the Feature

`react-native run-ios --simulator booted` should use the simulator that is already booted.
`simctl` has this alias  named`booted` that will replace with whatever udid the booted simulator has.

`react-native run-ios --simulator booted` gives `error No simulator available with name "booted".`

## Related Issues
https://github.com/facebook/react-native/issues/34057

**Comment by adamTrz** [comment]
Fixed by #1756
