### ISSUE TITLE
How to add a custom font with autolinking

### ISSUE THREAD

**Issue by danbudworthmead** [react-native-community/cli#1627]
## Ask your Question

Hi, I have a font in assets/fonts/

and I have this react-native.config.js file. But when I set fontFamily to that font, it doesn't work.

`module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  assets: ['./assets/fonts/'],
};
`

**Comment by danbudworthmead** [comment]
After about 5 hours of searching. Finally found it

npx react-native-asset

running this fixed my issue. I feel like it should do this as part of autolinking though...

**Comment by kuzkokov** [comment]
I believe this is still legitimate question. 
`react-native-asset` was last time published 2 years ago, so I am not sure if this is the best way to link fonts.
