### ISSUE TITLE
confused about "--project-path" removal

### ISSUE THREAD

**Issue by TomSwift** [react-native-community/cli#1634]
I see that in version 8 we no longer have a `--project path` option for `run-ios`.   The docs suggest this path is now set in the "project configuration".   But I don't see how I can support multiple native hosts for my single project.

That is, I have a single react-native codebase, and I have multiple native host apps.   How can I designate which to build when using run-ios?

**Comment by adamTrz** [comment]
Hi @TomSwift , what do you mean by "native host apps"? Like different build variants and flavours?

**Comment by bigorangemachine** [comment]
@adamTrz  & @TomSwift 

I think I am investigating this issue now.  I'm trying to leverage [project config](https://github.com/react-native-community/cli/blob/main/docs/platforms.md#projectconfig) (as per docs).

What I see so far is after loading the config it doesn't include `project[platform]` provided value I set in `sourceDir`.  The value is null.

We're trying to use this configuration override to the pod install process so we can have our app as a cocoa pod.  So I assume its similar to what Tom was suggesting.

**Comment by Arjan-Zuidema** [comment]
I am currently in the progress of updating the example project for [CameraRoll](https://github.com/react-native-cameraroll/react-native-cameraroll) to the latest version of react-native. We are using `--project-path` [here](https://github.com/react-native-cameraroll/react-native-cameraroll/blob/master/package.json#L24) to run the project in the example directory. Would be nice if this option returns.
