### ISSUE TITLE
react-native init with multiple arguments.

### ISSUE THREAD

**Issue by swizes** [react-native-community/cli#1636]
## Using init command with multiple arguments

I was trying to init rn v0.68.2 with typescript template and I was always getting latest version with typescript template. It seems that the --version command gets overwritten. Is it on purpose?

both commands does not work as expected.

`npx react-native init AwesomeTSProject --version 0.68.2 --template react-native-template-typescript `
`npx react-native init AwesomeTSProject --template react-native-template-typescript --version 0.68.2`

**Comment by thymikee** [comment]
It's on purpose. Use:
```
npx react-native init AwesomeTSProject --template react-native-template-typescript@0.68.2
```

**Comment by swizes** [comment]
> It's on purpose. Use:
> 
> ```
> npx react-native init AwesomeTSProject --template react-native-template-typescript@0.68.2
> ```

Hello, I have tried the following command 

```
npx react-native init AwesomeTSProject --template react-native-template-typescript@0.68.2
```

and got the following error output

```
error Error: Command failed: yarn add react-native-template-typescript@0.68.2
error Couldn't find any versions for "react-native-template-typescript" that matches "0.68.2"
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command
```

**Comment by liamjones** [comment]
@swizes The react-native-typescript-template project doesn't number their releases in sync with RN. It looks like you probably want [release tag 6.10.4](https://github.com/react-native-community/react-native-template-typescript/releases/tag/6.10.4) since that was the last one on the project before they moved to 0.69.0.

**Comment by cortinico** [comment]
Reviving this as I believe this is a weird behavior we might want to warn the user about. See https://github.com/facebook/react-native/issues/34681

**Comment by thymikee** [comment]
Happy to accept a PR adding a warning about this behavior when both `--version` and `--template` are used
