### ISSUE TITLE
Allow to configure different node_modules location

### ISSUE THREAD

**Issue by huyvuskedulo** [react-native-community/cli#1638]
## Describe the Feature
React Native should allow to define different location for node_modules for package locator instead of always define it as "../node_modules". It's because in our project, we only use some of our screen in React Native (for dynamic content from the server), and our projects are in separate repos for iOS and Android

Something look like
- root iOS Project (Repo)
-- node_modules
-- ....

- root android Project (Repo)
-- node_modules
-- ....

Therefore, we need a way to tell RN CLI to look for the node_modules packages and generate PackageList.java (also other stuff) in different location. In this case, which was "./node_modules", not "../node_modules"

**Comment by whhotw** [comment]
+1

**Comment by abbenyyyyyy** [comment]
+1

**Comment by adamTrz** [comment]
`sourceDir` option put into `react-native.config.js` should allow that :)
