### ISSUE TITLE
Critical security vulnerability in shell-quote <=1.7.2, dependency in cli 7.x

### ISSUE THREAD

**Issue by msrww** [react-native-community/cli#1641]
A critical security vulnerability exist in shell-quote <=1.7.2 which is an internal dependency of cli 7.x ([specifically in cli-tools](https://github.com/react-native-community/cli/blob/7.x/packages/tools/package.json#L17)). This affects all current React native <=0.68.x projects since they depend on @react-native-community/cli@7.0.3 or earlier.

Need to upgrade shell-quote to 1.7.3 for cli 7.x

Reference: https://github.com/advisories/GHSA-g4rg-993r-mgx7

**Comment by msrww** [comment]
When do we expect to get this published as a new release for @react-native-community/cli-tools?

**Comment by bradjones1** [comment]
What version is this encapsulated in? The latest 7.x release on NPM is from February? https://www.npmjs.com/package/@react-native-community/cli-tools
