### ISSUE TITLE
error Invalid platform "android" selected Apple M1 Silicon

### ISSUE THREAD

**Issue by thomasarogers** [react-native-community/cli#1654]
## Environment

Im not sure why it is saying react-native not found or @react-native-community/cli not found as I have installed the cli globally and when I run react-native I get the help

System:
    OS: macOS 12.5
    CPU: (8) x64 Apple M1
    Memory: 237.79 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: Not Found
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/thomas/.rvm/gems/ruby-2.3.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description
Trying to manually bundle Android react native project as never works via Android Studio by running below command before doing a project build:
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

Has always previously worked but failing with error below have restarted, and tried with Node 12, 14,15 and 16 as well as platform value 'ios'

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/42372294/180433715-d7d1f26e-e4b3-47b0-a4ab-1b398d69f4f6.png">

## Reproducible Demo
Just run the command above

**Comment by sudhanshusirohia** [comment]
error Invalid platform "android" selected.
@thomasarogers  how did you solve it?

**Comment by mansguiche** [comment]
> error Invalid platform "android" selected. @thomasarogers how did you solve it?

I just had this problem in a CI pipeline and could not replicate it on my local machine. Turns out I was missing the `npm ci` step to install node modules. These were already installed on my local which was why there was a difference. Hopefully you have the same issue as I did.

Best of luck

**Comment by sudhanshusirohia** [comment]
We had incorrect path value for "root" configuration in build.gradle, after fixing the same it worked fine.
