### ISSUE TITLE
List Available Apple Devices

### ISSUE THREAD

**Issue by esthor** [react-native-community/cli#1673]
## Describe the Feature
Instead of passing the `--simulator "{some apple device simulator string}"` I would like an _interactive_ option to first list the available simulators and select the one I want.

## Possible Implementations
1. add a `list` command of `--list` flag to `run-ios` command
2. Reuse available device listing & parsing logic in `findMatchingSimulator.ts` to print the devices to the console
3. User can use arrows to select the device
4. The selected devices is passed to a `react-native run-ios --simulator "{selected apple device simulator name}"` command

## Related Issues
Not in this repo, but a very popular tool called `ohmyzsh` has a [plugin for react-native](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/react-native), and to be up-to-date it is manually updated with device simulator flags. I think this main benefit of this aliasing plugin would be surpassed by an interactive `list` available devices function in the CLI itself.

For those not using the above ohmyzsh plugin, having this part of the CLI itself would be easier and clearer, and users wouldn't need to open up xCode to see available simulators or run `xcrun simctl list devices` either.

I'm happy to work on it, but wanted to know first if it would be well-received or not. 🙏

**Comment by thymikee** [comment]
Sounds like something useful, happy to review PR :)

**Comment by esthor** [comment]
Awesome, @thymikee. Thanks.

Do you know of any interactive cli functionality already in the repo? I didn't find anything in a quick glance. I want to make sure I don't introduce some new pattern if there already is an established one.

**Comment by thymikee** [comment]
Doctor command has some, you can check that

**Comment by esthor** [comment]
Thanks! I also found an unrelated bug while working on this, and put up a PR: https://github.com/react-native-community/cli/pull/1675

**Comment by szymonrybczak** [comment]
Closing since it's done by https://github.com/react-native-community/cli/pull/1676.
