### ISSUE TITLE
Use react-native start

### ISSUE THREAD

**Issue by Esemesek** [react-native-community/cli#168]
After `global-cli` will be removed, and whole `init` command will exist in `@react-native-community/cli` we should preserve strategy to use `react-native start` (https://github.com/react-native-community/react-native-cli/blob/master/packages/global-cli/index.js#L235)instead of `cli.js` script. We should also add deprecation notices in `cli.js` in `react-native` repository.

**Comment by grabbou** [comment]
What we should do here?

**Comment by Esemesek** [comment]
Default template already has `react-native start` in `start` script in `package.json`. Right now, there are 2 files called `cli.js` in `react-native` repo. We need one as an entry point for `init` command, so we need to keep at least one `cli.js` there. I think we should deprecate only `local-cli/cli.js`.

**Comment by thymikee** [comment]
@Esemesek I'm gonna close this issue as it refers to RN core repository. Feel free to suggest adjustments there, although I think there's still quite a bunch of tooling relying on `local-cli/cli.js` being present
