### ISSUE TITLE
Set a default iOS simulator

### ISSUE THREAD

**Issue by safaiyeh** [react-native-community/cli#169]
`react-native run-ios` defaults to the iPhone X simulator; however, my preference is to use the iPhone XS Max. Could we have a way to set a default simulator? I understand there is a `--simulator` option; however, I would like a faster way to switch between simulators.

## Possible Implementations
`react-native set ios-simulator="iPhone XS Max"`

**Comment by maieonbrix** [comment]
Hello ! My I work on this if the community reallyd needs it ?
Maybe I can display a list of the available simulators so that the user can know which one to target
I managed to found that the cli.js takes into account the --simulator argument so you can to what you want from now on @JSafaiyeh by doing this : 

```
react-native run-ios --simulator='iPhone XS Max'
```

It has to be the exact name simulator name.

Maybe instead of displaying a list I could just update the documentation ?

**Comment by thymikee** [comment]
@maieonbrix we'd love to have docs on that! Unfortunately, they don't exist yet. If you feel like it, how about starting to write the `packages/cli/README.md` in small steps? You can base it on what we already have inside `README.md` and `packages/global-cli/README.md` 😃

**Comment by thymikee** [comment]
As for @JSafaiyeh, stuff like that would require CLI config, which we haven't established yet. 
 
Also in the topic: https://github.com/react-native-community/react-native-cli/issues/12

**Comment by maieonbrix** [comment]
@thymikee I would be glad to do this ! I'm counting on you to review my english 😅 
I will work on this tomorrow night (in France)

How should I name the first header ? Or maybe can I just start with an option section like here : https://github.com/react-native-community/react-native-cli/blob/master/packages/global-cli/README.md#options and documenting what I can found in the cli.js file

**Comment by thymikee** [comment]
Yup, start small, with just the options header for now

**Comment by AmirHMousavi** [comment]
> Hello !
> 
> I managed to found that the cli.js takes into account the --simulator argument so you can do what you want from now on @JSafaiyeh by doing this :
> 
> ```
> react-native run-ios --simulator='iPhone XS Max'
> ```
> 
> And putting this into a npm script should do the trick for now \o/ :
> 
> ```
> "scripts": {
>    "ios": "react-native run-ios --simulator='iPhone XS Max"
> ...
> 
> $ npm run ios
> ```
> 
> It has to be the exact same name as the official simulator name.
> 
> I think that documenting this might be sufficient ? or not ?
> 
> (just to share, it was really satisfying to found the relevant bits of code, it's so damn well organized ! 💥 )

This does not set the default simulator, the next time you run `yarn ios` or `react-native run-ios` the wrong simulator starts.
