### ISSUE TITLE
When running npx react-native xxxx, it will let me download react-native@0.69.5, and then failed with errors

### ISSUE THREAD

**Issue by xiaohui-gsv** [react-native-community/cli#1692]
I want to initiate a new react-native 0.69 project, so I uninstall the `react-native-cli` with `npm uninstall -g react-native-cli`, and then I run the `npx react-native init rn69`, the prompt let me to download react-native@0.69.5, and then error happens, please refer to below screenshot:
<img width="611" alt="image" src="https://user-images.githubusercontent.com/38554198/187643941-291725f2-1564-4991-9c8b-e60ff09c0ab7.png">

Below is the log
[2022-08-31T09_13_40_737Z-debug-0.log](https://github.com/react-native-community/cli/files/9460265/2022-08-31T09_13_40_737Z-debug-0.log)

My node version is `16.17.0`

Thank you

**Comment by xiaohui-gsv** [comment]
Hi @adamTrz , I just tried, doesn't work. thank you.

**Comment by xiaohui-gsv** [comment]
Hi @adamTrz , the log said that found react-native@0.67.4, and I found this under `.npm/_npx` folder, please refer to below screenshot, I'm not sure if this has anything to do with him. Thank you.
<img width="806" alt="image" src="https://user-images.githubusercontent.com/38554198/187825255-c28b71fa-2e78-4f53-a3b1-df78aa91b720.png">

**Comment by adamTrz** [comment]
Try to delete `_npx` folder as well maybe?

**Comment by xiaohui-gsv** [comment]
@adamTrz will the `_npx` deletion affect my current project? since I have some projects base on 0.67.4, :)

**Comment by adamTrz** [comment]
It shouldn't I think :)
You can always make a copy just for safekeeping and rename it to sth like `_npx_backup`
Sth like that maybe? `cp -a /_npx/. /_npx_backup/`

**Comment by xiaohui-gsv** [comment]
It works, haha, thank you @adamTrz .
