### ISSUE TITLE
Could not find method isNewArchitectureEnabled() for arguments on project :app of type org.gradle.api.Project

### ISSUE THREAD

**Issue by sabinss** [react-native-community/cli#1696]
## Environment

System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.98 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: ^9.0.0 => 9.0.0 
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

![Screenshot 2022-09-05 at 10 03 45](https://user-images.githubusercontent.com/20257589/188361322-dc3fe5c7-7a78-425a-afcb-f18f6ec45d25.png)

## Reproducible Demo

npm run android giving above error

**Comment by thymikee** [comment]
RN CLI v9 is not intended for RN 0.63, but for 0.70. Please don't use the `@react-native-community/cli` dependency directly. Remove it and leverage `npx react-native` which calls correct version of the CLI under the hood.

**Comment by allemanfredi** [comment]
I'm using `"@react-native-community/cli": "v9.0.0-alpha.5"` but i get the same error.

**Comment by allemanfredi** [comment]
I'm using RN CLI v9 but i get the same error

**Comment by allemanfredi** [comment]
This is a patch that (i think) solves the above error. 

```diff
diff --git a/node_modules/@react-native-community/cli-platform-android/native_modules.gradle b/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
index 86bde62..7f06fa7 100644
--- a/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
+++ b/node_modules/@react-native-community/cli-platform-android/native_modules.gradle
@@ -544,7 +544,7 @@ ext.applyNativeModulesAppBuildGradle = { Project project, String root = null ->
 
   preBuild.dependsOn generatePackageList
 
-  if (isNewArchitectureEnabled()) {
+  if (project.hasProperty("newArchEnabled") && project.newArchEnabled == "true") {
     preBuild.dependsOn generateNewArchitectureFiles
   }
 ```

Unfortunately now i get another error but i think it's not related to this.

```
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Failed to transform hermes-enginehermes-debug.aar to match attributes {artifactType=android-manifest}.
```

**Comment by allemanfredi** [comment]
SOLVED: i had to change `build.gradle` like [here](https://github.com/react-native-community/react-native-template-typescript/blob/main/template/android/app/build.gradle#L307).
