### ISSUE TITLE
Build failed on Android after upgrading to react-native@0.70.0

### ISSUE THREAD

**Issue by mshavandi** [react-native-community/cli#1697]
## Environment

System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.46 GB / 15.84 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8815526
    Visual Studio: Not Found
  Languages:
    Java: 11.0.13
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.0 => 0.70.0
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

After upgrading from react-native@0.68.2 to 0.70.0, running on Android fails with the following error: (Windows)
```
Script ...node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 547       

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method isNewArchitectureEnabled() for arguments [] on project ':app' of type org.gradle.api.Project.
```

## Reproducible Demo

- Create a project with react-native@0.68.2
- Run `npx react-native upgrade`
- Run `yarn android`

**Comment by thymikee** [comment]
Is it possible you haven't updated your app/build.gradle to include the `isNewArchitectureEnabled` helper? Looking at https://react-native-community.github.io/upgrade-helper/?from=0.68.2&to=0.70.0 the helper is already there for 0.68 so maybe it was omitted earlier?

**Comment by vieMengm** [comment]
add this to the bottom of your build.gradle like this

`def isNewArchitectureEnabled() {
    // To opt-in for the New Architecture, you can either:
    // - Set `newArchEnabled` to true inside the `gradle.properties` file
    // - Invoke gradle with `-newArchEnabled=true`
    // - Set an environment variable `ORG_GRADLE_PROJECT_newArchEnabled=true`
    return project.hasProperty("newArchEnabled") && project.newArchEnabled == "true"
}`

**Comment by buasuwan** [comment]
I got the same error. There is no folder "/node_modules/hermes-engine"
Please try.

npm i hermes-engine  
or
yarn add hermes-engine  

After this error was gone, I had another problem. My app can't run on the Android emulator.

> ```
> Execution failed for task ':app:mergeDevDebugAssets'.
> > Could not resolve all files for configuration ':app:devDebugRuntimeClasspath'.
>    > Failed to transform hermes-debug.aar to match attributes {artifactType=android-assets}.
>       > Execution failed for JetifyTransform
> ```
