### ISSUE TITLE
Pipe stderr to 'inherit'

### ISSUE THREAD

**Issue by LitileXueZha** [react-native-community/cli#1712]
## Describe the Feature

react-native cli output errors when execute other programs, contains messy characters, usually in no-utf8 environment. It's very hardly to debugging.

## Possible Implementations

https://github.com/react-native-community/cli/blob/e89f296b1f1b27da23ffb77e3c8fc5bc2f4942ee/packages/cli-platform-android/src/commands/runAndroid/runOnAllDevices.ts#L89

**Comment by adamTrz** [comment]
Hi @LitileXueZha  - could you elaborate more on your feature request and what can be improved here?
