### ISSUE TITLE
Cannot find module 'ora'

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [react-native-community/cli#1713]
## Environment

System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.30 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
    Watchman: 2022.10.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.16.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

When starting the application using `npm run ios`, I am getting an error for this [library](https://www.npmjs.com/package/ora)
> Cannot find module 'ora' 

## Reproducible Demo

Create a new app using `"react-native": "0.64.0"`.
Run iOS app with `npm run ios`

**Comment by adamTrz** [comment]
Hi @ZeeshanAhmadKhalil - I wasn't able to reproduce this error - iOS app launched successfully. 
Have you installed `node_modules` and `pods` as per [docs](https://reactnative.dev/docs/environment-setup#installing-dependencies)?  
Closing as no repro but feel free to reopen if the issue pertains.
