### ISSUE TITLE
How do I check if an app is installed on phone?

### ISSUE THREAD

**Issue by whyashif** [react-native-community/cli#1714]
How do I check if an application exists on phone.And make a conditional button.For eg:  if whatsapp exists on phone then only it will show open in whatsapp. Please help me out. ## Ask your Question

**Comment by adamTrz** [comment]
I don't think it's possible to do a conditional button. Maybe you can try to use `Linking` module like described [here](https://stackoverflow.com/questions/52440796/how-to-check-if-whatsapp-is-installed-on-device)?

That being said it's definitely not issue with CLI so closing the ticket :)
