### ISSUE TITLE
Error on build in ios

### ISSUE THREAD

**Issue by roysG** [react-native-community/cli#1718]
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 90.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.11.0 - /usr/local/bin/npm
    Watchman: 2022.08.29.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0.1/14A400 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

I attached the errors on build
<img width="453" alt="Screen Shot 2022-10-16 at 17 20 19" src="https://user-images.githubusercontent.com/7311802/196041048-e8b10169-7b3a-45f3-ab0f-b7698c106b25.png">

**Comment by adamTrz** [comment]
Hi @roysG - could you please try to build app with terminal instead? Maybe we would be able to find some more meaningful error logs there :)
