### ISSUE TITLE
Cannot get Turbo Native Example to build on M1 Mac

### ISSUE THREAD

**Issue by tmchale** [react-native-community/cli#1725]
I am trying to get a simple RN app to build accessing a Turbo Native ObjC++ module. I followed the example in the Turbo Native docs (https://reactnative.dev/docs/next/the-new-architecture/pillars-turbomodules). I did comment out fabric_enabled and flipper lines from the Podfile and that got rid of some warnings. But I still get this error and I do not know how to solve it:

The following build commands failed:
        CompileC /Users/MCHALTX1/Library/Developer/Xcode/DerivedData/adcConsoleApp-eudyfqiurftvwseixxuzruouwnqy/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/rtn-dcs.build/Objects-normal/arm64/RTNDcs.o /Users/MCHALTX1/testdev/reactProjs/MyProject/MyProject/node_modules/rtn-dcs/ios/RTNDcs.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'rtn-dcs' from project 'Pods')
(1 failure)

I am stuck as to how to fix this.

**Comment by tmchale** [comment]
After some diagnosis and getting to build in Xcode I think the problem is this. In the docs referenced above the last thing to do on iOS is make the RTNCalculator .h and .mm files. They respectively reference NativeCalculatorSpec and NativeCalculatorSpecJSI, both of which I cannot find defined anywhere. Are these typos?

**Comment by adamTrz** [comment]
Hi @tmchale 
Sorry for late reply, verified the issue, followed [TurboModules guide](https://reactnative.dev/docs/the-new-architecture/pillars-turbomodules#ios) and iOS app works for me.  
Could you please recheck? 
Closing the issue for now but more than happy to reopen if it's still valid :)
