### ISSUE TITLE
Redirect react-native-template-typescript to react-native

### ISSUE THREAD

**Issue by thymikee** [react-native-community/cli#1740]
## Describe the Feature

From RN 0.71 RN will be the default template language, which removes the need for the `react-native-template-typescript` template. To ease the migration, as this way of starting a TS project is referenced all over the docs/tutorials/guides/etc, we could detect users using this template and treat it as `react-native`. Outputting extra warning about what's happening under the hood, so that users are aware.

Schedule for 11.0 release

**Comment by radko93** [comment]
The only concern would be creating projects with older RN versions, there are still some people doing that (look at the numbers lower than 6.12) https://www.npmjs.com/package/react-native-template-typescript

**Comment by adamTrz** [comment]
Quick check could look like so:
```ts
function checkVersionAndTemplate(options: Options, version: string): string {
  const isTypescriptTemplate = options.template?.includes(
    'template-typescript',
  );

  if (isTypescriptTemplate && options.template?.includes('@')) {
    const typescriptTemplateVersion = options.template.split('@')[1];
    if (semver.gte(typescriptTemplateVersion, '0.71.0')) {
      logger.warn(
        "Starting from verision '0.71' typescript is used by default.\nDiregarding template and using default react-native template",
      );
      return `react-native@${version}`;
    }
  }

  return options.template || `react-native@${version}`;
}
```

And then we could pass returned string here:

https://github.com/react-native-community/cli/blob/74bf4217f08fd87f76b60cf196774795679da28d/packages/cli/src/commands/init/init.ts#L184

Wdyt? @thymikee  @radko93

**Comment by thymikee** [comment]
Yeah along these lines. I'd be very explicit about matching this and only this template. We can figure out the best wording as well :)

**Comment by radko93** [comment]
Agreed, looks good but needs to match the exact name not just `template-typescript`. Likely there are more templates with that phrase.

**Comment by adamTrz** [comment]
Opened up #1743, can we move discussion there? :)
