### ISSUE TITLE
Installing Bundler failed

### ISSUE THREAD

**Issue by lifeeric** [react-native-community/cli#1745]
Hey folks,
Thank you so much for this wonderful project! I'm creating a fresh new RN project, but it shows the below errors, even I installed the `ruby: 2.7.6` through the `rbenv` but it still shows this error.

```
✖ Installing Bundler
error rbenv: version `2.7.5' is not installed (set by /AwesomeProject/.ruby-version)

✖ Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
```

***OS: macos big sur***

could anybody help me out? thank you

**Comment by adamTrz** [comment]
HI @lifeeric 
Can you please provide output from `react-native doctor` command?

**Comment by liamjones** [comment]
> error rbenv: version `2.7.5' is not installed (set by /AwesomeProject/.ruby-version)

This sounds like you have rbenv properly installed, so it's looking at `.ruby-version` to set the ruby version but you don't yet have Ruby 2.7.5 installed (this should maybe be something the CLI picks up on so it can advise you/fix it).

Try `rbenv install 2.7.5` and then creating the RN project again.

**Comment by lifeeric** [comment]
@liamjones 
I get this error when I install the `2.7.5`

`rbenv install 2.7.5
To follow progress, use 'tail -f /var/folders/71/q60svfcn2qj2jn8k2b1n0y3c0000gn/T/ruby-build.20221110054707.1504.log' or pass --verbose
Downloading openssl-1.1.1q.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
error: failed to download openssl-1.1.1q.tar.gz
-> https://www.openssl.org/source/openssl-1.1.1q.tar.gz
error: failed to download openssl-1.1.1q.tar.gz

BUILD FAILED (macOS 11.6 using ruby-build 20221101)

Inspect or clean up the working tree at /var/folders/71/q60svfcn2qj2jn8k2b1n0y3c0000gn/T/ruby-build.20221110054707.1504.3aop3D
Results logged to /var/folders/71/q60svfcn2qj2jn8k2b1n0y3c0000gn/T/ruby-build.20221110054707.1504.log

Last 10 log lines:
Date: Thu, 10 Nov 2022 06:48:05 GMT
ETag: "90d47d61531f00ea75500354ecf05f3a-2"
X-Cache: Hit from cloudfront
Via: 1.1 d5395aef0c58da123cbcc801b71e308c.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: MRS52-P2
X-Amz-Cf-Id: dvk7Uh20tukaoASbd43isPLR2xqBmWordu_Mtcwi6nWOE8SCH-jHcw==
Age: 14273

curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
curl: (28) Operation timed out after 300810 milliseconds with 0 out of 0 bytes received`

**Comment by liamjones** [comment]
> error: failed to download openssl-1.1.1q.tar.gz
...
>curl: (28) Operation timed out after 300810 milliseconds with 0 out of 0 bytes received

Looks like you machine is having an issue downloading files from the web. It failed to retrieve it from cloudfront and the backup of the openssl.org website directly.

**Comment by lifeeric** [comment]
@liamjones 
it's downloaded but now I see a different error:

```

✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing Bundler
✖ Installing CocoaPods dependencies (this may take a few minutes)
error warn Multiple Podfiles were found: ios/Podfile,vendor/bundle/ruby/2.7.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/Podfile. Choosing ios/Podfile automatically. If you would like to select a different one, you can configure it via "project.ios.sourceDir". You can learn more about it here: https://github.com/react-native-community/cli/blob/master/docs/configuration.md
Searching for inspections failed: undefined method `map' for nil:NilClass

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
```

**Comment by adamTrz** [comment]
Can you try to install cocoapods manually?
````bash
cd ios
bundle install
bundle exec pod install
```

**Comment by lucianomlima** [comment]
@adamTrz thanks works for me. But why use `pod install` directly fails? I try with cocoapods installed via gems and homebrew.

**Comment by JAYASHREEPATIL** [comment]
try to run : 

cd ios
npx pod-install 
OR
npm run android

**Comment by KingAmo** [comment]
maybe the [version](https://github.com/hoxyq/cli/blob/40dccc48259167187f25beac92f86dd1635d79a8/packages/cli-doctor/package.json#L17 ) of `execa` is too old ?
