### ISSUE TITLE
Automate issues and PRs triaging

### ISSUE THREAD

**Issue by adamTrz** [react-native-community/cli#1751]
## Describe the Feature

Nice to have feature would be to have some GH Actions automation that will triage new issues and close stale ones. 
Same goes for pull request. 

We can discuss implementation details here and then create some GH Action workflows as a result 💪

**Comment by TMisiukiewicz** [comment]
Hi,
just a few question that come to my mind:

- how many days should pass to mark issue as stale? i'd say 30 days is reasonable
- how many days should pass from marking as stale to closing the issue? The default value is 7 days and i think it's totally fine
- how often should the CRON for this action run? 
- should there be any labels exempted from stale? (if yes, i think there might be some differences between issues and PRs)
- should only some specific labels be checked? E.g. "needs repro"
- should any label be added when issue/PR becomes unstale?
- should there be automatically added any label while creating issue/PR?
- should there be automatically added any comment when some labels are assigned? I think e.g. "needs repro" is a good example of a label where the comment could automatically appear

if there is a need of adding any other settings, you can get familiar with all of the available options [here](https://github.com/actions/stale)

Additional requirements:
- adding "stale" label on the repository

**Comment by thymikee** [comment]
Added the "stale" label. Let the bot add the label and remove when anyone comments. We can run the cron once a month. I'd mark the issue stale after 90 days – check what others do. 7 days to close the issue is fine. We should check all issues, regardless the labels for now. Can tweak that later

**Comment by TMisiukiewicz** [comment]
> Added the "stale" label. Let the bot add the label and remove when anyone comments. We can run the cron once a month. I'd mark the issue stale after 90 days – check what others do. 7 days to close the issue is fine. We should check all issues, regardless the labels for now. Can tweak that later

thanks for the answer, I'd suggest running cron once a day to constantly mark issues as stale and close them

**Comment by adamTrz** [comment]
Fixed with #1755
