### ISSUE TITLE
Avoid duplication and useless stack traces in errors that are meant to be human-readable

### ISSUE THREAD

**Issue by motiz88** [react-native-community/cli#1766]
## Describe the Feature

During `npx react-native init` I got this very verbose error message:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/2246565/205621981-efaf5fd8-69d0-4582-a4ac-335d12fa4e2e.png">

The "human-readable" part of the second error message is duplicated, plus there are multiple lines of stack trace that are useless by definition in this case. (The actual error, and the one that *might* conceivably have a useful stack trace, is the first one about Ruby versions.)

Generally, we should clean up the error reporting logic so as to only show relevant information. I'm opening this issue in case there are more places in the code where we a similar cleanup is needed (not super familiar with the CLI codebase).

## Possible Implementations

A useful, simple pattern is to create a `HumanReadableError` class and throw that instead of `Error`. Then, our top level error handler can perform an `instanceof` check, and print just the message (without the stack trace) if the error is meant to be human-readable.

**Comment by thymikee** [comment]
Thanks! We already have the `CLIError`, maybe we could leverage that

**Comment by arushikesarwani94** [comment]
> Thanks! We already have the `CLIError`, maybe we could leverage that

That still doesn't explain the reason behind the error message being reported twice :

> error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.
Error: Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup and follow the React Native CLI QuickStart guide for macOS and iOS.

**Comment by arushikesarwani94** [comment]
> Hey @adamTrz, @arushikesarwani94 - I'm not sure this can be closed yet. The two fixes landed were for `runBundleInstall` _specifically_, whereas this issue is about the general _pattern_ of printing stack traces where they're not necessary, and a proposed general solution (e.g. check `instanceof CLIError` to decide whether to print a stack trace). Are we sure we have no more examples of this problem elsewhere in the CLI?

@motiz88  I agree with you on addressing the problem with fixing the general pattern of printing stack traces, however CLIError currently provides both capabilities(with or without stack trace depending on original error being available) and we can leverage that at other occurrences as well.

**Comment by adamTrz** [comment]
Reopening then for future work 🙂
