### ISSUE TITLE
Allow re-initialising a project in the same directory after a failed init

### ISSUE THREAD

**Issue by motiz88** [react-native-community/cli#1769]
## Describe the Feature

`npx react-native init` should arguably clean up after itself when there were fatal errors and `init` hasn't finished running. Alternatively it should run all the relevant checks (like for Ruby versions) before making changes to the target directory. As a user, I expect to be able to fix any environment issues reported by `init`, then re-run *the same `init` command* and see it succeed.

## Possible Implementations
See above.

**Comment by ShaswatPrabhat** [comment]
@motiz88 "Alternatively it should run all the relevant checks (like for Ruby versions) before making changes to the target directory." -- Should this check a part of the init script ?

**Comment by adamTrz** [comment]
> @motiz88 "Alternatively it should run all the relevant checks (like for Ruby versions) before making changes to the target directory." -- Should this check a part of the init script ?

Doctor will fail if not inside react-native project so that would not work I think :)
