### ISSUE TITLE
Is running packager by calling react-native internal script still necessary for run-android?

### ISSUE THREAD

**Issue by MateWW** [react-native-community/cli#1799]
# Background

I'm actively working on preparing a react-native monorepo template with enabled hoisting.
I've everything working besides one thing. 
When I'm running `react-native run-android` packager is starting from monorepo root(`./`) instead of app package `./apps/app`
I can workaround it by running packager upfront but I would love to have that template working without such workarounds.

# Findings

I've dived deeply into how I can work around it and figured out that there is no option to solve that without patching `react-native`.

### Current flow

Currently running packager for `run-android` is working the following way:

- CLI is calling [startServerInNewWindow](https://github.dev/react-native-community/cli/blob/f308a560ef8b771542578d876866c0e25920ff72/packages/cli-platform-android/src/commands/buildAndroid/startServerInNewWindow.ts#L1)
- `startServerInNewWindow` 
  - is overriding `.packager.env`
  - and is calling [lauchPackager.sh](https://github.dev/facebook/react-native/blob/4f94577d4281f76e25b2874158274c940d6eb3b5/scripts/launchPackager.command#L1)
- `lauchPackager.sh` is calling [packager.sh](https://github.dev/facebook/react-native/blob/4f94577d4281f76e25b2874158274c940d6eb3b5/scripts/packager.sh)
- `packager.sh` is calling `react-native start` from `PROJECT_ROOT` which is statically set to the path relative to `node_modules/react-native`

### Why is that a problem?

1. Currently the simplest option to change `PROJECT_ROOT` from CLI perspective is to overwrite `PROJECT_ROOT` environment variable inside `.packager.env`
    - In the currently released react-native 0.71 `packager.sh` is always overwriting `PROJECT_ROOT` path with a path relative to the script location.
    - In future version(react-native master) there it accepts `PROJECT_ROOT` from outside.
    - Sadly there is still [this condition](https://github.dev/facebook/react-native/blob/4f94577d4281f76e25b2874158274c940d6eb3b5/scripts/packager.sh#L11) that will overwrite this path because in monorepo we have hoisting so the react-native package is located in monorepo root instead `PROJECT_ROOT`

2. Generally configuration of `react-native start` from `CLI` perspective is limited. 
It seems that `packager.sh` [accepts additional arguments (with `"$@"` at the end)](https://github.com/facebook/react-native/blob/2430d1fcf3b7eaaa7fe78912fb7644c0b558dec3/scripts/packager.sh#L24) that will be forwarded to `react-native start`.
However [`launchPackager.command`](https://github.com/facebook/react-native/blob/2430d1fcf3b7eaaa7fe78912fb7644c0b558dec3/scripts/launchPackager.command#L28-L30) is not forwarding it from `CLI`

## Question

1. I'm curious what is the story behind this solution where `CLI` have to call `react-native internal script` that will call `CLI`.
Maybe there is someone who has some background on this one?

2. Is this script treated internally in react-native as something that should be used by the community?
This question is based on [this comment](https://github.com/facebook/react-native/blob/2430d1fcf3b7eaaa7fe78912fb7644c0b558dec3/scripts/packager.sh#L17) inside `packager.sh` that sounds like it is something for internal react-native testing.

3. If this is something that should be used by the community then I'm wondering if there is a way to make it more configurable from a `CLI` perspective.

## Reproducible demo:

- clone repo https://github.com/MateWW/react-native-new-arch-monorepo
- install dependencies
- make sure you have packager running
- trigger `yarn android`(doesn't matter if you will do that from app directory or root)

**Comment by cortinico** [comment]
> Is this script treated internally in react-native as something that should be used by the community?
This question is based on [this comment](https://github.com/facebook/react-native/blob/2430d1fcf3b7eaaa7fe78912fb7644c0b558dec3/scripts/packager.sh#L17) inside packager.sh that sounds like it is something for internal react-native testing.

Yup so `packager.sh` should not be used externally. That's a script we use to invoke Metro for RN Tester. The CLI should not invoke it

**Comment by cortinico** [comment]
> Yup so `packager.sh` should not be used externally. That's a script we use to invoke Metro for RN Tester. The CLI should not invoke it

Also this explains why we had user reports of issues like:
- https://github.com/facebook/react-native/issues/34146

**Comment by MateWW** [comment]
@cortinico 
I'm reviewing IOS because it also has a problem with launching packager in my monorepo.
I found that inside react-native you are also using this `lauchPackager.command` for IOS.
This time it's internally inside react-native during  `Start Packager` build phase.
Do you think this should be unified somehow across both platforms?

![Screenshot 2023-01-25 at 22 25 09](https://user-images.githubusercontent.com/16048381/214694412-745ae883-65d2-4bbc-bcf2-ebcb014ea90d.png)
