### ISSUE TITLE
Android CLI fails to launch emulator automatically when running `yarn android`

### ISSUE THREAD

**Issue by UNIDY2002** [react-native-community/cli#1801]
## Environment

```
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 2.64 GB / 13.51 GB
    Shell: 3.5.1 - /usr/bin/fish
  Binaries:
    Node: 19.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 19.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.0 => 0.71.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Additional information:
- Android SDK version 33.0.0
- Android emulator version 31.2.8.0
- CLI version 10.0.0

## Description

After I execute `yarn android`, it prints an error message:
```
error Failed to launch emulator. Reason: The emulator (Pixel_4_API_30) quit before it finished opening. You can try starting the emulator manually from the terminal with: /home/unidy/.sdk/Android/emulator/emulator @Pixel_4_API_30.
```

I suspect there is something to do with this line: https://github.com/react-native-community/cli/blob/d351048/packages/cli-platform-android/src/commands/runAndroid/tryLaunchEmulator.ts#L27

When `port` is undefined, the subprocess parameters fall back to ```[`@${emulatorName}`, '', '']```, and the empty strings may be the cause of the problem.

I think it is a regression, because it worked fine before I upgraded `react-native` to 0.71.

## Suggestion for a fix

Change this line: https://github.com/react-native-community/cli/blob/d351048/packages/cli-platform-android/src/commands/runAndroid/tryLaunchEmulator.ts#L27
into:
```TypeScript
port ? [`@${emulatorName}`, '-port', `${port}`] : [`@${emulatorName}`]
```

**Comment by adamTrz** [comment]
Hi @UNIDY2002 thanks for reporting! Fix is on the way :)

**Comment by koralgooll** [comment]
In my case the problem was not turn on virtualization in BIOS. So the expo probable was not able to start virtual Pixel device. You can check in Android Virtual Device Manager if you can run it.

**Comment by LabGecko** [comment]
Still seeing this error. Same basic error to the original poster.

> System:
    OS: Windows 11 Pro
    CPU: AMD Ryzen 7 7735HS with Radeon Graphics           3.20 GHz
    Memory: 32.0 GB (27.7 GB usable)
  Binaries:
    Node: 19.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  SDKs: Android SDK: Android 14 (API 34)
  IDEs: Android Studio: Hedgehog 2023.1.1 Patch 2 (Build #AI-231.9392.1.2311.11330709)
  Languages: Java: 17
  npmPackages:
    yarn
    cli

**Comment by codewitharun** [comment]
Got 2 solutions from [here](https://stackoverflow.com/a/78111618/16115046) and [here](https://stackoverflow.com/questions/78108733/android-emulator-always-giving-error-emu-crash-xx-xx-db-and-quit-before-it-finis/78113527#78113527) it is working.

**Comment by Mynameisjohndev** [comment]
![image](https://github.com/react-native-community/cli/assets/47609014/27565d0a-2114-4edb-a8a5-78539b4e4d1f)


The download links don't appear, I've already tested it on 4 browsers and nothing. If you can view it, please provide the links to all platforms here.

**Comment by AYASOFT** [comment]
@Mynameisjohndev here are the direct links as shown on page 
Zip files
  Windows (64-bit): [emulator-windows_x64-11237101.zip](https://redirector.gvt1.com/edgedl/android/repository/emulator-windows_x64-11237101.zip) (361338481 bytes)
  Mac (Intel): [emulator-darwin_x64-11237101.zip](https://redirector.gvt1.com/edgedl/android/repository/emulator-darwin_x64-11237101.zip) (317369570 bytes)
  Mac (Apple Silicon): [emulator-darwin_aarch64-11237101.zip](https://redirector.gvt1.com/edgedl/android/repository/emulator-darwin_aarch64-11237101.zip) (267679962 bytes)
  Linux: [emulator-linux_x64-11237101.zip](https://redirector.gvt1.com/edgedl/android/repository/emulator-linux_x64-11237101.zip) (247516525 bytes)

  SHA-256 Checksums
  4f21ad916568459a4e38d75755a5cf27c658b844673388e2bfe0f407ae3e8bb9 emulator-windows_x64-11237101.zip
  c603ec70071d215f0351fc14ede329504af1608091918dd6804353ac9a9e66e3 emulator-darwin_x64-11237101.zip
  8322f2a738cc29eaff26e9de856755ed5a1273d770e01d8347f0d84c8a487696 emulator-darwin_aarch64-11237101.zip
  cfd54ce620ad5f9f786682ecad88b8b9da7ac48827d57406cc2a31bb8f6e73fe emulator-linux_x64-11237101.zip

**Comment by kadirmetin** [comment]
This error still persists on my computer. Is this the case for all users?

![image](https://github.com/react-native-community/cli/assets/82063998/0d9cb47c-b0c5-449f-a85c-c71e0864d37d)

**Comment by AYASOFT** [comment]
@kadirmetin did you try the solution of @codewitharun 
try downloading the previous stable version & replace files after a full restart of the machine.

**Comment by haris-dev-72** [comment]
> This error still persists on my computer. Is this the case for all users?
> 
> ![image](https://private-user-images.githubusercontent.com/82063998/316857380-0d9cb47c-b0c5-449f-a85c-c71e0864d37d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODM5MTEsIm5iZiI6MTcxMTg4MzYxMSwicGF0aCI6Ii84MjA2Mzk5OC8zMTY4NTczODAtMGQ5Y2I0N2MtYjBjNS00NDlmLWE4NWMtYzcxZTA4NjRkMzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDExMTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MWY1Y2VhNTYxZjZiOGMxYThkZDc5MGNiY2FhMzc3OTUyNGY5YWJlMTQ4OThiNTY0NWU1NDY5NmRiODg0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1KNp-CAwotvAa1SmXFQY4ymGrSQaUeydKhN7ly1Uhs)

did you found any solution ???

**Comment by kadirmetin** [comment]
> > This error still persists on my computer. Is this the case for all users?
> > ![image](https://private-user-images.githubusercontent.com/82063998/316857380-0d9cb47c-b0c5-449f-a85c-c71e0864d37d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODM5MTEsIm5iZiI6MTcxMTg4MzYxMSwicGF0aCI6Ii84MjA2Mzk5OC8zMTY4NTczODAtMGQ5Y2I0N2MtYjBjNS00NDlmLWE4NWMtYzcxZTA4NjRkMzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDExMTMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MWY1Y2VhNTYxZjZiOGMxYThkZDc5MGNiY2FhMzc3OTUyNGY5YWJlMTQ4OThiNTY0NWU1NDY5NmRiODg0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1KNp-CAwotvAa1SmXFQY4ymGrSQaUeydKhN7ly1Uhs)
> 
> did you found any solution ???

No. The only solution I found was to run the application in the console after running the emulator. But in the past, when I ran the application through the console, it worked in the emulator.

**Comment by GNUGradyn** [comment]
Couldn't this utility just be fixed to ignore lines that start with INFO when parsing the emulator output..?

**Comment by LabGecko** [comment]
The error is now only appearing occasionally for me using VSCode. No idea what is causing the intermittency.

VSCode Version: 1.89.1 (user setup)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows 11 Pro x64 ver 23H2 (misreports as Windows_NT x64 10.0.22631 so not sure what other values might be misreporting)

**Comment by waohwaohwaoh** [comment]
You can fix this by changing the logic of the getEmulators function in the file node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/tryLaunchEmulator.js
you need changed this line:
`return emulatorsOutput.split(_os().default.EOL).filter(name => name !== '');`
to:
`return emulatorsOutput.split(_os().default.EOL).filter(name => !name.startsWith('INFO') && name !== '');`

**Comment by Luiyit** [comment]
> emulatorsOutput.split(

Is a simple way to solve it. Thanks!
