### ISSUE TITLE
☂️ Improve developer experience in React Native CLI ✨ 

### ISSUE THREAD

**Issue by szymonrybczak** [react-native-community/cli#1820]
# Current stage
Currently there's ongoing effort to make React Native CLI better, and easier to use for developers. Recently these nice flags were created:
- `--interactive` (https://github.com/react-native-community/cli/pull/1815, https://github.com/react-native-community/cli/pull/1811),
- `--list-devices` (https://github.com/react-native-community/cli/pull/1676, https://github.com/react-native-community/cli/pull/1765),

which allows users to select options in a nice and user-friendly way. 
# Next stage
While contributing and improving CLI, we're thinking about other improvements which can make CLI *better*. Here's list of improvements we would like to have in CLI in the nearest future:
- https://github.com/react-native-community/cli/issues/1819

**Comment by tido64** [comment]
We recently discovered that pressing `d` in the terminal to open the dev menu only works on Android. It was introduced back in [0.47.0](https://github.com/facebook/react-native/commit/01adc71ade1c3453705e5c744fa836aa2ca23e3c) (and in [`@react-native-community/cli` 3.0.5-alpha.1](https://github.com/react-native-community/cli/commit/25a2c44c4a52341110e7a64d681aaefaf4726a97)) but only on Android. An iOS implementation is still missing today. Is this something that you can look into?

**Comment by szymonrybczak** [comment]
Hey @tido64, on CLI's side we're sending the `devMenu` socket, [see here](https://github.com/react-native-community/cli/blob/main/packages/cli-plugin-metro/src/commands/start/watchMode.ts#L54). I created PR https://github.com/facebook/react-native/pull/36115 adding handling this websocket in `react-native` 😄

**Comment by TMisiukiewicz** [comment]
I already mentioned that somewhere, but if possible, i think it would be a nice DX improvement if the prompt from `--list-devices` was available also in `--interactive` mode. I can create an issue with more detailed description if you find this worth adding to the CLI

**Comment by szymonrybczak** [comment]
Let's close this issue! If there are any other DevX improvements to CLI please report new issues! 🙏
