### ISSUE TITLE
How to custom option '--myValue' to React Native CLI?

### ISSUE THREAD

**Issue by McDreamy** [react-native-community/cli#1821]
Is there a way to add and pass value to custom option '--myValue' to React Native CLI?

for example:
`npx react-native run-ios --myValue 'abcd'`

**Comment by adamTrz** [comment]
Hi @McDreamy what would be the purpose of this option? 
Maybe CLI is already doing what you need :)

**Comment by McDreamy** [comment]
Hi @adamTrz, I'm trying to pass values as arguments to the CLI command that runs the app and accessed within the code
