### ISSUE TITLE
Add a field for the `ruby` version in `react-native info`

### ISSUE THREAD

**Issue by cortinico** [react-native-community/cli#1825]
## Describe the Feature
As the title says, it would be great to add a field for the `ruby` version in `react-native info`. 
It seems like a lot of the issues we're having are related to ruby misversions

## Possible Implementations
This looks really straightforward by just calling `ruby -v`

## Related Issues
Somehow related to https://github.com/react-native-community/cli/issues/1809

**Comment by blakef** [comment]
I'd like to grab this, the fix looks to be a config change for envinfo.  PR inbound.

**Comment by arushikesarwani94** [comment]
Working on this as part of adding Ruby version check in https://github.com/react-native-community/cli/pull/1818

**Comment by adamTrz** [comment]
Closing as completed by #1818

**Comment by arushikesarwani94** [comment]
@cortinico Is this information sufficient :
```
  Managers:
    CocoaPods: Not Found
    RubyGems: 3.0.3.1 - /usr/bin/gem
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 30
      Build Tools: 30.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_181 - /usr/local/bin/javac
```

Or the Ruby version instead of RubyGems is preferred in the Languages as :

```
  Languages:
    Java: 1.8.0_181 - /usr/local/bin/javac
    Ruby: 2.6.10 - /usr/bin/ruby
```

I'm unclear on which is more informative ?
