### ISSUE TITLE
`profile-hermes` command always downloads `dev` sourceMaps

### ISSUE THREAD

**Issue by phryneas** [react-native-community/cli#1831]
## Description

When calling `profile-hermes`, currently it downloads the `dev` sourcemaps as a hardcoded string - if the profile has been created with a production bundle the resulting source maps are completely useless.

This is the code in question:

https://github.com/react-native-community/cli/blob/a8ff4ff0406d44ebd1cfec603affda1c7d6e1642/packages/cli-hermes/src/profileHermes/sourcemapUtils.ts#L39

I have changed this to `dev=false` in my local `node_modules` and can verify that I am getting correct line numbers now. 

Would a PR that adds this as a command line option be welcome? 

Alternatively, this could probably be auto-detected, since a lot of the `name` fields of the original profile will contain substrings like `index.bundle?platform=android&dev=false&minify=false&app=my.amazing.app&modulesOnly=false&runModule=true:107805:5`, so this could be taken as a hint on what to actually pass to hermes to get the right sourceMaps.

**Comment by adamTrz** [comment]
Hey @phryneas 
Thanks for reporting the issue. 
Would welcome PR with a fix if you have capabilities to do one 🙂
