### ISSUE TITLE
iOS Native Extension Cherry Pick Dependencies

### ISSUE THREAD

**Issue by mfbx9da4** [react-native-community/cli#1839]
I'm building an iOS extension (both keyboard and notification service) and I would like to use RN to some extent. Many of the RN dependencies use APIs not available in extensions. Is there any way to allowlist / blocklist certain dependencies from auto linking?

**Comment by thymikee** [comment]
Yup, you can disable autolinking for certain packages: https://github.com/react-native-community/cli/blob/main/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library :)
