### ISSUE TITLE
doctor: Add check for `adb devices` 

### ISSUE THREAD

**Issue by arushikesarwani94** [react-native-community/cli#1852]
## Describe the Feature
I'd like to propose a feature for `doctor` that will verify if the android device is attached correctly by listing the available devices. This could be a non-required check/ Warning ●  in Common category to notify users of whether there is an attached device or not. This will allow users to differentiate device connection issues like : USB debugging enabled, developer options enabled etc. from others.

At times, restarting the adb server through `adb kill-server;
adb start-server` might be helpful seeing this check failure rather than struggling to understand why the app launch is failing.

## Possible Implementations
Fetch available devices (`adb device`) and emulators (`emulator -list-avds`) 

## Test Plan

1. Build cli codebase using : `node ./scripts/build.js && yarn build:debugger`
2. Link the cli-doctor using : `yarn link`
3. In the example React Native app(Awesome Project), run `yarn link "@react-native-community/cli-doctor"`
4. Run the CLI Doctor using : `npx @react-native-community/cli doctor`

## Related Issues
[#1765](https://github.com/react-native-community/cli/pull/1765)(Android)
[#1676](https://github.com/react-native-community/cli/pull/1676)(iOS)

**Comment by cortinico** [comment]
That's really cool + I think doctor should also call `adb reverse --list` and verify if the reverse proxy for the physical device has been set. If not, the autofix woudl be to call `adb reverse tcp:8081 tcp:8081`

**Comment by adamTrz** [comment]
Nice feature @arushikesarwani94 would you like to go on and implement it? 🙂 
There's a util function `listAndroidDevices` that already lists all available devices/emulators so we can start from there :)

**Comment by arushikesarwani94** [comment]
@adamTrz ATM we are not prioritising implementing these enhancements to `cli-doctor` ourselves but would encourage community contributions on these pieces so that folks are more aware of using `cli-doctor` as part of their set-up. WDYT ?

**Comment by adamTrz** [comment]
Very nice idea :) Let's see how it goes then 🙂

**Comment by ShaswatPrabhat** [comment]
I can give this a shot @adamTrz if seeking contributions.

**Comment by arushikesarwani94** [comment]
> I can give this a shot @adamTrz if seeking contributions.

Did a basic implementation of `adb devices` and reverse proxy in https://github.com/react-native-community/cli/pull/1880

Feel free to build on top of it. Things TODO : 
- Fetch emulator along with `adb devices`
- Try Run Adb Reverse as part of the fix
- Refactor listAndroidDevices() to separate out getting `allDevices` and then use that in both places.

**Comment by adamTrz** [comment]
Fixed with #1885
