### ISSUE TITLE
[flipper] react-native-cli will not work with next version of flipper v0.183

### ISSUE THREAD

**Issue by RichardFevrier** [react-native-community/cli#1853]
Hello, I tried to use the next `flipper` version with the lastest version of `react-native-cli` proposed by `npx` (`10.1.3`).
And it failed for `Android` (did not checked for `iOS` yet).
Everything is explained in [this issue](https://github.com/facebook/flipper/issues/4565) but to summarize `flipper-fresco-plugin` is not bumped to the same version of `flipper` anymore which is a problem with the current implementation of the cli.

**Comment by cortinico** [comment]
Thanks for reporting this. This is probably a release blocker for 0.72 imho.

@RichardFevrier can you please open a separate issue here: https://github.com/facebook/react-native/issues and ping me there? I'll try to get this sorted.

**Comment by RichardFevrier** [comment]
Sure @cortinico ! I will first let time for @passy to answer your questions before adding maybe a superfluous issue at [https://github.com/facebook/react-native/issues](https://github.com/facebook/react-native/issues) 🙂

**Comment by cortinico** [comment]
> I will first let time for @passy to answer your questions before adding maybe a superfluous issue at [facebook/react-native/issues](https://github.com/facebook/react-native/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) 🙂

That's fine. I've noted it here https://github.com/reactwg/react-native-releases/discussions/54
