### ISSUE TITLE
feat : Bump minimum Android_SDK requirement to Android SDK Platform 33 for RN 0.72 in `doctor`

### ISSUE THREAD

**Issue by arushikesarwani94** [react-native-community/cli#1855]
## Describe the Feature
React Native is increasing the minimum Android_SDK requirement from `Android SDK Platform 31` to `Android SDK Platform 33` for 0.72 onwards. 

https://reactnative.dev/docs/next/environment-setup#installing-dependencies

We need to make the corresponding change in `doctor`.

## Possible Implementations
Change the version in 
https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts
to `>=33.x`

## Test Plan
1. Build cli codebase using : `node ./scripts/build.js && yarn build:debugger`
2. Link the cli-doctor using : `yarn link`
3. In the example React Native app(Awesome Project), run `yarn link "@react-native-community/cli-doctor"`
4. Run the CLI Doctor using : `npx @react-native-community/cli doctor`

**Comment by adamTrz** [comment]
I don't think `ANDROID_SDK` from [versionRanges](https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts
) file is used anymore.
If you look at `androidSDK` healthcheck you can see that we're getting required SDK version from `android/build.gradle` file via `getBuildToolsVersion`  helper function. So it depends what is shipped with core I think?

**Comment by arushikesarwani94** [comment]
Actually that makes sense. Even for NDK I can see the `android/build.gradle` has version 23.

Though I will still update the [versionsRanges](https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts) for posterity.

**Comment by cortinico** [comment]
> So it depends what is shipped with core I think here?

Oh TIL I guess.
Can we make sure both NDK and SDK versions are used from the same source of truth?

**Comment by arushikesarwani94** [comment]
> both NDK and SDK versions are used from the same source of truth

Do you suggest using the [versionRanges](https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts) or the `android/build.gradle` file as the single source of truth ?
