### ISSUE TITLE
feat : Bump minimum Android_NDK requirement from 19 to 23 for RN 0.72 in `doctor`

### ISSUE THREAD

**Issue by arushikesarwani94** [react-native-community/cli#1856]
## Describe the Feature
React Native is increasing the minimum Android_SDK requirement from `Android SDK Platform 31` to `Android SDK Platform 33` for 0.72 onwards.

https://reactnative.dev/docs/next/environment-setup#installing-dependencies

Which means we need to make the corresponding change for ANDROID_NDK from 19 to 23 in `doctor`.

## Possible Implementations
Change the version in
https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/src/tools/versionRanges.ts
to >= 23.x

## Related Issues
https://github.com/react-native-community/cli/issues/1855

**Comment by cortinico** [comment]
Small heads up that was needed also for RN 0.71 and should probably be backproted

**Comment by szymonrybczak** [comment]
Closing this issue. These changes are released in:
```
 - @react-native-community/cli-doctor@10.2.2
 - @react-native-community/cli@10.2.2
```
