### ISSUE TITLE
AAPT2 aapt2-7.0.4-7396180-osx Daemon #1: Daemon startup failed, This should not happen under normal circumstances, please file an issue if it does.

### ISSUE THREAD

**Issue by karocksjoeli** [react-native-community/cli#1860]
## Environment

System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 7.71 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.npm-global/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.03.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK: Not Found
    Android SDK:
      API Levels: 31
      Build Tools: 30.0.2, 31.0.0
      System Images: android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0 
    react-native: 0.69.6 => 0.69.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

`> Task :app:processDebugResources FAILED
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform material-1.1.0.aar (com.google.android.material:material:1.1.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/1cb1d0b58a4b0d8117d0404fc3084595/transformed/material-1.1.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #1: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform appcompat-1.4.1.aar (androidx.appcompat:appcompat:1.4.1) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/2b822756a0a287210a722005b652001a/transformed/appcompat-1.4.1.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #4: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform appcompat-1.4.1.aar (androidx.appcompat:appcompat:1.4.1) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/2b822756a0a287210a722005b652001a/transformed/appcompat-1.4.1.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #4: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform play-services-base-17.0.0.aar (com.google.android.gms:play-services-base:17.0.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/ed8506b40663b5fcd51a375a60ee0f8b/transformed/play-services-base-17.0.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform play-services-base-17.0.0.aar (com.google.android.gms:play-services-base:17.0.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/ed8506b40663b5fcd51a375a60ee0f8b/transformed/play-services-base-17.0.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform play-services-base-17.0.0.aar (com.google.android.gms:play-services-base:17.0.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/ed8506b40663b5fcd51a375a60ee0f8b/transformed/play-services-base-17.0.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform play-services-base-17.0.0.aar (com.google.android.gms:play-services-base:17.0.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/ed8506b40663b5fcd51a375a60ee0f8b/transformed/play-services-base-17.0.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform play-services-base-17.0.0.aar (com.google.android.gms:play-services-base:17.0.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/ed8506b40663b5fcd51a375a60ee0f8b/transformed/play-services-base-17.0.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #0: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform exoplayer-ui-2.13.3.aar (com.google.android.exoplayer:exoplayer-ui:2.13.3) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/da28e0a6fd90fe9750da432f4f9039c5/transformed/jetified-exoplayer-ui-2.13.3.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #2: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.
   > Failed to transform core-1.7.0.aar (androidx.core:core:1.7.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.status=release}.
      > Execution failed for AarResourcesCompilerTransform: /private/var/root/.gradle/caches/transforms-3/095d9919b0515fb80ab42335eaf4c064/transformed/core-1.7.0.
         > AAPT2 aapt2-7.0.4-7396180-osx Daemon #3: Daemon startup failed
           This should not happen under normal circumstances, please file an issue if it does.`

## Reproducible Demo

My Package.json : 

`"dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.11",
    "@react-native-material/core": "~1.3.5",
    "@react-native-picker/picker": "2.4.2",
    "@react-navigation/drawer": "~6.4.3",
    "@react-navigation/native": "~6.0.10",
    "@react-navigation/native-stack": "~6.6.2",
    "@reduxjs/toolkit": "~1.8.6",
    "crypto-js": "~4.1.1",
    "expo": "~46.0.0",
    "expo-av": "~12.0.4",
    "expo-barcode-scanner": "~11.4.0",
    "expo-camera": "~12.3.0",
    "expo-file-system": "~14.1.0",
    "expo-font": "~10.2.0",
    "expo-image-manipulator": "~10.4.0",
    "expo-splash-screen": "~0.16.2",
    "expo-status-bar": "~1.4.0",
    "expo-updates": "~0.14.7",
    "i18next": "~21.9.1",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-i18next": "~11.18.5",
    "react-native": "0.69.6",
    "react-native-date-picker": "~4.2.6",
    "react-native-dotenv": "~3.3.1",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-honeywell-scanner-v2": "~1.1.6",
    "react-native-modal": "^13.0.1",
    "react-native-progress-steps": "~1.3.4",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.16.0",
    "react-native-web": "~0.18.7",
    "react-native-webview": "11.26.1",
    "react-redux": "~8.0.4",
    "redux": "~4.2.0",
    "redux-persist": "~6.0.0"
  },
  "devDependencies": {
    "@babel/core": "~7.18.6",
    "@types/react-dom": "~18.0.2",
    "@types/react-native": "~0.69.1",
    "@types/react-redux": "~7.1.24",
    "typescript": "~4.6.3"
  },`

**Comment by cortinico** [comment]
> w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

Please do `cd android && ./gradlew --stop` and try again.
You likely have stale Gradle/Kotlin daemons around.

**Comment by Diaa-Ghonim** [comment]
> > w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
> 
> Please do `cd android && ./gradlew --stop` and try again. You likely have stale Gradle/Kotlin daemons around.

didn't work

**Comment by adamTrz** [comment]
Hi @Diaa-Ghonim 
Ary you able to build the app with Android Studio? Wondering if this is a CLI issue at all or maybe some gradle / android related thing... 🤔

**Comment by bryanltobing** [comment]
installing rosetta indeed solve this issue for me. but why do I need to install it? @Diaa-Ghonim

**Comment by Pratik-2102** [comment]
I am also facing this issue. Can anyone Please let me know how to fix it 
.
Thanks

**Comment by divyanshu1432** [comment]
Thanks @Diaa-Ghonim for this command

**Comment by vigneshsurendran** [comment]
> Thanks @Diaa-Ghonim for this command softwareupdate --install-rosetta

**Comment by PlanCZero** [comment]
> Hi @adamTrz Thank you for your reply! 👍
> 
> I tried many suggestions, but none of them fixed the issue. I managed to solve it by installing the Rosetta software using the command **_`softwareupdate --install-rosetta.`_**

Thanks for the ans, it has been 3 days struggling with this issue.

**Comment by sudippaudel793** [comment]
> Hi @adamTrz Thank you for your reply! 👍
> 
> I tried many suggestions, but none of them fixed the issue. I managed to solve it by installing the Rosetta software using the command **_`softwareupdate --install-rosetta.`_**

This works

**Comment by marceloccosta** [comment]
> Hi @adamTrz Thank you for your reply! 👍
> 
> I tried many suggestions, but none of them fixed the issue. I managed to solve it by installing the Rosetta software using the command **_`softwareupdate --install-rosetta.`_**

It worked for me. Thanks ;)

**Comment by Ashkan-san** [comment]
> cd android && ./gradlew --stop

thank you, just ./gradlew --stop worked for me!

**Comment by fFernandoh** [comment]
worked for me change 
`classpath 'com.android.tools.build:gradle:7.0.0'`
to
`classpath 'com.android.tools.build:gradle:7.1.3'`

in build.gradle

**Comment by fernandodx** [comment]
> worked for me change `classpath 'com.android.tools.build:gradle:7.0.0'` to `classpath 'com.android.tools.build:gradle:7.1.3'`
> 
> in build.gradle

its worked for me, too

**Comment by GaaiChyunLu** [comment]
Same issue on Intel chip Mac. Solved.
In Terminal, run below commands:
```bash
$ cd "your project location"
$ ./gradlew --stop
```

**Comment by kingfisherphuoc** [comment]
> Same issue on Intel chip Mac. Solved. In Terminal, run below commands:
> 
> $ cd "your project location"
> $ ./gradlew --stop

It's magic, but it works in my case as well (Android Studio Meerkat | 2024.3.1 - MacOS - M1)
