### ISSUE TITLE
Support Windows Subsystem for Android

### ISSUE THREAD

**Issue by rhyst** [react-native-community/cli#1865]
## Describe the Feature

Not sure if this is a bug or a feature request but I am running an android build in Windows Subsystem for Android. If I press `r` to reload in the metro bundler CLI then app will close and will not reopen. Pressing `a` to `Run on android` rebuilds and the app opens.

I experimented a bit and if I reload the app (so it closes) and then make changes to the app source and then reopen the application from the windows start menu then it does include the changes so I doesn't seem like anything is crashing, maybe just minimising in a weird way because of the lack of home screen?

## Possible Implementations

This should just work like it does with an emulator or real device.

## Related Issues
I raised an issue on the metro repo as well but it was suggested that it might be more relevant here: https://github.com/facebook/metro/issues/939

**Comment by szymonrybczak** [comment]
Hey @rhyst, I will take a look at this.

**Comment by szymonrybczak** [comment]
Hey @rhyst, so basically this works for me: 

https://user-images.githubusercontent.com/63900941/227318554-b3dcac1c-d5ca-449d-a093-0105f9650f02.mp4

As you can see, I'm pressing `r` in Metro bundler and the app reloads correctly.
I have question, so if you initially run your app it bundles correctly?
