### ISSUE TITLE
Error: str.replace is not a function

### ISSUE THREAD

**Issue by JosueOlivero** [react-native-community/cli#1883]
## Environment

System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 116.00 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: 2023.03.13.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/jolivero/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9619390
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 18.0.1.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: ^10.2.1 => 10.2.1
    react: ^18.2.0 => 18.2.0
    react-native: ^0.71.4 => 0.71.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

Hello there,
I'm trying a new app, and I got this error.
Any idea?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16158669/226716108-8627ac1b-18ec-4042-9661-431d3023e0d6.png">

Thanks!

**Comment by berikiushi** [comment]
@JosueOlivero 

try this, it helped me - https://stackoverflow.com/a/68579858/2005679

**Comment by JosueOlivero** [comment]
> @JosueOlivero
> 
> try this, it helped me - https://stackoverflow.com/a/68579858/2005679

I already have Command Line Tools selected. Just in case I re-select it again, but it didn't work.

**Comment by emilstepanian** [comment]
Same issue here

**Comment by pen1064** [comment]
same here, but I am using Windows
<img width="815" alt="image" src="https://user-images.githubusercontent.com/45325095/227679001-a2486c43-6630-44c1-8c84-1f308dd7094d.png">

**Comment by DEVARSHI-GOHEL** [comment]
hi, did you find solution to this problem? i have tried doing the command line tools thing but it's not working for me and this error is occurring after creating new project. Are you using js or ts as before i had created a project in TS and it was working fine

**Comment by TMisiukiewicz** [comment]
looks like it throws an error because it cannot run `xcodebuild` command on your machines. Can you make sure you have XCode installed and running e.g. `xcodebuild -list -json` command in `ios` folder returns an output correctly?

In my opinion failing to read the project configuration should not prevent user from running an app. I'll prepare a fix that will only warn user about it and skip the check if configuration cannot be read

**Comment by mohammad-fahad** [comment]
> Try this, it helped me - https://stackoverflow.com/a/68579858/2005679

### Thanks @JosueOlivero your reference saved me as well, I was mad for a couple of days then I found this solution that fixed the issue like magic 😳 
Stay blessed!!

**Comment by towardsnewtech** [comment]
![image](https://github.com/react-native-community/cli/assets/127037083/04436f69-4bf3-464e-b728-2ed931c51a92)
This is very stressful for me.

**Comment by jaykksingh** [comment]
sudo xcode-select --switch /Applications/Xcode.app
run this and you will be good to go

**Comment by Spencer1O1** [comment]
If anyone else is still having problems, for some reason I had two projects in my ios folder and I had to remove the wrong one. The output of `xcodebuild -list -json` in the ios folder was helpful.

**Comment by AlexCods** [comment]
In my case, i just had to open XCode to accept new licence agreements

![image](https://github.com/react-native-community/cli/assets/32845580/d7060b54-752b-4878-a40c-bf50c6af50b2)

**Comment by abanoubamin** [comment]
> > Try this, it helped me - https://stackoverflow.com/a/68579858/2005679
> 
> ### Thanks @JosueOlivero your reference saved me as well, I was mad for a couple of days then I found this solution that fixed the issue like magic 😳
> Stay blessed!!

This fixed mine

**Comment by Nagibaba** [comment]
Make sure you have run `pod install` first

**Comment by zacchaeuschok** [comment]
I ran this:

```
sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
```
