### ISSUE TITLE
Support Kotlin projects

### ISSUE THREAD

**Issue by Krizzu** [react-native-community/cli#19]
Adding support for Kotlin based Android projects.

Link could detect if project is Java/Kotlin based and act accordingly.

**Comment by grabbou** [comment]
This has to wait until we finish rewrite of the `link`. We don't know yet what is the outcome of that, postponing for now.

**Comment by thymikee** [comment]
With [new init](https://github.com/react-native-community/cli/blob/master/docs/init.md) it's now straight-forward to create a Kotlin template as a community package :)

**Comment by beshur** [comment]
But how does one link a module when main file is in Kotlin rather than Java?
