### ISSUE TITLE
Add flag to upgrade command, to change project name

### ISSUE THREAD

**Issue by Krizzu** [react-native-community/cli#190]
## Describe the Feature

So today we used `upgrade` in our project and we've spotted a small issue. The problem was that our `name` in `package.json` wasn't the same as the name we've initialized project with. 

`upgrade` [uses `name` form `package.json` and and applies diffing based on it,](https://github.com/react-native-community/react-native-cli/blob/master/packages/cli/src/upgrade/upgrade.js#L43) so it would be great to have a feature to override this behavior. 

## Possible Implementations
Just a flag `--project-name` passed to CLI would be sufficient. I can prepare a PR.

Thanks.

**Comment by grabbou** [comment]
Maybe instead of passing a flag, the upgrade script should read the name for a place where it's always correct?

We already have these utilities in the CLI (used for `link`) that are able to locate the application source files. We could use that to determine the name.

**Comment by Krizzu** [comment]
I believe we could re-use some logic to make it happen our-of-the-box, but that could be a cumbersome task to do. IMHO, adding a flag to support it would be a faster and cleaner approach.

CC @thymikee @Esemesek

**Comment by thymikee** [comment]
@Krizzu would you like to play with `link`'s mechanisms for determining names? If it takes too much time though, I'm still good with a flag for now.
