### ISSUE TITLE
--package-name option doesn't work properly

### ISSUE THREAD

**Issue by yaroslavnikiforov** [react-native-community/cli#1903]
## Environment

System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.83 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2023.04.03.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/yaroslav/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

If the --package-name value provided does not start with `com.`, the tool automatically adds `com.` to the beginning of the package name value. For instance, running the command:
 `npx @react-native-community/cli init ProjectName --package-name net.company.projectname` 
 would result in a package name of `com.net.company.projectname`. This issue can cause confusion and may require users to manually modify their package names after initialization. Package names are not required to start with `com`.,

## Reproducible Demo

Run the following command and check the result:
```
npx @react-native-community/cli init ProjectName --package-name net.company.projectname
```

**Comment by cortinico** [comment]
> If the --package-name value provided does not start with `com.`, the tool automatically adds `com.` to the beginning of the package name value.

Oh that's odd, and we definitely want to fix it if it's really a bug
