### ISSUE TITLE
CLI does not support subrojects

### ISSUE THREAD

**Issue by AnnatarHe** [react-native-community/cli#1908]
## Environment

```bash
# xcodebuild -version
Xcode 14.3
Build version 14E222b
```

```bash
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 224.83 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.1.0 - ~/Library/Caches/fnm_multishells/67662_1681404637528/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/67662_1681404637528/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/67662_1681404637528/bin/npm
    Watchman: 2023.04.03.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/USERNAME/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 10.2.2
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

got error: `error str.replace is not a function.
TypeError: str.replace is not a function`

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/8704175/231839684-c0d5e2d6-6e5e-4fce-bbc7-ab4763d89128.png">

run at `ios` folder: `xcodebuild -list -json`

<img width="916" alt="image" src="https://user-images.githubusercontent.com/8704175/231840030-4d1dd2d0-f46e-4089-aec0-8d89a6e40ec1.png">

## Reproducible Demo

if a react native project has more than 1 project(1 main app + 1 widget). it will throw error like this.

my ios folder like this:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/8704175/231841923-f7029a3b-119e-4a32-b171-b8e95c6b34be.png">

if add `-project xxxx.xcodeproj` to `xcodebuild`, looks good.

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/8704175/231841145-454c0955-2a5f-45cc-9a8b-e388312260ec.png">

Thanks

**Comment by adamTrz** [comment]
Hi @AnnatarHe , could you try to run the app with `--extra-params` flag passed in? 
So something like `react-native run-ios --extra-params "-project yourproject.xcodeproj"`

**Comment by adamTrz** [comment]
Oh my! Sorry that's on us... 😶‍🌫️ 
`--extra-params` was added with [v11.0.0](https://github.com/react-native-community/cli/releases/tag/v11.0.0)

Could you then try to update your CLI as described here and try again? 🙏 

https://github.com/react-native-community/cli#updating-the-cli

**Comment by TMisiukiewicz** [comment]
Did a bit of investigation around it and `--extra-params` flag won't work in this case and it's a bit more complicated problem. When having more than one project, CLI is doing a guess about which one of them to put in the context, so even if we pass this name to `xcodebuild -list -json` it's not enough because it might be a false assumption. IMO we should add a check if there are multiple projects in the `/ios` folder and add a prompt to select one if so, additionally a `--project` flag would be very helpful to build without any interactions

**Comment by AnnatarHe** [comment]
Hi, @adamTrz I tried, but I don't think the guide can work.
when I tried to run `yarn`, it always returned to the old 10.2.2.

the version of CLI seems locked by react-native.

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/8704175/235601999-3fc7a979-aa60-4766-87b6-520b79b747a5.png">

**Comment by AnnatarHe** [comment]
any idea to fix this issue?

**Comment by szymonrybczak** [comment]
@AnnatarHe we're trying to fix this issue.
