### ISSUE TITLE
iOS Destination: "My Mac (Designed for iPhone)"

### ISSUE THREAD

**Issue by staltz** [react-native-community/cli#1917]
## Describe the Feature

> Versions:
> - CLI: 9.3.2
> - React Native: 0.70.6
> - node: 16.17.0
> - npm: 8.15.0
> - Hardware: `MacBookPro18,1` and macOS Ventura 13.3.1

I have a React Native project working correctly, and for development I use a **M1 Pro** MacBook Pro, thus Apple Silicon.

From Xcode, one of the destinations I can choose is "My Mac (Designed for iPhone)" and this is NOT the same thing as Mac Catalyst, which I understand RN CLI already supports. From Xcode, this destination works just fine, when I press the "Run" :play_or_pause_button: button. 

| | |
|-|-|
| ![photo_2023-04-18_10-20-52](https://user-images.githubusercontent.com/90512/232708206-59dc7d91-cfdb-455c-b58f-f9a546cfd397.jpg) | ![photo_2023-04-18_10-20-57](https://user-images.githubusercontent.com/90512/232708212-f1323c0d-11be-47af-95d5-9476760fa022.jpg) |

However, I couldn't select this destination **from RN CLI**.
**Feature suggestion:** the ability to select "My Mac (Designed for iPhone)" as a destination for the command `run-ios`.

## Possible Implementations

At first, this may seem like a simple matter of discovering the `udid` of this destination and then using it in `run-ios --udid $UDID`. Or `run-ios --device $ID`. However, neither one works.

I understand that RN CLI uses [`xcrun xcdevice list`](https://github.com/react-native-community/cli/blob/6e9a441a65d002ddee54691d680cb1b4223a1e07/packages/cli-platform-ios/src/tools/listIOSDevices.ts#L56) to find the UDIDs (actually, on CLI v9.3.2 which I was using, it was using [`xcrun xctrace list devices`](https://github.com/react-native-community/cli/blob/978b1c81128e996dcaca2e0b2e957174193866f5/packages/cli-platform-ios/src/commands/runIOS/index.ts#L84)). I tried all these methods to find the correct UDID:

1. `xcrun xcdevice list`
2. `xcodebuild -workspace ios/MyProject.xcworkspace -scheme MyProject -showdestinations`
3. `xcrun xctrace list devices`

Their outputs differed a bit:

1. the `identifier` field shows a UDID that starts with `00006000-.....`
2. `id` field shows the same `00006000-.....`
3. This one had a different ID, `1E8......`

And `run-ios --udid` responded differently to each case:

- `00006000-.....`:  "Could not find a device with udid:" and lists basically the same list that `xcrun xctrace list devices` listed
- `1E8.........`: "success Installed the app on the device." But then failed to open `Build/Products/Debug-iphoneos-maccatalyst` because the folder `Debug-iphoneos` exists but `Debug-iphone-maccatalyst` does not exist

## Related Issues

N/A

**Comment by staltz** [comment]
It is still relevant, still occurs with current versions of RN.

**Comment by phraemer** [comment]
@staltz did you ever figure this out?

I'm also trying to install/run an iOS app on "My Mac (Designed for iPhone)" from the command line.
It can be done from Xcode so there must be a way on the command line.

**Comment by staltz** [comment]
No luck

**Comment by shawnthye-guru** [comment]
Can we reopen this? This will useful when you need to test call, share, deeplink, or things like WhatsApp.
