### ISSUE TITLE
How to generate Android release apk or bundle without launching the emulator?

### ISSUE THREAD

**Issue by kamal-j** [react-native-community/cli#1930]
## Ask your Question

This is the command I'm using `yarn react-native build-android --mode=release --tasks clean,assembleRelease`
But it always launches the emulator and install the app. Is there a way to avoid this as I want to be able to build apk and bundle in github workflows.

**Comment by szymonrybczak** [comment]
Hey @kamal-j 👋, that's very strange. We're launching emulators only in `run-android` command. Could you please create fresh React Native app, and try there?

**Comment by kamal-j** [comment]
@szymonrybczak Yes it's working fine in a fresh RN app.
