### ISSUE TITLE
Allow unknown options

### ISSUE THREAD

**Issue by smikheiev** [react-native-community/cli#1938]
## Describe the Feature
Now, if to pass some additional options to a cli command (eg, `run-ios`), it fails with `unknown option` error. Would it make sense to skip unknown options instead of failing?

A use case for this.
We have a custom script `install-pods.sh` that installs pods with some additional config based on whether we're running app on a simulator or physical device (it checks `--device` option). The script accepts some custom options (eg, `--force-pods-install`) but also some options from `run-ios` (eg, `--device`). Therefore, we have a custom `run-ios.sh` script, which first runs `install-pods.sh`, and then runs `react-native run-ios`.
So to run an app on iOS, we run `run-ios.sh` with all the required options, eg:
```
./run-ios.sh --configuration A --scheme B --force-pods-install --simulator "iPhone 14 Plus"
```
But, we can't just pass all options to `react-native run-ios`, because there might be some unknown options (eg, `--force-pods-install`). So now we need to filter all unknown option first and then pass the rest to `run-ios`, which makes the `run-ios.sh` script more cumbersome.

## Possible Implementations
Use `allowUnknownOption()` of [commander](https://github.com/tj/commander.js). Are there some risks?

**Comment by cortinico** [comment]
> Would it make sense to skip unknown options instead of failing?

I would prefer those commands to be strict and not allow unknown options.

> So now we need to filter all unknown option first and then pass the rest to run-ios, which makes the run-ios.sh script more cumbersome.

This is not a strong enough argument to justify this. I would actually argue that it makes your bash file more polish as every command has only the flags that it actually uses. Otherwise it will make really hard to know if `run-ios` is consuming a flag or not.

**Comment by smikheiev** [comment]
> I would actually argue that it makes your bash file more polish as every command has only the flags that it actually uses.

well, not sure that it makes the script more polish. but it for sure makes it more cumbersome and will require changes every time flags are changed in the `react-native run-ios` cli.

but, if your preference is to keep those commands strict, then well, let it be so ¯\_(ツ)_/¯
