### ISSUE TITLE
error Gem::Ext::BuildError: ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by imorakzai** [react-native-community/cli#1942]
following script fix it for me
`brew install libffi`
`ln -s $(brew --cellar libffi)/*/include/ffi.h /usr/local/include/ffi.h`
`ln -s $(brew --cellar libffi)/*/include/ffitarget.h /usr/local/include/ffitarget.h`
referred to this thread: https://github.com/ffi/ffi/issues/814#issuecomment-677655537

_Originally posted by @qi-xia in https://github.com/react-native-community/cli/issues/1832#issuecomment-1552264615_

**Comment by szymonrybczak** [comment]
Hey, I'm closing this issue. Please provide your setup, and error that you have when installing bundler. Also make sure that you have properly configured your development setup (see [here](https://reactnative.dev/docs/environment-setup) for more details). Please continue discussing about this issue under #1832 to have one issue covering this problem.
