### ISSUE TITLE
Script '/Users/patpat/patpat/app-rn/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 131

### ISSUE THREAD

**Issue by liangyi-h5** [react-native-community/cli#1948]
# After gradle is upgraded to 7.4.2, the compilation error, syntax error, in node_modules/@react-native-community/cli-platform-android/native_modules.gradle 131

FAILURE: Build failed with an exception.

* Where:
Script '/Users/patpat/patpat/app-rn/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 131

* What went wrong:
Execution failed for task ':app:generatePackageList'.
> argument type mismatch

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by cortinico** [comment]
> After gradle is upgraded to 7.4.2

That's happening most likely because you should not upgrade Gradle version independently from React Native version.

**Comment by liangyi-h5** [comment]
I tried removing it and it compiled successfully, I don't want to upgrade the react-native version because it's more complicated

**Comment by liangyi-h5** [comment]
> > After gradle is upgraded to 7.4.2
> 
> That's happening most likely because you should not upgrade Gradle version independently from React Native version.

I tried removing it and it compiled successfully, I don't want to upgrade the react-native version because it's more complicated

**Comment by liangyi-h5** [comment]
> > After gradle is upgraded to 7.4.2
> 
> That's happening most likely because you should not upgrade Gradle version independently from React Native version.


Our gradle is upgraded to 7.5, what version of react native is recommended?

**Comment by szymonrybczak** [comment]
So I think I can close this issue, please use the Gradle version compatible with RN version provided by Liam 👍
