### ISSUE TITLE
The purpose of `--host` option 

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#195]
I've been recently looking at the `react-native start` command while working on #193 and #194. 

From Metro documentation:

> It will listen on the specified host:port, and can then be queried to retrieve bundles for various entry points.

What can be the `host` value, rather than `0.0.0.0` (listen from all incoming APIs)? I think the general idea is that Metro should accept all incoming requests, regardless whether it's coming from `localhost` or from an IP address, e.g. when we are debugging on the remote device. 

CC: @rafeca @cpojer

**Comment by cpojer** [comment]
Should be any address that the server is reachable from, so any IP address. Theoretically you can run Metro on a different server than localhost and connect through that. In practice, it's probably `localhost` or `0.0.0.0` in 99% of the cases.

**Comment by grabbou** [comment]
@cpojer, but even if you run Metro on a different server (say under `8.8.8.8` public IP), you still want Metro to listen at `0.0.0.0` so that it accepts incoming requests from `8.8.8.8` (when remote device is accessing Packager) or `localhost` (when local Simulator is accessing it).

That's why I am a bit confused as to when you might change this option.

What do you think? Would it make sense to actually kill it?

**Comment by cpojer** [comment]
I don't know the answer, I'm sorry. Maybe ask on twitter whether anyone uses it?

**Comment by grabbou** [comment]
CC: @sebmck, Rick told me that you are now working on Metro. Got some ideas whether this would be needed in the Open Source?

**Comment by asklar** [comment]
Used to run the packager in one machine and the app on another; see #829

**Comment by Esemesek** [comment]
I think the purpose of this option is now clear. Closing C:
