### ISSUE TITLE
Unable to run npx react-native run-ios

### ISSUE THREAD

**Issue by memodiaz44** [react-native-community/cli#1952]
## Environment

Command `info` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project. (because it will not create the project I install "react-native-cli").
OS: macOS v12.6.2 (21G320)

## Description

I am not being able to run this command "npx react-native run-ios"

## Reproducible Demo

ii install "npm install -g react-native-cli I" and then create my project "npx react-native init M/yProjectName"it will not Create it and give me this message instead n**TypeError: cli.init is not a function**. So I have to do "npm uninstall -g react-native-cli" in order to proceed but when my projecte is finally created Iand finished downloading all dependencies I got this error ** Installing Bundler
error Error: Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/next/environment-setup **

**Comment by szymonrybczak** [comment]
Hey @memodiaz44,  you shouldn't use `react-native-cli` package (because it is not maintained, and its basically stale), you should create the project with this command `npx react-native@latest init <ProjectName>`

**Comment by memodiaz44** [comment]
I see, thanks for checking!
