### ISSUE TITLE
Doctor reporting error if Cocoapods is not installed on standard directory

### ISSUE THREAD

**Issue by fattahmuhyiddeen** [react-native-community/cli#1956]
## Environment

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M2
    Memory: 193.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 17.0.7 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Description

 I'm using mac without sudo / admin priviledge, therefore I need to install Java, Android Studio, Cocoapods etc in non-standard directory. All are working but the doctor said Android SDK and Cocoapods are missing

## Reproducible Demo

Install all dependencies in non standard directory and you will get the error

**Comment by szymonrybczak** [comment]
@fattahmuhyiddeen, any updates? :)

**Comment by adamTrz** [comment]
Closing the issue for now, will gladly reopen if there's an update :)
