### ISSUE TITLE
Dependency Update needed - fast-xml-parser@4.2.4

### ISSUE THREAD

**Issue by IDrumsey** [react-native-community/cli#1973]
The fast-xml-parser dependency for the `cli-platform-ios` needs updated to at least `4.2.4` to resolve [this vulnerability](https://github.com/NaturalIntelligence/fast-xml-parser/security/advisories/GHSA-6w63-h3fj-q4vw)

**Comment by szymonrybczak** [comment]
Thanks for your vigilance! Closing this issue since, the version was bumped to `4.2.5` :) See here: https://github.com/react-native-community/cli/pull/1993
