### ISSUE TITLE
npx-react profile-hermes returning error in windows

### ISSUE THREAD

**Issue by FrancisChristy** [react-native-community/cli#1979]
When i use this command to convert hermes file to chrome readable file, its throwing the following error

info Downloading a Hermes Sampling Profiler from your Android device...
info No filename is provided, pulling latest file
'grep' is not recognized as an internal or external command,
operable program or batch file.
error Error: Command failed: adb shell run-as com.newdocumentpicker ls cache/ -tp | grep -v /$ | grep -E '.cpuprofile' | head -1

**Comment by thymikee** [comment]
We would appreciate some help from you, as we don't have too much capacity for windows testing 🙏🏼

**Comment by FrancisChristy** [comment]
Sure. What should i do? 

> We would appreciate some help from you, as we don't have too much capacity for windows testing 🙏🏼

Sure. What should I do?

**Comment by thymikee** [comment]
Um, help us fix this :D Looking at the error, it seems we make assumption that "grep" command is there, while it's not on your Windows. We could either hint users to install grep (or equivalent) or use a different tool internally so that users don't need to install anything else, which is preferred.

**Comment by FrancisChristy** [comment]
> Um, help us fix this :D Looking at the error, it seems we make assumption that "grep" command is there, while it's not on your Windows. We could either hint users to install grep (or equivalent) or use a different tool internally so that users don't need to install anything else, which is preferred.

But if i give each command in that error ome by one, its working. I don't know the command o should give after head -1. If someone can help me with it, it mightfix everything.

**Comment by szymonrybczak** [comment]
Hey, I can reproduced the issue. @FrancisChristy your help will be very appreciated. I found that there are equivalent such as `findstr` or `find`.
