### ISSUE TITLE
run-ios fails to find scheme if it inside .xcworkspace

### ISSUE THREAD

**Issue by Reeywhaar** [react-native-community/cli#1997]
`run-ios` does lookup only inside `.xcodeproj` file but not in `.xcworkspace`. It fails with `Could not find scheme ***` error if scheme is inside `.xcworkspace`. For example my schemes are located in `./ios/Project.xcworkspace/xcshareddata/xcschemes/***.xcscheme`

[Corresponding code is here](https://github.com/react-native-community/cli/blob/5d8a8478cd104adf4a4dd34c09c2e256325ae61d/packages/cli-platform-ios/src/tools/getBuildConfigurationFromXcScheme.ts#L16)

**Comment by szymonrybczak** [comment]
Hm, afaik defining scheme is only possibly in `.xcodeproj` file. Why can't you simply create schemes in the `.xcodeproj` file? . cc. @cipolleschi pining to confirm if I'm thinking correctly

**Comment by Reeywhaar** [comment]
I didn't move them myself under .xcworkspace so I guess xCode can place them inside .xcworkspace under some circumstances. Yeah, I moved schemes under .xcodeproj and it seems to solve the issue for me I guess.

**Comment by szymonrybczak** [comment]
> Also everything worked on react-native pre 0.71

Very strange, please make sure to clean all caches, derived data etc. after upgrading to the latest version.

**Comment by cipolleschi** [comment]
Yeah, that should not happen. The .xcworkspace is automatically generated by Cocoapods, so it's very weird that the configuration is different from the standard.
You can always safely remove the `xcworkspace` and run `pod install` to regenerate it.

**Comment by giantslogik** [comment]
Had this happen, when migrating an App to RN 0.72.5. Best i can tell this happened cause the scheme always existed under the workspace, with no issues till RN 0.70.9.

Simple fix is to open the workspace in Xcode. Goto Product > Scheme > Manage Scheme and change the container of the scheme from "<My App> Workspace" to "<My App> Project"

**Comment by WeiXiaokun-iHealth** [comment]
I'm facing the same issue, and I've already tried above ways, it's not working.
So I init a new react-naive project and compare these two ios projects.
I found the diff project scheme is last one in the scheme list.
I move it to first one.
I know so werid, but It's working!

<img width="765" alt="image" src="https://github.com/react-native-community/cli/assets/165108295/0fc026f9-984f-478f-9a79-b32b747922b2">

**Comment by yunnnyunnn** [comment]
> I'm facing the same issue, and I've already tried above ways, it's not working. So I init a new react-naive project and compare these two ios projects. I found the diff project scheme is last one in the scheme list. I move it to first one. I know so werid, but It's working!
> 
> <img alt="image" width="765" src="https://private-user-images.githubusercontent.com/165108295/321525553-0fc026f9-984f-478f-9a79-b32b747922b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDk0OTYsIm5iZiI6MTcxNDEwOTE5NiwicGF0aCI6Ii8xNjUxMDgyOTUvMzIxNTI1NTUzLTBmYzAyNmY5LTk4NGYtNDc4Zi05YTc5LWIzMmI3NDc5MjJiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwNTI2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODhjMDM2Y2JiNTc0YWY1ZTVmMWJmMDg3NzEyODU0ZmE1ZmUzMGJlNzE0ZGM1NGMwMmFjZDBmMmM4YmJkZTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WgDWgYB-fl1DzqxOZiJA20-r4ozITNdRvR_UnPWta_4">

This helps!

**Comment by Ender-Wiggin2019** [comment]
> I'm facing the same issue, and I've already tried above ways, it's not working. So I init a new react-naive project and compare these two ios projects. I found the diff project scheme is last one in the scheme list. I move it to first one. I know so werid, but It's working!
> 
> <img alt="image" width="765" src="https://private-user-images.githubusercontent.com/165108295/321525553-0fc026f9-984f-478f-9a79-b32b747922b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQwMjI0MjEsIm5iZiI6MTc0NDAyMjEyMSwicGF0aCI6Ii8xNjUxMDgyOTUvMzIxNTI1NTUzLTBmYzAyNmY5LTk4NGYtNDc4Zi05YTc5LWIzMmI3NDc5MjJiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQwN1QxMDM1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MWYzMGE5NTA3NDE3NDI1NGQ0MWViNmI0YzljZjRiNTQwZTY4NWE4YTVlYjU1MDUxODUzZTkyZjNhYzBmZTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aumtoeHxvPkNfYkCXIDilUre4QRq4ujtZl864TZwAic">

Thanks, you save my day
