### ISSUE TITLE
React Native CLI depends on a vulnerable version of `semver`

### ISSUE THREAD

**Issue by jimblanc** [react-native-community/cli#2001]
## Description

React Native CLI is generating vulnerability alerts in NPM due to a recently published Semver vulnerability: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw

I noticed there is an approved PR out that should resolve this issue: https://github.com/react-native-community/cli/pull/1985

Would it be possible to get this merged & released to clear up the warnings?

## Reproducible Demo

```
npm install @react-native-community/cli
npm audit
```

**Comment by thymikee** [comment]
https://github.com/react-native-community/cli/pull/1985 is already merged. We'll release it later with other changes, as it's a moderate severity and we're not affected
