### ISSUE TITLE
ios-deploy recommended installation method

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [react-native-community/cli#2011]
Hi

When trying to run a react-native app on a physical iOS device, you are required to have `ios-deploy` installed. The message you receive from `npx react-native run-ios` if you try to run it on a device without having `ios-deploy` installed is 

> error Failed to install the app on the device because we couldn't execute the "ios-deploy" command. Please install it by running "npm install -g ios-deploy" and try again.

[From this code](https://github.com/react-native-community/cli/blob/5234f69ca77b565b80c8e3e08269e86f1ad6e7fa/packages/cli-platform-ios/src/commands/runIOS/index.ts#L362C7-L364C27).

However, the only recommended way of installing `ios-deploy` from their own [documentation](https://github.com/ios-control/ios-deploy#Installation) is via Homebrew. As the [React Native "getting-started" documentation](https://reactnative.dev/docs/environment-setup) already encourages the use of Homebrew, I was wondering if the error message mentioning `npm` is a conscious choice?

Best regards
Jens

**Comment by szymonrybczak** [comment]
Hi @jenskuhrjorgensen 👋 Thanks for creating issue! I created [PR](https://github.com/react-native-community/cli/pull/2013) with fixing this :)
