### ISSUE TITLE
Add option to start command to reverse 8081 port after connection is lost

### ISSUE THREAD

**Issue by bcye** [react-native-community/cli#2019]
## Describe the Feature

When the connection to a physical android device is lost, one is unable to reload the bundle/app after reconnecting the device, as the port reversal done as part of run-android is not valid anymore. I would suggest adding another option "c - reconnect server" to the shortcuts available in the start command (D for developer menu, a for android, etc.). Would like to try to implement this if it's wanted :)

## Possible Implementations

This should just need to
It should be enough to run adb reverse tcp:8081 tcp:8081, though it needs to be adjusted if the bundler is running on a different port

## Related Issues

[I reported this first in the metro repository](https://github.com/facebook/metro/issues/1034#issuecomment-1638869106)

**Comment by szymonrybczak** [comment]
> It could be run automatically after this error message:
No apps connected. Sending "reload" to all React Native apps failed. Make sure your app is running in the simulator or on a phone connected via USB.

AFAIK the part for this lives in React Native core, so I *think* there should be added implementation for this.

**Comment by bcye** [comment]
@cortinico Thanks, though I already raised it [there and they directed me here](https://github.com/facebook/metro/issues/1034#issuecomment-1638869106), I also already found code relating to this in `enableWatchMode` in cli-plugin-metro.

@szymonrybczak Do you know where it would relate in React Native? I'm a bit confused now :D I already had a look at the code and found that the error message ("No apps connected...") is produced in `handleSendBroadcast` in createMessageSocketEndpoint (cli-server-api). I'd think it should be possible to just add the adb call to that logic, though I'm unsure if its possible to call adb there, or how I'd get a hold of the metro port there?

**Comment by cortinico** [comment]
> @cortinico Thanks, though I already raised it [there and they directed me here](https://github.com/facebook/metro/issues/1034#issuecomment-1638869106), I also already found code relating to this in `enableWatchMode` in cli-plugin-metro.

Oh thanks for the pointer, I thought the menu you see is part of Metro, but it turns out it's not. Then you're in the right place.

**Comment by szymonrybczak** [comment]
@bcye oh sorry, yeah that lives in CLI - I never remember correctly which parts lives in React Native and which in CLI. I think we can go with something like this - add to error message information that maybe to solve this problem you just need to reverse port, and to do so you need to run `adb reverse port port`, or press `a` (maybe we can figure out better letter for this) in terminal window that is running Metro bundler. (I wouldn't show in terminal that "`a` - reverse adb ports" because it isn't used very often, I would just handle a key press and run `adb reverse` once it is pressed.)
