### ISSUE TITLE
How do I define reporter in metro.config.js?

### ISSUE THREAD

**Issue by zhiqingchen** [react-native-community/cli#2020]
## Ask your Question

Cli always overrides the definition of reporter, I can't override the reporter in metro.config.js

### metro reporter config
https://facebook.github.io/metro/docs/configuration/#reporter

### cli override
https://github.com/react-native-community/cli/blob/main/packages/cli-plugin-metro/src/commands/start/runServer.ts#L56-L65

**Comment by szymonrybczak** [comment]
Hey @zhiqingchen, you can use [`--customLogReporterPath`](https://github.com/react-native-community/cli/blob/main/packages/cli-plugin-metro/README.md#--custom-log-reporter-path---customlogreporterpath-string) option to provide path to custom TerminalReporter when starting Metro. Does this solution satisfy you? or do you need to replace the whole reporter in your case?

**Comment by zhiqingchen** [comment]
@szymonrybczak Thanks for the reply.
I've customized the metro configuration a bit more, and the reporter is logically associated with the cacheStore and server.

https://github.com/NervJS/taro/blob/feat/react-native-72/packages/taro-rn-supporter/src/Support.ts#L85-L107

The --customLogReporterPath option is more difficult for me to use.

**Comment by zhiqingchen** [comment]
ok, i will try
