### ISSUE TITLE
CLI update instructions in README.md don't work

### ISSUE THREAD

**Issue by liamjones** [react-native-community/cli#2030]
## Environment

```
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 217.78 MB / 32.00 GB
    Shell: 5.9 - /usr/local/bin/zsh
  Binaries:
    Node: 18.17.0 - /var/folders/h6/g6rldscd6h389g9w42_7k_jm0swv2d/T/yarn--1690274747721-0.5199367476257593/node
    Yarn: 1.22.19 - /var/folders/h6/g6rldscd6h389g9w42_7k_jm0swv2d/T/yarn--1690274747721-0.5199367476257593/yarn
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/15092_1689782556741/bin/npm
    Watchman: 2023.07.24.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29, 30, 31, 32, 33
      Build Tools: 27.0.3, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0
      System Images: android-24 | Google APIs Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-31 | Google APIs Intel x86_64 Atom, android-32 | Google Play Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86 Atom_64, android-S | Google Play Intel x86 Atom_64, android-Tiramisu | Google Play Intel x86 Atom_64, android-UpsideDownCake-ext5 | Google Play Intel x86_64 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: Flamingo 2022.2.1 Patch 2 Flamingo 2022.2.1 Patch 2
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /Users/liam.jones/.sdkman/candidates/java/11.0.19-tem/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.12 => 0.71.12
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.72.3 is now available (your project is running on v0.71.12).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.72.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.71.12
info For more info, check out "https://reactnative.dev/docs/upgrading".
```

## Description

[The README](https://github.com/react-native-community/cli/blob/1fc7eba4fc40b1de88cc4ea3268ea24e8ec67b32/README.md#updating-the-cli) talks about clearing the `@react-native-community/cli*` packages from your lock file and reinstalling to update the CLI.

However, the react-native package seems to configure the CLI to a specific version so this doesn't work.

0.71.12 (our version): https://github.com/facebook/react-native/blob/v0.71.12/package.json#L113
0.72.3 (latest): https://github.com/facebook/react-native/blob/v0.72.3/packages/react-native/package.json#L82

This means it doesn't update after clearing the lock and reinstalling. For example, 10.2.5 is available, which should be compatible with 0.71.12 but 10.2.4 still gets reinstalled.

Let me know if you want this raised on the RN project repo instead? I wasn't sure if you wanted to update the instructions to suggest yarn resolutions / npm overrides or adding the CLI to your project's package.json directly as the solution or for the version specifier in the RN package to be loosened instead.

## Reproducible Demo

```shell
~/code
❯ npx react-native@latest init TestProject --version 0.72.3
[...snip...]

~/code
❯ cd TestProject

~/code/TestProject
❯ yarn list --pattern @react-native-community/cli
yarn list v1.22.19
├─ @react-native-community/cli-clean@11.3.5
├─ @react-native-community/cli-config@11.3.5
├─ @react-native-community/cli-debugger-ui@11.3.5
├─ @react-native-community/cli-doctor@11.3.5
├─ @react-native-community/cli-hermes@11.3.5
├─ @react-native-community/cli-platform-android@11.3.5
├─ @react-native-community/cli-platform-ios@11.3.5
├─ @react-native-community/cli-plugin-metro@11.3.5
├─ @react-native-community/cli-server-api@11.3.5
├─ @react-native-community/cli-tools@11.3.5
├─ @react-native-community/cli-types@11.3.5
└─ @react-native-community/cli@11.3.5
✨  Done in 0.52s.``` 

(Note 11.3.5 installed even though 11.3.6 is released)

**Comment by szymonrybczak** [comment]
Hey, thanks for creating issue! I believe this was changed few releases ago, and we didn't sync the docs with how actually should we update CLI. I think that the only way to update CLI right now regardless of React Native releases is to specify `overrides` or `resolutions` field in `package.json`. I would wait for @thymikee to confirm that, but he is right now on vacation, so this can take a while.

**Comment by liamjones** [comment]
Removing the stale tag and reminding @thymikee Szymon was looking for his input here.

**Comment by thymikee** [comment]
Yeah, what @szymonrybczak says, use resolutions. We picked pinned dependencies to avoid certain class of bugs for react-native users, and unfortunately it comes with some downsides like this. Thankfully resolutions provide workaround :) Do you want to send a PR?
