### ISSUE TITLE
How do I set this up in a Kotlin multiplatform library project?

### ISSUE THREAD

**Issue by dcabanfc** [react-native-community/cli#2037]
I'm trying to install the react native modules in my kotlin multiplatform project in order to create UI components specific to android and ios in this shared library. The goal is to build an SDK that will return a ready to go native component so a consumer can just add this component to their project without having to know the implementation details. Ideally, I'd like to return a native component from the SDK for the dependent mobile platform. Whether it be an Android react component on Android or w.e iOS's specifc UI component is. 

Basically, mySDK.GetComponent() should return a native component for the mobile project using this SDK.

I've tried converting some of the gradle commands I saw to my kotlin shared library project but it seems it isn't working due to the native_modules.gradle file using syntax that kotlin or this type of project doesn't know about.

`apply(from = "../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle")
val applyNativeModulesAppBuildGradle: Closure<Any> by ext
applyNativeModulesAppBuildGradle(project)`

Error: Could not get unknown property 'preBuild' for root project 'MySDK' of type org.gradle.api.Project. 

This error is thrown from applyNativeModulesAppBuildGradle.

Any ideas if I'm going about this incorrectly or is it that the project just doesn't support kotlin yet?

**Comment by szymonrybczak** [comment]
@cortinico mind looking at this issue? 🙏

**Comment by cortinico** [comment]
> Any ideas if I'm going about this incorrectly or is it that the project just doesn't support kotlin yet?

@dcabanfc do you have a playground project we could look into?
The problem you're having is that you're attempting to use `applyNativeModulesAppBuildGradle` inside a `build.gradle.kts` file rather than a `build.gradle` file I believe, but without seeing the code is going to be hard to support you.
