### ISSUE TITLE
What's wrong with react-native upgrade command? 0.67.5 to any upper version

### ISSUE THREAD

**Issue by AdarshJais** [react-native-community/cli#2038]
## Environment

info Fetching system and libraries information...
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 120.59 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /Users/adarshjaiswal/.rvm/gems/ruby-2.7.5/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33
      Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 25.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 30.0.3, 32.0.0, 32.1.0, 33.0.0
      System Images: android-31 | Google Play ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.20 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 6.0.0 => 6.0.0 
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.5 => 0.67.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Things I’ve done to figure out my issue

- [check] I used [upgrade-helper](https://react-native-community.github.io/upgrade-helper/) to do my upgrade.
i used react-native upgrade command

## Upgrading version

0.68.0

## Description

<img width="935" alt="Screenshot 2023-07-26 at 7 50 46 PM" src="https://github.com/react-native-community/upgrade-support/assets/40723757/80c8d613-33cf-40a3-9fd4-a9a9cd872c69">

**Comment by szymonrybczak** [comment]
Hey, thanks for creating issue! Recently we removed `upgrade` command - and we do not support it anymore. Please follow [React Native Upgrader Helper](https://react-native-community.github.io/upgrade-helper/) to upgrade your app.

**Comment by AdarshJais** [comment]
So you mean, we have to manually do all the relevant changes? If yes, May I know what's the idea behind this? Was there any limitation or issues that weren't able to accomplish? Basically in a nutshell Is there any case study behind this decision?

**Comment by szymonrybczak** [comment]
Unfortunately right now you have to everything manually, [here's](https://github.com/react-native-community/cli/pull/1879) the Pull Request where we discussed this decision. We know that is big pain of React Native, and we're working on improving this. I hope that in future this will be much easier!
