### ISSUE TITLE
Stuck at info JS server already running on Windows 11 Build:22621.1992 AFter uninstalling React Native App on Physical device

### ISSUE THREAD

**Issue by harontaiko** [react-native-community/cli#2039]
## Environment

System:
  OS: Windows 10 10.0.22621
  CPU: (4) x64 Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
  Memory: 308.80 MB / 3.88 GB
Binaries:
  Node:
    version: 18.16.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 9.5.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "25"
      - "26"
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 29.0.2
      - 29.0.3
      - 30.0.0
      - 30.0.1
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
    System Images:
      - android-33 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-222.4459.24.2221.10121639
  Visual Studio: Not Found
Languages:
  Java:
    version: 11.0.18
    path: /c/Program Files/Microsoft/jdk-11.0.18.10-hotspot/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

## Description

Initially, the app was working fine, and after running it some issues with firebase, i uninstalled the app from the device, and re run 
`npm run android`, from terminal(gitbash) on vscode, it opened another terminal like so
![Screenshot 2023-07-27 162259](https://github.com/react-native-community/cli/assets/43775270/a4e5d291-ec58-48be-b647-548ade1aecc6)
I have even tried, creating another app with a different name still doesn't work and completely shutting down the machine several times, killing node, adb processes but nothing works, it still gets stuck at this place

## Reproducible Demo
 - Create a react app using `npx react-native@latest init ProjectName`
 - Run Successfully, assuming the evironment is setup
 - Uninstall App from the device at least once, then try running using npm run android

**Comment by szymonrybczak** [comment]
Hey @harontaiko 👋 Thanks for creating issue! Recently we fixed very similar bug (https://github.com/react-native-community/cli/pull/2014) but I think in your case is something different.
Can you you please test few things, so that it will be easier for us to fix your issue: 
- Does `build-android` command works correctly?
- Does running app on emulator works correctly?

**Comment by harontaiko** [comment]
yes, on emulatorit works great, but i need it to run on the physical device

**Comment by szymonrybczak** [comment]
Hm, could you please try building app via Android Studio?

**Comment by harontaiko** [comment]
i tried via android studio, and i run either npm run android, still opens another terminal and gets stuck at infoJS server already running

**Comment by harontaiko** [comment]
So, i cd into the android folder from my root foder, once in the android folder i ran ./gradlew clean and it got stuck at 71% the issue being 'no aar for react native reanimated found', so i removed the react-native-reanimated package, it was version, [2.17.0](https://www.npmjs.com/package/react-native-reanimated/v/2.17.0) and ran npm run android and it Worked!

**Comment by AriqAhmer** [comment]
> So, i cd into the android folder from my root foder, once in the android folder i ran ./gradlew clean and it got stuck at 71% the issue being 'no aar for react native reanimated found', so i **removed the react-native-reanimated package**, it was version, [2.17.0](https://www.npmjs.com/package/react-native-reanimated/v/2.17.0) and ran npm run android and it Worked!

The last part worked for me! After running ./gradlew clean, mine got stuck at 50% but it didn't throw any error. So I decided to end the task and removed the **react-native-reanimated** package. Thanks a lot @harontaiko

**Comment by omnaladkar** [comment]
> > So, i cd into the android folder from my root foder, once in the android folder i ran ./gradlew clean and it got stuck at 71% the issue being 'no aar for react native reanimated found', so i **removed the react-native-reanimated package**, it was version, [2.17.0](https://www.npmjs.com/package/react-native-reanimated/v/2.17.0) and ran npm run android and it Worked!
> 
> The last part worked for me! After running ./gradlew clean, mine got stuck at 50% but it didn't throw any error. So I decided to end the task and removed the **react-native-reanimated** package. Thanks a lot @harontaiko

does it work ? bcoz i also not getting any error
