### ISSUE TITLE
Update doctor Java version to reflect >= 17

### ISSUE THREAD

**Issue by cortinico** [react-native-community/cli#2044]
## Describe the Feature
This line needs to be updated:
https://github.com/react-native-community/cli/blob/0cbed3d09d3009f0b116ecb4882d12af0ee30bde/packages/cli-doctor/src/tools/versionRanges.ts#L7

Specifically from React Native 0.73, we'll require user to have JDK 17.
I would also like to ask if someone is up for trying the `react-native@nightly` against JDK 19 and 20 so that we can verify if it works correctly in those scenarios and relax the range.

**Comment by szymonrybczak** [comment]
> Specifically from React Native 0.73, we'll require user to have JDK 17. I would also like to ask if someone is up for trying the `react-native@nightly` against JDK 19 and 20 so that we can verify if it works correctly in those scenarios and relax the range.

I ran `./gradlew assmebleRelease` and `./gradlewBundleRelease` with these two version of Java in `@nightly` version and everything is working fine!

**Comment by cortinico** [comment]
@szymonrybczak have you tested with JDK 20 plus React Native 0.72.x? As this user is reporting a failure: https://github.com/facebook/react-native/issues/39436

**Comment by szymonrybczak** [comment]
@cortinico Yup, I tested it with Java 20.0.2, and it works fine for me.

![CleanShot 2023-09-18 at 21 51 43](https://github.com/react-native-community/cli/assets/63900941/71d6dfea-623a-4acc-87f5-d4b64d4adf57)
