### ISSUE TITLE
Init command with --title option doesn't reflect changes

### ISSUE THREAD

**Issue by prawat-stackflow** [react-native-community/cli#2053]
## Environment

System:
  OS: macOS 13.1
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
  Memory: 1.94 GB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 16.20.1
    path: ~/.nvm/versions/node/v16.20.1/bin/node
  Yarn: Not Found
  npm:
    version: 8.19.4
    path: ~/.nvm/versions/node/v16.20.1/bin/npm
  Watchman:
    version: 2023.08.07.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9477386
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Description

Tried to create a fresh react-native app with --title option but the app title still shows as <projectName>

COMMAND :
npx react-native init RNTestApp --title="MyApp"
npx react-native init RNTestApp --title "MyApp"
npx react-native init RNTestApp --title "My App"

All of the above commands didnt change app title

## Reproducible Demo

Just try to use above commands and the app title isn't updated

**Comment by szymonrybczak** [comment]
Hey @prawat-stackflow, so I ran `npx react-native@latest init RNTestApp --title "MyApp"`, and the "MyApp" was replaced in correct files, see here:
<img width="617" alt="CleanShot 2023-08-09 at 16 27 14@2x" src="https://github.com/react-native-community/cli/assets/63900941/fcf3dd7d-71e3-4b27-a9d9-e1108aea641c">
so that after I ran this app on simulator I can see the "MyApp" as app name.

**Comment by prawat-stackflow** [comment]
@szymonrybczak Yes, now working for me as well don't know why it didn't worked yesterday. I also tried with "My App" and "My&#x2007;App" for the space which doesn't work as well,found out spaces are not supported in react-native title option,. Closing this one

**Comment by szymonrybczak** [comment]
> " for the space which doesn't work as well,found out spaces are not supported in react-native title optio

That's looks like something we should fix.
