### ISSUE TITLE
Autostart metro server in Xcode with monorepo

### ISSUE THREAD

**Issue by exzos28** [react-native-community/cli#2064]
## Environment

"react-native": "0.72.3"
"@react-native-community/cli" "11.3.5"

## Description

Hi, I have this problem that the server autostart is not working.

I have a monorep:
- packages
-- mobile
-- shared

All modules are stored in the root.

The error occurs when running packages/mobile/ios in Xcode (without running metro server):
```
Node found at: /Users/user/.nvm/versions/node/v16.20.0/bin/node
error No metro config found in /Users/user/Documents/dev/monorepo.
Process terminated. Press <enter> to close the window
```

This is because `launchPackager.command` is trying to find `metro.config.js` relative to where it is located (in the root node_modules). 

<img width="1155" alt="image" src="https://github.com/react-native-community/cli/assets/39951413/f0e9494c-d487-44f8-ad55-83f5119df723">

## Demo
You need to open `packages/mobile/ios` in XCode and just run it.
https://github.com/exzos28/mono-repo

**Comment by szymonrybczak** [comment]
Hey! Thanks for creating issue, so the problem is that some time ago we introduced new field `PROJECT_ROOT`, and that's where we're starting a dev server. But in your script you have only the `RCT_METRO_PORT`, so there are two ways to fix it:
- Add exporting `PROJECT_ROOT` to the build phase:
  <details>
  <summary>With this diff</summary>
  
  ```diff
  diff --git forkSrcPrefix/packages/mobile/ios/mobile.xcodeproj/project.pbxproj forkDstPrefix/packages/mobile/ios/mobile.xcodeproj/project.pbxproj
  index 4a7e4c10e75e9de9902ed7d550e24d2c74b9ea43..9c640d3e5f42bd4e1f626b46d8e46d328946d404 100644
  --- forkSrcPrefix/packages/mobile/ios/mobile.xcodeproj/project.pbxproj
  +++ forkDstPrefix/packages/mobile/ios/mobile.xcodeproj/project.pbxproj
  @@ -394,7 +394,7 @@
 			  );
 			  runOnlyForDeploymentPostprocessing = 0;
 			  shellPath = /bin/sh;
  -			shellScript = "export RCT_METRO_PORT=\"${RCT_METRO_PORT:=8081}\"\necho \"export RCT_METRO_PORT=${RCT_METRO_PORT}\" > \"${SRCROOT}/../../../node_modules/react-native/scripts/.packager.env\"\nif [ -z \"${RCT_NO_LAUNCH_PACKAGER+xxx}\" ] ; then\n  if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then\n    if ! curl -s \"http://localhost:${RCT_METRO_PORT}/status\" | grep -q \"packager-status:running\" ; then\n      echo \"Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly\"\n      exit 2\n    fi\n  else\n    open \"$SRCROOT/../../../node_modules/react-native/scripts/launchPackager.command\" || echo \"Can't start packager automatically\"\n  fi\nfi\n";
  +			shellScript = "export RCT_METRO_PORT=\"${RCT_METRO_PORT:=8081}\"\necho \"export PROJECT_ROOT=$(pwd) export RCT_METRO_PORT=${RCT_METRO_PORT}\" > \"${SRCROOT}/../../../node_modules/react-native/scripts/.packager.env\"\nif [ -z \"${RCT_NO_LAUNCH_PACKAGER+xxx}\" ] ; then\n  if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then\n    if ! curl -s \"http://localhost:${RCT_METRO_PORT}/status\" | grep -q \"packager-status:running\" ; then\n      echo \"Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly\"\n      exit 2\n    fi\n  else\n    open \"$SRCROOT/../../../node_modules/react-native/scripts/launchPackager.command\" || echo \"Can't start packager automatically\"\n  fi\nfi\n";
 			  showEnvVarsInLog = 0;
 		  };
   /* End PBXShellScriptBuildPhase section */
  
  ```
  </details>
- Remove this _Start Packager_ build phase, in newer versions of React Native a template won't contain it (see here: https://github.com/react-native-community/discussions-and-proposals/discussions/681). I would go with the second way, and just start the packager in another terminal window before starting a build - as this is a new behaviour.

**Comment by exzos28** [comment]
@szymonrybczak I appreciate your quick response. I should learn more about shell script. 🤔

Issue may be closed.
