### ISSUE TITLE
Components Url update

### ISSUE THREAD

**Issue by Ashackq** [react-native-community/cli#2068]
## Possible Implementations
downloadAndUnzip.downloadurl == "...."

## Related Issues
update the URL for android studios 
it is still downloading v3.18

**Comment by szymonrybczak** [comment]
Hey @Ashackq, could you please elaborate more on this issue? The description should be described better.

**Comment by Ashackq** [comment]
Hello @szymonrybczak 
When I use native doctor for fixing my issues like installing Android Studios and the SDK and as I press e to fix my errors 
The doctor downloaded the Android studios@3.18 version and not the latest i.e. flamingo. 
Due to this, I wasn't able to use new emulator versions and cmd - line tool were not latest too

I was suggesting to update the URL for the SDK and android studios to solve the same

**Comment by Ashackq** [comment]
> Hey @Ashackq, could you please elaborate more on this issue? The description should be described better.
Hello @szymonrybczak 
When I use native doctor for fixing my issues like installing Android Studios and the SDK and as I press e to fix my errors 
The doctor downloaded the Android studios@3.18 version and not the latest i.e. flamingo. 
Due to this, I wasn't able to use new emulator versions and cmd - line tool were not latest too

I was suggesting to update the URL for the SDK and android studios to solve the same

**Comment by szymonrybczak** [comment]
Oh, that's sounds like a great idea. I'll update those versions soon. 🙌

**Comment by Ashackq** [comment]
Perfect
