### ISSUE TITLE
Run `clean` command when we're unable to resolve issues in `doctor`

### ISSUE THREAD

**Issue by szymonrybczak** [react-native-community/cli#2069]
## Describe the Feature
When we're unable to resolve the issue in `doctor` command we can try running `clean` command to clean caches for user, maybe that's the possible solution for fixing the problem.

**Comment by thymikee** [comment]
We could offer this as an option prompted to the user

**Comment by cortinico** [comment]
> When we're unable to resolve the issue in `doctor` command we can try running `clean` command to clean caches for user,

Can you be more specific on which kind of issues?
As a rule of thumb, `doctor` should inspect the environment. Suggesting `./gradlew clean` shouldn't affect the environment. Moreover, if the environment is broken, invoking `clean` will most likely not work properly.
