### ISSUE TITLE
Open js server in a new tab instead of a new window

### ISSUE THREAD

**Issue by siddarthkay** [react-native-community/cli#2070]
## Describe the Feature
Whenever we run something like `npx react-native run-android` and when the js server is not already running, there is a new terminal window opened up because of code at : 
`packages/cli-tools/src/startServerInNewWindow.ts`

Its my personal opinion that it would be better if in such cases it was possible to open a new tab in the existing terminal instead of opening up a new window.

Would you be open to such a feature request?
If yes then I would be happy to send in a PR

## Possible Implementations
This behaviour could be disabled by default.
Make something like this `packages/cli-tools/src/startServerInNewTab.ts` and maybe allow passing a flag to `run-android` command to enable this behaviour.
 
## Related Issues
There are no related issues :)

**Comment by szymonrybczak** [comment]
Hey, that's very interesting. In my case it is working properly see here: 

https://github.com/react-native-community/cli/assets/63900941/75f0730b-c4f7-4257-9552-18200160a666

maybe it's problem with your terminal? And please provide your system details, are you on MacOS or Linux - just run `npx react-native info`.

**Comment by siddarthkay** [comment]
Hi @szymonrybczak : Thanks for your swift response, I'm on MacOS
On MacOS Terminal.app this opens in a new window, However when I use iTerm I can see that a new tab is opened(The same way as shown in your screen recording).

My info incase it is needed : 
```
info Fetching system and libraries information...
System:
  OS: macOS 13.5.2
  CPU: (8) arm64 Apple M2
  Memory: 122.19 MB / 24.00 GB
  Shell:
    version: 5.2.15
    path: /nix/store/n45jv82x1cpkmyl2qiy5gqsm3vhdg9sc-bash-interactive-5.2-p15/bin/bash
Binaries:
  Node:
    version: 18.16.0
    path: /nix/store/mfrzb46340qzyzf0laa24y0xg06xsif9-nodejs-18.16.0/bin/node
  Yarn:
    version: 1.22.19
    path: /nix/store/a5ccf2qwsdz9sji78n2cngy0alq63gf7-yarn-1.22.19/bin/yarn
  npm:
    version: 9.5.1
    path: /nix/store/mfrzb46340qzyzf0laa24y0xg06xsif9-nodejs-18.16.0/bin/npm
  Watchman:
    version: 4.9.0
    path: /nix/store/6finpn1yrlhcxx16a7zqhi2in2wawimi-watchman-4.9.0/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /nix/store/898zp2782i08wd1gygnyhglqyzl0081a-cocoapods-1.12.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 19.0.1
    path: /usr/bin/javac
  Ruby:
    version: 3.1.2
    path: /Users/siddarthkumar/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 11.3.7
    wanted: ^11.3.7
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: false
  newArchEnabled: Not found
  ```
github repo : https://github.com/status-im/status-mobile

**Comment by cortinico** [comment]
I believe @robhogan did some investigation in this space in the past

**Comment by siddarthkay** [comment]
If opening in tab is indeed the intended behaviour then I can try investigating further and would be interested to open a PR for fixing this issue. 
Although if a fix is already in the works that would be good to know as well @cortinico @robhogan :)

**Comment by szymonrybczak** [comment]
@robhogan do you have maybe any updates on this?

**Comment by robhogan** [comment]
Hey, no, I *was* looking into an issue with the way we launch a terminal from xcode causing a permissions error on macOS, but I think that went away with a subsequent macOS version. I don't have anything else related in the works.
