### ISSUE TITLE
cocoapods and SSL Failed

### ISSUE THREAD

**Issue by abdelfatah-ashour** [react-native-community/cli#2080]
## Environment

- Node 20
- ruby 2.7.8
- cocoapods 1.12

## Description

Try to set the local environment using React Native CLI, And the process being installing cocopods I got this error related to SSL.  on visiting this URL [cocoapods CDN](https://cdn.jsdelivr.net/cocoa/Specs/0/9/9/libevent/2.1.11/libevent.podspec.json) response with not found and must open VPN to get it.

`CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/0/9/9/libevent/2.1.11/libevent.podspec.json Response: SSL connect error`

## Reproducible Demo

`npx react-native@latest init AwesomeProject`

**Comment by cortinico** [comment]
Closing as per https://github.com/facebook/react-native/issues/39491#issuecomment-1725312286
