### ISSUE TITLE
react-native doctor not find Android Studio

### ISSUE THREAD

**Issue by sli930** [react-native-community/cli#2084]
## Ask your Question

```
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: 30.0.3, 33.0.1, 34.0.0
   - Version supported: 33.0.0
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
```
- local.properties
```
sdk.dir=/home/sam/Android/Sdk
```

- echo $PATH
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/lib/jvm/java-17-openjdk-amd64/bin:/snap/android-studio/current/android-studio/bin:/home/sam/Android/Sdk/emulator:/home/sam/Android/Sdk/build-tools:/home/sam/Android/Sdk/platforms:/home/sam/Android/Sdk/platform-tools:/home/sam/Android/Sdk/cmdline-tools/latest/bin
```

- echo $ANDROID_HOME
```
/home/sam/Android/Sdk
```

I installed Snap Version Android Studio on Ubuntu Software. I have checked the Sdk floder is correct.

**Comment by muammertopcu** [comment]
I have the same issue on Ubuntu 22.04

```
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ yarn - Required to install NPM dependencies

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✖ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 33.0.0
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

```

**Comment by szymonrybczak** [comment]
Hey @sli930, could you please install [`envinfo`](https://www.npmjs.com/package/envinfo) package globally and try running `envinfo --IDEs` to check if this tool finds correctly Android Studio path?

**Comment by ctoto93** [comment]
@szymonrybczak I have exactly a similar problem. Envinfo does not find the Android Studio path, installed from snap. What can I do to solve the issue? Thank you for your help :)

**Comment by szymonrybczak** [comment]
@ctoto93 mind sharing output of `envinfo --IDEs` command?

**Comment by liquidvisual** [comment]
Just ran into this when upgrading to Sonoma. Android sdk is not being recognised after install. Can anyone help out?

**Comment by prasantadh** [comment]
I came here having the same issue. For me the problem wasn't the configuration or the installation. It just required Android Studio to be running (I thought installation was enough)

**Comment by gaozhidf** [comment]
I create an issue, and it seems the bug by `envinfo`
https://github.com/tabrindle/envinfo/issues/250

**Comment by seyedmahdii** [comment]
For me this was the solution (Ubuntu 22.04.4 LTS):
1. for ✖ Android SDK as others said, you need to install sdkmanager using android sdk command line tools in settings/android sdk/sdk tools
2. For ✖ Android Studio I changed the custom installation path to /opt/ for shared users. You can read more [[here](https://developer.android.com/studio/install#linux)](url)

**Comment by ILOVEZC** [comment]
How can I resolve this problem
`  IDEs:
    VSCode: 0.46.8 - d:\cursor\resources\app\bin\code.CMD`

**Comment by ILOVEZC** [comment]
I have everything ready except the as.
