### ISSUE TITLE
Specifying --port or metro.config.js 's server.port bootstraps the metro server twice

### ISSUE THREAD

**Issue by DefiCake** [react-native-community/cli#2090]
Original issue opened at https://github.com/facebook/react-native/issues/39703

## Environment

System:
OS: macOS 13.5.2
CPU: (10) arm64 Apple M1 Pro
Memory: 412.50 MB / 16.00 GB
Shell:
version: "5.9"
path: /bin/zsh
Binaries:
Node:
version: 18.18.0
path: ~/.nvm/versions/node/v18.18.0/bin/node
Yarn:
version: 1.22.19
path: ~/.nvm/versions/node/v18.17.1/bin/yarn
npm:
version: 9.8.1
path: ~/.nvm/versions/node/v18.18.0/bin/npm
Watchman:
version: 2023.09.18.00
path: /opt/homebrew/bin/watchman
Managers:
CocoaPods:
version: 1.13.0
path: /Users/mad/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
iOS SDK:
Platforms:
- DriverKit 23.0
- iOS 17.0
- macOS 14.0
- tvOS 17.0
- watchOS 10.0
Android SDK: Not Found
IDEs:
Android Studio: Not Found
Xcode:
version: 15.0/15A240d
path: /usr/bin/xcodebuild
Languages:
Java:
version: 11.0.20.1
path: /usr/bin/javac
Ruby:
version: 2.7.6
path: /Users/mad/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
"@react-native-community/cli": Not Found
react:
installed: 18.2.0
wanted: 18.2.0
react-native:
installed: 0.72.5
wanted: 0.72.5
react-native-macos: Not Found
npmGlobalPackages:
"react-native": Not Found
Android:
hermesEnabled: true
newArchEnabled: false
iOS:
hermesEnabled: true
newArchEnabled: false

## Description

I am having a weird issue where if npx react-native start --port 8090 or do this in the metro.config.js file:

```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  server: {
    port: 8091,
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
```

when I run the android (haven't checked on ios) build, another window opens in my terminal. The first and second terminal run in parallel and if ports are coincidental, one will crash due to EADDR IN USE.

## Reproducible Demo

Not sure how to give a demo on this. Attached a video recording

https://github.com/react-native-community/cli/assets/46090742/afc09c1c-26bc-45df-b0a0-9d0d5422b5ce

**Comment by szymonrybczak** [comment]
Hey @DefiCake, this can seem strange behaviour, but we need to keep it in that way. We need to care about cases that someone needs to bundle iOS app from another port that Android app. If that's annoying for you can disable starting packager from `react-native.config.js`:

```
module.exports = {
  project: {
    android: {
      watchModeCommandParams: ['--no-packager'],
    },
  },
};
```
