### ISSUE TITLE
launchPackager.command Exec format error

### ISSUE THREAD

**Issue by wilav-dev** [react-native-community/cli#2095]
I'm getting the following error on my mac when running npm run android.

`Failed to execute process '..../react_native/node_modules/.bin/launchPackager.command'. Reason:
exec: Exec format error
The file '.../react_native/node_modules/.bin/launchPackager.command' is marked as an executable but could not be run by the operating system.
`

react-native-cli: 2.0.1
react-native: 0.72.5

As a workaround I add #!/bin/bash to the first line in launchPackager.command.
Any idea?

**Comment by szymonrybczak** [comment]
Hey @wilav-dev,
thanks for creating issue! That's a proper solution I added the `#!/bin/bash` line to the `launchPackager.command` 👍 Do you mind testing it?

**Comment by wilav-dev** [comment]
Thank you! I'm reinstalling package from npm and still getting the file without the shebang. Any idea? I clean npm cache, deleted node_modules and package-lock.json
