### ISSUE TITLE
option to initialize a project without flipper

### ISSUE THREAD

**Issue by AminDannak** [react-native-community/cli#2098]
## Describe the Feature
just having an option to initialize a new react native project without being forced to use flipper!

## Possible Implementations
probably something like this:
`npx react-native init --template no-flipper`
or
`npx react-native init --no-flipper`
## Related Issues
I saw this issue in flipper repo: https://github.com/facebook/flipper/issues/4748

**Comment by szymonrybczak** [comment]
Hey @AminDannak, as of this [RFC](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0641-decoupling-flipper-from-react-native-core.md) Core Team is removing Flipper integration from template so starting from React Native 0.73 Flipper is not longer included by default in template.

**Comment by cortinico** [comment]
> Hey @AminDannak, as of this [RFC](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0641-decoupling-flipper-from-react-native-core.md?rgh-link-date=2023-10-05T10%3A42%3A37Z) Core Team is removing Flipper integration from template so starting from React Native 0.73 Flipper is not longer included by default in template.

To clarify, this is not entirely correct. Flipper is still included in the template for 0.73 as deprecated, but will be removed in 0.74
