### ISSUE TITLE
run-android with --mode fails without error info (after upgrading to v72.5)

### ISSUE THREAD

**Issue by fikkatra** [react-native-community/cli#2105]
## Environment
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1 Pro
  Memory: 104.59 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.15.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.0
    path: /usr/local/bin/npm
  Watchman:
    version: 2023.10.02.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.13.0
    path: /Users/fikkatra/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/fikkatra/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.5
    wanted: 0.72.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Description

After following the guide to upgrade from 71 to 72, we get an error when running Android. 

The command:
`react-native run-android --mode=myAppDevDebug --appId com.myapp.dev`

fails with the following output (and nothing else):

> info JS server already running.
> 
> info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor
> 
> error Failed to install the app.

Except from following the steps mentioned in the upgrade guide, and updating library versions, nothing has changed.

We have the following product flavors defined:
```
    flavorDimensions "default"
    productFlavors {
        myappdev {
            applicationId "com.myapp.dev"
            manifestPlaceholders = [appAuthRedirectScheme: 'com.myapp.auth.dev']
        }
        myapptst {
            applicationId "com.myapp.tst"
            manifestPlaceholders = [appAuthRedirectScheme: 'com.myapp.auth.tst']
        }
        myappprd {
            applicationId "com.myapp.prd"
        }
    }
```

## Additional info
* run-ios works perfectly
* Gradle build succeeds (using `./gradlew app:installMyAppDevDebug`)
* Running via Android Studio succeeds
* Running react-native doctor succeeds, apart from finding the SDK. However, I'm sure the SDK is installed (otherwise running from Android Studio wouldn't work). The doctor also displayed the SDK error before upgrading, and it worked just fine.
* **Removing the --mode flag also makes the build succeed**. However, we depend on product flavors to manage different environments

Is there any way we can get more error info? I tried adding the --verbose flag, but the output is the same.

**Comment by szymonrybczak** [comment]
Hey @fikkatra, thanks for creating issue! It is really well described! Some time ago we were working on improving error messages and I think we added some regressions and the proper error is not shown. Adding this code to `build.gradle` causes this error: 

```
error Couldn't find "MyAppDevDebug" build variant. Available variants are: "MyappdevDebug", "MyappdevRelease", "MyappprdDebug", "MyappprdRelease", "MyapptstDebug", "MyapptstRelease".
```

So you should change variant (to `MyappdevDebug`) which you pass to the command (I'm not sure why this is happening, but that's how Gradle returns it). I hope that helps 🙌

**Comment by fikkatra** [comment]
@szymonrybczak thank you so much for looking into it. Indeed you are right: changing the casing of the variant fixed it.

Since we've been using these variants successfully for ages, this means something regarding the casing  of variants must have changed with the update (gradle 8)?
