### ISSUE TITLE
I tried `npx @react-native-community/cli init` but still got same error.

### ISSUE THREAD

**Issue by imorakzai** [react-native-community/cli#2109]
I tried `npx @react-native-community/cli init` but still got same error.
<img width="938" alt="Screenshot 2022-09-29 at 12 52 40 AM" src="https://user-images.githubusercontent.com/30732342/192870496-0cbd5e08-b78b-45fc-b6c1-958efdad7ef6.png">

_Originally posted by @rjatin007 in https://github.com/react-native-community/cli/issues/1681#issuecomment-1261367594_

**Comment by szymonrybczak** [comment]
Hey @imorakzai, you should use `npx react-native@latest init myApp` to create a project.

**Comment by szymonrybczak** [comment]
@imorakzai, any updates? :)

**Comment by imorakzai** [comment]
> @imorakzai, any updates? :)

i set the environment the solved the problem
