### ISSUE TITLE
react native 0.67 in android 14 app crashes when open the app

### ISSUE THREAD

**Issue by Akilan-katomaran** [react-native-community/cli#2117]

**Comment by szymonrybczak** [comment]
Hey, could you please provide more informations? Btw. React Native 0.67 is not supported, you should upgrade React Native version in the project.

**Comment by Akilan-katomaran** [comment]
> Hey, could you please provide more informations? Btw. React Native 0.67 is not supported, you should upgrade React Native version in the project.

I'm using 0.67 for my mobile app, which is currently in production and working properly on Android 13; however, when I install the app on Android 14 and open it, the app crashes. 

node v - 16.14.2
react v -  17.0.2
react native - 0.67.0-rc.0
this error showing after crashed
if i upgrade react native version to 0.70.0 lot errors on when build ,please help me to resolve this issue

![Screenshot from 2023-10-14 14-32-17](https://github.com/react-native-community/cli/assets/103435824/8deaf9c3-9ec5-4ae3-804b-a294c2785e1f)

**Comment by szymonrybczak** [comment]
Hey @Akilan-katomaran, you're using first 0.67.0-rc.0 - which is the first release candidate and contains a lot of bugs, at your place I would first upgrade to the [latest 0.67 release ](https://react-native-community.github.io/upgrade-helper/?from=0.67.0&to=0.67.5), and step by step upgrading to supported version. Please check also what is the the highest SDK version that you're supporting - and what is minimal to run app on Android 14 (that's probably the issue) - also take a look at [this information](https://x.com/thymikee/status/1678396094353494016?s=20), that you won't be able to submit update of your app to the Google Play Store if you don't upgrade your SDK version.

**Comment by ThalesBMC** [comment]
@Akilan-katomaran Did you find a solution?
