### ISSUE TITLE
impossible to init a new project in Linux version 0.72.x and 0.73. RC

### ISSUE THREAD

**Issue by Productivix** [react-native-community/cli#2119]
## Environment
System: OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm) CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz Memory: 55.70 GB / 62.62 GB Shell: version: 5.2.15 path: /bin/bash Binaries: Node: version: 18.18.0 path: /usr/local/bin/node Yarn: version: 1.22.19 path: /usr/local/bin/yarn npm: version: 10.1.0 path: /usr/local/bin/npm Watchman: Not Found SDKs: Android SDK: Not Found IDEs: Android Studio: Not Found Languages: Java: version: 11.0.20 path: /usr/bin/javac Ruby: Not Found npmPackages: "@react-native-community/cli": Not Found react: Not Found react-native: Not Found npmGlobalPackages: "*react-native*": Not Found Android: hermesEnabled: Not found newArchEnabled: Not found iOS: hermesEnabled: Not found newArchEnabled: Not found 

## Description

For RN 0.72.6 or 0.73 RC == same

 In Linux , I do simply :

npx react-native@next init RN0730RC2 --version 0.73.0-rc.2
I get

`
✔ Downloading template
⠋ Copying template/home/william/.npm/_npx/a3b05839d1f21af4/node_modules/graceful-fs/polyfills.js:265
if (!chownErOk(er)) throw er
^

Error: ENOENT: no such file or directory, chmod '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/RN0730RC2/babel.config.js'
at Object.chmodSync (node:fs:1991:3)
at Object.chmodSync (/home/william/.npm/_npx/a3b05839d1f21af4/node_modules/graceful-fs/polyfills.js:263:21)
at ReadStream. (/home/william/.npm/_npx/a3b05839d1f21af4/node_modules/@react-native-community/cli/build/tools/copyFiles.js:83:19)
at ReadStream.emit (node:events:517:28)
at emitCloseNT (node:internal/streams/destroy:132:10)
at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
errno: -2,
syscall: 'chmod',
code: 'ENOENT',
path: '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/RN0730RC2/babel.config.js'
}

Node.js v18.18.0
`
we cannot init the projet at all !

## Reproducible Demo
simply : in a user account on Debian !

npx react-native@next init RN0730RC2 --version 0.73.0-rc.2
or

npx react-native@next init RN0726 --version 0.72.6

**Comment by szymonrybczak** [comment]
Hey, thanks for creating issue! We're aware issue and it has been already [fixed](https://github.com/react-native-community/cli/pull/2096). We'll release it soon.

**Comment by Productivix** [comment]
hi, thanks @szymonrybczak , but in which RN version will it be integrated please , because the version 11.3.9 does not tell me anything

**Comment by szymonrybczak** [comment]
@Productivix it will be shipped next week with React Native 0.72.7, and React Native 0.73 RC3

**Comment by caishenye886** [comment]
> @Productivix it will be shipped next week with React Native 0.72.7, and React Native 0.73 RC3.
> 
> 11.3.9 is the CLI version

Today I got same problem, when could this problem sovled ? Thx

**Comment by Productivix** [comment]
@szymonrybczak : why this issue is closed before solved ??

**Comment by szymonrybczak** [comment]
> : why this issue is closed before solved ??

I closed this issue because we've fixed this inside CLI, right now we're waiting for Core Team to release patch fix. I'll let you know when you have test it out.

**Comment by Productivix** [comment]
hi, 
npx react-native@latest init AwesomeProject runs well now on 0.72.7 - good thanks  !
