### ISSUE TITLE
Run `pod install` after upgrade

### ISSUE THREAD

**Issue by thymikee** [react-native-community/cli#212]
## Describe the Feature

`upgrade` command could use [installPods](https://github.com/react-native-community/cli/blob/master/packages/cli/src/tools/installPods.js) helper, and run: 
```sh
pod repo update
pod install
``` 
after installing JS deps. 

Here's how `init` uses it:
https://github.com/react-native-community/cli/blob/a3d468e54dd3de51c2a0c788c1c8962d1c6abfc1/packages/cli/src/commands/init/init.js#L164-L166

It's likely that `installPods` will need another option introduced to decide whether update the pods or not. It's not necessary during `init` because all pods are local, but it's usually necessary when having 3rd party libraries. We can also be smart about it and check for presence of 3rd party RN libs by accessing `config.dependencies`.

cc @orta @fson what do you think?

**Comment by orta** [comment]
I think that's reasonable, yep 👍

**Comment by maciejsimka** [comment]
I'd like to work on this issue, if nobody works on it yet

**Comment by thymikee** [comment]
Sure, take it 👍 However, I'd only run it after the upgrade was successful. Otherwise just log to the console something like 'hey, don't forget to run "pod install" once your done upgrading manually'.
