### ISSUE TITLE
Have CLI doctor check permissions on gradlew script

### ISSUE THREAD

**Issue by paulordbm** [react-native-community/cli#2127]
## Describe the Feature
I've recently cloned a project on a new computer and `yarn android` was failing without much explanation, only suggesting I run the cli doctor to check my environment. I did have an issue with it not detecting I had Android SDK 33.0 installed, but it was due to me actually not having the Android SDK Command Line Tools version 10.0 installed.

I go on to fix it and now I'm in this interesting state where the cli doctor tells me everything is fine but the android build was still failing with the exact same output. I found out the issue was that I had to `chmod +x gradlew` in this new machine. So maybe having the cli doctor check for these permissions could be useful.

## Possible Implementations
No idea guys, sorry. You are better prepared than me.

**Comment by szymonrybczak** [comment]
Hey @Raj29Kumar your comment is not related to this issue. Please create separate issue with your problem.

**Comment by szymonrybczak** [comment]
I think we can add this check, @cortinico WDYT?

**Comment by jeferson-sb** [comment]
@szymonrybczak I will take a look on this one. Just to make sure, Is this something we can add to the `healthchecks` or is it some other file?

**Comment by szymonrybczak** [comment]
> @szymonrybczak I will take a look on this one. Just to make sure, Is this something we can add to the `healthchecks` or is it some other file?

Yeah, sure
