### ISSUE TITLE
--config option can support relative path

### ISSUE THREAD

**Issue by Starryi** [react-native-community/cli#213]
## Describe the Feature
with current implementation, if the --config options was set  a path relative to rootProject,  command will crash, and report an error that the path doesn't exist.

**Comment by thymikee** [comment]
Happy to accept a PR supporting relative paths :)

**Comment by thymikee** [comment]
Just to be sure, it's about custom-placed `metro.config.js` passed through `--config` flag passed to `start` or `bundle` commands?
