### ISSUE TITLE
Allow custom path for podspecs

### ISSUE THREAD

**Issue by teodorciuraru** [react-native-community/cli#2137]
## Describe the Feature
My RN module is residing inside a JS module. This forces me to relocate its podspec at the JS root, which breaks having all my RN files collocated inside my `/react-native` folder. The solution would be to allow me to keep auto-linking while specifying a different podspec path.

## Possible Implementations
I don't know why it was deprecated, but a solution similar to `podspecPath` inside my module's `react-native.config.js` will do the trick. Currently, it doesn't work and I get a warning: `warn Package @myPackage/package contains invalid configuration: "dependency.platforms.ios.podspecPath" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.`

**Comment by szymonrybczak** [comment]
Hey @teodorciuraru! If I understand correctly, you can set the the `package` root inside `react-native.config.js` and then autolinking system will find the `.podspec` file. For example:

```
const path = require('path');

module.exports = {
  dependencies: {
    'react-native-library-name': {
      root: path.join(__dirname, '..'),
    },
  },
};
```

**Comment by teodorciuraru** [comment]
@szymonrybczak Hmm, I'm unsure how it will detect my custom location`.podspec`. My podspec is in `./MyLibrary.podspec`, and my RN project is inside `./react-native/`.

**Comment by szymonrybczak** [comment]
So, inside `react-native.config.js` under `./react-native` directory add this code:

```js
const path = require('path');

module.exports = {
  dependencies: {
    'react-native-library-name': {
      root: path.join(__dirname, '..'),
    },
  },
};
```

**Comment by teodorciuraru** [comment]
@szymonrybczak It worked, but I think my problem is the other way around. I want to have my podspec **inside** the `/react-native` folder, not in root and when RN CLI installs the JS package (root), to still autolinking by finding the `.podspec` inside the `/react-native` folder. It might be that I didn't understand how to apply your solution to have this working.
```
├── package.json
├── src/
└── react-native/
    ├── MyLib.podspec
    ├── react-native.config.js
    └── src/
```

**Comment by szymonrybczak** [comment]
As you wrote above, that "my RN project is inside `./react-native`", so to link your library properly you should provide in app's `react-native.config.js` path to the root of the library (so in your case `path.join(__dirname, '..')`). But you **shouldn't** add `.podspec` file to the example app because whenever somebody will try to install your package it will fail at installing Cocoapods since the `.podspec` file will not be accessible (since it will be in example app). 

If you provide `dependencies` as me above, Android should also work properly.

**Comment by teodorciuraru** [comment]
@szymonrybczak I think I didn't explain it well cause I don't understand the `example app` reference. This is the entire picture: the root is a JS module with sources for multiple platforms (rn, node, etc.), while `./react-native` is an RN native module / plugin.

I would like this structure to work if users are installing this JS module:

```
├── package.json -> Here I specify `react-native entry point is inside `/react-native/src/index.ts`
├── react-native.config.js -> Here I want to trigger autolink to find my `.podspec` and android gradle project somehow.
├── src/
**├── node/**
└── react-native/
    ├── android/
    ├── ios/
    ├── MyLib.podspec
    └── src/
