### ISSUE TITLE
react-native init with --title doesn't change the `displayName` field in app.json file

### ISSUE THREAD

**Issue by rick-ast** [react-native-community/cli#2146]
## Environment

System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 83.66 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: /opt/homebrew/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.1
    path: /opt/homebrew/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.14.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.0.1/15A507
    path: /usr/bin/xcodebuild
Languages:
  Java: Not Found
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Description

run `npx react-native init movie_ticket_app --title Movie`
the names in `strings.xml` and `Info.plist` are 'Movie' as expected, while the field `displayName` in `app.json` file is still 'movie_ticket_app'.

Is this by design or a bug, since if I use `react-native eject` the app display name uses the displayName in app.json.

**Comment by motdde** [comment]
Using the title, package name, and project name needs to be more consistent. You'd get different behaviours depending on the flags you pass in.

For example this command
npx react-native@latest init --title "Project Name" --package-name "com.new_project" New Project

package.json.name is com.new_project
project Directory is a New
app.json name and display name is New
CFBundleDisplayName in info. plist is New
app_name in strings.xml is New

The Java package, application, and bundle identifier skip the userscore | hyphen, which should relate to new-project.com domain.
