### ISSUE TITLE
How to Add compiled libraries (.h and .a) to custom react native module and link them in iOS project

### ISSUE THREAD

**Issue by Vetagiri-Hrushikesh** [react-native-community/cli#2163]
## Ask your Question

I compiled a third-party source and **obtained both the .h and .a files**. Subsequently, I created a folder within my react-native-custom-module project, naming it **deps/library/iOS/include** and **deps/library/iOS/libs**. I'm utilizing these .h files within the cpp folder of my react-native-custom-module. Now, when I execute **yarn add ../react-native-custom-module**, how can I properly incorporate these .a and .h files into my iOS project to ensure that my C++ files do not report errors regarding missing header files?

**Comment by atlj** [comment]
Hey @Vetagiri-Hrushikesh, seems like you are creating a library from scratch. While it is perfectly fine, you can take a look into [react-native-builder-bob](https://github.com/callstack/react-native-builder-bob). It automatically handles the project setup and has a C++ template.
