### ISSUE TITLE
error >> app:checkDebugAarMetadata   ?  need little  help plz

### ISSUE THREAD

**Issue by telo2** [react-native-community/cli#2168]
npx react-native run-android

info Starting JS server...
info Installing the app...
> Task :app:checkDebugAarMetadata FAILED
9 actionable tasks: 4 executed, 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform lifecycle-process-2.4.0.aar (androidx.lifecycle:lifecycle-process:2.4.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find lifecycle-process-2.4.0.aar (androidx.lifecycle:lifecycle-process:2.4.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/lifecycle/lifecycle-process/2.4.0/lifecycle-process-2.4.0.aar
   > Failed to transform startup-runtime-1.0.0.aar (androidx.startup:startup-runtime:1.0.0) to match attributes {artifactType=android-aar-metadata, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find startup-runtime-1.0.0.aar (androidx.startup:startup-runtime:1.0.0).
        Searched in the following locations:
            https://dl.google.com/dl/android/maven2/androidx/startup/startup-runtime/1.0.0/startup-runtime-1.0.0.aar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
error Failed to install the app.

------------------------------------------------------------------------

react-native doctor

⠋ Running diagnostics...(node:34123) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ npm - Required to install NPM dependencies

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation

Errors:   0
Warnings: 0
------------------------------------------------------------------------
react native version 0.72.6
------------------------------------------------------------------------
java version open jdk 11
------------------------------------------------------------------------
os Ubuntu 22.04.2 LTS
------------------------------------------------------------------------
sdk target 33 
 ------------------------------------------------------------------------
android test device android pie 9 
------------------------------------------------------------------------

all files can be downloaded manually  >> mean non blocked 

what i should do

**Comment by telo2** [comment]
also tried with java 17 same

**Comment by szymonrybczak** [comment]
hey @telo2 did you manage to solve your issue?
