### ISSUE TITLE
react-native start and run android with default flavor

### ISSUE THREAD

**Issue by huiqun922** [react-native-community/cli#2181]
## react-native start with default flavor

I have three flavor : dev stg prod

react-native run-android --mode=StgDebug ,it's run perfect.

but react-native start and enter a to run android, can't specify flavor.

what should I do

<img width="534" alt="image" src="https://github.com/react-native-community/cli/assets/4495165/528e6048-9a40-43d4-8f59-7929a1ea5bbe">

**Comment by TMisiukiewicz** [comment]
Hi @huiqun922 , starting from React Native 0.73, you'll be able to use [watchModeCommandParams](https://github.com/react-native-community/cli/blob/main/docs/projects.md#projectandroidwatchmodecommandparams) to pass the params you need. It's just around the corner 😉

**Comment by huiqun922** [comment]
@TMisiukiewicz Thanks a lot.

<img width="684" alt="image" src="https://github.com/react-native-community/cli/assets/4495165/e4343e26-e330-4180-84e2-6efdc391ad2a">
