### ISSUE TITLE
Unsupported class file major version 65

### ISSUE THREAD

**Issue by 2ant** [react-native-community/cli#2184]
Hi, react newbie here.
I tried to install react native with cli on my new windows 11 machine:
-fresh android studio 2022.3.1 patch 4

```
Gradle 8.4

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21.0.1 (Oracle Corporation 21.0.1+12-LTS-29)
```
I get this error when doing "npx react-native run-android":

```
info Starting JS server...
* daemon not running; starting now at tcp:5037
* daemon started successfully
info Installing the app...
Starting a Gradle Daemon, 2 incompatible and 2 stopped Daemons could not be reused, use --status for details

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor


FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file 'C:\Users\antoi\Desktop\Code\React_Native\AwesomeProject\android\settings.gradle' (C:\Users\antoi\.gradle\caches\8.0.1\scripts\1mrpar4986zd3t4i3s9z4ro8x).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 65

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
error Failed to install the app.
info Run CLI with --verbose flag for more details.
```
I tried changing the version in gradle-wrapper.properties since it was there that there was 8.0.1:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip
```
I also tried changing the JAVA_HOME version.

I found this post : https://github.com/react-native-community/cli/issues/1719  that seems to indicate a mismatch between gradle/java/react native but i haven't been able to find a combination that works.
I either get what i put earlier or an error with kotlin.

I found that page : https://docs.gradle.org/current/userguide/compatibility.html

From it's release page Gradle 8.4 shoud be compatible with jdk 21 : https://docs.gradle.org/8.4/release-notes.html

What is the most recent version of each compatible with react native ?

Any help is appreciated.

**Comment by szymonrybczak** [comment]
Hey @2ant, could you please run `npx react-native doctor`?

**Comment by szymonrybczak** [comment]
Hey @2ant did you manage to fix your issue? :)

**Comment by marcinbogiel** [comment]
> For those that stumble upon this (and because there was no real answer to the question here): it's an incompatible Java SDK version. You need to use a correct / compatible one, e.g. use the one bundled within Android Studio.

Hey @lumpidu 

Could you say more about using the one bundled within Android Studio? I checked the sdk path both for Godot and Android studio and are the same:

<img width="559" alt="Zrzut ekranu 2024-02-13 o 00 38 12" src="https://github.com/react-native-community/cli/assets/13196133/ecdaeee7-dcfe-4f2e-a744-4cf231ea9ced">
<img width="848" alt="Zrzut ekranu 2024-02-13 o 00 38 36" src="https://github.com/react-native-community/cli/assets/13196133/0bb3add7-9674-4816-b5bf-a1354e14b6d0">
