### ISSUE TITLE
react native init project get error of Could not create an empty Git repository, see debug logs with --verbose

### ISSUE THREAD

**Issue by techUdayMungalpara** [react-native-community/cli#2212]
## Environment

System:
  OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
  CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
  Memory: 4.45 GB / 7.71 GB
  Shell:
    version: 5.1.16
    path: /bin/bash
Binaries:
  Node:
    version: 20.10.0
    path: /snap/node/8007/bin/node
  Yarn:
    version: 1.22.19
    path: /snap/node/8007/bin/yarn
  npm:
    version: 10.2.3
    path: /snap/node/8007/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11076708
Languages:
  Java:
    version: 11.0.21
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false
git --version
git version 2.34.1

## Description

react native init projext get error of

**Comment by szymonrybczak** [comment]
Hey @techUdayMungalpara 👋, so CLI for some reason failed at creating project, but the project should be initialised and ready to use!

**Comment by szymonrybczak** [comment]
hey @Vadim51515, that's strange! you're also able to turn off git initialisation during `init` command by passing `--skip-git-init`
