### ISSUE TITLE
☂️ `cli-platform-apple` - further improvements 

### ISSUE THREAD

**Issue by okwasniewski** [react-native-community/cli#2217]
## Descripiton

`cli-platform-apple` is a new package introduced for OOT platforms. This issue lists further improvements that can be done to improve the codebase.

- [x] Remove `getFallbackSimulator()` and use first available simulator
- [x] Extract duplicated logic between `createRun` and `createLog` commands: https://github.com/react-native-community/cli/pull/2208#discussion_r1431019199
- [x] Implement app launching for React Native macOS: [PR](https://github.com/react-native-community/cli/pull/2232)
- [x] Move prompt from `createLog` to `prompts.ts`: [PR](https://github.com/react-native-community/cli/pull/2224)
- [x] Create a getter for `buildOptions` / `runOptions` to include proper platformName - [PR](https://github.com/react-native-community/cli/pull/2226)
- [x] Modify warning `Multiple Podfiles were found` to take OOT platforms into account [PR](https://github.com/react-native-community/cli/pulls)
- [x] Make dependencyConfig into a builder - [PR](https://github.com/react-native-community/cli/pull/2226)
- [x] Remove code duplication between `createRun` and `createBuild`. Logic to re-check Xcode project can be moved to `getXcodeProjectAndDir` behind a flag #2220 
- [x] merge `buildOptions` into `runOptions` to avoid confusion when importing/extending

**Comment by matthargett** [comment]
I think the last item in the list can be check off now, right? Are there any additional/new items we want to add here based on @Saadnajmi observations so far on the macOS side?

**Comment by okwasniewski** [comment]
Thanks @matthargett, I checked off the last item from the list 👍🏻 Can we close this @szymonrybczak or is there something more you want to add under this umbrella issue?
