### ISSUE TITLE
Allow plugins to override built in commands

### ISSUE THREAD

**Issue by tom-sherman** [react-native-community/cli#2227]
## Describe the Feature

Commands and healthchecks defined in the config should override built-in commands so that I can, for example, provide my own `react-native start` command implementations.

This would allow repack to override the start command instead of requiring an alternative `webpack-start` cmd.

## Possible Implementations

I believe it requires flipping the order here:

https://github.com/react-native-community/cli/blob/ae056a11334636d9031154ecb6b63c3072120af6/packages/cli-config/src/loadConfig.ts#L146

However I tried this and it didn't allow me to override `start`.

## Related Issues

This would offer a first party solution to https://github.com/nrwl/nx/issues/20847

**Comment by szymonrybczak** [comment]
Hey @tom-sherman, I think we can add support for this! Also for Re.Pack it will solve one other problem - when we're running `run-ios` we're also starting new window where we run `start` command, and in most cases it opens Metro instance which can be confusing for non-advanced users 😅 cc @jbroma
