### ISSUE TITLE
Can not get my name of project when init my template

### ISSUE THREAD

**Issue by mduc-dev** [react-native-community/cli#2240]
## Environment
System:
  OS: macOS 11.7.10
  CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
  Memory: 40.70 MB / 16.00 GB
  Shell:
    version: "5.8"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.4.0
    path: ~/.nvm/versions/node/v21.4.0/bin/node
  Yarn:
    version: 1.22.15
    path: /usr/local/bin/yarn
  npm:
    version: 8.6.0
    path: ~/node_modules/.bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/manhnguyen/.rvm/gems/ruby-3.0.0/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 21.2
      - iOS 15.2
      - macOS 12.1
      - tvOS 15.2
      - watchOS 8.3
  Android SDK:
    API Levels:
      - "27"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-31 | Google Play Intel x86 Atom_64
      - android-33 | Google Play Intel x86 Atom_64
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10811636
  Xcode:
    version: 13.2.1/13C100
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16.1
    path: /usr/local/opt/openjdk@11/bin/javac
  Ruby:
    version: 3.0.0
    path: /Users/manhnguyen/.rvm/rubies/ruby-3.0.0/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.0
    wanted: 0.73.0
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

## Description

I created a template to make initing a new project faster, and here is my repo [RN-Boilerplate](https://github.com/mduc-dev/react-native-boilerplate) but now I'm having problems using **--template**, it can't get the **project name as well as the bundle id** I created at init

## Reproducible Demo
**npx react-native@latest init MyApp --template https://github.com/mduc-dev/react-native-boilerplate.git**. I using this command for this init

<img width="1003" alt="Screen_Shot_2024-01-02_at_20 48 34" src="https://github.com/react-native-community/cli/assets/80993895/11ffce04-e726-40c5-a729-1937c329d006">

**Comment by szymonrybczak** [comment]
Hey @mduc-dev, does pure `npx react-native@latest init` work for you? also can you change the format to template location to this `mduc-dev/react-native-boilerplate`? as we support only [these formats](https://github.com/react-native-community/cli/blob/main/docs/commands.md#--template-string).

**Comment by mduc-dev** [comment]
> Hey @mduc-dev, does pure `npx react-native@latest init` work for you? also can you change the format to template location to this `mduc-dev/react-native-boilerplate`? as we support only [these formats](https://github.com/react-native-community/cli/blob/main/docs/commands.md#--template-string).

Hi @szymonrybczak, I just tried this format, but the project name still retains the name of the template I originally created.
<img width="1436" alt="Screen Shot 2024-01-02 at 23 21 06" src="https://github.com/react-native-community/cli/assets/80993895/54760df9-de84-41f5-8124-eac8cbdde97a">

**Comment by szymonrybczak** [comment]
@mduc-dev while `init` CLI replaces all place where there's a `HelloWorld`, in your case there's https://github.com/mduc-dev/react-native-boilerplate/blob/07d00c4c3bd3b832fe3e569f8c1cf69d21faf69d/template/package.json#L2

**Comment by mduc-dev** [comment]
I don't really understand, so I need to change it to HelloWorld?  I tried a few other repo templates and tried init with a different name and it worked.
Eg: **npx react-native@latest init MyApp --template @thecodingmachine/react-native-boilerplate**

**Comment by szymonrybczak** [comment]
@mduc-dev ugh, sorry for confusing you 😅 you can also pass the custom value in `template.config.js` , same as [here](https://github.com/thecodingmachine/react-native-boilerplate/blob/82d25df0cdbceb953816c97f2cdacb4f3e5d14fa/template.config.js#L2).

**Comment by mduc-dev** [comment]
@szymonrybczak Huh, So every time I init with this template, I have to go here to edit this value?

**Comment by szymonrybczak** [comment]
@mduc-dev, no `template.config.js` is the file in template's repo so all you need to do is to just change this [value](https://github.com/mduc-dev/react-native-boilerplate/blob/07d00c4c3bd3b832fe3e569f8c1cf69d21faf69d/template.config.js#L2), to "BaseRN" :)

**Comment by mduc-dev** [comment]
> @mduc-dev, no `template.config.js` is the file in template's repo so all you need to do is to just change this [value](https://github.com/mduc-dev/react-native-boilerplate/blob/07d00c4c3bd3b832fe3e569f8c1cf69d21faf69d/template.config.js#L2), to "BaseRN" :)

Oh, I see, it needs to be the same. Thank you for your help 🔥
