### ISSUE TITLE
Unable to produce apps 0.73.1

### ISSUE THREAD

**Issue by cyhnkckali** [react-native-community/cli#2243]
- Node version 20.10.0
- JDK version jdk-17.0.8.7-hotspot
- Gradle version 8.3
- All environment variables set
- react-native-doctor cannot find errors or warnings
-  Android SDK 33 installed

  **### Despite this, the practice cannot stand up!!!**

<img width="878" alt="Code Error" src="https://github.com/react-native-community/cli/assets/93313260/89ce6a65-a92a-4f4b-879a-008b2c087ffa">
<img width="554" alt="reactnative doctor" src="https://github.com/react-native-community/cli/assets/93313260/edf02483-52d8-4312-aded-febb11100495">

**Comment by szymonrybczak** [comment]
hey @cyhnkckali, please make sure you have installed packages, and `npx react-native config` is passing.

**Comment by cyhnkckali** [comment]
Hi @szymonrybczak ,
Thank you. 
Running the following commands in sequence fixed it.
npm cache verify
yarn install
npx react-native config
