### ISSUE TITLE
Can't run on Android 5.1.1

### ISSUE THREAD

**Issue by sun-jkp** [react-native-community/cli#2244]
## After install and run app on emulator. It's crash.
The emulator that I used is 
-7" WSVGA(Tablet)
-Lollipop (Android 5.1)
-API Level 22

I got error message "Unfortunately, AwesomeProject has stopped." on emulator's screen.
Can Anyone help me this problem.

#Environment
![Screenshot 2024-01-04 114817](https://github.com/react-native-community/cli/assets/122416761/f720fdba-2840-485a-8ecd-c8bb7527d0a4)

#React-Native Doctor
![Screenshot 2024-01-04 114631](https://github.com/react-native-community/cli/assets/122416761/ddd02220-765e-41aa-8afc-8953326ed1c1)

![Screenshot 2024-01-04 114430](https://github.com/react-native-community/cli/assets/122416761/6e9ea4e0-6590-4da3-b44a-975413fbe132)

**Comment by szymonrybczak** [comment]
Hey, what's the minSDK in your build.gradle? You need to make sure that the version provided there is higher or equal to the one that device is on. Btw Android 5 is very old OS and you probable don't have to support it :)

**Comment by thymikee** [comment]
Worth to note that RN 0.73 is the last one to support Android 5. Starting from 0.74 the min supported version will be 6. Read more here: https://reactnative.dev/blog/2023/12/06/0.73-debugging-improvements-stable-symlinks#min-sdk-bump

**Comment by sun-jkp** [comment]
The fix will be in 0.73.2 which will be released in the near future.
https://github.com/facebook/react-native/issues/42135

@szymonrybczak => minSDK: 21

**Comment by szymonrybczak** [comment]
Ok, so as Nicola said it will be fixed in 0.73.2 and I think we can close this issue
