### ISSUE TITLE
The current character read is 'i' with an int value of 105

### ISSUE THREAD

**Issue by AhmadAlz7** [react-native-community/cli#2248]
## Environment

> System:
>     OS: Windows 10 10.0.19045
>     CPU: (12) x64 AMD Ryzen 5 PRO 4650G with Radeon Graphics
>     Memory: 3.51 GB / 15.30 GB
>   Binaries:
>     Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
>     npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
>     Watchman: 20220918.223204.0 - C:\ProgramData\chocolatey\bin\watchman.EXE
>   SDKs:
>     Android SDK:
>       API Levels: 31, 33
>       Build Tools: 30.0.3, 31.0.0, 33.0.0, 33.0.1, 34.0.0
>       System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-33 | Google APIs Intel x86_64 Atom, android-33 | Google Play Intel x86_64 Atom
>       Android NDK: Not Found
>     Windows SDK: Not Found
>   IDEs:
>     Android Studio: Not Found
>     Visual Studio: 17.4.33110.190 (Visual Studio Professional 2022), 17.4.33110.190 (Visual Studio Community 2022)
>   Languages:
>     Java: 11.0.20 - C:\Program Files\Microsoft\jdk-11.0.20.8-hotspot\bin\javac.EXE
>   npmPackages:
>     @react-native-community/cli: ^9.3.5 => 9.3.5
>     react: 18.1.0 => 18.1.0
>     react-native: 0.70.6 => 0.70.6
>     react-native-windows: Not Found
>   npmGlobalPackages:
>     *react-native*: Not Found

## Description

> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'E:\Projects\Freelancing\Rahal\repos\driver-app\RahalTaxiDriver\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 450
> 
> * What went wrong:
> A problem occurred evaluating script.
> > Calling `[node, E:\Projects\Freelancing\Rahal\repos\driver-app\RahalTaxiDriver\node_modules\@react-native-community\cli\build\bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
> 
>   The current character read is 'i' with an int value of 105
>   Unable to determine the current character, it is not a string, number, array, or object
>   line number 1
>   index number 0
>   info Run CLI with --verbose flag for more details.
>   ^. Output: info Run CLI with --verbose flag for more details.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 6s

## Reproducible Demo

> 1- remove folder "Node_modules"
> 2- remove file "yarn.lock"
> 3- run command "yarn"
> 4- run command "yarn react-native run-android"
> 

## Dependencies

> 
>   "dependencies": {
>     "@gorhom/bottom-sheet": "^4",
>     "@notifee/react-native": "^7.8.0",
>     "@react-native-async-storage/async-storage": "^1.17.7",
>     "@react-native-community/cli": "^9.3.5",
>     "@react-native-community/datetimepicker": "^6.7.1",
>     "@react-native-community/netinfo": "^9.3.7",
>     "@react-native-community/push-notification-ios": "^1.11.0",
>     "@react-native-firebase/app": "^17.4.3",
>     "@react-native-firebase/database": "^17.4.3",
>     "@react-native-firebase/messaging": "^18.5.0",
>     "@react-native-masked-view/masked-view": "^0.2.7",
>     "@react-navigation/bottom-tabs": "^6.3.2",
>     "@react-navigation/material-top-tabs": "^6.6.1",
>     "@react-navigation/native": "^6.0.11",
>     "@react-navigation/stack": "^6.2.2",
>     "@reduxjs/toolkit": "^1.8.3",
>     "@types/react-native-push-notification": "^8.1.2",
>     "formik": "^2.2.9",
>     "i18next": "^21.8.14",
>     "lottie-ios": "3.4.0",
>     "lottie-react-native": "^5.1.6",
>     "moment": "^2.29.4",
>     "prop-types": "^15.8.1",
>     "react": "18.1.0",
>     "react-i18next": "^11.18.3",
>     "react-native": "0.70.6",
>     "react-native-background-actions": "^3.0.0",
>     "react-native-background-timer": "^2.4.1",
>     "react-native-blob-util": "^0.17.0",
>     "react-native-compass-heading": "^1.5.0",
>     "react-native-confirmation-code-field": "^7.3.1",
>     "react-native-device-info": "^10.5.1",
>     "react-native-document-picker": "^8.1.3",
>     "react-native-fast-image": "^8.6.3",
>     "react-native-flash-message": "^0.3.1",
>     "react-native-flipper": "0.164.0",
>     "react-native-geocoding": "^0.5.0",
>     "react-native-geolocation-service": "^5.3.1",
>     "react-native-gesture-handler": "^2.9.0",
>     "react-native-google-maps-directions": "^2.1.1",
>     "react-native-image-crop-picker": "^0.40.2",
>     "react-native-linear-gradient": "^2.6.2",
>     "react-native-maps": "1.7.1",
>     "react-native-maps-directions": "^1.9.0",
>     "react-native-modal-datetime-picker": "^14.0.1",
>     "react-native-pager-view": "^6.1.4",
>     "react-native-paper": "^5.1.3",
>     "react-native-pdf": "^6.6.2",
>     "react-native-permissions": "^3.6.1",
>     "react-native-phone-number-input": "^2.1.0",
>     "react-native-progress": "^5.0.0",
>     "react-native-push-notification": "^8.1.1",
>     "react-native-ratings": "^8.1.0",
>     "react-native-reanimated": "3.1.0",
>     "react-native-restart": "^0.0.24",
>     "react-native-safe-area-context": "^4.3.1",
>     "react-native-screens": "^3.15.0",
>     "react-native-svg": "^13.6.0",
>     "react-native-tab-view": "^3.5.0",
>     "react-native-track-player": "^4.0.1",
>     "react-native-vector-icons": "^9.2.0",
>     "react-redux": "^8.0.2",
>     "redux": "^4.2.0",
>     "redux-flipper": "^2.0.2",
>     "redux-persist": "^6.0.0",
>     "use-debounce": "^9.0.3",
>     "yup": "^0.32.11"
>   },
>   "devDependencies": {
>     "@babel/core": "^7.12.9",
>     "@babel/preset-env": "^7.20.2",
>     "@babel/runtime": "^7.12.5",
>     "@react-native-community/eslint-config": "^3.0.1",
>     "@types/fbemitter": "^2.0.32",
>     "@types/jest": "^29.2.4",
>     "@types/react": "^18.2.43",
>     "@types/react-native": "^0.70.8",
>     "@types/react-native-background-timer": "^2.0.0",
>     "@types/react-native-vector-icons": "^6.4.12",
>     "@types/react-redux": "^7.1.24",
>     "@types/react-test-renderer": "^18.0.0",
>     "babel-jest": "^26.6.3",
>     "babel-plugin-module-resolver": "^4.0.0",
>     "eslint": "^7.32.0",
>     "eslint-import-resolver-babel-module": "^5.1.2",
>     "eslint-plugin-import": "^2.22.0",
>     "eslint-plugin-jest": "^24.3.5",
>     "identity-obj-proxy": "^3.0.0",
>     "jest": "^26.6.3",
>     "metro-react-native-babel-preset": "^0.70.3",
>     "prettier": "^2.7.1",
>     "react-native-asset": "^2.0.1",
>     "react-test-renderer": "18.0.0",
>     "typescript": "^4.9.4"
>   },

**Comment by szymonrybczak** [comment]
hey @AhmadAlz7, can you please run `npx react-native config` inside your project and try fixing error that it is producing? After fixing error there, `run-android` command will work correctly 👍

**Comment by AhmadAlz7** [comment]
> hey @AhmadAlz7, can you please run `npx react-native config` inside your project and try fixing error that it is producing? After fixing error there, `run-android` command will work correctly 👍

Thanks, it worked
