### ISSUE TITLE
requireNativeComponent: "RNSScreenStackHeaderConfig"

### ISSUE THREAD

**Issue by redrose4y293** [react-native-community/cli#2260]
When i use react native navigation its show me the error 
Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.
With out navigation my components work fine and do not show any error i already install all the require dependencies 
   "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "react": "18.2.0",
    "react-native": "0.73.1",
    "react-native-gesture-handler": "^2.14.1",
    "react-native-safe-area-context": "^4.8.2",
    "react-native-screens": "^3.29.0",
    "twrnc": "^3.6.7"

**Comment by szymonrybczak** [comment]
hey, probably you need to install Cocoapods and rebuild your app. But this repository is not the right place to raise this kind of issues.

**Comment by redrose4y293** [comment]
This error is not belong to the Cocoapods because I am using android emulator
