### ISSUE TITLE
How do we build different variation of android apps?

### ISSUE THREAD

**Issue by Dajust** [react-native-community/cli#2277]
Given the `--variant` option for the command `react-native run-android` no longer exists in the latest CLI, how do we build different variations of Android apps?

Usually, we would run something like `npx react-native run-android --variant=devDebug`. But in the latest CLI (react-native 0.73.2) the `--variant` option no longer exists.

**Comment by gfzy9876** [comment]
Is...solved?
I have the save issue
@Dajust
