### ISSUE TITLE
 Getting Error While initialization react native app in ubuntu 22.04.3 LTS.

### ISSUE THREAD

**Issue by ankitshivmalan** [react-native-community/cli#2284]
## Description

 "✖ Downloading template". while i perform the same on windows it's executed perfectly but the issue i am facing in ubuntu

-->

## Reproducible Demo

Steps to reproduce

1.Setup the environment as described in the react native documentation
2. command for initialization a new project
![Screenshot from 2024-01-31 23-21-28](https://github.com/react-native-community/cli/assets/58619844/bfbd230d-6a29-4edf-b775-e1076b147c31)

**Comment by szymonrybczak** [comment]
hey @ankitshivmalan, could you please try running this command with `--npm`? :)

**Comment by km-saifullah** [comment]
@ankitshivmalan what are the commands?

**Comment by ankitshivmalan** [comment]
@km-saifullah
npm install -g yarn
yarn global add react-native-cli
react-native init sample
yarn run android
yarn start
