### ISSUE TITLE
Could not create an empty Git repository, see debug logs with --verbose

### ISSUE THREAD

**Issue by mcnaveen** [react-native-community/cli#2297]
## Environment

- react-native@0.73.4
- Darwin macbook-air 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64

## Description
Trying to init a new react native project.

Upon running `npx react-native@latest init myapp` It throws the following error. Also the create folder is empty.

```
Downloading template error
✖ Downloading template
✖ Could not create an empty Git repository, see debug logs with --verbose
```

I have attached a screenshot of the error below.

![image](https://github.com/react-native-community/cli/assets/8493007/6fb37eae-e568-4b14-b31b-3fce39621a5c)

Similar issue #2212 | Proposed/Merged fix: #2215 But it's still occuring.

## Reproducible Demo

Create a new React Native project with the command `npx react-native@latest init myapp`

---
> Also, when you run `npx react-native info` it says unknown command.

**Comment by szymonrybczak** [comment]
hey @mcnaveen, can you run with `--verbose`?

**Comment by mcnaveen** [comment]
Hi @szymonrybczak Sure, here it is.

```
$ npx react-native init watermelon --verbose
debug We couldn't find a package.json in your project. Are you sure you are running it inside a React Native project?
debug Failed to load configuration of your project. Only a subset of commands will be available.
debug Initializing new project


                  Welcome to React Native!
                 Learn once, write anywhere

debug Installing template from react-native@latest
yarn init v1.22.19
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
✨  Done in 0.08s.
yarn config v1.22.19
success Set "nodeLinker" to "node-modules".
✨  Done in 0.09s.
yarn add v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "Invalid URL".
info If you think this is a bug, please open a bug report with the information provided in "/private/var/folders/j8/6l83d1h53s1_10sqlgdn2drc0000gn/T/rncli-init-template-XI48fR/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Installing pods failed. This doesn't affect project initialization and you can safely proceed.
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.



info 💡 To enable automatic CocoaPods installation when building for iOS you can create react-native.config.js with automaticPodsInstallation field.
For more details, see https://github.com/react-native-community/cli/blob/main/docs/projects.md#projectiosautomaticpodsinstallation

debug Error: Command failed with exit code 1: git commit -m Initial commit


On branch main

Initial commit

nothing to commit (create/copy files and use "git add" to track)


  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/mcnaveen/Documents/dev/watermelon" && npx react-native run-android

  Run instructions for iOS:
    • cd "/Users/mcnaveen/Documents/dev/watermelon/ios"

    • Install Cocoapods
      • bundle install # you need to run this only once in your project.
      • bundle exec pod install
      • cd ..

    • npx react-native run-ios
    - or -
    • Open watermelon/ios/watermelon.xcodeproj in Xcode or run "xed -b ios"
    • Hit the Run button

  Run instructions for macOS:
    • See https://aka.ms/ReactNativeGuideMacOS for the latest up-to-date instructions.

```

and I can't find this log `/private/var/folders/j8/6l83d1h53s1_10sqlgdn2drc0000gn/T/rncli-init-template-XI48fR/yarn-error.log`

**Comment by szymonrybczak** [comment]
Can you try with `--npm`?

**Comment by mcnaveen** [comment]
With `--npm` it seems to be working.

Also, here is the yarn config.

```bash
$yarn config list
yarn config v1.22.19
info yarn config
{
  'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.npmjs.org',
  'strict-ssl': true,
  'user-agent': 'yarn/1.22.19 npm/? node/v18.13.0 darwin arm64',
  lastUpdateCheck: 1707900363661,
  nodeLinker: 'node-modules'
}
info npm config
{
  editor: 'code',
  'registry.npmjs.org/:_authToken': 'npm_XXXXXXXXXXXXXX'
}
```

**Comment by szymonrybczak** [comment]
After initializing the project, can you install dependencies with Yarn? Or do you have the same error as when initializing?

**Comment by szymonrybczak** [comment]
Hm, very strange. Unfortunately I cannot reproduce it myself :(

**Comment by mcnaveen** [comment]
Happy to provide more info if needed.

**Comment by szymonrybczak** [comment]
I see that there's a log file that probably contain more useful information about the failure:
```
info If you think this is a bug, please open a bug report with the information provided in "/private/var/folders/j8/6l83d1h53s1_10sqlgdn2drc0000gn/T/rncli-init-template-XI48fR/yarn-error.log".
```

Maybe you could run `init` one more time and look inside this file?

**Comment by mcnaveen** [comment]
Hi @szymonrybczak This is strange, I can't reproduce this on my Linux machine. Happens only on Mac M1. Also, I can't access the log fie. It says file not found.

```
Linux mcnaveen 6.5.0-14-generic #14~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov 20 18:15:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by mcnaveen** [comment]
So, here is the update on the issue.:

It of course fails with the yarn `v1.22.19`. But after enabling the Yarn v4 via `corepack` this seems to be working normally.

Here are the steps to set the yarn to v4. By default, the corepack is being shipped with node latest version.

1. corepack enable
2. yarn set version stable
3. now run the init command again. 

This time it'll use yarn v4 and works without any issue.

**Comment by szymonrybczak** [comment]
Alright, so let's keep the latest version of Yarn, as it's faster and more secure. Thanks for digging into this issue! :pray:

**Comment by anamK4923** [comment]
this also happend on windows 11
![image](https://github.com/react-native-community/cli/assets/110364680/e5880dbb-0cef-40c3-9b4b-a17751165634)

**Comment by anamK4923** [comment]
> this also happend on windows 11 ![image](https://private-user-images.githubusercontent.com/110364680/306534853-e5880dbb-0cef-40c3-9b4b-a17751165634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDA5NjYsIm5iZiI6MTcwODUwMDY2NiwicGF0aCI6Ii8xMTAzNjQ2ODAvMzA2NTM0ODUzLWU1ODgwZGJiLTBjZWYtNDBjMy05YjRiLWExNzc1MTE2NTYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwNzMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDgwNDc0YjY2MTdjMTRjZmM3OTg4OWQzOGMxZDcxNjgwNjc2YjJkOWE0ZjI5NWQ4MGZkMjk4ZjQ1NGUzM2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TkLueM4jbcDZBpbRHgs8bIn9Bf2AdrqaOU9-G8spQTM)

I have solved this problems by deleting yarn.lock, package.json, package-lock.json in C:\Users\ACER
![image](https://github.com/react-native-community/cli/assets/110364680/b199cdad-d5d6-4a3d-9897-bb9b1916c35e)

**Comment by Heliosoto1987** [comment]
> > this also happend on windows 11 ![image](https://private-user-images.githubusercontent.com/110364680/306534853-e5880dbb-0cef-40c3-9b4b-a17751165634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDA5NjYsIm5iZiI6MTcwODUwMDY2NiwicGF0aCI6Ii8xMTAzNjQ2ODAvMzA2NTM0ODUzLWU1ODgwZGJiLTBjZWYtNDBjMy05YjRiLWExNzc1MTE2NTYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwNzMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDgwNDc0YjY2MTdjMTRjZmM3OTg4OWQzOGMxZDcxNjgwNjc2YjJkOWE0ZjI5NWQ4MGZkMjk4ZjQ1NGUzM2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TkLueM4jbcDZBpbRHgs8bIn9Bf2AdrqaOU9-G8spQTM)
> 
> I have solved this problems by deleting yarn.lock, package.json, package-lock.json in C:\Users\ACER ![image](https://private-user-images.githubusercontent.com/110364680/306537780-b199cdad-d5d6-4a3d-9897-bb9b1916c35e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDg1OTMsIm5iZiI6MTcxNjU0ODI5MywicGF0aCI6Ii8xMTAzNjQ2ODAvMzA2NTM3NzgwLWIxOTljZGFkLWQ1ZDYtNGEzZC05ODk3LWJiOWIxOTE2YzM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxMDU4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjkzMTdlMDZmZmQwMDQzYjA1MTdkYzM1M2FhNjVlOWViYjc3YzQzZDk1ZWNmNjMxMjBiOGZjMDQzZWZkMTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bF1fkA0swLVlmoNATeduPpPE3eGXSvYvZl9So4TaGyM)

That work for me, thanks

**Comment by Andreas-UI** [comment]
> > this also happend on windows 11 ![image](https://private-user-images.githubusercontent.com/110364680/306534853-e5880dbb-0cef-40c3-9b4b-a17751165634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDA5NjYsIm5iZiI6MTcwODUwMDY2NiwicGF0aCI6Ii8xMTAzNjQ2ODAvMzA2NTM0ODUzLWU1ODgwZGJiLTBjZWYtNDBjMy05YjRiLWExNzc1MTE2NTYzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQwNzMxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDgwNDc0YjY2MTdjMTRjZmM3OTg4OWQzOGMxZDcxNjgwNjc2YjJkOWE0ZjI5NWQ4MGZkMjk4ZjQ1NGUzM2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TkLueM4jbcDZBpbRHgs8bIn9Bf2AdrqaOU9-G8spQTM)
> 
> I have solved this problems by deleting yarn.lock, package.json, package-lock.json in C:\Users\ACER ![image](https://private-user-images.githubusercontent.com/110364680/306537780-b199cdad-d5d6-4a3d-9897-bb9b1916c35e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODM0NTEsIm5iZiI6MTcyMDA4MzE1MSwicGF0aCI6Ii8xMTAzNjQ2ODAvMzA2NTM3NzgwLWIxOTljZGFkLWQ1ZDYtNGEzZC05ODk3LWJiOWIxOTE2YzM1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQwODUyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTBjNzY2MWRjZmEwMjcyY2FkZmU1ZWUxOTNjMTM1ZGU3YjdlNjgzZjMxMjhjZDVlMGVmOTRkN2MxYTk5MTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o635roUZvrRaPUd4XlsrXqY-9N59tiE9aztfvgEp57s)

This works for me too, thanks

**Comment by owenwangsp** [comment]
> npx react-native init RNProject --version 0.73.10
is ok for me
