### ISSUE TITLE
Implement support for Android activity aliases

### ISSUE THREAD

**Issue by andresesfm** [react-native-community/cli#2311]
Android Manifests might contain Activity aliases: https://developer.android.com/guide/topics/manifest/activity-alias-element. This allows mapping activity paths. Such aliases might contain <intent-filter>s no different from regular activities.

Proposed implementation: 
https://github.com/react-native-community/cli/pull/2310

**Comment by szymonrybczak** [comment]
https://github.com/react-native-community/cli/pull/2310#issuecomment-2018058279
