### ISSUE TITLE
Passing registry for different package managers

### ISSUE THREAD

**Issue by lunaleaps** [react-native-community/cli#2320]
## Describe the Feature
Currently we use `--yarn-config-options` in React Native to e2e testing to use privately published monorepo packages when running our template app tests
See: https://github.com/facebook/react-native/blob/main/scripts/e2e/init-template-e2e.js#L125

We've recently switched to using `npm` because Yarn v3 doesn't respect the `npmRegistryConfig` set. See https://github.com/facebook/react-native/pull/43130

`yarnConfigOptions` is only used when the package manager is `yarn -- from my understanding there isn't a way to pass a registry for `npm`
See https://github.com/react-native-community/cli/blob/main/docs/commands.md#init

## Possible Implementations
Introduce another flag for npm specifically, or let me know if there is a way to do this.

**Comment by szymonrybczak** [comment]
hey @lunaleaps! :wave: to make Yarn working with custom `npmRegistryServer` we can do it by just adding another argument to `--yarn-config-options`:

```
❯ yarn config get npmRegistryServer
Alias tip: y config get npmRegistryServer
https://registry.yarnpkg.com

❯ yarn config set npmRegistryServer localhost:4732
Alias tip: y config set npmRegistryServer localhost:4732
➤ YN0000: Successfully set npmRegistryServer to 'localhost:4732'
```

So I think that would work for Core's use case for now, right? Let me know if I'm missing something.

Also I agree that we should make this option more generic so that with flag we can pass custom config options for other package managers.

**Comment by lunaleaps** [comment]
@szymonrybczak Thanks for looking, my question is how do we set a registry for `npm` specifically. Because as I understand it using `--yarn-config-options` only affects using the package manager `yarn`, is that right? 

We want to use `npm` and use a custom registry. My understanding is that we need a flag like `registry <registryhost>`

**Comment by szymonrybczak** [comment]
> @szymonrybczak Thanks for looking, my question is how do we set a registry for npm specifically. Because as I understand it using --yarn-config-options only affects using the package manager yarn, is that right?

Yes, I think we can create also more generic `--registry` option 👍 

I have doubts why you moved there from Yarn to NPM? Since Yarn 3.x seems to support `npmRegistryServer`

**Comment by lunaleaps** [comment]
Yea these are the CI tests that were failing: https://app.circleci.com/pipelines/github/facebook/react-native/42789/workflows/9

![CleanShot 2024-03-05 at 14 00 44@2x](https://github.com/react-native-community/cli/assets/1309636/8e8626a0-f37e-4056-9919-dbf40d381f5a)
d0e9e3f-afac-43c4-be30-e008e8d407da/jobs/1401065?invite=true#step-116-157494_82

It looks like yarn v1.22.19, yea it sounds worthwhile to try upgrading.

**Comment by szymonrybczak** [comment]
Yea, because while creating project with CLI we're installing package in temporary path, and in React Native case on CI there's Yarn v1 installed so it is ignoring `npmRegistryServer` :< Are there any things that blocks upgrading global version in CI? 🤔
