### ISSUE TITLE
How to build android release but with JS dev flag enabled?

### ISSUE THREAD

**Issue by aljidy** [react-native-community/cli#2327]
## Ask your Question

I need to debug my release build but I'm unsure how to pass the dev flag as true to JS. 

It may be in the bundle step this is set and there is a --dev flag here https://github.com/facebook/react-native/tree/main/packages/community-cli-plugin#options-1 however Im unsure how I could set that if I were using the `run-android ` command.

**Comment by richao03** [comment]
running into the same issue, i am building via `./gradlew assembleQa`  in my `metro.config.js` `process.env.NODE_ENV` is reading as `development` but by the time it gets into `cli-plugin-metro` `args.dev` becomes false, and everywhere down the pipe line environment becomes production and `__DEV__` becomes false, am i missing a flag somewhere?

**Comment by liamjones** [comment]
I believe you can control it via your `android/app/build.gradle`: https://github.com/facebook/react-native/blob/d0bb396ddb0c738524099b034276e0c3fb031347/packages/react-native/template/android/app/build.gradle#L20

**Comment by szymonrybczak** [comment]
hey @aljidy, @liamjones  let me know if option mentioned by Liam works for you 👍

**Comment by aljidy** [comment]
Sadly this doesn't work, RN expects release variants   to have a js bundle but adding a variant to debuggableVariants doesn't bundle the app
<img width="728" alt="Screenshot 2024-07-03 at 16 37 21" src="https://github.com/react-native-community/cli/assets/5462907/1bcbb730-f9a9-4541-8c40-37bff56c83c5">
<img width="799" alt="Screenshot 2024-07-03 at 16 36 58" src="https://github.com/react-native-community/cli/assets/5462907/0e384c5c-5d6a-477e-839e-7492c2779f47">

**Comment by liamjones** [comment]
@aljidy I've just tried it locally and it seems to connect back to the packager fine.

At a guess; it might be your emulator's local 8081 port isn't forwarded to your host port 8081. Normally the `run-android` command would be doing this for you. You can run it manually; `adb reverse tcp:8081 tcp:8081`.
