### ISSUE TITLE
API not working in React native android but working in ios.

### ISSUE THREAD

**Issue by azamdev00** [react-native-community/cli#2337]
## Environment

Run `yarn start` 
`yarn android`

## Description

I m using react native latest version 0.73.6. My API is running on a sub-domain. If i run my API on ios simulator the is working fine but when i try to run in android then it is giving me network error. I can run my deployed API with IP address of VPS but not with sub-domain.

## Reproducible Demo

<img width="256" alt="Screenshot 2024-03-17 at 2 30 00 PM" src="https://github.com/react-native-community/cli/assets/110926768/6ce0f591-f395-43dd-a702-742a68b440eb">

<img width="550" alt="Screenshot 2024-03-17 at 2 30 32 PM" src="https://github.com/react-native-community/cli/assets/110926768/179b86c0-ca74-48a0-9ff2-83260b8c1238">

<img width="868" alt="Screenshot 2024-03-17 at 2 33 39 PM" src="https://github.com/react-native-community/cli/assets/110926768/c3a8a606-9461-455b-9ca4-7a8274125d15">

Error
<img width="460" alt="Screenshot 2024-03-17 at 2 31 17 PM" src="https://github.com/react-native-community/cli/assets/110926768/7988033c-ffbe-4d30-bd2d-222608cdf9b6">

**Comment by szymonrybczak** [comment]
hey! this is not issues related to CLI - please try searching for an answer on StackOverflow or inside [React Native](https://github.com/facebook/react-native) repo.
