### ISSUE TITLE
Can CRNA change name inside project like NPX react-native init?

### ISSUE THREAD

**Issue by amela-fe2** [react-native-community/cli#2338]
I tried installed a React-Native using this command: `npx create-react-native-app TestProject --template https://github.com/amela-technology/react-native-templet-v1/tree/master/template`
https://prnt.sc/mERAPqGyV24V

Although my name I want to display is *TestProject*, all names in the project are still **DemoApp**.
https://prnt.sc/FZshUavZECWE

Do we have any flag or option to enable this feature?
Thank you!

**Comment by szymonrybczak** [comment]
hey @amela-fe2, if you want to create a project with `@react-native-community/cli` and use the standard template please use `npx react-native@latest init` to do so. AFAIK CRNA doesn't contain all regexes that RNC CLI - so there might be some edge cases where project won't have all placeholders replaced correctly. Also CRNA in the future will be proposing to use framework's specific initialisation method, see [here](https://github.com/react-native-community/discussions-and-proposals/blob/main/proposals/0759-react-native-frameworks.md#the-init-command) for more details.
