### ISSUE TITLE
✖ Could not create an empty Git repository, see debug logs with --verbose

### ISSUE THREAD

**Issue by code-hasaki** [react-native-community/cli#2339]
## Environment

info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.18363
  CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
  Memory: 8.64 GB / 15.87 GB
Binaries:
  Node:
    version: 20.11.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 4.1.1
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.2.4
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    Android NDK: 22.1.7171670
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Disabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.8.34511.84 (Visual Studio Community 2022)
Languages:
  Java: 17.0.10
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

## Description

![image](https://github.com/react-native-community/cli/assets/71576322/a82664fb-096b-4675-ae53-8942443df9c4)
npx react-native@latest init AwesomeProject

![image](https://github.com/react-native-community/cli/assets/71576322/110503df-d80a-40ae-81a2-6ffc000fe9e5)
npx react-native@latest init AwesomeProject --verbose

just git not commit, i can commit the init log manually,  project work well.

**Comment by szymonrybczak** [comment]
hey @code-hasaki, I'm glad that you resolved your issue!
