### ISSUE TITLE
(node:23249) [DEP0040] DeprecationWarning: The punycode module is deprecated

### ISSUE THREAD

**Issue by edocbuhtig** [react-native-community/cli#2356]
## Description

$npx react-native run-ios
(node:23249) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info Found Xcode project "rc_demo_ios_app.xcodeproj"
info No booted devices or simulators found. Launching first available simulator...

** BUILD FAILED **

## Reproducible Demo

https://youtu.be/7px98MaspaE

**Comment by szymonrybczak** [comment]
hey, it looks like you didn't install Cocoapods, please run inside your project:
`bundle install` 
`cd ios && bundle exec pod install` and then try running `run-ios` again.

**Comment by archisvaze** [comment]
I would recommend you use the LTS(long term support) version of the node. I was getting the same error on the current version (21.x.x). Stopped getting punycode deprecated warning after I reverted back to the LTS v20.12.2.

**Comment by jalargo** [comment]
(node:77235) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server running at http://localhost:3000

Shouldn't have to roll back to outdated version.

**Comment by archisvaze** [comment]
> Shouldn't have to roll back to outdated version.

The latest LTS release is not an outdated version!

**Comment by jalargo** [comment]
> > Shouldn't have to roll back to outdated version.
> 
> The latest LTS release is not an outdated version!
> 
> It is actually the recommended version to install for most users. LTS means Long term support. It won't be outdated for many years

To each their own. Encountered this warning on another app I was working on as well and in both cases it seemed like an incompatibility with MongoDB.

**Comment by szymonrybczak** [comment]
Solved in https://github.com/react-native-community/cli/pull/2381, more context [here](https://github.com/react-native-community/cli/pull/2381#issuecomment-2152091264).
