### ISSUE TITLE
react-native link adds duplicated lines to ios project.pbxproj file

### ISSUE THREAD

**Issue by saraervik** [react-native-community/cli#236]
Recreating an issue reported in react-native project (https://github.com/facebook/react-native/issues/18295)

## Environment

Environment:
  OS: macOS Mojave 10.14.3
  Node: 10.15.1
  Yarn: 1.13.0
  npm: 6.4.1
  Watchman: 4.9.0

## Description

Linking multiple native packages results in duplicated lines in project.pbxproj:

```
LIBRARY_SEARCH_PATHS = (
	"$(inherited)",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
	"\"$(SRCROOT)/$(TARGET_NAME)\"",
);
```

## Reproducible Demo

Link 2 or more native packages

**Comment by thymikee** [comment]
`link` is obsolete now and we're not going to spend too much time on it. [Autolinking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md) is a way to go, available since v2 (ships with RN 0.60).
