### ISSUE TITLE
Error on fresh projects  in Lauching app in the emulator, RN -v 0.73 - Starting: intent

### ISSUE THREAD

**Issue by zeeshan9** [react-native-community/cli#2360]
### npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.3
  CPU: (11) arm64 Apple M3 Pro
  Memory: 78.30 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.12.1
    path: ~/.nvm/versions/node/v20.12.1/bin/node
  Yarn: Not Found
  npm:
    version: 10.5.0
    path: ~/.nvm/versions/node/v20.12.1/bin/npm
  Watchman:
    version: 2024.04.08.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "29"
      - "33"
      - "34"
    Build Tools:
      - 34.0.0
    System Images:
      - android-33 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.6
    wanted: 0.73.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

---------------------------

### npx react-native doctor
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ npm - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode
 ✓ Metro - Required for bundling the JavaScript code

Android
 ✓ Adb - Required to verify if the android device is attached correctly
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 ✓ Gradlew - Build tool required for Android builds
 ✓ Android SDK - Required for building and installing your app on Android

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby - Required for installing iOS dependencies
 ✖ CocoaPods - Required for installing iOS dependencies
   - Version found: N/A
   - Version supported: >= 1.10.0
 ● ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   1
Warnings: 1

---------------------
## Description

I have created multiple poject in react-native cli but all give error when lauching app in the android emulator. Its a fresh project nothing is added yet, just start the app as usual. i have tried created using version 0.72.x and 0.73.x but give same error after project is created. I have search this issue but most were discussing, its occuring because of namespace or appId issue but i have not even done anything in the project. envirement is fully set. I am using macbook pro m3 pro chip. Also i am using java 17
 Stuck on it from few days appriciate your help and thanks in advance.

## Reproducible Demo

just create the project with the latest version of react native. And just start like usual cmd app will start but give error on lauch.
### Error:
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.starterkit/.MainActivity }

**Comment by thymikee** [comment]
Possible fixed by https://github.com/react-native-community/cli/pull/2358, mind checking if this fits your case?

**Comment by zeeshan9** [comment]
Thats a different issue,  I find a more relevent one #2194  but in my case i don't have any appId issue neither i am using expo or any other tool yet,  I have created multiple fresh project using 0.72 and 0.73.x all of them are giving same issue when running app first time in the emulator.

**Comment by zeeshan9** [comment]
@thymikee , I have caught the issue, the issue was due to the aeroplane mode was on in the emulator by default. As this is my first jump in react-native cli app dev i didn't know that. Thanks a lot.
