### ISSUE TITLE
sdk version problem

### ISSUE THREAD

**Issue by Muqaddas-Akram** [react-native-community/cli#2361]
I am still getting the same error on macOS Monterey Android SDK - Required for building and installing your app on Android  Versions found: N/A Version supported: 34.0.0
![Screenshot 2024-04-20 at 3 02 25 AM](https://github.com/react-native-community/cli/assets/118925189/2084315d-80e9-44aa-be12-a729c34e8b24)

**Comment by szymonrybczak** [comment]
hey! we use [`envinfo`](https://github.com/tabrindle/envinfo) package, which sometimes doesn't work in various setups, if your Android app is working correctly then you should be fine and you should ignore this error :)
