### ISSUE TITLE
Android SDK: Not Found

### ISSUE THREAD

**Issue by xiaohao970113** [react-native-community/cli#2369]
## Ask your Question
this is my systemInfo:
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 65.48 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 22.0.0 - /usr/local/bin/node
    Yarn: 1.22.11 - ~/Desktop/ZXZG-APP/zxzg-app/node_modules/.bin/yarn
    npm: 10.5.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: Not Found
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: 2023.2 AI-232.10300.40.2321.11567975
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.2 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.4 => 0.64.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

i running npx react-native doctor result ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 29.0.2

**Comment by szymonrybczak** [comment]
hey @xiaohao970113, we're aware of this issue, it's problem with `envinfo`, a package that we use under the hood to check informations about your setup. If your apps build correctly, you can ignore this issue.
