### ISSUE TITLE
Some files are missing the license header

### ISSUE THREAD

**Issue by matei-radu** [react-native-community/cli#238]
While working on #96 I stumbled across some files that are missing the usual copyright and license header (e.g. [`getDependencyConfig`](https://github.com/react-native-community/react-native-cli/blob/master/packages/cli/src/commands/link/getDependencyConfig.js), [`logger`](https://github.com/react-native-community/react-native-cli/blob/master/packages/cli/src/tools/logger.js)).

In general, are contributors encouraged to be proactive about it and add the header when they happen to be working on these files or do we have any specific policy/strategy for dealing with this type of things?

**Comment by thymikee** [comment]
I don't think we actually need copyright headers in this project. They were added when it was moved to Facebook repository. 

@cpojer @joelmarcey @hramos can you advise?

**Comment by cpojer** [comment]
Could we keep using the FB copyright header for the cli, given that this project is the primary entry point for RN and the code was part of RN itself and mostly written by FB engineers in the past? I think removing them would not be right, technically.

**Comment by thymikee** [comment]
Removing would certainly be wrong. We could omit them in new files, but then again – it raises confusion. I'm good with adding the copyright, just would be nice to adapt a script to enforce it (either copy the one from Jest or use eslint plugin header)

**Comment by matt-block** [comment]
I have no legal background to express an opinion on whether the copyright notice should be there or not, but I think it wouldn't do any harm to mention just the license used (MIT in our case).

**Comment by grabbou** [comment]
I think it makes sense to leave current copyrighted files "as is" and just add a React Native Community one to new files or the ones we refactor in a major way. 

There are files that were done by Facebook engineers, but there are also files that were created in `rnpm` (e.g. core/link/unlik) too. I wouldn't add Facebook copyright to files created by the community.

I hope that makes sense.

I think it would be good to keep this written down in the guidelines as other projects will be running into this use-case too.

CC: @kelset

**Comment by kelset** [comment]
Yeah, that's actually an interesting question.

I'm not sure what actual legal value the headers have "over" the License.md file hosted in each repo, but ideally for now let's keep the headers.

**Comment by JoelMarcey** [comment]
Was this originally a Facebook project? Or has this always been a community project? Normally for code headers, we do something like:

```
Copyright (c) Facebook, Inc. and its affiliates.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
```

**Comment by thymikee** [comment]
@JoelMarcey community -> FB -> community (it's funny right? :D )

**Comment by grabbou** [comment]
It's a mix. It was part of Facebook project and then, I added non-Facebook code [here](https://github.com/facebook/react-native/pull/7550). It's all extracted here now. It's worth mentioning that non-Facebook copyrighted code received SLA-signed contributions later too.

**Comment by JoelMarcey** [comment]
IANAL, but my impression would be that given that this is no longer a Facebook managed project, that any original code with the FB license headers should remain, updates should have whatever license header underneath that. New code should have whatever license header you use now. But I will verify.

**Comment by grabbou** [comment]
@JoelMarcey any update on that? We've been following that approach so far.

**Comment by JoelMarcey** [comment]
@grabbou Just pinged an email. Should know today. Sorry for the delay.

**Comment by matt-block** [comment]
Do we have any updates on this?

**Comment by thymikee** [comment]
Ping @JoelMarcey :)

**Comment by JoelMarcey** [comment]
Oh sorry - yep. What I said looks to be correct. So if you have been following that approach, please continue to do so.
