### ISSUE TITLE
How to fix CompileC normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Pods-urbex' from project 'Pods') failure in react-native ios

### ISSUE THREAD

**Issue by PMP2022** [react-native-community/cli#2395]
How can i solve this error?

`** BUILD FAILED **

The following build commands failed:
	CompileC /Users/ad8kunle/Library/Developer/Xcode/DerivedData/urbex-dtwbdzepmtovrybueqxbhkctyppq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Pods-urbex.build/Objects-normal/arm64/Pods-urbex-dummy.o /Users/ad8kunle/Documents/mobileapp/ios/Pods/Target\ Support\ Files/Pods-urbex/Pods-urbex-dummy.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Pods-urbex' from project 'Pods')
(1 failure)
`

My issues log on xcode looks like this
<img width="271" alt="Screenshot 2024-05-18 at 19 04 47" src="https://github.com/react-native-community/cli/assets/121024400/0abda9c0-3375-4629-af3d-cf753c89048a">

My pod file
<img width="728" alt="Screenshot 2024-05-18 at 19 06 18" src="https://github.com/react-native-community/cli/assets/121024400/4bf94d86-4941-40bd-8dd9-8a76cbe04d12">

My CLI
<img width="1440" alt="Screenshot 2024-05-18 at 19 07 21" src="https://github.com/react-native-community/cli/assets/121024400/ddfc76aa-56f9-497f-9053-5bf31101c5b1">

**Comment by szymonrybczak** [comment]
hey @PMP2022, could you please create an issue inside https://github.com/facebook/react-native?

**Comment by mtx-tnguyen** [comment]
Hi @PMP2022, did you find a solution to your problem?
