### ISSUE TITLE
Experimental debugger support for custom hostnames

### ISSUE THREAD

**Issue by Jesse-Cameron** [react-native-community/cli#2396]
## Describe the Feature

Experimental debugger support for custom hostnames.

Currently the experimental debugger rejects all [requests that don't come from the `localhost` hostname](https://github.com/react-native-community/cli/blob/main/packages/cli-server-api/src/securityHeadersMiddleware.ts#L17). We are using the `--host` flag when starting the react native. It would be good if the debugger supported this.

## Possible Implementations

We could possibly pass the host param in to the [security header middleware](https://github.com/react-native-community/cli/blob/main/packages/cli-server-api/src/securityHeadersMiddleware.ts#L9) and substitute that for `localhost`? Thoughts?

**Comment by Jesse-Cameron** [comment]
If the approach outline works for the team. LMK and I can take a stab at a PR.

**Comment by szymonrybczak** [comment]
Closing as Pull Request implementing this feature was merged! 🎉
