### ISSUE TITLE
AndroidManifest.xml intent-filter error

### ISSUE THREAD

**Issue by billnbell3** [react-native-community/cli#2400]
If I don't put 
```
      <intent-filter>
         <action android:name="android.intent.action.MAIN" />
         <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
```

First in the list in AndroidManifest.xml it does not pickup the  MainActivity.

If the list is not 1st, I get a mapping exception and have to use `--main-activity .MainActivity"`

**Comment by szymonrybczak** [comment]
hey @billnbell3, can you file an example `AndroidManifest.xml` that is failing for you? :pray: That'd help me fix your issue :)

**Comment by szymonrybczak** [comment]
hey @billnbell3, I've submitted https://github.com/react-native-community/cli/pull/2432, could you please take a look if it solves your issue? :pray:

**Comment by szymonrybczak** [comment]
Let's close this issue as I'm pretty sure that https://github.com/react-native-community/cli/pull/2432 fixes this problem :) Please let me know if there's any other case that is still failing.
