### ISSUE TITLE
please Help me I can't fix this error

### ISSUE THREAD

**Issue by SparrowCoding** [react-native-community/cli#2401]
I use react native first time I can't fix it
Android
 ✖ Adb - No devices and/or emulators connected. Please create emulator with Android Studio or connect Android device.
 ✓ JDK - Required to compile Java code
 ✓ Android Studio - Required for building and installing your app on Android
 ✖ Android SDK - Required for building and installing your app on Android
   - Versions found: N/A
   - Version supported: 33.0.0
 ✓ ANDROID_HOME - Environment variable that points to your Android SDK installation
 
 and "adb devices" > adb devices
List of devices attached

what can i do for it fix the error
Plsease help me I've been staying up all night for two days to fix this error.

**Comment by BenSalvesen** [comment]
hey, not sure if this will help but for me, if I do not have device turned on through Android studio and then I type "adb devices" it will just say "list of devices attached". But if I turn a device on, and then type "adb devices", the emulator will show up. So make sure you turn your emulator on before you run your project

**Comment by pnthach95** [comment]
Your information is useless. Show error log when you run project

**Comment by szymonrybczak** [comment]
hey, basically role of `doctor` command is to check if your environment is correctly prepared for React Native development. For your problem @SparrowCoding you just simply need to install an emulator or plug a physical device. You can validate if the destination is available by running `adb devices` in your shell. 

For SDK problem, sometimes `envinfo` tool that we use for checking informations have troubles with detecting versions - so the best way to validate your setup is try running a fresh app or an app that you're working on 👍
