### ISSUE TITLE
Downloading template error installing pods failed on Windows

### ISSUE THREAD

**Issue by wildman82** [react-native-community/cli#2409]
Hello,

I have been running react-native projects for over a year. However, recently the template isn't downloading.

I am on windows and I have the development dependencies installed correctly by running the command here:

https://microsoft.github.io/react-native-windows/docs/rnw-dependencies

When I try to create a new React Native project, I now get a "downloading template error installing pods failed" and the template isn't being downloaded.

I have tried the command "npx --yes react-native@latest init <projectName> --version "latest"" here:

https://microsoft.github.io/react-native-windows/docs/getting-started

And also the "npx @react-native-community/cli@latest init AwesomeProject" command here:

https://reactnative.dev/docs/getting-started-without-a-framework

Any suggestions would be much appreciated.

Thanks

**Comment by szymonrybczak** [comment]
hey @wildman82, could you please try running with `--verbose` options and sending over the logs?

**Comment by wildman82** [comment]
Thanks mate, adding --pm npm to the end of the command seems to have done the trick:

npx react-native@latest init ProjectName --pm npm

**Comment by wasupalonely** [comment]
That worked for me, thanks a lot!
