### ISSUE TITLE
Error while initializing React Native Project

### ISSUE THREAD

**Issue by aryan2621** [react-native-community/cli#2425]
## Environment

Mac Apple M1
Node 18 +
Watchmen version 2024.06.17.00
Installed Android studio and  Xcode
Installed cocoapods using gem (sudo gem install cocoapds)
Ruby version 3.x.x

## Description

Whenever it try to initialize my project using `npx @react-native-community/cli@latest init AwesomeProject` or `npx react-native init testprojectl`, `Downloading templateerror Installing pods failed. This doesn't affect project initialization and you can safely proceed. 
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section`

This error used to come. The command results increation of a empty folder, no template no files nothing.

I went through some stack-overflow sugessting update ruby version , but error remains same

## Reproducible Demo

I already have projects on Expo and I want to try my hand on react-native-cli
Just run `npx @react-native-community/cli@latest init AwesomeProject` or `npx react-native init testprojectl` to see errors
![Screenshot 2024-06-23 at 12 54 14 PM](https://github.com/react-native-community/cli/assets/69208178/d5a62780-ea4f-4791-972a-cf34dff5028e)

**Comment by aryan2621** [comment]
My bad, just found the causing error by --verbose [Life saviour] the issue was the init command was trying to connect to some private registory, that was throwing error 

If any one facing the issue can try in this direction also.

**Comment by elite-mob** [comment]
The same error - 

ruby - 2.7.5/2.7.6/3.3.0
node - 21/22.3.0
cocoapod - 1.15.2

Tried everything from re-installing the cocoapods, but got failed. Is there anyone with the resolution for this? Thank you!


--------------
Here are the logs on the terminal:

npx react-native@latest init MyApp --verbose

Running: npx @react-native-community/cli init

debug We couldn't find a package.json in your project. Are you sure you are running it inside a React Native project?
debug Failed to load configuration of your project. Only a subset of commands will be available.
debug Initializing new project
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

warn The directory MyApp contains files that will be overwritten:
   .git

debug Interaction observers paused
✔ Do you want to replace existing files? … yes
debug Interaction observers resumed
debug Installing template from react-native@latest
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 51ms
➤ YN0000: Successfully set nodeLinker to 'node-modules'
➤ YN0000: Successfully set nmHoistingLimits to 'workspaces'
➤ YN0000: · Yarn 4.2.2
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + react-native@npm:0.74.2, @ampproject/remapping@npm:2.3.0, @babel/code-frame@npm:7.24.7, @babel/compat-data@npm:7.24.7, @babel/core@npm:7.24.7, @babel/generator@npm:7.24.7, @babel/helper-annotate-as-pure@npm:7.24.7, and 588 more.
➤ YN0000: └ Completed in 3s 452ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0002: │ rncli-init-template-zCFuoT@workspace:. doesn't provide react (pe4b8d), requested by react-native.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 420ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed in 1s 20ms
➤ YN0000: · Done with warnings in 4s 980ms
debug Getting config from /var/folders/fk/2wj690dx0972k9xr12040xw80000gn/T/rncli-init-template-zCFuoT/node_modules/react-native/template.config.js
error Installing pods failed. This doesn't affect project initialization and you can safely proceed. 
However, you will need to install pods manually when running iOS, follow additional steps in "Run instructions for iOS" section.

info 💡 To enable automatic CocoaPods installation when building for iOS you can create react-native.config.js with automaticPodsInstallation field. 
For more details, see https://github.com/react-native-community/cli/blob/main/docs/projects.md#projectiosautomaticpodsinstallation
  
  Run instructions for Android:
    • Have an Android emulator running (quickest way to get started), or a device connected.
    • cd "/Users/admin/Documents/GitHub/MyApp" && npx react-native run-android
  
  Run instructions for iOS:
    • cd "/Users/admin/Documents/GitHub/MyApp/ios"
    
    • Install Cocoapods
      • bundle install # you need to run this only once in your project.
      • bundle exec pod install
      • cd ..
    
    • npx react-native run-ios
    - or -
    • Open MyApp/ios/MyApp.xcodeproj in Xcode or run "xed -b ios"
    • Hit the Run button
    
  Run instructions for macOS:
    • See https://aka.ms/ReactNativeGuideMacOS for the latest up-to-date instructions.

**Comment by szymonrybczak** [comment]
hey @elite-mob, please try running:

`npx react-native@latest init MyApp --skip-install`

and then run this command inside a project:

`yarn config set nodeLinker node-modules`

and then try installing your dependencies.

**Comment by elite-mob** [comment]
Thanks a lot! It worked perfectly for me.
