### ISSUE TITLE
When I debugger with node --inspect-brk /cli/path/packages/cli/build/bin.js,Iget a error of not .ts.map,And build dir have .js.map

### ISSUE THREAD

**Issue by Hao-yiwen** [react-native-community/cli#2442]
<img width="416" alt="截屏2024-07-03 19 46 18" src="https://github.com/react-native-community/cli/assets/42827938/82b71ea2-5a46-4e73-abbc-8804038f1c4c">

<img width="751" alt="截屏2024-07-03 19 47 22" src="https://github.com/react-native-community/cli/assets/42827938/2ca903a8-518a-4ef1-9a5e-45353c5f2269">

**Comment by Hao-yiwen** [comment]
I replace all .ts.map to .js.map to solve this question.But I think maybe have more better ways.

**Comment by szymonrybczak** [comment]
hey @Hao-yiwen, I thought we fixed similar issue to this one, here: https://github.com/react-native-community/cli/pull/2330. Could you please take a look?

**Comment by Hao-yiwen** [comment]
Thanks.I use v13.6.8 to debugger,So I also have this question.But I know how to solve it now.
