### ISSUE TITLE
Config "--platform" arg causing builds to fail

### ISSUE THREAD

**Issue by micaww** [react-native-community/cli#2463]
## Description

Builds failing with latest release because "--platform" arg is being passed to "config", but the arg is unknown causing validation issues.

Introduced in this PR, `--platform android` is being passed to `config` now: https://github.com/react-native-community/cli/pull/2379

Commander needs to know about the option (ideal) or disable the validation via `.allowUnknownOption()`

## Reproducible Demo

Run config the way the build script is trying to:

```sh
> node ./node_modules/@react-native-community/cli/build/bin.js config --platform android

error: unknown option '--platform'
```

**Comment by choijiho0021** [comment]
It's the same issue, how should I apply it?

**Comment by TMisiukiewicz** [comment]
@choijiho0021 what React Native version are you using?

**Comment by choijiho0021** [comment]
"react-native": "0.71.12" 를 사용하고 있습니다.
