### ISSUE TITLE
Managing Multiple React Native config file in 

### ISSUE THREAD

**Issue by sandeep36butte** [react-native-community/cli#2481]
We have a common React Native module integrated with the multiple existing android Applications.
Everytime when we want to build RN bundle to any specific android apps, needs an manual update for the react-native.conig file and change the sourceDir and package name within the project config.

Is there any better way to handle this rather than doing the manual update each time might be we can pass the custom reactnative conifg file path and the properties picked up from there.

**Comment by szymonrybczak** [comment]
I'm not sure I understand the issue, could you please elaborate and give more examples & structure of the project and library?

**Comment by sandeep36butte** [comment]
I have a couple of existing native apps, where i need to integrate the react native .
Basically we are trying to build a brown field apps with react native.

I have a single RN repo which links to the android app src configured in the React native metro.
This is My Folder Stricture
- Root
 - AndroidApp1
 - AndroidApp2
 - ReactNativeApp
 
Every time Iam building the Android Apps, I need to manually change the Android Src folder in the Reactnative.config File.
Iam just curise is there any way were i can configure the android and ios src folder from the cli or script before running the react native build.

**Comment by szymonrybczak** [comment]
We only support one Android app, so if you have multiple ones you need to develop a custom script that runs before running  RNC CLI.
