### ISSUE TITLE
RN@0.75: `npx @react-native-community/cli config` fails with _Permissions denied_ error

### ISSUE THREAD

**Issue by birdofpreyru** [react-native-community/cli#2484]
Migrating my projects from RN 0.74 to RN 0.75. On Ubuntu build host, with Android target, found that `npx @react-native-community/cli config` step of the build fails with _Permissions defined_ error, unless I go to `@react-native-community/cli` sources and do `chmod u+x *.js` within the `build` folder.

**Comment by szymonrybczak** [comment]
hey @birdofpreyru, what tool creates `build` folder?

**Comment by birdofpreyru** [comment]
Hmm... I mean the `build` folder in `node_modules/@react-native-community/cli/build`, so I guess that's CLI package's CI/CD setup created it.

**Comment by szymonrybczak** [comment]
Ah, you mean `build/` folder in `@react-native-community/cli` - I don't think we changed anything in our release process between 0.74 and 0.75. Btw is changing permission one time thing? or you need to do it every time you install packages?

**Comment by birdofpreyru** [comment]
Hmm... I just tried to remove `node_modules` and `yarn` again in the projects I had this issue, this time around the `@react-native-community/cli/build/bin.js` file turns out with execution permission, and it looks enough to work fine.

I guess, we can close it for now, as it sounds the issue is not on your side anyway.

**Comment by szymonrybczak** [comment]
@birdofpreyru oh, I'm glad that it worked!
