### ISSUE TITLE
npx react-native run-anroid fails with error autolinkLibrariesFromCommand at '/Users/mac/rn75test/android/settings.gradle' line: 3

### ISSUE THREAD

**Issue by jacobkim9881** [react-native-community/cli#2490]
## Environment
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.15.1
    path: ~/.nvm/versions/node/v20.15.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v20.15.1/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.1/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    API Levels:
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-30 | Google APIs Intel x86 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2021.2 AI-212.5712.43.2112.8815526
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /usr/local/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: 0.75.2
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: true

## Description
When `npx react-native run-anroid`, error occurs as soon. It says error occurs on `android/settings.gradle` but I haven't touched the setting file since it was fresh made app from `npx @react-native-community/cli init`. I tried deleting and installing `react-native-community` in the `node_modules` dir but same error happens. The error msg below:

```js
info A dev server is already running for this project on port 8081.
info Installing the app...
8 actionable tasks: 2 executed, 6 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor

ERROR: autolinkLibrariesFromCommand: process npx @react-native-community/cli config exited with error code: 1

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/mac/rn75test/android/settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'android'.
> ERROR: autolinkLibrariesFromCommand: process npx @react-native-community/cli config exited with error code: 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 5s
error Failed to install the app. Command failed with exit code 1: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
ERROR: autolinkLibrariesFromCommand: process npx @react-native-community/cli config exited with error code: 1 FAILURE: Build failed with an exception. * Where:
Settings file '/Users/mac/rn75test/android/settings.gradle' line: 3 * What went wrong:
A problem occurred evaluating settings 'android'.
> ERROR: autolinkLibrariesFromCommand: process npx @react-native-community/cli config exited with error code: 1 * Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org. BUILD FAILED in 5s.
info Run CLI with --verbose flag for more details.

```

## Reproducible Demo
1. `npx @react-native-community/cli init` and put information.
2. `cd <the-repo-you-created>`
3. `npx react-native run-anroid`

**Comment by szymonrybczak** [comment]
hey @jacobkim9881! what's the output of `npx @react-native-community/cli config` command if you run it in the root directory of your project?

**Comment by jacobkim9881** [comment]
hi @szymonrybczak! It provide bunch of json obj:

```js

{
  "root": "/Users/mac/rn75test",
  "reactNativePath": "/Users/mac/rn75test/node_modules/react-native",
  "reactNativeVersion": "0.75",
  "dependencies": {},
  "commands": [
    {
      "description": "fully automated project state clean: like a freshly-cloned, never-started repo",
      "name": "clean-project-auto"
    },
    {
      "description": "interactive project state clean: choose types of react-native state to clean",
      "name": "clean-project"
    },
    {
      "name": "bundle",
      "description": "Build the bundle for the provided JavaScript entry file.",
      "options": [
        {
          "name": "--entry-file <path>",
          "description": "Path to the root JS file, either absolute or relative to JS root"
        },
        {
          "name": "--platform <string>",
          "description": "Either \"ios\" or \"android\"",
          "default": "ios"
        },
        {
          "name": "--transformer <string>",
          "description": "Specify a custom transformer to be used"
        },
        {
          "name": "--dev [boolean]",
          "description": "If false, warnings are disabled and the bundle is minified",
          "default": true
        },
        {
          "name": "--minify [boolean]",
          "description": "Allows overriding whether bundle is minified. This defaults to false if dev is true, and true if dev is false. Disabling minification can be useful for speeding up production builds for testing purposes."
        },
        {
          "name": "--bundle-output <string>",
          "description": "File name where to store the resulting bundle, ex. /tmp/groups.bundle"
        },
        {
          "name": "--bundle-encoding <string>",
          "description": "Encoding the bundle should be written in (https://nodejs.org/api/buffer.html#buffer_buffer).",
          "default": "utf8"
        },
        {
          "name": "--max-workers <number>",
          "description": "Specifies the maximum number of workers the worker-pool will spawn for transforming files. This defaults to the number of the cores available on your machine."
        },
        {
          "name": "--sourcemap-output <string>",
          "description": "File name where to store the sourcemap file for resulting bundle, ex. /tmp/groups.map"
        },
        {
          "name": "--sourcemap-sources-root <string>",
          "description": "Path to make sourcemap's sources entries relative to, ex. /root/dir"
        },
        {
          "name": "--sourcemap-use-absolute-path",
          "description": "Report SourceMapURL using its full path",
          "default": false
        },
        {
          "name": "--assets-dest <string>",
          "description": "Directory name where to store assets referenced in the bundle"
        },
        {
          "name": "--unstable-transform-profile <string>",
          "description": "Experimental, transform JS for a specific JS engine. Currently supported: hermes, hermes-canary, default",
          "default": "default"
        },
        {
          "name": "--asset-catalog-dest [string]",
          "description": "Path where to create an iOS Asset Catalog for images"
        },
        {
          "name": "--reset-cache",
          "description": "Removes cached files",
          "default": false
        },
        {
          "name": "--read-global-cache",
          "description": "Try to fetch transformed JS code from the global cache, if configured.",
          "default": false
        },
        {
          "name": "--config <string>",
          "description": "Path to the CLI configuration file"
        },
        {
          "name": "--resolver-option <string...>",
          "description": "Custom resolver options of the form key=value. URL-encoded. May be specified multiple times."
        }
      ]
    },
    {
      "name": "start",
      "description": "Start the React Native development server.",
      "options": [
        {
          "name": "--port <number>"
        },
        {
          "name": "--host <string>",
          "default": ""
        },
        {
          "name": "--projectRoot <path>",
          "description": "Path to a custom project root"
        },
        {
          "name": "--watchFolders <list>",
          "description": "Specify any additional folders to be added to the watch list"
        },
        {
          "name": "--assetPlugins <list>",
          "description": "Specify any additional asset plugins to be used by the packager by full filepath"
        },
        {
          "name": "--sourceExts <list>",
          "description": "Specify any additional source extensions to be used by the packager"
        },
        {
          "name": "--max-workers <number>",
          "description": "Specifies the maximum number of workers the worker-pool will spawn for transforming files. This defaults to the number of the cores available on your machine."
        },
        {
          "name": "--transformer <string>",
          "description": "Specify a custom transformer to be used"
        },
        {
          "name": "--reset-cache, --resetCache",
          "description": "Removes cached files"
        },
        {
          "name": "--custom-log-reporter-path, --customLogReporterPath <string>",
          "description": "Path to a JavaScript file that exports a log reporter as a replacement for TerminalReporter"
        },
        {
          "name": "--https",
          "description": "Enables https connections to the server"
        },
        {
          "name": "--key <path>",
          "description": "Path to custom SSL key"
        },
        {
          "name": "--cert <path>",
          "description": "Path to custom SSL cert"
        },
        {
          "name": "--config <string>",
          "description": "Path to the CLI configuration file"
        },
        {
          "name": "--no-interactive",
          "description": "Disables interactive mode"
        },
        {
          "name": "--experimental-debugger",
          "description": "[Experimental] Enable the new debugger experience and 'j' to debug. This enables the new frontend experience only: connection reliability and some basic features are unstable in this release."
        }
      ]
    },
    {
      "name": "codegen",
      "options": [
        {
          "name": "--path <path>",
          "description": "Path to the React Native project root.",
          "default": "/Users/mac/rn75test"
        },
        {
          "name": "--platform <string>",
          "description": "Target platform. Supported values: \"android\", \"ios\", \"all\".",
          "default": "all"
        },
        {
          "name": "--outputPath <path>",
          "description": "Path where generated artifacts will be output to."
        }
      ]
    },
    {
      "name": "log-ios",
      "description": "starts iOS device syslog tail",
      "options": [
        {
          "name": "-i --interactive",
          "description": "Explicitly select simulator to tail logs from. By default it will tail logs from the first booted and available simulator."
        }
      ]
    },
    {
      "name": "run-ios",
      "description": "builds your app and starts it on iOS simulator",
      "examples": [
        {
          "desc": "Run on a different simulator, e.g. iPhone SE (2nd generation)",
          "cmd": "npx react-native run-ios --simulator \"iPhone SE (2nd generation)\""
        },
        {
          "desc": "Run on a connected device, e.g. Max's iPhone",
          "cmd": "npx react-native run-ios --device \"Max's iPhone\""
        },
        {
          "desc": "Run on the AppleTV simulator",
          "cmd": "npx react-native run-ios --simulator \"Apple TV\"  --scheme \"helloworld-tvOS\""
        }
      ],
      "options": [
        {
          "name": "--no-packager",
          "description": "Do not launch packager while running the app"
        },
        {
          "name": "--port <number>",
          "default": 8081
        },
        {
          "name": "--terminal <string>",
          "description": "Launches the Metro Bundler in a new window using the specified terminal path.",
          "default": "iTerm.app"
        },
        {
          "name": "--binary-path <string>",
          "description": "Path relative to project root where pre-built .app binary lives."
        },
        {
          "name": "--list-devices",
          "description": "List all available iOS devices and simulators and let you choose one to run the app. "
        },
        {
          "name": "--udid <string>",
          "description": "Explicitly set the device to use by UDID"
        },
        {
          "name": "--simulator <string>",
          "description": "Explicitly set the simulator to use. Optionally set the iOS version between parentheses at the end to match an exact version: \"iPhone 15 (17.0)\""
        },
        {
          "name": "--device [string]",
          "description": "Explicitly set the device to use by name or by unique device identifier . If the value is not provided,the app will run on the first available physical device."
        },
        {
          "name": "--mode <string>",
          "description": "Explicitly set the scheme configuration to use. This option is case sensitive."
        },
        {
          "name": "--scheme <string>",
          "description": "Explicitly set Xcode scheme to use"
        },
        {
          "name": "--destination <string>",
          "description": "Explicitly extend destination e.g. \"arch=x86_64\""
        },
        {
          "name": "--verbose",
          "description": "Do not use xcbeautify or xcpretty even if installed"
        },
        {
          "name": "--xcconfig [string]",
          "description": "Explicitly set xcconfig to use"
        },
        {
          "name": "--buildFolder <string>",
          "description": "Location for iOS build artifacts. Corresponds to Xcode's \"-derivedDataPath\"."
        },
        {
          "name": "--extra-params <string>",
          "description": "Custom params that will be passed to xcodebuild command."
        },
        {
          "name": "--target <string>",
          "description": "Explicitly set Xcode target to use."
        },
        {
          "name": "-i --interactive",
          "description": "Explicitly select which scheme and configuration to use before running a build"
        },
        {
          "name": "--force-pods",
          "description": "Force CocoaPods installation"
        }
      ]
    },
    {
      "name": "build-ios",
      "description": "builds your app for iOS platform",
      "examples": [
        {
          "desc": "Build the app for all iOS devices in Release mode",
          "cmd": "npx react-native build-ios --mode \"Release\""
        }
      ],
      "options": [
        {
          "name": "--mode <string>",
          "description": "Explicitly set the scheme configuration to use. This option is case sensitive."
        },
        {
          "name": "--scheme <string>",
          "description": "Explicitly set Xcode scheme to use"
        },
        {
          "name": "--destination <string>",
          "description": "Explicitly extend destination e.g. \"arch=x86_64\""
        },
        {
          "name": "--verbose",
          "description": "Do not use xcbeautify or xcpretty even if installed"
        },
        {
          "name": "--xcconfig [string]",
          "description": "Explicitly set xcconfig to use"
        },
        {
          "name": "--buildFolder <string>",
          "description": "Location for iOS build artifacts. Corresponds to Xcode's \"-derivedDataPath\"."
        },
        {
          "name": "--extra-params <string>",
          "description": "Custom params that will be passed to xcodebuild command."
        },
        {
          "name": "--target <string>",
          "description": "Explicitly set Xcode target to use."
        },
        {
          "name": "-i --interactive",
          "description": "Explicitly select which scheme and configuration to use before running a build"
        },
        {
          "name": "--force-pods",
          "description": "Force CocoaPods installation"
        }
      ]
    },
    {
      "name": "log-android",
      "description": "starts logkitty"
    },
    {
      "name": "run-android",
      "description": "builds your app and starts it on a connected Android emulator or device",
      "options": [
        {
          "name": "--mode <string>",
          "description": "Specify your app's build variant"
        },
        {
          "name": "--tasks <list>",
          "description": "Run custom Gradle tasks. By default it's \"assembleDebug\". Will override passed mode and variant arguments."
        },
        {
          "name": "--active-arch-only",
          "description": "Build native libraries only for the current device architecture for debug builds.",
          "default": false
        },
        {
          "name": "--extra-params <string>",
          "description": "Custom params passed to gradle build command"
        },
        {
          "name": "-i --interactive",
          "description": "Explicitly select build type and flavour to use before running a build"
        },
        {
          "name": "--no-packager",
          "description": "Do not launch packager while running the app"
        },
        {
          "name": "--port <number>",
          "default": 8081
        },
        {
          "name": "--terminal <string>",
          "description": "Launches the Metro Bundler in a new window using the specified terminal path.",
          "default": "iTerm.app"
        },
        {
          "name": "--appId <string>",
          "description": "Specify an applicationId to launch after build. If not specified, `package` from AndroidManifest.xml will be used.",
          "default": ""
        },
        {
          "name": "--appIdSuffix <string>",
          "description": "Specify an applicationIdSuffix to launch after build.",
          "default": ""
        },
        {
          "name": "--main-activity <string>",
          "description": "Name of the activity to start"
        },
        {
          "name": "--device <string>",
          "description": "Explicitly set the device to use by name. The value is not required if you have a single device connected."
        },
        {
          "name": "--deviceId <string>",
          "description": "**DEPRECATED** Builds your app and starts it on a specific device/simulator with the given device id (listed by running \"adb devices\" on the command line)."
        },
        {
          "name": "--list-devices",
          "description": "Lists all available Android devices and simulators and let you choose one to run the app",
          "default": false
        },
        {
          "name": "--binary-path <string>",
          "description": "Path relative to project root where pre-built .apk binary lives."
        },
        {
          "name": "--user <number>",
          "description": "Id of the User Profile you want to install the app on."
        }
      ]
    },
    {
      "name": "build-android",
      "description": "builds your app",
      "options": [
        {
          "name": "--mode <string>",
          "description": "Specify your app's build variant"
        },
        {
          "name": "--tasks <list>",
          "description": "Run custom Gradle tasks. By default it's \"assembleDebug\". Will override passed mode and variant arguments."
        },
        {
          "name": "--active-arch-only",
          "description": "Build native libraries only for the current device architecture for debug builds.",
          "default": false
        },
        {
          "name": "--extra-params <string>",
          "description": "Custom params passed to gradle build command"
        },
        {
          "name": "-i --interactive",
          "description": "Explicitly select build type and flavour to use before running a build"
        }
      ]
    }
  ],
  "healthChecks": [],
  "platforms": {
    "ios": {},
    "android": {}
  },
  "assets": [],
  "project": {
    "ios": {
      "sourceDir": "/Users/mac/rn75test/ios",
      "xcodeProject": {
        "name": "rn75test.xcworkspace",
        "path": ".",
        "isWorkspace": true
      },
      "assets": []
    },
    "android": {
      "sourceDir": "/Users/mac/rn75test/android",
      "appName": "app",
      "packageName": "com.rn75test",
      "applicationId": "com.rn75test",
      "mainActivity": ".MainActivity",
      "assets": []
    }
  }
}
```

**Comment by szymonrybczak** [comment]
Hm, so it looks like config is generated without any issues but Android build cannot access `npx @react-native-community/cli config` command, strange!

**Comment by jacobkim9881** [comment]
Strange, is it? I haven't tried on Android Studio.

**Comment by jacobkim9881** [comment]
Running on Android SDK resolved the issue! My Android SDK was old one(2021's version) so I installed latest one.

**Comment by jacobkim9881** [comment]
Let me close this.

**Comment by 4cc3ssX** [comment]
I'm also facing this issue with following output of `npx @react-native-community/cli config`
```sh
$ npx @react-native-community/cli config
sh: /Users/username/Documents/Project/node_modules/.bin/rnc-cli: Permission denied
```

**Comment by jacobkim9881** [comment]
@szymonrybczak It was strange. In my case, my physical devices to install react native 75 doesn't have Android 14(but have 13). After running on emulator having Android 14, the error haven't occurred.

**Comment by jacobkim9881** [comment]
I think the error would occur while proceeding in the file: 
`/node_modules/@react-native/gradle-plugin/settings-plugin/src/main/kotlin/com/facebook/react/ReactSettingsExtension.kt`

```kotlin
import java.util.concurrent.TimeUnit
import javax.inject.Inject
import org.gradle.api.GradleException
import org.gradle.api.file.FileCollection
import org.gradle.api.initialization.Settings
import org.gradle.api.logging.Logging

abstract class ReactSettingsExtension @Inject constructor(val settings: Settings) {

  private val outputFile =
      settings.layout.rootDirectory.file("build/generated/autolinking/autolinking.json").asFile
  private val outputFolder =
      settings.layout.rootDirectory.file("build/generated/autolinking/").asFile

  private val defaultConfigCommand: List<String> =
      windowsAwareCommandLine(listOf("npx", "@react-native-community/cli", "config")).map {
        it.toString()
      }

  /**
   * Utility function to autolink libraries using an external command as source of truth.
   *
   * This should be invoked inside the `settings.gradle` file, and will make sure the Gradle project
   * is loading all the discovered libraries.
   *
   * @param command The command to execute to get the autolinking configuration. Default is
   *   `npx @react-native-community/cli config`.
   * @param workingDirectory The directory where the command should be executed.
   * @param lockFiles The list of lock files to check for changes (if lockfiles are not changed, the
   *   command will not be executed).
   */
  @JvmOverloads
  public fun autolinkLibrariesFromCommand(
      command: List<String> = defaultConfigCommand,
      workingDirectory: File? = settings.layout.rootDirectory.dir("../").asFile,
      lockFiles: FileCollection =
        ¦ settings.layout.rootDirectory
        ¦     .dir("../")
        ¦     .files("yarn.lock", "package-lock.json", "package.json", "react-native.config.js")
  ) {
    outputFile.parentFile.mkdirs()
    val lockFilesChanged = checkAndUpdateLockfiles(lockFiles, outputFolder)
    if (lockFilesChanged || outputFile.exists().not() || outputFile.length() != 0L) {
      val process =
        ¦ ProcessBuilder(command)
        ¦     .directory(workingDirectory)
        ¦     .redirectOutput(ProcessBuilder.Redirect.to(outputFile))
        ¦     .redirectError(ProcessBuilder.Redirect.INHERIT)
        ¦     .start()
      val finished = process.waitFor(5, TimeUnit.MINUTES)
      if (!finished || (process.exitValue() != 0)) {
        val prefixCommand =
        ¦   "ERROR: autolinkLibrariesFromCommand: process ${command.joinToString(" ")}"
        val message =
        ¦   if (!finished) "${prefixCommand} timed out"
        ¦   else "${prefixCommand} exited with error code: ${process.exitValue()}"
        val logger = Logging.getLogger("ReactSettingsExtension")
        logger.error(message)
        if (outputFile.length() != 0L) {
        ¦ logger.error(outputFile.readText().substring(0, 1024))
        }
        outputFile.delete()
        throw GradleException(message)
      }
    }
...
```

**Comment by pranshuchittora** [comment]
Anyone facing this 
1. Check `npx @react-native-community/cli config`
2. Fix `chmod +x /Users/[RN-PROJECT-PATH]/node_modules/.bin/rnc-cli`

**Comment by sarwanand24** [comment]
> I ran into same issue with error code 1

**Comment by mattallard123** [comment]
I had the same issue but fixed with adding to my settings.gradle:
android.useAndroidX=true
android.enableJetifier=true


https://stackoverflow.com/questions/55909804/duplicate-class-android-support-v4-app-inotificationsidechannel-found-in-modules

**Comment by szymonrybczak** [comment]
> Same issue here: 
> 
> BUILD FAILED in 8s                                                                                                      error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081 FAILURE: Build failed with an exception. * Where: Settings file 

hey! could you please open a separate issue with all necessary details?

**Comment by DEveL0perLuckY** [comment]
@szymonrybczak  plz what i do my code is stuck here 
`info Opening app on Android...
info A dev server is already running for this project on port 8081.
info Installing the app...
> Task :gradle-plugin:settings-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:compileKotlin UP-TO-DATE
> Task :gradle-plugin:shared:compileJava NO-SOURCE
> Task :gradle-plugin:shared:processResources NO-SOURCE
> Task :gradle-plugin:shared:classes UP-TO-DATE
> Task :gradle-plugin:shared:jar
> Task :gradle-plugin:settings-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:settings-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:settings-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:settings-plugin:processResources
> Task :gradle-plugin:settings-plugin:classes
> Task :gradle-plugin:settings-plugin:jar
8 actionable tasks: 5 executed, 3 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

ERROR: autolinkLibrariesFromCommand: process cmd /c npx @react-native-community/cli config exited with error code: 1

FAILURE: Build failed with an exception.

* Where:
Settings file 'C:\Users\lucky\Desktop\HealthCare\android\settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'android'.
> ERROR: autolinkLibrariesFromCommand: process cmd /c npx @react-native-community/cli config exited with error code: 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
info Run CLI with --verbose flag for more details.
`
plz some one plz help me

**Comment by Aditys018** [comment]
port 8081 is already in use by some another process, either kill tht process or use another port

**Comment by sarwanand24** [comment]
> @szymonrybczak plz what i do my code is stuck here This is my new Fresh project
> 
> `info Opening app on Android... info A dev server is already running for this project on port 8081. info Installing the app...
> 
> > Task :gradle-plugin:settings-plugin:checkKotlinGradlePluginConfigurationErrors
> > Task :gradle-plugin:shared:checkKotlinGradlePluginConfigurationErrors
> > Task :gradle-plugin:shared:compileKotlin UP-TO-DATE
> > Task :gradle-plugin:shared:compileJava NO-SOURCE
> > Task :gradle-plugin:shared:processResources NO-SOURCE
> > Task :gradle-plugin:shared:classes UP-TO-DATE
> > Task :gradle-plugin:shared:jar
> > Task :gradle-plugin:settings-plugin:compileKotlin UP-TO-DATE
> > Task :gradle-plugin:settings-plugin:compileJava NO-SOURCE
> > Task :gradle-plugin:settings-plugin:pluginDescriptors UP-TO-DATE
> > Task :gradle-plugin:settings-plugin:processResources
> > Task :gradle-plugin:settings-plugin:classes
> > Task :gradle-plugin:settings-plugin:jar
> > 8 actionable tasks: 5 executed, 3 up-to-date
> 
> info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor
> 
> ERROR: autolinkLibrariesFromCommand: process cmd /c npx @react-native-community/cli config exited with error code: 1
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Settings file 'C:\Users\lucky\Desktop\HealthCare\android\settings.gradle' line: 3
> * What went wrong:
>   A problem occurred evaluating settings 'android'.
> 
> > ERROR: autolinkLibrariesFromCommand: process cmd /c npx @react-native-community/cli config exited with error code: 1
> 
> * Try:
> 
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 3s info Run CLI with --verbose flag for more details. ` plz some one plz help me

**Comment by sarwanand24** [comment]
@DEveL0perLuckY have you got the solution? I am also stuck with the same problem.

**Comment by DEveL0perLuckY** [comment]
> @DEveL0perLuckY have you got the solution? I am also stuck with the same problem.
Not yet. 
My project is working until I install any package, so I've decided to use Expo for now.
If I find a solution, I'll let you know.

**Comment by DEveL0perLuckY** [comment]
> hey @jacobkim9881! what's the output of `npx @react-native-community/cli config` command if you run it in the root directory of your project?

bro my code is working thank u

**Comment by DEveL0perLuckY** [comment]
> @DEveL0perLuckY have you got the solution? I am also stuck with the same problem.

try this command npx @react-native-community/cli config

**Comment by LeonardoRosaa** [comment]
I got the issue below after trying to download the Gradle sources within the Android Studio.

```autolinkLibrariesFromCommand: process npx @react-native-community/cli config exited with error code: 1```

React native version: 0.76
Node: 20.11.1
Npx: 10.2.4

**Comment by Shravaniproj** [comment]
@LeonardoRosaa , I have got the same issue now. have you found a solution on it?

**Comment by LeonardoRosaa** [comment]
> @LeonardoRosaa , I have got the same issue now. have you found a solution on it?

Yes! I ran `npx react-native doctor`, and it showed some errors to resolve related to `ANDROID_SDK` and `JAVA_HOME`.

**Comment by Shravaniproj** [comment]
Please help to resolve this issue
PS C:\Users\HP\Documents\MyApp> npx @react-native-community/cli config
error Failed to build the app: No package name found. We couldn't parse the namespace from neither your build.gradle[.kts] file at C:\Users\HP\Documents\MyApp\node_modules\MyApp\android\build.gradle nor your package in the AndroidManifest at C:\Users\HP\Documents\MyApp\node_modules\MyApp\android\app\src\main\AndroidManifest.xml.

**Comment by jacobkim9881** [comment]
`ERROR: autolinkLibrariesFromCommand: process npx @react-native-community/cli config exited with error code: 1`
This error occurs too when node version isn't matched for the react native app. Upgraded node version from 20.15.1 to 20.18.0 and rebooted the machine. However I am not sure this case of the error occurs in every react native app or in certain react native app.

You can check node version after rebooting. Check the version by `node --version`. 

On linux environment, `nvm install 20.18.0` and `nvm use 20.18.0` is another easy way.

**Comment by exzos28** [comment]
Guys who are looking for solutions to this, then just uninstall node_modules and install the dependencies again.
Something strange happens with cli when switching to other branches.

`rm -rf node_modules && yarn`

**Comment by nikolov9996** [comment]
> Guys who are looking for solutions to this, then just uninstall node_modules and install the dependencies again. Something strange happens with cli when switching to other branches.
> 
> `rm -rf node_modules && yarn`

This works for me RN 0.75.2
Make sure you clean everything

**Comment by silentEngineer009** [comment]
I have created a react native sdk and published it to npm. It has no custom code just an app generated from 
`npx @react-native-community/cli@latest init sampleapp`
when I install that package into another newly created react native app and run it I get the following error

`info Opening app on Android...
info A dev server is already running for this project on port 8081.
info Installing the app...
> Task :gradle-plugin:settings-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:processResources NO-SOURCE
> Task :gradle-plugin:settings-plugin:pluginDescriptors
> Task :gradle-plugin:settings-plugin:processResources
> Task :gradle-plugin:shared:compileKotlin
> Task :gradle-plugin:shared:compileJava NO-SOURCE
> Task :gradle-plugin:shared:classes UP-TO-DATE
> Task :gradle-plugin:shared:jar
> Task :gradle-plugin:settings-plugin:compileKotlin
> Task :gradle-plugin:settings-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:settings-plugin:classes
> Task :gradle-plugin:settings-plugin:jar
8 actionable tasks: 8 executed

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

ERROR: autolinkLibrariesFromCommand: process npx @react-native-community/cli config exited with error code: 1

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/ajayshenoy/Desktop/work/test/sampleapp/android/settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'android'.
> begin 0, end 1024, length 116

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s`

both the react native apps have no changes in them just newly generated using terminal command

**Comment by Rajkretoss** [comment]
info Opening app on Android...
info A dev server is already running for this project on port 8081.
info Installing the app...
> Task :gradle-plugin:settings-plugin:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:checkKotlinGradlePluginConfigurationErrors
> Task :gradle-plugin:shared:compileKotlin UP-TO-DATE
> Task :gradle-plugin:shared:compileJava NO-SOURCE
> Task :gradle-plugin:shared:processResources NO-SOURCE
> Task :gradle-plugin:shared:classes UP-TO-DATE
> Task :gradle-plugin:shared:jar UP-TO-DATE
> Task :gradle-plugin:settings-plugin:compileKotlin UP-TO-DATE
> Task :gradle-plugin:settings-plugin:compileJava NO-SOURCE
> Task :gradle-plugin:settings-plugin:pluginDescriptors UP-TO-DATE
> Task :gradle-plugin:settings-plugin:processResources UP-TO-DATE
> Task :gradle-plugin:settings-plugin:classes UP-TO-DATE
> Task :gradle-plugin:settings-plugin:jar UP-TO-DATE
8 actionable tasks: 2 executed, 6 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/kretoss/react-native/JHL1/android/settings.gradle' line: 3

* What went wrong:
A problem occurred evaluating settings 'android'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 812ms
info Run CLI with --verbose flag for more details.

I am getting this error pls help me.

**Comment by sanjeevyadavIT** [comment]
I was getting this issue when running `autolinkLibrariesFromCommand()` when upgrading to 0.76.6 from 0.73.7 in My Brownfield ReactNative setup

```
process npx @react-native-community/cli config exited with error code: 1
```

Solution:
https://github.com/facebook/react-native/issues/47154#issuecomment-2626522995

**Comment by VikasReactNative** [comment]
node_modules\react-native-splash-screen\android\build.gradle
**add->** namespace 'org.devio.rn.splashscreen'
node_modules\react-native-splash-screen\android\src\main\AndroidManifest.xml
**remove** package="org.devio.rn.splashscreen"

same for react native fastImage,customui,@react-native-voice

_in my case i have to remove package from xml fire from the node modules_
