### ISSUE TITLE
Having this issue: Invalid `Podfile` file: 809: unexpected token at ''.

### ISSUE THREAD

**Issue by shadhussain-crgl** [react-native-community/cli#2492]
## Ask your Question
Hi all, I'm having the above issue when trying to run `pod install` after adding the @realm/react library (https://www.npmjs.com/package/@realm/react). 

I have tried removing my node_modules folder, Pods, Podfile, Podfile.lock, reinstalling everything, unadding other dependencies/packages that may be causing conflict issues, and then re-running `pod install` and it still provides that same issue. 

I created a brand new react-native project and tried installing this package and running the `pod install` command and that worked. After trying again with the `--verbose` flag, I saw this output:

```
 #  from /ios/Podfile:42
 #  -------------------------------------------
 #    use_expo_modules!
 >    config = use_native_modules!
 #  
 #  -------------------------------------------

/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:335:in `rescue in block in from_ruby'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:329:in `block in from_ruby'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:50:in `initialize'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `new'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:327:in `from_ruby'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/podfile.rb:293:in `from_file'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.2/lib/cocoapods/config.rb:206:in `podfile'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:160:in `verify_podfile_exists!'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:46:in `run'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `load'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `<main>'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
/Users/shadhussain/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
```

I've ensured that my other dependencies match the ones stated in this repo (https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md) as well.

Does anybody have any suggestions on what else I can try or take a look at? Any help is appreciated.

**Comment by szymonrybczak** [comment]
hey @shadhussain-crgl, please check which version of Ruby you've installed and if it's supported by the React Native version that your project is on. Also how did you installed Cocoapods?

**Comment by szymonrybczak** [comment]
@shadhussain-crgl does it also happen in a fresh project?

**Comment by shadhussain-crgl** [comment]
@szymonrybczak no, it works in a fresh project where the `realm` and `@realm/react` libraries are the only ones in there. So, it is most likely a compatibility issue with some other dependency that's in my project.

**Comment by shadhussain-crgl** [comment]
I believe I got the answer working. Made sure the dependencies were all set at the right version according to this link: https://github.com/realm/realm-js/blob/main/COMPATIBILITY.md and specifically had the @realm/react dependency set to version ^0.5.0. This seemed to solve issues.

**Comment by szymonrybczak** [comment]
@shadhussain-crgl I'm glad that it worked!
