### ISSUE TITLE
get same error

### ISSUE THREAD

**Issue by Devendra7409** [react-native-community/cli#2496]
* Where:
Script '/Users/Documents/project1/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 450

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /Users/Documents/project1/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
  
  The current character read is 'i' with an int value of 105
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  info Run CLI with --verbose flag for more details.
  ^. Output: info Run CLI with --verbose flag for more details.
  
  
  {
  "name": "project1",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "android-r": "react-native run-android --variant=Release",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.11",
    "@react-native-clipboard/clipboard": "^1.11.1",
    "@react-native-community/geolocation": "^3.0.5",
    "@react-navigation/drawer": "^6.5.3",
    "@react-navigation/material-top-tabs": "^6.5.0",
    "@react-navigation/native": "^6.1.0",
    "@react-navigation/native-stack": "^6.9.1",
    "moment": "^2.29.4",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-accordion-list-view": "^1.0.4",
    "react-native-device-info": "^10.6.0",
    "react-native-document-picker": "^8.1.3",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-image-picker": "^4.10.2",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-material-menu": "^2.0.0",
    "react-native-otp-inputs": "^7.4.0",
    "react-native-pager-view": "^6.1.2",
    "react-native-quick-base64": "^2.0.5",
    "react-native-reanimated": "^2.13.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.4.1",
    "react-native-screens": "~3.18.0",
    "react-native-tab-view": "^3.3.4",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^11.26.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by szymonrybczak** [comment]
hey @Devendra7409, what's the output of?
```
node /Users/Documents/project1/node_modules/@react-native-community/cli/build/bin.js config
```

**Comment by Devendra7409** [comment]
The current character read is 'i' with an int value of 105
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
info Run CLI with --verbose flag for more details.
^. Output: info Run CLI with --verbose flag for more details.



i get this error ?

**Comment by szymonrybczak** [comment]
@Devendra7409 please run just CLI command, the output from Gradle doesn't say too much:
```
node /Users/Documents/project1/node_modules/@react-native-community/cli/build/bin.js config
```

**Comment by Devendra7409** [comment]
where write this code ?
