### ISSUE TITLE
Error: unknown option `--config-cmd'

### ISSUE THREAD

**Issue by emreer94** [react-native-community/cli#2507]
## Environment

System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 161.17 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.7.0
    path: ~/.nvm/versions/node/v22.7.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.8.2
    path: ~/.nvm/versions/node/v22.7.0/bin/npm
  Watchman:
    version: 2024.05.06.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.2
    wanted: ^0.75.2
  react-native-macos:
    installed: 0.75.2
    wanted: ^0.75.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
npx react-native doctor:
Common
 ✓ Node.js - Required to execute JavaScript code
 ✓ npm - Required to install NPM dependencies
 ✓ Watchman - Used for watching changes in the filesystem when in development mode
 ✓ Metro - Required for bundling the JavaScript code

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ Ruby - Required for installing iOS dependencies
 ✓ CocoaPods - Required for installing iOS dependencies
 ● ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

## Description

I generated many builds before the update to react-native@0.75.2 while targeting MacOS(designed for iPad). After this update, the build are failed with Error: unknown option `--config-cmd'. Below is the screen shots
![image](https://github.com/user-attachments/assets/99a310d5-8c25-463c-8982-6ada3233d940)
The image below is the detailed logs related to the error
![image](https://github.com/user-attachments/assets/76a8f4a3-9be2-4b48-81d2-f27080b2406b)

**Additional Information:** In react-native@0.75.3, react-native/scripts/bundle.js file had an update with a line **.allowUnknownOption()**. I added this line manually as well but could not make it work again. 

How to resolve or work around this problem?

## Reproducible Demo

Bootstrap a project with react-native and react-native-macos library versions set to 0.75.2. Try to generate a build by targeting MacOS (designed for iPad) and you should see the error mentioned

**Comment by thymikee** [comment]
Hey @emreer94 I'm afraid this error has nothing to do with the Community CLI. Can you file this in react-native-macos repository? Sounds like it's the most appropriate project to reach out to.

**Comment by emreer94** [comment]
I was going to open an issue on react-native-macos library but when I see the error thrown is in the path **react-native/scripts/bundle.js** I opened it here. Also, I added .allowUnknownOptions() as well but it did not work as well. Should I still open the issue in react-native-macos repo?
