### ISSUE TITLE
Gradle Daemon stuck when using latest react native - upgrade from 64 to 75

### ISSUE THREAD

**Issue by sahad00** [react-native-community/cli#2508]
` "resolutions": {
    "@react-native-community/cli": "^13.0.0",
    "@react-native-community/cli-config": "^13.0.0",
    "@react-native-community/cli-debugger-ui": "^13.0.0",
    "@react-native-community/cli-doctor": "^13.0.0",
    "@react-native-community/cli-platform-android": "^13.0.0",
    "@react-native-community/cli-platform-ios": "^13.0.0",
    "@react-native-community/cli-server-api": "^13.0.0",
    "@react-native-community/cli-tools": "^13.0.0",
    "@react-native-community/cli-types": "^13.0.0"
  },`

if I don't add resolution to 13 , default is 14 compatible with react native 0.75 my metro bundler is stuck at 0% for so long 
once I added this resolution on one step downgrade the build is successful, what may be the reason ? 

<img width="1060" alt="Screenshot 2024-09-17 at 4 48 01 PM" src="https://github.com/user-attachments/assets/717b4511-0350-4895-99a1-b39b85ca1910">

**Comment by szymonrybczak** [comment]
Did you try running Metro with `--reset-cache`?

**Comment by sahad00** [comment]
<img width="1133" alt="Screenshot 2024-09-18 at 12 53 12 PM" src="https://github.com/user-attachments/assets/dc8aeaee-4318-4232-9e84-e9a2c19afa1c">

Tried @szymonrybczak  its stuck at 0% , tried for an hour no progress , If I downgrade works cool

**Comment by szymonrybczak** [comment]
hey, that's not a Metro bundler 😅 That's output from Gradle - to fix this scenario you can try running:
```
./gradlew clean && ./gradlew —stop
```
and once again run `npx react-native run-android`

**Comment by sahad00** [comment]
@szymonrybczak  I have tried this the ./gradlew clean itself is stuck

**Comment by sahad00** [comment]
for someone who needs an answer , 

```
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
```

removing this solved this , this piece of code is not required on newer RN versions on `settings.gradle`
