### ISSUE TITLE
Android Build Error

### ISSUE THREAD

**Issue by takawww** [react-native-community/cli#2523]
HI all

I am currently migrating my app from react-native from 0.73 to 0.75
before any change, I can run `patch-package && react-native run-android --port 7777` and build successfully

However, once I have updated react-native version by `yarn add react-native@0.75.4`, I cannot build my app successfully
Here is the log

```
Debugger attached.
yarn run v1.22.22
$ patch-package && react-native run-android --port 7777
Debugger attached.
patch-package 8.0.0
Applying patches...
react-native-camera-kit@14.0.0-beta13 ✔
Waiting for the debugger to disconnect...
Debugger attached.
info A dev server is already running for this project on port 7777.
info Installing the app...
Error executing command '[node, Debugger attached.
************\node_modules\@react-native-community\cli\build\bin.js
Waiting for the debugger to disconnect..., config, --platform, android]': Command '[node, Debugger attached.
************\node_modules\@react-native-community\cli\build\bin.js
Waiting for the debugger to disconnect..., config, --platform, android]' failed with exit code 1.
                                                                                                                                    
info 💡 Tip: Make sure that you have set up your development environment correctly, by running npx react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 


FAILURE: Build failed with an exception.

* Where:
Script '************\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 420   

* What went wrong:
A problem occurred evaluating script.
> Command '[node, Debugger attached.
  ************\node_modules\@react-native-community\cli\build\bin.js
  Waiting for the debugger to disconnect..., config, --platform, android]' failed with exit code 1.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
```

I have double checked the version of @react-native-community/cli and @react-native-community/cli-platform-android has been updated to 14.1.0

**Comment by szymonrybczak** [comment]
@takawww you can try debugging this issue by executing `npx @react-native-community/cli config` in the root directory of your project 👍

**Comment by takawww** [comment]
> @takawww you can try executing `npx @react-native-community/cli config` in the root directory of your project, to see if it returns correct config👍

Thanks @szymonrybczak , I have checked the config before(0.73) and after(0.75) react native version changed, I cant see any obvious problem, each dependency has 
```
"cxxModuleCMakeListsModuleName": null,
"cxxModuleCMakeListsPath": null,
"cxxModuleHeaderName": null,
"isPureCxxDependency": false
```

and also added commands `codegen` and less `ram-bundle` in 0.75

and i guess they are not the root cause of the error :(

**Comment by szymonrybczak** [comment]
hey @takawww, did you resolve your issue?
>  each dependency has
I've checked in some example projects and that shouldn't be an issue that these properties are equal to `null`, most of libraries didn't adopt convention yet.

> and also added commands codegen and less ram-bundle in 0.75

That's intended, we've removed this commands.

**Comment by takawww** [comment]
> hey @takawww, did you resolve your issue?
> 
> > each dependency has
> 
> I've checked in some example projects and that shouldn't be an issue that these properties are equal to `null`, most of libraries didn't adopt convention yet.
> 
> > and also added commands codegen and less ram-bundle in 0.75
> 
> That's intended, we've removed this commands.

Hey, 

I got it all resolved, 
I have re-cloned my repo, 
‘’’
Nvm use 20.13.0
‘’’
Update react, react and required packages and files suggested by react native upgrade helper one by one

and then the problem is gone 

cheers

**Comment by szymonrybczak** [comment]
Alright, I'm glad that it is working! 💯
