### ISSUE TITLE
Doctor cant find Android Studio in toolbox

### ISSUE THREAD

**Issue by lianzhy** [react-native-community/cli#2525]
My Android studio is installed somewhere else, but I can't detect it with npx react-native doctor, how should I configure it to fix this?
I've tried to create a soft connection between the C:\Users\YaGao\AppData\Local\Android directory and my installation directory, but it doesn't seem to work
![image](https://github.com/user-attachments/assets/aba0b2ad-cfdf-4cda-a9da-200419b584a0)
![image](https://github.com/user-attachments/assets/2ca3749c-a9aa-4963-a64d-179bc5675c72)
![image](https://github.com/user-attachments/assets/5e5fe3ad-aa4d-4f4d-a14c-5dffb2fd835c)
![image](https://github.com/user-attachments/assets/9a15363f-d64d-4b71-b8ed-a4661538c9bf)

**Comment by liamjones** [comment]
The doctor command uses the [envinfo](https://www.npmjs.com/package/envinfo) package to locate tools so this should probably be reported there. It looks like it might be a known issue? https://github.com/tabrindle/envinfo/issues/258

**Comment by lianzhy** [comment]
thinks,i did not anything,just use mklink command to instead of the fix android studio path
