### ISSUE TITLE
Build waits forever for config process if output does not fit in buffer

### ISSUE THREAD

**Issue by ivanzamanov** [react-native-community/cli#2528]
## Environment

System:
  OS: macOS 15.0.1
  CPU: (8) arm64 Apple M3
  Memory: 65.59 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: /usr/local/bin/node
  Yarn:
    version: 4.5.0
    path: /usr/local/bin/yarn
  npm:
    version: 9.9.3
    path: /private/tmp/ci-build/builds/CsHpycHx4/0/company/frontend/company-app/node_modules/.bin/npm
  Watchman:
    version: 2024.10.07.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.0
      - iOS 18.0
      - macOS 15.0
      - tvOS 18.0
      - visionOS 2.0
      - watchOS 11.0
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.3
      - 34.0.0
      - 35.0.0
    System Images:
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 16.0/16A242d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

## Description

Gradle build freezes if output from `@react-native-community/cli/build/bin.js config --platform android` is too large.

Fundamentally, the issue is that the gradle script expects the process to first exit and only then reads its output. However, the process cannot exit if the pipe buffer needs to be flushed and blocks forever.

## Reproducible Demo

On MacOS in particular the pipe buffer is 64 KB, so making sure to exceed that size either with plenty of dependencies or "long enough" file paths reliably reproduces this. Other platforms have different buffer sizes.

**Comment by cortinico** [comment]
Hey @ivanzamanov 
I saw your PR #2529 however the logic that is running `config` inside React Native 0.75 is here:

https://github.com/facebook/react-native/blob/60bc3c5aed96a54416161128111ac18962fc4510/packages/gradle-plugin/settings-plugin/src/main/kotlin/com/facebook/react/ReactSettingsExtension.kt#L58-L69

**Comment by cortinico** [comment]
> Looks like this is standard for setting up auto-linking of native modules [`main`/docs/autolinking.md#platform-android](https://github.com/react-native-community/cli/blob/main/docs/autolinking.md?rgh-link-date=2024-10-14T11%3A06%3A06Z#platform-android)

Yeah this has changed since 0.75 so using `native_modules.gradle` is effectively deprecated

**Comment by ivanzamanov** [comment]
I see, so the template and docs are somewhat outdated for newer versions, then.

How would you like to proceed with this issue and PR?

**Comment by cortinico** [comment]
> I see, so the template

mmm the template should be updated: 
https://github.com/react-native-community/template

> and docs are somewhat outdated for newer versions, then.

Do you refer to the CLI docs? If so, they should be updated yes

**Comment by ivanzamanov** [comment]
I believe we used the upgrade helper when upgrading the RN version. Looking at it now, we must've simply skipped removing the reference to `native_modules.gradle`, so the template seems correct. So it's only the docs that are misleading at this point. I'm not too sure what the current mechanism for linking native modules is, otherwise I'd be happy to help update the docs.

Anyway, I guess feel free to close this issue and I can close the PR, since this whole script appears to be deprecated.

Thanks for the help!

**Comment by cortinico** [comment]
> So it's only the docs that are misleading at this point. I'm not too sure what the current mechanism for linking native modules is, otherwise I'd be happy to help update the docs.

Can you point me to the documentation you're referring to so I can update it?
