### ISSUE TITLE
'[node_modules\@react-native-community\cli\build\bin.js, config]' command failed. FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by ganesh42shrma** [react-native-community/cli#2533]
## Ask your Question

The app builds without installing any new packages , but after i install any package , it shows the following error:
`:ReactNative:Running '[node, D:\wizpeerTourGuideFe wrkbld\wizpeerTourGuideFe\node_modules\@react-native-community\cli\build\bin.js, config]' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'D:\wizpeerTourGuideFe wrkbld\wizpeerTourGuideFe\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 401

* What went wrong:
A problem occurred evaluating script.
> Process 'command 'node'' finished with non-zero exit value 1   `

npx react-native info shows:

`info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.19045
  CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Memory: 9.51 GB / 15.88 GB
Binaries:
  Node:
    version: 18.20.4
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 10.8.3
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google APIs Intel x86_64 Atom
      - android-34 | Google Play Intel x86_64 Atom
      - android-35 | Google Play Intel x86_64 Atom
    Android NDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-241.19072.14.2412.12360217
  Visual Studio: Not Found
Languages:
  Java: 17.0.12
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: 0.74.1
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found ,`
 
I see that it says "@react-native-community/cli": Not Found but I can see it in the node_modules , however it doesnt work even if I force install this package. Here is the package.json file :
` {
      "name": "wizpeerTourGuideFe",
      "version": "0.0.1",
      "private": true,
      "scripts": {
        "android": "react-native run-android",
        "ios": "react-native run-ios",
        "lint": "eslint .",
        "start": "react-native start",
        "test": "jest"
      },
      "dependencies": {
        "@react-native-community/netinfo": "^11.3.2",
        "axios": "^1.7.0",
        "body-parser": "^1.20.2",
        "date-fns": "^3.6.0",
        "lottie-react-native": "^7.0.0",
        "moment": "^2.30.1",
        "react": "18.2.0",
        "react-native": "0.74.1",
        "react-native-calendars": "^1.1305.0",
        "react-native-chart-kit": "^6.12.0",
        "react-native-compressor": "^1.8.25",
        "react-native-device-info": "^11.1.0",
        "react-native-document-picker": "^9.3.0",
        "react-native-fs": "^2.20.0",
        "react-native-gifted-chat": "^2.4.0",
        "react-native-htmlview": "^0.17.0",
        "react-native-http-bridge-refurbished": "^1.2.9",
        "react-native-image-base64": "^0.1.4",
        "react-native-image-crop-picker": "^0.41.2",
        "react-native-image-picker": "^7.1.2",
        "react-native-keep-awake": "^4.0.0",
        "react-native-network-info": "^5.2.1",
        "react-native-paper": "^5.12.5",
        "react-native-permissions": "^4.1.5",
        "react-native-popup-menu": "^0.16.1",
        "react-native-safe-area-context": "^4.11.1",
        "react-native-share": "^10.2.1",
        "react-native-sqlite-storage": "^6.0.1",
        "react-native-svg": "^15.3.0",
        "react-native-swiper-flatlist": "^3.2.5",
        "react-native-vector-icons": "^10.2.0",
        "react-native-video": "^6.1.2",
        "react-native-view-shot": "^3.8.0",
        "wizpeerTourGuideFe": "file:"
      },
      "devDependencies": {
        "@babel/core": "^7.20.0",
        "@babel/preset-env": "^7.20.0",
        "@babel/runtime": "^7.20.0",
        "@react-native/babel-preset": "0.74.83",
        "@react-native/eslint-config": "0.74.83",
        "@react-native/metro-config": "0.74.83",
        "babel-jest": "^29.6.3",
        "eslint": "^8.19.0",
        "jest": "^29.6.3",
        "prettier": "2.8.8",
        "react-test-renderer": "18.2.0"
      },
      "engines": {
        "node": ">=18"
      }
    }
`
I tried uninstalling node modules and package.json , and runnning npm i , I also tried running gradlew clean inside the android folder but all in vain , somehow I end up with the same error. I even tried switching my node version from 18 and 20 back and forth.

**Comment by ganesh42shrma** [comment]
I think I missed this part in my androidmanifest.xml file :
 In line 1 : 

What it was before :

    <manifest `xmlns:android="http://schemas.android.com/apk/res/android">

what I added : package="com.wizpeertourguidefe"

what it should have been : 

    <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.wizpeertourguidefe">

after this I did `gradlew clean` and then the build ran with no problems.

**Comment by Teut2711** [comment]
> I think I missed this part in my androidmanifest.xml file : In line 1 :
> 
> What it was before :
> 
> ```
> <manifest `xmlns:android="http://schemas.android.com/apk/res/android">
> ```
> 
> what I added : package="com.wizpeertourguidefe"
> 
> what it should have been :
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.wizpeertourguidefe">
> ```
> 
> after this I did `gradlew clean` and then the build ran with no problems.

Hello, thanks for the solution, btw how did you get this since in bare metal react native, often this parameter was omitted,
