### ISSUE TITLE
Unable to start development server !

### ISSUE THREAD

**Issue by Ayman-MohammedAlsurayh** [react-native-community/cli#2566]
## Ask your Question
![image (11)](https://github.com/user-attachments/assets/e5551c2b-3fb7-47d4-9ddb-0dc6ad68f375)

**Comment by Ayman-MohammedAlsurayh** [comment]
I used old versions a year ago and now I can not start server !

**Comment by szymonrybczak** [comment]
hey, this problem is not related to React Native Community CLI. If you have any troubles with Expo, try looking under: https://github.com/expo/expo
