### ISSUE TITLE
Link assets customization for iOS and Android

### ISSUE THREAD

**Issue by ferrannp** [react-native-community/cli#3]
Right now we can do:

```js
“rnpm”: {
   “assets”: [“./path to your fonts”]
}
```

What do you think of:

```js
“rnpm”: {
   “assets”: {
      "android": [path to folders]
      "ios": [path to folders]
   }
}
```

In this way we won't link/copy assets that are not specific to one platform (like one font only used on iOS).

**Comment by grabbou** [comment]
@ferrannp how big of a use-case this is for you? With new linking mechanism being out really soon, I want to focus on bug fixes instead of rolling out new features.

Auto-linking will have this solved.

@orta @Salakar

**Comment by thymikee** [comment]
@grabbou autolinking hasn't solve it yet, we still need to think about better solution to handle assets on both platforms.
