### ISSUE TITLE
Open Metro in iTerm on macOS

### ISSUE THREAD

**Issue by cpojer** [react-native-community/cli#303]
## Describe the Feature
A lot of people use iTerm 2 on macOS. When using `run-android` or `run-ios`, Metro is started in `Terminal.app` even when launched from iterm. Ideally we'd create a new tab or window in iTerm.

## Possible Implementations
* If there is a way to detect whether run-android/ios was invoked from within iTerm, use iTerm.
* Otherwise, provide a way to set this as a configuration (per project, per computer) once and reuse the setting

## Related Issues
Note that `run-android` already has an option to chose the terminal via an environment variable. It looks like it should work but it didn't when I just tested it.

**Comment by t-hughes** [comment]
You can always open Finder and find the `launchPackager.command` file under `node_modules/react-native/scripts/`. Right click the file, choose get info, then change the "Open with:" section to iTerm, and click on Change All.

**Comment by gatspy** [comment]
npx react-native run-ios also open `Terminal.app`

**Comment by swrobel** [comment]
anyone ... maybe @lucasbento ... clear on why both of these still open Terminal.app, not iTerm?
```
$ yarn react-native run-ios --terminal iTerm

$ REACT_TERMINAL=iTerm yarn react-native run-ios
```

I've also tried `iTerm.app` instead of `iTerm` and the behavior is the same

macOS 10.17.7
react-native-community/cli: 4.13.1
react-native: 0.63.4

**Comment by mattwoberts** [comment]
@swrobel I think the `--terminal` attribute only applies to the build of the project. Metro always loads in teminal.app for me, no matter what you try changing this to. I resolved this with the handy hint from @TheTalonHughes above.

**Comment by swrobel** [comment]
Thanks @mattwoberts but the examples provided in https://github.com/react-native-community/cli/pull/310 indicate that it should work with `run-ios`...

**Comment by good-idea** [comment]
I'm using tmux and the trick above doesn't work... It would be nice if the process just ran in the same shell where I invoke `run-ios`!!

**Comment by willxy** [comment]
Looks like this was implemented in https://github.com/facebook/react-native/pull/24436 which added support for $RCT_TERMINAL, $REACT_TERMINAL, and $TERM_PROGRAM in `React/React.xcodeproj/project.pbxproj`, but looks like `React/React.xcodeproj/project.pbxproj` was later removed in https://github.com/facebook/react-native/pull/25583.  

There's now a https://github.com/facebook/react-native/blob/main/template/ios/HelloWorld.xcodeproj/project.pbxproj but that doesn't include any of the support for $RCT_TERMINAL, $REACT_TERMINAL, $TERM_PROGRAM etc.

**Comment by dev-danilo** [comment]
> anyone ... maybe @lucasbento ... clear on why both of these still open Terminal.app, not iTerm?
> 
> ```
> $ yarn react-native run-ios --terminal iTerm
> 
> $ REACT_TERMINAL=iTerm yarn react-native run-ios
> ```
> 
> I've also tried `iTerm.app` instead of `iTerm` and the behavior is the same
> 
> macOS 10.17.7 react-native-community/cli: 4.13.1 react-native: 0.63.4

Worked here
Thank you! 🚀
