### ISSUE TITLE
Command to reload Android / iOS simulator

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#308]
## Describe the Feature

Users should be able to run `react-native reload` in order to reload Android / iOS devices. The behaviour for reloading is different now on every platform and can be tricky to perform in some cases (e.g. no physical menu button on Android).

## Possible Implementations

There is one implementation that we should look at before implementing, CC: @TheSavior.

Before sending the code, please look at `platform-ios` and `platform-android` packages to see how to provide platform-specific commands.

**Comment by grabbou** [comment]
CC: @pbitkowski

**Comment by grabbou** [comment]
We should consider doing a Jest-like mode, when running start command would also allow you to press certain letters in order to achieve an action. E.g. `r` for reload or running an iOS simulator.

**Comment by pbitkowski** [comment]
Thanks for documenting this feature, @grabbou . I'll work on it this week.

**Comment by grabbou** [comment]
@pbitkowski, were you able to look into that issue? I am trying to get an
idea whether we can ship it in next React Native or not.

>

**Comment by pbitkowski** [comment]
I weren't able to do so. I will work on that, but I don't think so that it will be ready for 0.60.

**Comment by thymikee** [comment]
I second to @pbitkowski if we want to create a reliable watch mode, this is gonna take a while and I wouldn't rush it

**Comment by grabbou** [comment]
Sounds good, I was just referring to his previous estimation.

**Comment by thymikee** [comment]
Bump: https://github.com/react-native-community/discussions-and-proposals/issues/134#issuecomment-501259954

**Comment by iremlopsum** [comment]
I have had aliases to reload and shake android for awhile now, never figured out how to do it for iOS, but maybe my android commands will help

`alias shake="adb -d shell input keyevent 82"`
`alias reload="adb -d shell input keyevent KEYCODE_MENU && adb -d shell input keyevent ENTER && adb -d shell input keyevent ENTER"`

**Comment by thymikee** [comment]
It's available since CLI v3.x as "watch mode" where you can press "r" in terminal with Metro server running to reload the app.

**Comment by yashaka** [comment]
@thymikee is there a way to reload it "remotely", for example from different terminal, maybe via some get response by curl, etc?

**Comment by szymonrybczak** [comment]
Hey @yashaka, you can trigger that by invoking endpoint `localhost:8081/reload`, and then all apps connected to Metro bundler should reload.
