### ISSUE TITLE
cleanup asset

### ISSUE THREAD

**Issue by gengjiawen** [react-native-community/cli#313]
## Describe the Feature
https://twitter.com/janicduplessis/status/1115025287329271808

## Possible Implementations
https://gist.github.com/janicduplessis/b8423f28977d80c1feda437756054627

## Related Issues
none

**Comment by Taym95** [comment]
Hey @thymikee, I would like to give this issue a try, can you explain a litle bit? should we add a command `cleanupAssets`?

**Comment by thymikee** [comment]
I'm not really sure if this should sit in core CLI? How about first making it a plugin and see if it gets traction? :) You'll find the docs on making plugins here: https://github.com/react-native-community/cli/blob/master/docs/plugins.md

cc @grabbou @satya164 @ferrannp what do you think about this `cleanupAssets` idea anyway?

**Comment by grabbou** [comment]
I think it's a good idea to make it a plugin. No reason to put it in the core, especially now that we have a public interface that is nicely described.

**Comment by thymikee** [comment]
Gonna close the issue then, but happy to keep the discussion going :)
