### ISSUE TITLE
how to upgrade 0.58 to 0.59 using new command

### ISSUE THREAD

**Issue by export-mike** [react-native-community/cli#315]
Hi I'm using react-native upgrade but it appears to only update to the latest 0.58 for me, is there a way to specify a range to get to 0.59?

**Comment by thymikee** [comment]
Hey! Unfortunately we can't magically inject the new features into od React Native versions. The new `upgrade` command is available _from_ 0.59.0 and later.

What you can do however is to use the CLI as a standalone, e.g. by using `npx`. Feel free to try this:
```sh
npx @react-native-community/cli upgrade 
```

Please note that the new `upgrade` command is also git-based and it can still fail. However, if it fails, it should provide you with instructions on how to upgrade manually.
