### ISSUE TITLE
react-native run-ios doesn't start packager in debug mode if React is linked via Pods

### ISSUE THREAD

**Issue by noahtallen** [react-native-community/cli#317]
## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
      Memory: 3.11 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.8.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.3
        System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
```

## Description
At some point through my iOS "journey", I must have disabled launching the packager. I think this happened at the same time I started linking react native exclusively through Pods. As a result, I have _no_ React libs imported into the xcode project manually. I got rid of all of that and did it all through Pods, which has been working _much_ better for linking other libraries!

Anyways, when I did that, it stopped launching the packager, so now I have to do it manually. I suppose I'm wondering A) how do I turn that back on? and B) is it possible the CLI should check and launch the packager itself if it was not launched during the build process?

**Comment by thymikee** [comment]
cc @lucasbento as he's working on similar field in #310. Feel free to check it out and suggest improvements!

**Comment by lucasbento** [comment]
@noahtallen: thanks for opening this issue!

By _doesn't always_ do you mean that it launches the packager sometimes and other times not?

Would you be able to provide a small repo with a code that I can reproduce locally?

**Comment by noahtallen** [comment]
I'll try to create a repo for that! No, I'm sorry for the poor phrasing. It never launches the packager for iOS ewhen running from xcode or from the cli. It does launch for Android.
  

  
Noah
  

  
  

  
  
>

**Comment by lucasbento** [comment]
@noahtallen: alright, I'll wait for the project then.

**Comment by noahtallen** [comment]
Howdy! Here's a repo reproducing the issue: [test-react-native-packager](https://github.com/noahtallen/test-react-native-packager). Please let me know if you have any questions. You should be able to see instructions in the readme. The rational behind removing the manually linked react is that I got _so_ many build errors conflicting with other Pods and whatnot when I had it linked _both_ ways! Having it this way has really reduced the amount of friction our team has when working with third party dependencies. If I'm not wrong, this is how it would be set up if one was adding react-native to an existing iOS project.

**Comment by lucasbento** [comment]
@noahtallen: cool, I'll check it out!

**Comment by lucasbento** [comment]
@noahtallen: FYI I see that you mentioned that you couldn't build it, I updated my local `cocoapods` to `1.6.1` and did this to get it to run: https://github.com/CocoaPods/CocoaPods/issues/8091#issuecomment-421538684.

**Comment by lucasbento** [comment]
So, as per what I can see this is because the target `React` on `Pods` doesn't have a start packager build phase as it does when you use it without pods.

### Without pods

![image](https://user-images.githubusercontent.com/6207220/56271018-c502e280-60f7-11e9-8511-1b3cb31c8f7e.png)

### With pods

![image](https://user-images.githubusercontent.com/6207220/56271058-dd72fd00-60f7-11e9-8586-9f649b3b2744.png)

I believe I can include the script to start the packager [here](https://github.com/facebook/react-native/blob/master/React.podspec) by doing something like https://stackoverflow.com/a/20505234/4252781, I don't have much experience with this so I am not sure.

@thymikee / @grabbou would you be able to point someone that can check if this is the right thing to do or not?

**Comment by orta** [comment]
The file `React.podspec` will want that script adding via [`script_phases`](https://guides.cocoapods.org/syntax/podspec.html#script_phases) key 👍

**Comment by grabbou** [comment]
I was thinking we could do it as a part of new `autolinking` supporting
build phases. We could then tell React Native to declare it just like any
other dep.

**Comment by orta** [comment]
That can work, you can see how the support works here: https://github.com/react-native-community/cli/blob/master/packages/platform-ios/native_modules.rb#L43-L62

I should get some docs on this out

**Comment by lucasbento** [comment]
I tried to investigate more of this but I don't really understand how this would fit in the autolinking, I'll be waiting for @orta's docs.

**Comment by ou2s** [comment]
Also having this issue after linking react native exclusively with Cocoapods during 0.59.5 update. In our case the issue is ALWAYS occurring in Debug. So please change the title of the issue as @noahtallen confirmed it is the same for him.

I found a workaround:
- Add manually the Build Phase script and change the path of the launchPackager.command. Below you'l find the modified script
```
export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../scripts/.packager.env"
if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
  if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
    if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
      echo "warning: Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
      exit 2
    fi
  else
    open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "warning: Can't start packager automatically"
  fi
fi
```

**Comment by noahtallen** [comment]
I tried to put the meat of the issue in the title ;) @ou2s

**Comment by vinchentsoKN** [comment]
> So, as per what I can see this is because the target `React` on `Pods` doesn't have a start packager build phase as it does when you use it without pods.
> 
> ### Without pods
> ![image](https://user-images.githubusercontent.com/6207220/56271018-c502e280-60f7-11e9-8511-1b3cb31c8f7e.png)
> 
> ### With pods
> ![image](https://user-images.githubusercontent.com/6207220/56271058-dd72fd00-60f7-11e9-8586-9f649b3b2744.png)
> 
> I believe I can include the script to start the packager [here](https://github.com/facebook/react-native/blob/master/React.podspec) by doing something like https://stackoverflow.com/a/20505234/4252781, I don't have much experience with this so I am not sure.
> 
> @thymikee / @grabbou would you be able to point someone that can check if this is the right thing to do or not?

I had a problem after upgrade to RN 0.60 - The packager wasn't starting 
Using your package script I have managed to run it ! :)

**Comment by orta** [comment]
Yep, I can confirm that's the right thing to do

I think the react-native upgrade tool would need to add support for this

**Comment by chrisbobbe** [comment]
@orta [said](https://github.com/react-native-community/cli/issues/317#issuecomment-528763027):
> Yep, I can confirm moving the script into your app target's build phases is the right thing to do

Ah, OK, thanks, I've managed to do that. But a solution like this one —

@orta [said](https://github.com/react-native-community/cli/issues/317#issuecomment-484240980):
> The file `React.podspec` will want that script adding via [`script_phases`](https://guides.cocoapods.org/syntax/podspec.html#script_phases) key 👍

— isn't being considered anymore, it sounds like.

IIUC, though, doesn't that mean that improvements like https://github.com/facebook/react-native/commit/4ea62041118fb031d7540726df2d29185c6b130d have no effect on RN v0.60.0 and above, where everyone is using CocoaPods?

**Comment by chrisbobbe** [comment]
See also my post in Upgrade Support, at https://github.com/react-native-community/upgrade-support/issues/76.

**Comment by lifenautjoe** [comment]
> Also having this issue after linking react native exclusively with Cocoapods during 0.59.5 update. In our case the issue is ALWAYS occurring in Debug. So please change the title of the issue as @noahtallen confirmed it is the same for him.
> 
> I found a workaround:
> 
> * Add manually the Build Phase script and change the path of the launchPackager.command. Below you'll find the modified script
> 
> ```
> export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
> echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
> if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
>   if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
>     if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
>       echo "warning: Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
>       exit 2
>     fi
>   else
>     open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "warning: Can't start packager automatically"
>   fi
> fi
> ```

Hi everyone,

I've added this script to the app Build Phases (as @orta suggested) -> Run Script but see no change.

Is there something else to do to make the packager start automatically?

![image](https://user-images.githubusercontent.com/12737509/91719081-f36e4a00-eb94-11ea-8863-992df60bac62.png)

**Comment by Voltron369** [comment]
uncheck "For install builds only"

**Comment by Voltron369** [comment]
> > Also having this issue after linking react native exclusively with Cocoapods during 0.59.5 update. In our case the issue is ALWAYS occurring in Debug. So please change the title of the issue as @noahtallen confirmed it is the same for him.
> > I found a workaround:
> > 
> > * Add manually the Build Phase script and change the path of the launchPackager.command. Below you'll find the modified script
> > 
> > ```
> > export RCT_METRO_PORT="${RCT_METRO_PORT:=8081}"
> > echo "export RCT_METRO_PORT=${RCT_METRO_PORT}" > "${SRCROOT}/../node_modules/react-native/scripts/.packager.env"
> > if [ -z "${RCT_NO_LAUNCH_PACKAGER+xxx}" ] ; then
> >   if nc -w 5 -z localhost ${RCT_METRO_PORT} ; then
> >     if ! curl -s "http://localhost:${RCT_METRO_PORT}/status" | grep -q "packager-status:running" ; then
> >       echo "warning: Port ${RCT_METRO_PORT} already in use, packager is either not running or not running correctly"
> >       exit 2
> >     fi
> >   else
> >     open "$SRCROOT/../node_modules/react-native/scripts/launchPackager.command" || echo "warning: Can't start packager automatically"
> >   fi
> > fi
> > ```
> 
> Hi everyone,
> 
> I've added this script to the app Build Phases (as @orta suggested) -> Run Script but see no change.
> 
> Is there something else to do to make the packager start automatically?
> 
> ![image](https://user-images.githubusercontent.com/12737509/91719081-f36e4a00-eb94-11ea-8863-992df60bac62.png)

uncheck "For install builds only"
