### ISSUE TITLE
Check compatibility with new way of handling assets on Android

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#326]
Since [this commit](https://github.com/facebook/react-native/commit/f01c4e2a14c194c7a02bc5afe1900573af02b0c7), we no longer need to copy assets on Android. We can now handle them in a much better way.

We need to check whether there's anything to be done on the link side of things. For example, shall we `noop` on Android when linking assets of a dependency, that uses this new way?

How Gradle handles duplicates?

Going to check and figure out the upgrade strategy.

**Comment by thymikee** [comment]
Ping, anybody willing to tackle it? :)

**Comment by Kida007** [comment]
I can try it (with a bit of mentorship)

**Comment by theweavrs** [comment]
@thymikee I can do it but I would need a little bit of specification as regards to what needs be done.
