### ISSUE TITLE
react-native link assume Podfile first target is identical to project name

### ISSUE THREAD

**Issue by philjoseph** [react-native-community/cli#329]
## Environment

➜  myproj git:(RN594Upgrade) ✗ react-native info
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
      Memory: 18.08 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5264788
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-log-ios: 1.0.1

## Description

running `react-native link react-native-google-signin`  --verbose I am getting an error 

➜  myproj git:(RN594Upgrade) ✗ react-native link react-native-google-signin --verbose
debug Available platforms: iOS, Android
debug Targeted platforms: iOS, Android
debug Getting project config for iOS...
debug Getting project config for Android...
debug Package to link: react-native-google-signin
debug Reading /Users/philc/dev/myproj/ios/Podfile
info Linking "react-native-google-signin" iOS dependency
debug Reading /Users/philc/dev/myproj/ios/Podfile
error Something went wrong while linking. Error: Cannot read property 'match' of undefined
Please file an issue here: https://github.com/react-native-community/react-native-cli/issues
error Cannot read property 'match' of undefined
debug TypeError: Cannot read property 'match' of undefined
    at findLineToAddPod (/Users/philc/dev/myproj/node_modules/@react-native-community/cli/build/commands/link/pods/findLineToAddPod.js:32:44)
    at getLinesToAddEntry (/Users/philc/dev/myproj/node_modules/@react-native-community/cli/build/commands/link/pods/registerNativeModule.js:47:40)
    at registerNativeModulePods (/Users/philc/dev/myproj/node_modules/@react-native-community/cli/build/commands/link/pods/registerNativeModule.js:32:27)
    at Object.registerNativeModule [as register] (/Users/philc/dev/myproj/node_modules/@react-native-community/cli/build/commands/link/ios/common/registerNativeModule.js:24:40)
    at Object.keys.forEach.platform (/Users/philc/dev/myproj/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:39:16)
    at Array.forEach (<anonymous>)
    at linkDependency (/Users/philc/dev/myproj/node_modules/@react-native-community/cli/build/commands/link/linkDependency.js:18:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)

## Analysis

My project let's say `myproj` is multi-target, let's say `target1` and `target2`

I see the following code in `cli/build/commands/link/pods/findPodTargetLine.js` 
```
     16 function findPodTargetLine(podLines, projectName) {
     17   const targetName = projectName.replace('.xcodeproj', ''); // match first target definition in file: target 'target_name' do
     18
     19   const targetRegex = new RegExp(`target ('|")${targetName}('|") do`, 'g');
```

so the code assumes wrongly that my first target is named after the project while it is not and therefore the function returns null and caused the below error.

## Steps to repro
Create a RN ios project, make it multi target and have a Podfile as follow

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'target1' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for target1
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
end

target 'target2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for target2
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
end
```

and then do `react-native link react-native-google-signin` 

Note that I've tried to workaround it by changing the `targetRegex` but this is not enough, since it ignored my 2nd target in the Podile, so may be the issue is that react-native link is not ios multi target ready. I am concerned that it is not just the link command but the whole cli...

Note that it works ok with RN 0.53.3!

**Comment by thymikee** [comment]
`link` is soon to be removed. Should be fixed with autolinking available since RN 0.60+
