### ISSUE TITLE
UX: throw error about `ios-deploy` not being installed earlier in the process

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/cli#330]
## Describe the Feature

For some reason I always get errors with `ios-deploy` not being installed so I have to install it again, right now I have to go through these steps to know that it's not installed:

- Run `run-ios` with `--device` argument;
- Wait a few minutes for the build;
- See the error;
- Install `ios-deploy`;
- Rerun `run-ios`.

This could be improved to show the error to the user as soon as it sees that the `--device` argument is fulfilled and there's no `ios-deploy`.

## Possible Implementations

Run `which ios-deploy` as soon as it sees that there's a `--device` or a `--udid` that matches a device, if it outputs something continue, throw the error if not.

**Comment by thymikee** [comment]
Sounds like a nice improvement!

**Comment by lucasbento** [comment]
I'll work on this later on this week.
