### ISSUE TITLE
"rnpm" deprecation warnings encourage library to not be backwards compatible

### ISSUE THREAD

**Issue by thymikee** [react-native-community/cli#346]
## Description

If a package defines both `"rnpm"` key in `package.json` and a `react-native.config.js` file, we still produce warnings: 
https://github.com/react-native-community/cli/blob/29ae2531393d42758b49a1b18a31f2ef0f897b64/packages/cli/src/tools/config/index.js#L41-L43

I don't think this is what we want, because if a package wants to get rid of the warning, they'll need to remove "rnpm" entry and in turn bump major version, becoming only compatible with RN 0.60+.

We need to swap the order of loading deps and handle it accordingly.

**Comment by grabbou** [comment]
Good catch. We should have a check before doing it. I'll move `warn` to be printed in `index.js`, instead of inside `readLegacyDependencyConfigFromDisk` and that will solve it :)
