### ISSUE TITLE
Can't upgrade from 0.59.4 to 0.59.5

### ISSUE THREAD

**Issue by seriiix** [react-native-community/cli#351]
## Environment

```
    System:
      OS: macOS 10.14.1
      CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
      Memory: 164.46 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 24.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.3
        System Images: android-22 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.4 => 0.59.4 
    npmGlobalPackages:
      react-native-asset: 1.1.3
      react-native-cli: 2.0.1
```

## Description

When i use `react-native upgrade` on 0.59.4 it produces the following error:
```
info No version passed. Fetching latest...
info Fetching diff between v0.59.4 and v0.59.5...
error Failed to fetch diff for react-native@0.59.5. Maybe it's not released yet?
info For available releases to diff see: https://github.com/react-native-community/rn-diff-purge#version-changes
```

## Reproducible Demo

Upgrade from 0.59.4 to 0.59.5

**Comment by thymikee** [comment]
What's the error you get? Do you have a repro maybe? The only difference is the RN version, see: https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.4..release/0.59.5

**Comment by seriiix** [comment]
> What's the error you get? Do you have a repro maybe? The only difference is the RN version, see: https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.4..release/0.59.5

Sorry, I accidentally pressed enter on my keyboard and created this issue without writing anything. Now I edited and wrote the problem.

**Comment by thymikee** [comment]
Oh, I forgot 0.59.5 was reverted and you should upgrade to 0.59.6, which is not available in `rn-diff-purge` repo yet. @pvinis can you fix it?

**Comment by pvinis** [comment]
0.59.5 is correct, 0.59.6 was reverted and removed from purge.

**Comment by thymikee** [comment]
Anyway, cli 1.x uses this link: https://github.com/react-native-community/rn-diff-purge/compare/version/0.59.4...version/0.59.5.diff
which doesn't produce any diff
The diff between 0.59.3 and 0.59.4 works as expected: https://github.com/react-native-community/rn-diff-purge/compare/version/0.59.3...version/0.59.4.diff
So it looks like it wasn't published as a tag as it used to (we still need to support this scenario for a couple of versions for people upgrading from 0.59 to anything later)

**Comment by pvinis** [comment]
Ah. This I can fix. ;)

**Comment by pvinis** [comment]
fixed! @seriiix please try again. @thymikee your first link now produces the correct diff. all is well with the world. :)

**Comment by pvinis** [comment]
I don't have permission to close this issue, so any of you two, feel free to do so.

**Comment by thymikee** [comment]
Thank you @pvinis!

**Comment by seriiix** [comment]
Thank you @thymikee and @pvinis!
