### ISSUE TITLE
CocoaPods linking broken for yarn workspaces

### ISSUE THREAD

**Issue by Ashoat** [react-native-community/cli#352]
## Environment

```
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
      Memory: 128.74 MB / 32.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.13.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        Build Tools: 26.0.3, 27.0.3, 28.0.3
        API Levels: 23, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```

## Description

I've discovered that if you're using yarn workspaces, the path to Podspecs need to be relative to the whole repo root. In effect, [this line](https://github.com/react-native-community/cli/blob/5f7dba3d6e5720e91c967bdd8bc6867d67485737/packages/platform-ios/src/link-pods/addPodEntry.js#L18) needs to have an additional `../` in front of it when using yarn workspaces.

Note that the `:path` for the `React` pod must also be relative to whole repo root, but for some reason Yoga and the `third-party` pods work either way (relative to whole repo root or just React Native project root). Here is a working Podfile:

```
target 'SquadCal' do

  pod 'React', :path => '../../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
  ]

  pod 'yoga', :path => '../../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../../node_modules/react-native/third-party-podspecs/Folly.podspec'

  pod 'RNScreens', :path => '../../node_modules/react-native-screens'

  target 'SquadCalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

I'm excited about the work on autolinking! Would be awesome if we could get it working with yarn workspaces too.

## Reproducible Demo

I can create a repo that reproduces the issue if desired. `react-native init` within a yarn workspace, creating a Podfile, and linking a native module will reproduce the issue.

**Comment by thymikee** [comment]
We could use `--reactNativePath` flag to infer this and fix the issue, but I don't think we're going to spend any time on that, since autolinking should make the source of the issue gone. Always happy to review a PR if anyone fancy :)

**Comment by ymeel** [comment]
@thymikee, having the same problem here with yarn workspaces and cocoapods. What's the 'autolinking' feature you're talking about here? Is this something coming in the near future or still a long way off?

**Comment by thymikee** [comment]
@ymeel near future, see https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by thymikee** [comment]
CocoaPods are now autolinked since RN 0.60, closing.

**Comment by MANTENN** [comment]
It's not working. 

I am using Lerna, and Yarn Workspaces.

After setting `use_native_modules` to `../../../`.

Running `pod install` crashes again with `Errno::ENOENT - No such file or directory @ rb_sysopen` because its looking for those files relatively rather than whats being set.

**Comment by thymikee** [comment]
Can you set up a repro we can download?

**Comment by MANTENN** [comment]
> Can you set up a repro we can download?

Yes, here is roughly what I got so far.  
https://github.com/MANTENN/react-native-cli-podfile.

**Comment by MANTENN** [comment]
I didn't include any JS? What.

**Comment by lauhon** [comment]
After react native 60 (ish) there is a post_install step called `react_native_post_install` which looks one directory "above" for the react native packages which will cause this error.

To fix it add the `react_native_path` option to `react_native_post_install`

```ruby
  react_native_post_install(
      installer,
      react_native_path = "../../../node_modules/react-native",
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
```
