### ISSUE TITLE
normal linking will be deprecated?

### ISSUE THREAD

**Issue by karanpratapsingh** [react-native-community/cli#359]
## Ask your Question
Hey guys, I was wondering if the normal linking (via build phases) will be deprecated after the official release of autolinking + cocoapods? or like how do we migrate from one linking to another and ensure working??

**Comment by thymikee** [comment]
We hope it's gonna be deprecated some day, but not in the nearest future. We first need to make sure all major 3rd party React Native packages supports it without issues, which can take a while (we hope for joined community effort to help us with that). 

The plan is to make autolinking so easy to use, that people will forgot what the `link` command is for – then deprecate it.

**Comment by karanpratapsingh** [comment]
Thank you :D
