### ISSUE TITLE
Improve overall interface

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#36]
The CLI experience is very `raw`. We should analyse what other CLI tools do in that space (Yarn, Jest and more - suggestions are welcome) and try to come up with our plan.

I've been working quite heavily on Haul where we did a "Create React App" - like interface that takes up the whole available space and cleans up the terminal when e.g. the build finishes.

I am leave this issue here open for discussion - would love to gather some ideas before we get started.

**Comment by grabbou** [comment]
https://github.com/react-native-community/react-native-cli/pull/30#discussion_r240776317

**Comment by grabbou** [comment]
I really like "Yargs" and the way it's set up in Metro CLI. I am thinking this should help us simplify the overall interface even more and get rid of custom "parsing" functions that are causing an unnecessary maintenance.

**Comment by thymikee** [comment]
This is mostly done now. What we need now is small incremental adjustments to the UI, no need to track it in this ticket.
