### ISSUE TITLE
Automatically run `pod install` when a template ships with a Podfile

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#368]
New React Native template has CocoaPods integration and other templates might soon have it too.

Unfortunately, the drawback is that you need to run `pod install` yourself after initing a project.

We want to improve this workflow and make CLI run `pod install` automatically for users when CocoaPods is available or attempt installing. 

Since this code is only going to be run when platform is Mac, we can assume `gem` is available and run `sudo gem install cocoapods` as per [the docs](https://guides.cocoapods.org/using/getting-started.html).

We can also allow users to `skip` that step where we only print an information that they should install CocoaPods afterwards in order to run `iOS` application.

**Comment by lucasbento** [comment]
Any idea on how we would let the user skip the step of installing cocoapods and running `pod install`?

**Comment by grabbou** [comment]
A `--skip-pods` flag? Why would you want to skip it tho?

**Comment by lucasbento** [comment]
> We can also allow users to skip that step where we only print an information that they should install CocoaPods afterwards in order to run iOS application.

Just asked because of this :P

**Comment by grabbou** [comment]
Ah, sorry! I meant something like this:
```
CocoaPods was not found on your laptop. Do you want to install it? [y/n]
```
(and you can go with `n` if you don't want to do it).

**Comment by Vyazovoy** [comment]
I would discourage using `sudo` installation option for Cocoapods as it is rarely used. Usually people use Ruby installed with a help of `rbenv` instead of system one. Either way providing instructions how to install Cocoapods instead of installing it by `cli` looks like more wise approach. As end user suppose to know what is Cocoapods if they are going to use it as an iOS dependency manager.

**Comment by thymikee** [comment]
Agreed, we should leave installation of CocoaPods to the user, as there are multiple ways it can be installed. The best we can do is to propose a bunch of solutions and link to official CP docs.

**Comment by lucasbento** [comment]
IMO it's not harmful to ask the user if the CLI should automatically install it or not, the approach suggested is [the one recommended in the docs](https://guides.cocoapods.org/using/getting-started.html#installation), for me it just looks a bit weird to ask for user's password when doing it as it uses `sudo` (you can see on #373).
