### ISSUE TITLE
Why `react-native init` generates TypeScript code in `.js` file?

### ISSUE THREAD

**Issue by kochoru** [react-native-community/cli#399]
## Environment
- OS:macOS
```
❯ react-native -v
react-native-cli: 2.0.1
react-native: 0.59.8
```

## Question

Why `react-native init` generates TypeScript code in Javascript file?
For example, `App.js` looks like that.

**Comment by thymikee** [comment]
It's not TypeScript, it's Flow and there's nothing changed lately about that.

**Comment by kochoru** [comment]
Thanks!
