### ISSUE TITLE
react-native link only works on ios when working with a monorepo

### ISSUE THREAD

**Issue by Federkun** [react-native-community/cli#408]
## Environment

```
info 
  React Native Environment Info:
    System:
      OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
      CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
      Memory: 480.12 MB / 15.55 GB
      Shell: 5.4.2 - /usr/bin/zsh
    Binaries:
      Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v8.15.0/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
    SDKs:
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 25.0.2, 26.0.1, 26.0.2, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    npmGlobalPackages:
      react-native-git-upgrade: 0.2.7
```

## Description

When working on a monorepo ( eg. https://github.com/brunolemos/react-native-web-monorepo ), and one of the multiple packages is a react-native application, running `react-native link` will correctly link iOS, but not android.

## The issue

It works on ios because https://github.com/react-native-community/cli/blob/c3b0d4729eed305d046344e8c56ba6db1d57a5f3/packages/cli/src/tools/ios/findProject.js#L41-L57

Will try to look deep in the root folder https://github.com/react-native-community/cli/blob/c3b0d4729eed305d046344e8c56ba6db1d57a5f3/packages/cli/src/tools/ios/findProject.js#L16

While on android 

https://github.com/react-native-community/cli/blob/c3b0d4729eed305d046344e8c56ba6db1d57a5f3/packages/cli/src/tools/android/findAndroidAppFolder.js#L17-L29

it won't do that; it will just search inside the root folder, leading in the situation that a monorepo will link ios but not android.

I'll try to submit a PR at some point tomorrow.

## Note:

AFAIK, v2.0.0-alpha.23 works correctly, the issue is with the previous major version.

**Comment by thymikee** [comment]
Thanks! Looking forward to it

**Comment by Quadriphobs1** [comment]
I setup a monorepo using yarn-workspace but if I want to link it keep complaining that I must be inside a `react-native` project and that is because of `node_modules` in the root folder, I am wondering how you get to link ios @Federkun

**Comment by Federkun** [comment]
v2.0.0-alpha.23 currently works fine for me, for both ios and android. When you run `react-native link` you must be inside the packages with react native in it ( in my case is `packages/mobile` ), not the root folder.

v2.0.0-rc.1 is not working in my project, as soon as I find a bit of time I'll try to correct it. Sorry for the delay.

**Comment by thymikee** [comment]
We're moving away from `react-native link` in favor of autolinking in RN 0.60. I don't think we should spend too much time fixing it, but move quicker to a better solution.
