### ISSUE TITLE
bug on custom config for podspec on autolinking

### ISSUE THREAD

**Issue by sibelius** [react-native-community/cli#412]
## Environment

```jsx
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
      Memory: 106.45 MB / 16.00 GB
      Shell: 5.0.7 - /usr/local/bin/bash
    Binaries:
      Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 22, 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.3
        System Images: android-25 | Android TV Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-N | Android TV Intel x86 Atom, android-N | Android Wear ARM EABI v7a, android-N | Android Wear Intel x86 Atom, android-N | Intel x86 Atom, android-N | Intel x86 Atom_64, android-P | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react-native: 0.59.8 => 0.59.8 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.4.1
```

## Description

I'm following this doc https://github.com/react-native-community/cli/blob/master/docs/dependencies.md to provide a custom path for podspec for react-native-app-auth

https://github.com/react-native-community/cli/blob/master/docs/dependencies.md

My config is like this:

```jsx
module.exports = {
  dependencies: {
    'react-native-app-auth': {
      platforms: {
        ios: {
          podspec: 'ios/RNAppAuth.podspec',
        },
      },
    },
  },
};
```

If I add `ios/RNAppAuth.podspec`, it will re-add another .podspec to Podfile location

[!] Invalid `Podfile` file: [!] No podspec exists at path `/app/node_modules/react-native-app-auth/ios/RNAppAuth.podspec.podspec`..

If I remove `.podspec`, like this `podspec: 'ios/RNAppAuth',` it throw this error:

[!] No podspec found for `RNAppAuth` in `/app/node_modules/react-native-app-auth`

## Reproducible Demo
```jsx
npx @react-native-community/cli@next init --template=@react-native-firebase/template@alpha Awesome

yarn add react-native-app-auth

cd ios
pod install
```

related to this issue: https://github.com/react-native-community/cli/issues/411

**Comment by thymikee** [comment]
@sibelius I've checked that recently and with current design we expect podspec to be inside root of the project only. We'd be very welcome to support broader use cases though.

**Comment by sibelius** [comment]
isn't react-native.config.js to enable this kind of customizations?

**Comment by thymikee** [comment]
It is, that's why I'm not closing this issue :D

**Comment by thymikee** [comment]
@sibelius mind checking if this works for you? https://github.com/react-native-community/cli/pull/442
To test it, checkout CLI locally, `yarn link` all modules inside `packages/` dir, then in your test project
```
yarn link @react-native-community/cli-tools @react-native-community/cli-platform-ios  @react-native-community/cli-platform-android @react-native-community/cli
```
and then `pod install`
