### ISSUE TITLE
Standardize how we make HTTP requests?

### ISSUE THREAD

**Issue by matei-radu** [react-native-community/cli#423]
During the review of [#268](https://github.com/react-native-community/cli/pull/268), we noticed that we are using multiple fetch implementations across the CLI. These are:
 
1. `fetch` function from [`cli/src/tools/fetch.js `](https://github.com/react-native-community/cli/blob/master/packages/cli/src/tools/fetch.js). This is a very, very minimalistic GET-only wrapper around the standard `https` module. 
2. `httpsGet` function from [`cli/src/tools/releaseChecker/getLatestRelease.js`](https://github.com/react-native-community/cli/blob/master/packages/cli/src/tools/releaseChecker/getLatestRelease.js). This is, again, a GET-only wrapper around `https` that exists because the above mentioned `fetch` does not satisfies the requirements ([see discussion](https://github.com/react-native-community/cli/pull/268#discussion_r283701172)).
3. `node-fetch` in [`tools/src/isPackagerRunning.js`](https://github.com/react-native-community/cli/blob/644380f769ec1c9b53259c0b45c66f3c36270d0e/packages/tools/src/isPackagerRunning.ts).

#### Should we standardize the way we make HTTP requests in this project?

I propose to discuss and decide on one implementation to use across the entire CLI to keep things consistent. Of course, it doesn't have to be one of the above implementations if you want to suggest a different one (e.g. [`axios`](https://github.com/axios/axios) or the standard `https` Node module) 😃

I'll start! I believe we can stick with `node-fetch` and replace the other implementations with it. We should also mention somewhere in the Contributing doc to use `node-fetch` when making network request so that we avoid this inconsistency happening again in the future.

**Comment by thymikee** [comment]
Thanks for bringing this up. I'm also for using `node-fetch` since we have it already. However, I'd build a small abstraction around it, so we can switch the implementation easily in the future, and call it `tools/networking.js` or so. Then it will be pretty obvious what we use to handle network requests :)
