### ISSUE TITLE
`react-native init` has an issue when providing a Git version of React Native to `--version`

### ISSUE THREAD

**Issue by empyrical** [react-native-community/cli#425]
## Environment

```
System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (4) x64         Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz
    Memory: 552.95 MB / 7.48 GB
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 11.12.0 - ~/.nvm/versions/node/v11.12.0/bin/node
    Yarn: 1.16.0 - /usr/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.12.0/bin/npm
```
## Description

In older versions of the React Native CLI (I think this was before it got moved back into its own repo) I was able to provide GitHub repos/`file:` paths (basically whatever npm/yarn are able to install from) to `--version` and it would successfully init a new React Native project using a Git version or a local working version of the React Native repo.

It still works a little bit at first - but then at some point it grabs the version from the repo's `package.json` (which is `1000.0.0` typically) and tries to install `react-native@1000.0.0` instead of using the repo url I provided to `--version`. Since this is not valid, the init process stalls at a Yarn prompt asking to choose a proper version of `react-native` from NPM.

## Reproducible Demo

```sh
react-native init rntinker --version facebook/react-native.git#2ae43e5aa0c18ec8a8877e077d0975cbc043443b
This will walk you through creating a new React Native project in /trimmed/rntinker
Using yarn v1.13.0
Installing facebook/react-native.git#2ae43e5aa0c18ec8a8877e077d0975cbc043443b...
yarn add v1.13.0

# snipped yarn add output

Done in 174.59s.
info Setting up new React Native app in /trimmed/rntinker
info Adding required dependencies
yarn add v1.13.0
[1/4] Resolving packages...
Couldn't find any versions for "react-native" that matches "1000.0.0"
? Please choose a version of "react-native" from this list:
```

**Comment by thymikee** [comment]
Legacy init is not actively developed anymore. Please use new init for such use cases: https://github.com/react-native-community/cli/blob/master/docs/init.md#for-react-native0600-or-greater

The `--version` argument in new init can only be a valid npm tag, for all else `--template` is used.

**Comment by empyrical** [comment]
Thanks! 

These work partially:

```sh
> npx facebook/react-native.git#6c0eccd46d157804fde767263ec8856ff8c99cfb init Project

# or

> yarn init && yarn add facebook/react-native.git#6c0eccd46d157804fde767263ec8856ff8c99cfb & yarn react-native init ProjectName
```

Seem to get this error however:

```
                  Welcome to React Native!
                 Learn Once Write Anywhere

✔ Downloading template
✖ Copying template
error Error: Cannot find module '/var/folders/ny/grqg4bx1135gc_rmxb6kqpfw0000gn/T/rncli-init-template-X8QBwH/node_modules/react-native/template.config'
```

A similar bug seems to be affecting users in invertase/react-native-firebase#2126. I will see if I can figure out what's going on there.

**Comment by thymikee** [comment]
init will take the RN from `latest` tag by default (which is 0.59.9 currently). You need to pass `--template` argument:

```sh
yarn init && yarn add facebook/react-native.git#6c0eccd46d157804fde767263ec8856ff8c99cfb & yarn react-native init --template https://github.com/facebook/react-native.git#6c0eccd46d157804fde767263ec8856ff8c99cfb ProjectName
```

**Comment by empyrical** [comment]
I get the same error when providing the git repo as a template too.

**Comment by thymikee** [comment]
So I tried locally:
```
init --template 'https://github.com/facebook/react-native.git#master' ProjectName
``` 

and it fails for clear reason:

```
error Error: Command failed: yarn install
error Couldn't find any versions for "react-native" that matches "1000.0.0"
```

Forgot to tell you that RN uses `1000.0.0` as a version on master :D You need to checkout RN locally, change the version to `$pwd` (absolute path to React Native) and pass `--template /absolute/path/to/react-native`.

Maybe, since 1000.0.0 is pretty special, we could apply some special handling to it.
