### ISSUE TITLE
linking failed after change android package

### ISSUE THREAD

**Issue by KingAmo** [react-native-community/cli#430]
## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
      Memory: 176.93 MB / 8.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 12.3.1 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 28
        Build Tools: 28.0.3
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.8 => 0.59.8
    npmGlobalPackages:
      react-native-cli: 2.0.1

```
## Description
i changed my package from `com.fastHealthExam` to `com.cmlabs.fastHealthExam`，when i install a new dependency，`react native link`  seems like not recognize it .
the new directory of  `MainApplication.java` is in `com/cmlabs/fastHealthExam/MainApplication.java`, not the error info below
```
info Linking "react-native-baidumap-sdk" Android dependency
error Something went wrong while linking. Error: ENOENT: no such file or directory, open '/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-app/android/app/src/main/java/com/fastHealthExam/MainApplication.java'
Please file an issue here: https://github.com/react-native-community/react-native-cli/issues
error ENOENT: no such file or directory, open '/Users/qinshuai/Documents/ReactNativeProj/NewFold/FastHealthExamination-app/android/app/src/main/java/com/fastHealthExam/MainApplication.java'. Run CLI with --verbose flag for more details.
```
the location of my `MainApplication.java` is wrong

- new package hierarchy：
![image](https://user-images.githubusercontent.com/29938227/59546795-9f168480-8f66-11e9-9445-e5045699e172.png)

**Comment by KingAmo** [comment]
i solved this problem: in `AndroidManifest.java` ,  change `package="com.cmlabs.fastHealthExam"`

**Comment by thymikee** [comment]
Check out https://github.com/react-native-community/cli/blob/master/docs/projects.md#project-1 and packageFolder option. The docs are written for newer config available in next major version, but there's a migration guide on the bottom which should give you some hints on how to do it with "rnpm" old config format.

Even better, check how RN Firebase does it: https://github.com/invertase/react-native-firebase/blob/62715f894e559e75cf4761581938f04c16b48e74/package.json#L110
