### ISSUE TITLE
Autolink doesn't add pod for some 3rd party libs

### ISSUE THREAD

**Issue by kelset** [react-native-community/cli#446]
## Environment

Latest RC3.

## Description

Basically, for some "fully native" libraries like [`react-native-app-auth`](https://github.com/FormidableLabs/react-native-app-auth), the autolinking feature doesn't add the pod in the Podspec.

I spoke with @thymikee about this and it seems that we have two options:
1) document that you need to add the pod, and then just run pod install, that's it, no more running react-native link
2) figure out an ergonomic way for lib maintainers to add extra pods; this is where we define every pod: https://github.com/react-native-community/cli/blob/master/packages/platform-ios/native_modules.rb#L60 we could add a next line that would e.g. iterate over, let's say package_config["extraPods"] array and add them automatically

It could go also go - like this on lib side, in react-native.config.js:
```js
module.exports = { 
  dependency: { 
    platforms: { 
      ios: { 
        extraPods: [{name: 'AppAuth', version: '1.0.0'}] 
      }
    } 
  } 
}
```

## Reproducible Demo

react-native init Abrakadabra --version react-native@next
cd Abrakadabra
yarn add react-native-app-auth@FormidableLabs/react-native-app-auth#feature/upgrade-appauth-ios
react-native link react-native-app-auth
cd ios
pod install

**Comment by kadikraman** [comment]
Hi 👋 - it looks like this works when the `.podspec` is in the root level, but not when it's in the `/ios` directory.

I've ended up in a weird situation when I've got two. When I add the [AppAuth](https://github.com/FormidableLabs/react-native-app-auth/pull/338/commits/b0eb1746c240dd3bdbcd7370b5021af81825cb48) dependency in the root level Podspec, this does work.

**Comment by thymikee** [comment]
I just tried on a latest CLI and it understands the `ios/*.podspec` and installs `AppAuth` correctly. Are you sure you have `@react-native-community/cli@2.0.0-rc.3`? That's where this improvement landed. If you do, we can close this issue, as it's solved through proper CocoaPods usage.

**Comment by kadikraman** [comment]
Try
```
yarn add react-native-app-auth@FormidableLabs/react-native-app-auth#aa9819e745af32d5adba682772a7dc2f13637273
```
^^ this is the commit before I added the AppAuth dependency to the root level podspec

**Comment by thymikee** [comment]
Also it's worth to note that since `rc.3` we first look at root level and then fall back to the directory where the Xcode project is located. If you didn't have the `s.dependency` in the root `.podspec`, I'd suspect that's why it didn't work

**Comment by kadikraman** [comment]
I see, I thought that might be the case. I recently merged a PR from a contributor that added a `.podspec` to the root level, which is how I've ended up with two. Sorry about the confusion.

Would you be able to advise, would it be preferred for the `.podspec` live in the root lever or in the `/ios` directory?

**Comment by thymikee** [comment]
> this is the commit before I added the AppAuth dependency to the root level podspec

Yep. That's the issue exactly. If you depend on a certain pod, you're supposed to have in depenencies, that's expected and works just fine with autolinking.

You can get rid of the second podspec if you don't bother supporting RN 0.59 and 0.60 at the same time because that would be a breaking change if someone passes path to your podfile in `/ios` and now it's gone.

>Would you be able to advise, would it be preferred for the .podspec live in the root lever or in the /ios directory?

It's totally up to you, we support both just in case :D. I think having it in root is a bit more common in the community, but didn't do any research on that.

**Comment by thymikee** [comment]
Thank you very much for participating in this and have it sorted, we can close this now :)

**Comment by kadikraman** [comment]
Thanks for your help! 🙌
