### ISSUE TITLE
Use `xed ios` for opening Xcode instructions after `init`

### ISSUE THREAD

**Issue by thymikee** [react-native-community/cli#452]
## Describe the Feature

We can point users to using `xed -b ios` to open Xcode project after running init (legacy and new one). https://twitter.com/lbentosilva/status/1143055879664783360?s=20

The `-b` flag is added for opening Xcode in the background, so it doesn't block the terminal session.

cc @lucasbento

**Comment by lucasbento** [comment]
Where would this be best placed? Maybe [printRunInstructions.js](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/init/printRunInstructions.js)?

**Comment by thymikee** [comment]
We could adjust this line:
https://github.com/react-native-community/cli/blob/f6b546e83a3b51711f48fe320e1ea5d454019c8c/packages/cli/src/commands/init/printRunInstructions.js#L34

To say:

```
• Open ${relativeXcodeProjectPath} in Xcode or run "xed -b ios"
```

However, now that I think of it, cmd+press on the xcode project path is easier than running a command, it's good to know though.

**Comment by lucasbento** [comment]
Agreed :)

**Comment by princiya** [comment]
Is this taken? I would like to work on this.

**Comment by thymikee** [comment]
@princiya feel free to take it, but please think about users, especially new ones, as I don't expect experienced RN devs to read this (not every time anyway). If you have ideas on how to make the message more approachable and less confusing, that's very welcome!

**Comment by princiya** [comment]
@thymikee thank you. will look into it.

**Comment by thymikee** [comment]
@princiya ping. Do you need any help?

**Comment by princiya** [comment]
@thymikee I am on it, sorry it's taking a lot more time. I need help in getting more time for myself :) Is this like a time critical issue, then I might free this one for someone else. If not, I will see if I can push some changes by the end of this weekend.

**Comment by Taym95** [comment]
I can take care of this issue!
