### ISSUE TITLE
Command "react-native config" in native_moduless.gradle throws error

### ISSUE THREAD

**Issue by jenbuzz** [react-native-community/cli#465]
## Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 5.47 GB / 15.88 GB
Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
    Android Studio: Version  3.0.0.0 AI-171.4443003

## Description

After changes react-native config command it is no longer possible to execute "react-native run-android" in Windows. See the following commit that caused the error: https://github.com/react-native-community/cli/commit/023360b5750845d44a21cceceaa91ac67275cbb2#diff-375026a0607eb034a6fc70cca7d74689)

File: @react-native-community\cli-platform-android\native_modules.gradle

After removing 'node' from command it works again.

`def command = "./node_modules/.bin/react-native config"`

**Comment by thymikee** [comment]
Fix incoming: https://github.com/react-native-community/cli/pull/464

**Comment by jenbuzz** [comment]
Awesome. Thanks for the quick fix.
