### ISSUE TITLE
Run tests on a Windows CI

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/cli#471]
## Describe the Feature

The CLI should run tests automatically for each PR (and `master` push) on Windows to be sure that future releases work well on that platform.

## Possible Implementations

We can configure [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) for that, it seems to be pretty straightforward.

**Comment by theweavrs** [comment]
@thymikee should be closed...

**Comment by thymikee** [comment]
Yep! It's working now thanks to you :)
