### ISSUE TITLE
Manual linking of packages is not working

### ISSUE THREAD

**Issue by mehulmpt** [react-native-community/cli#473]
## Environment

```
info Fetching system and libraries information...
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
    Memory: 87.27 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Description

Auto linking of FBSDKPackage fails with the message

```
constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types;
      new FBSDKPackage(),
      ^
  required: CallbackManager
  found: no arguments
```

which makes sense because earlier I was passing a callback manager when initializing this. So I try to manually link it using 

```
List<ReactPackage> packages = new PackageList(this).getPackages();
			// Packages that cannot be autolinked yet can be added manually here, for example:
			packages.add(new FBSDKPackage(mCallbackManager));
			return packages;
```

But the exact same error (i.e. no arguments passed) is still there. It seems like my manually linked package is not picked up and like I’m missing something with Manual linking part. What is it?

## Reproducible Demo

Just try to manually link FBSDKPackage in react native android platform

**Comment by mehulmpt** [comment]
Okay I just found this commit ( https://github.com/facebook/react-native-fbsdk/commit/321923e800f03c41b9c0c2802ee6e529af4024e2 ) which removes the need for passing a callback manager to the constructor which makes it work with autolink. But I’m still curious about how I could make the previous version work with manual linking.

**Comment by thymikee** [comment]
Are you sure you recompiled your project, maybe clean as well?

Anyway, use the 1.0.0-rc.4 of fbsdk or higher, it works with autolinking
