### ISSUE TITLE
Consuming lot of RAM : Continous increase in RAM consumption

### ISSUE THREAD

**Issue by Rishabh-Rathod** [react-native-community/cli#477]
## Environment

System:
OS: Linux 4.15 Ubuntu 18.04 LTS (Bionic Beaver)
CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Memory: 3.42 GB / 7.65 GB
Shell: 4.4.19 - /bin/bash
Binaries:
Node: 12.5.0 - /usr/bin/node
npm: 6.10.0 - /usr/bin/npm
Watchman: 4.9.0 - /home/linuxbrew/.linuxbrew/bin/watchman
npmPackages:
react: 16.8.6 => 16.8.6
react-native: 0.60.0 => 0.60.0
npmGlobalPackages:
react-native-cli: 2.0.1
## Reproducible Demo

    go to the project root folder
    run "react-native start"

**Comment by thymikee** [comment]
Please send a detailed report. We haven't observed issues with memory yet. Pointing to some numbers, how it worked previously, etc will be helpful. For now I'm closing the issue, because it's not actionable. Happy to reopen, once you spent some time investigating what's happening.

**Comment by Rishabh-Rathod** [comment]
Detailed reported including what ?
Well i tried downgrading my node version to 10.x and now it works fine.

**Comment by thymikee** [comment]
We track it here now: https://github.com/react-native-community/cli/issues/485
