### ISSUE TITLE
A broken link on a warning about "rnpm"

### ISSUE THREAD

**Issue by ddzirt** [react-native-community/cli#486]
## Description

Add appcenter to fresh RN project using 0.60 and run:
```
npm start
```

you will get:
<img width="698" alt="Screen Shot 2019-07-05 at 15 17 56" src="https://user-images.githubusercontent.com/973562/60727896-afa79280-9f47-11e9-9203-423f7bef40dd.png">

where is link after "You can find more details at" is broken:
<img width="734" alt="Screen Shot 2019-07-05 at 15 21 04" src="https://user-images.githubusercontent.com/973562/60727938-ce0d8e00-9f47-11e9-921c-6bfe5b0fb8a6.png">

**Comment by thymikee** [comment]
The link is fixed in `v2.1.0`. Please update `@react-native-community/cli` entry in you lock file (remove it and run install again)
