### ISSUE TITLE
Avoid using absolute path for podspec for version control

### ISSUE THREAD

**Issue by jpolo** [react-native-community/cli#488]
## Environment

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Memory: 88.32 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /var/folders/78/3_1gd4qx1gj_qtw62hhywmtm0000gn/T/yarn--1562337540193-0.22427215859470917/node
    Yarn: 1.16.0 - /var/folders/78/3_1gd4qx1gj_qtw62hhywmtm0000gn/T/yarn--1562337540193-0.22427215859470917/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.0, 26.0.1, 26.0.3, 27.0.3, 28.0.3
      System Images: android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.1.0 => 2.1.0
    react: 16.8.6 => 16.8.6
    react-native: 0.59.9 => 0.59.9
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description

The pod lock file created by iOS autolinking saves absolute file references (ex: `/Users/MyUser/MyProject/node_modules/react-native-lib`)

Using relative paths to the root is better because they are portable and versionable ( the example should be `../node_modules/react-native-lib`)

**Comment by thymikee** [comment]
Would you like to send a PR with this improvement? :) We'll need to make changes to this file: https://github.com/react-native-community/cli/blob/master/packages/platform-ios/native_modules.rb

**Comment by jpolo** [comment]
I have to confess that I am not quite fluent in Ruby language.
I'll wait a few days and if nobody react to this issue for help, I'll try and tinker a fix.

**Comment by maciejsimka** [comment]
if this one's not taken, I'd be happy to try ;)

**Comment by jpolo** [comment]
Thanks @maciejsimka ! I looked at your solution to learn some Ruby.
As I understand the code does not seems portable to systems with folder separator than Unix (i.e. Windows).
Is that a problem ? (The real question behind that, is does react native cli officially supports Windows?)

**Comment by thymikee** [comment]
@jpolo iOS project is only available for development on macOS, so no Windows there. Windows is supported by the CLI. We're working on making sure we don't break things there, but it can take some time. If you'd like to help: #471

**Comment by jpolo** [comment]
@thymikee You're right, the ruby part is only for iOS platform, so there is no problem...
