### ISSUE TITLE
react-native eject in latest version

### ISSUE THREAD

**Issue by ajfick** [react-native-community/cli#503]
With the new release which coincides with React Native 0.60, the `react-native eject` command has been removed. Is there any replacement for `react-native eject`? 

If for some reason I need to remove and recreate the Android or iOS directories, there is now no simple way to recreate those from what I can tell. Having the eject command or something similar would be very useful.

**Comment by thymikee** [comment]
cc @Esemesek

**Comment by thymikee** [comment]
Here's the diff that removed `eject`: https://github.com/react-native-community/cli/pull/275. Feel free to create a [custom plugin](https://github.com/react-native-community/cli/blob/master/docs/plugins.md) for that if you care about this functionality :)

**Comment by ugursogukpinar** [comment]
+1

**Comment by ajfick** [comment]
@thymikee I will look into that! Thanks!

**Comment by liftyourgame** [comment]
Plugin does not work
https://github.com/ramyareye/react-native-eject/issues/1

**Comment by Ankit199** [comment]
not able to regenerate android folder in react native app 0.61.5 version

**Comment by Ankit199** [comment]
https://www.npmjs.com/package/react-native-eject  
this plugin also not working
