### ISSUE TITLE
Missing resource file

### ISSUE THREAD

**Issue by AnOptimistSeePessimist** [react-native-community/cli#508]
## Ask your Question
my english is not very good....

Missing resource file. please help me, thanks.

![IMG_1363](https://user-images.githubusercontent.com/27407218/60854876-5041cf00-a234-11e9-993d-2137b0321a25.JPG)
![QQ截图20190709095619](https://user-images.githubusercontent.com/27407218/60854882-520b9280-a234-11e9-8fd3-1b9d5e3a6252.png)
![QQ截图20190709102650](https://user-images.githubusercontent.com/27407218/60854984-9eef6900-a234-11e9-8bfd-248954c2ef25.png)

**Comment by wizebin** [comment]
Please refer to the library you are trying to use:
https://github.com/oblador/react-native-vector-icons/

This has nothing to do with the react native cli

**Comment by thymikee** [comment]
Autolinking doesn't support copying assets yet. You need to manually link assets for `react-native-vector-icons`. Please run `react-native link` after running `pod install` – this will trigger linking of assets on both platforms.
