### ISSUE TITLE
Issue in React native Version 0.60 ->null is not an object ( evaluating 'RNGestureHandlerModule.Direction') 

### ISSUE THREAD

**Issue by Rahish** [react-native-community/cli#512]
## Environment
info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 70.09 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.3.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description

Hi,
I'm using react-native-gesture-handler within react-navigation and getting this error

null is not an object ( evaluating 'RNGestureHandlerModule.Direction')

Workspace file is automatically created with new React native version(0.60). And there is no libraries under libraries folder in Xcode project.

## Reproducible Demo

I created new project in react native and new project created with react-native version 0.60 automatically. Then I installed following dependencies

- npm install —save react-navigation
- npm install —save react-native-gesture-handler

After installing I am getting runtime error

 null is not an object ( evaluating 'RNGestureHandlerModule.Direction') 

I also tried to manually link react-native-gesture-handler dependencies with following steps

1. Right Click Libraries "Add Files to Project"
2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
3. Go to build phases and add libRNGestureHandler.a
4. Run

After that I am getting following errors

-> <React/RCTEventDispatcher.h> File not found
-> <React/RCTBridge.h> File not found

Any suggestion for me to fix this?

**Comment by thymikee** [comment]
Unlink your project for iOS and make sure to run `pod install`, because you're now in Xcode Workspace with CocoaPods. Please see my comment with detailed instructions on what to do: https://github.com/kmagiera/react-native-gesture-handler/issues/671#issuecomment-508903588

**Comment by kqzh** [comment]
> ## Environment
> info Fetching system and libraries information...
> System:
> OS: macOS 10.14.5
> CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
> Memory: 70.09 MB / 16.00 GB
> Shell: 3.2.57 - /bin/bash
> Binaries:
> Node: 12.3.1 - /usr/local/bin/node
> Yarn: 1.16.0 - /usr/local/bin/yarn
> npm: 6.9.0 - /usr/local/bin/npm
> Watchman: 4.9.0 - /usr/local/bin/watchman
> SDKs:
> iOS SDK:
> Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
> IDEs:
> Xcode: 10.2/10E125 - /usr/bin/xcodebuild
> npmPackages:
> react: 16.8.6 => 16.8.6
> react-native: 0.60.0 => 0.60.0
> npmGlobalPackages:
> react-native-cli: 2.0.1
> 
> ## Description
> Hi,
> I'm using react-native-gesture-handler within react-navigation and getting this error
> 
> null is not an object ( evaluating 'RNGestureHandlerModule.Direction')
> 
> Workspace file is automatically created with new React native version(0.60). And there is no libraries under libraries folder in Xcode project.
> 
> ## Reproducible Demo
> I created new project in react native and new project created with react-native version 0.60 automatically. Then I installed following dependencies
> 
> * npm install —save react-navigation
> * npm install —save react-native-gesture-handler
> 
> After installing I am getting runtime error
> 
> null is not an object ( evaluating 'RNGestureHandlerModule.Direction')
> 
> I also tried to manually link react-native-gesture-handler dependencies with following steps
> 
> 1. Right Click Libraries "Add Files to Project"
> 2. /node_modules/react-native-gesture-handlers/ios/RNGestureHandler.xcodeproj
> 3. Go to build phases and add libRNGestureHandler.a
> 4. Run
> 
> After that I am getting following errors
> 
> -> <React/RCTEventDispatcher.h> File not found
> -> <React/RCTBridge.h> File not found
> 
> Any suggestion for me to fix this?

I met the same problem of you , how did you solve this problem later?
