### ISSUE TITLE
Autolinking example apps

### ISSUE THREAD

**Issue by ShaMan123** [react-native-community/cli#518]
## Autolinking example apps
How do I run an example app from within a library I'm developing?
Formerly it was done using `metro.config.js` and manual linking.
How can I do it with `autolinking`?

I tried configuring `react-native.config.js` and got this error on android:
`Multiple projects in this build have project directory`

It is very unclear how to configure projects/dependencies using `react-native.config.js`

Thanks

<details>
<summary>

`example/react-native.config.js`
</summary>

```js
module.exports = {
    // config for a library is scoped under "dependency" key
    dependencies: {
        'lib-in-dev': {
            root: '..',
            platforms: {
                android: {
                    sourceDir: '../android'
                }
            }
        }
    },
};


```
</details>

**Comment by thymikee** [comment]
Please see https://github.com/react-native-community/react-native-slider/

How can we make it easier for you in the documentation? It's here: https://github.com/react-native-community/cli/blob/master/docs/dependencies.md

The naming is confusing and we definitely need to think about it more.

**Comment by thymikee** [comment]
Also the Migration Guide may be helpful to get a grasp of the config: https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide

**Comment by ShaMan123** [comment]
tried the migration guide.
It seems `react-native-slider` does not have a standalone example app

**Comment by thymikee** [comment]
Isn't it? https://github.com/react-native-community/react-native-slider/tree/master/example

**Comment by ShaMan123** [comment]
don't think so.
but it seems there's a bug regarding path resolution that `react-native-slider/react-native.config.js` works around successfully using `process.cwd()`

**Comment by thymikee** [comment]
It's not a bug, it's how we tell the CLI where to look for a local package. You're also expected (at least for now) to run the CLI from the root of your project, hence tricks like this one are needed: https://github.com/react-native-community/react-native-slider/blob/master/package.json#L15

**Comment by ShaMan123** [comment]
This must be documented. So to my understanding it is good practice to specify absolute paths.

**Comment by thymikee** [comment]
It's documented here: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-autolink-a-local-library

If you have ideas on how to make it all a bit more approachable, please send a PR!

**Comment by ShaMan123** [comment]
This works for me:

`example/react-native.config.js`

```js

const root = path.resolve(__dirname, '..');
const config = require('../react-native.config');

module.exports = {
    dependencies: {
        'lib-in-dev': {
            root,
            ...config.dependency
        }
    },
};

```

**Comment by thymikee** [comment]
Do you really need the `...config.dependency`? What's inside?

**Comment by ShaMan123** [comment]
I do 'cause it doesn't read the root config file for some reason.

בתאריך יום ה׳, 11 ביולי 2019, 13:36, מאת Michał Pierzchała ‏<
notifications@github.com>:

**Comment by ShaMan123** [comment]
I think I found the reason.
when specifying `platform.android.folder | platform.android.sourceDir` config read fails

**Comment by ShaMan123** [comment]
You are right, no need ` ...config.dependency`.
The problem was caused by `platform.android.folder & platform.android.sourceDir` in the library's `react-native.config.js` file

```js

const root = path.resolve(__dirname, '..');

module.exports = {
    dependencies: {
        'lib-in-dev': {
            root,
        }
    },
};

```

**Comment by rardoz** [comment]
Just for feedback - based off of reading the documentations this is what I ended up with which doesn't work. Reading some info up above I'm sure I can work this out. Having a few complete examples of some use cases for ios and android customizations would be great. ```js

const android = require('@react-native-community/cli-platform-android')

module.exports = {
  project: {
    android: {
      sourceDir: '/apps/mobile',
      linkConfig: android.linkConfig,
      projectConfig: android.projectConfig,
      dependencyConfig: android.dependencyConfig,
    },
  },
}

```

**Comment by thymikee** [comment]
You don't need to import anything to your config. See https://github.com/react-native-community/cli/issues/1137 for details on what's needed for setup with and without yarn workspaces. 

@rardoz I'd be grateful for documenting this, I encourage you to contribute :)
