### ISSUE TITLE
Make it easier to use libraries which don't support autolinking

### ISSUE THREAD

**Issue by satya164** [react-native-community/cli#521]
Maybe we could improve the experience when using libraries which don't support autolinking and/or android x.

This can involve as little as detecting if a library uses old support libraries and showing a warning with instructions on how to use `jetifier`. Similar for autolinking (we could have a list of libraries/support some key in `package.json` to allow a library to say if it can be autolinked).

Another idea is to include `jetifier` in the RN template temporarily during the migration period. It doesn't seem have any downsides and will improve the UX.

**Comment by thymikee** [comment]
> Another idea is to include jetifier in the RN template temporarily during the migration period. It doesn't seem have any downsides and will improve the UX.

Like it. I think it proved to be a good tool. Can you send a PR to `react-native`? That's where the template lives.

> Similar for autolinking (we could have a list of libraries/support some key in package.json to allow a library to say if it can be autolinked).

If we ever gonna do that, I'd go with a list of unsupported libraries that we know of (like appcenter and gesture-handler). I'm hesitating, because it will cause these libraries to migrate later (I know that appcenter is working hard on being compatible though, but no signs from RNGH)

**Comment by satya164** [comment]
What do you think about a key in `package.json` to tell the CLI that it shouldn't try to autolink a library?

**Comment by thymikee** [comment]
They can control it by publishing with `react-native.config.js` that disables autolinking. However that's buggy and I'd like to work on that – seems like a good path forward.

**Comment by thymikee** [comment]
AndroidX is tackled here: https://github.com/react-native-community/cli/pull/526

**Comment by grabbou** [comment]
Right now, a library can disable link entirely. That said, not just auto-linking.

What kind of libraries do not support autolinking, except for CocoaPods-less iOS projects? I'd like to better understand this use case.

**Comment by RioFiveJack** [comment]
hi, i would like to ask if it's possible to override package's `react-native.config.js` ? sometimes i want to have different packages constructor for my app ?

**Comment by thymikee** [comment]
@RioFiveJack https://github.com/react-native-community/cli/blob/master/docs/dependencies.md#platformsandroidpackageinstance

**Comment by RioFiveJack** [comment]
@thymikee thanks for quick reply , i've read it before, but could i put on my project folder and override node_modules packages setting ? if the package also have `react-native.config.js`

**Comment by thymikee** [comment]
Your root config will override the package's one.

**Comment by grabbou** [comment]
Can we get an example of a library that doesn't support autolinking here to have a good testing environment?

**Comment by thymikee** [comment]
@grabbou https://github.com/Tealium/tealium-react-native

**Comment by thymikee** [comment]
I think most of the community caught up already and this is not an issue anymore.
