### ISSUE TITLE
Possibility to prevent autolinking for a module?

### ISSUE THREAD

**Issue by RobTS** [react-native-community/cli#523]
I have a module that I only need for iOS and would prefer not to have imported on android, with the recent 0.60.0 changes, all that I seem to be able to do to prevent this is removing the module from package.json temporarily. 

Is there a better way to do this already, or are you planning to support some form of exceptions?

**Comment by thymikee** [comment]
Here you go: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
