### ISSUE TITLE
CLI completion message for iOS requires an extra path element

### ISSUE THREAD

**Issue by orta** [react-native-community/cli#524]
## Environment

N/A

## Description

First off, love this messaging!

<img width="870" alt="Screen Shot 2019-07-12 at 9 49 57 AM" src="https://user-images.githubusercontent.com/49038/61132950-6e087180-a48a-11e9-8c3f-638a99055ac4.png">

This line

>    Open ios/AwesomeProject.xcworkspace in Xcode or run "xed -b iOS"

Should probably not make the assumption you're in your root dir because none of the others do.

**Comment by thymikee** [comment]
Good catch. Do you think we should make it an absolute path, or prepend project name?

**Comment by orta** [comment]
project name IMO, ideally all of them have that

**Comment by thymikee** [comment]
I'm a fan of that. We tried that earlier with @Esemesek but failed with the implementation. Should be easier now.

**Comment by Taym95** [comment]
I will take care of this issue.
