### ISSUE TITLE
warn and exit when `xcrun` is not installed

### ISSUE THREAD

**Issue by sw-yx** [react-native-community/cli#528]
## Description

i have cocoapods installed
![image](https://user-images.githubusercontent.com/6764957/61161346-6b7d3a80-a4d1-11e9-8c51-519f32a277b0.png)

but the cli thinks i dont
![image](https://user-images.githubusercontent.com/6764957/61161361-7932c000-a4d1-11e9-9651-8f8b0945a851.png)

i think this is because i have an implicit dependency on xcode and i didnt know i needed it

![image](https://user-images.githubusercontent.com/6764957/61161401-92d40780-a4d1-11e9-92a4-5dfbb555eda3.png)

we should detect this first and prompt

**Comment by sw-yx** [comment]
furthermore, i've been using xcode 11 beta, and it looks like i need xcode 10 so i am downgrading.

**Comment by sw-yx** [comment]
output of `git -v`:

![image](https://user-images.githubusercontent.com/6764957/61161871-eb0c0900-a4d3-11e9-9c6c-fa670f6f2d6b.png)

**Comment by thymikee** [comment]
We can print the error output when it's failing. Would that help?

**Comment by sw-yx** [comment]
yes! would be better than what i suggested.

**Comment by grabbou** [comment]
We should also add this to `doctor`.
