### ISSUE TITLE
config file read fails

### ISSUE THREAD

**Issue by ShaMan123** [react-native-community/cli#529]
## Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.23 GB / 7.87 GB
  Binaries:
    Node: 8.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

## Description
when specifying `dependency.platforms.android.folder | dependency.platforms.android.sourceDir` config read fails

related to #518

**Comment by thymikee** [comment]
It's platforms (plural), not platform: https://github.com/react-native-community/cli/blob/master/docs/dependencies.md#platforms

**Comment by ShaMan123** [comment]
It's a typo that doesn't exist in the config file.

**Comment by thymikee** [comment]
Can you send a repro we can download and investigate?

**Comment by thymikee** [comment]
I cannot repro. Setting `sourceDir` works just fine:

```js
module.exports = {
  dependency: {
    platforms: {
      android: {
        sourceDir: 'android',
        packageImportPath: 'import io.autodidact.rnmathview.RNMathViewPackage;',
      },
    },
  },
};
```
As a result I can see the output in `react-native config` run from package that imports `react-native-math-view`:
<img width="564" alt="Screenshot 2019-07-16 at 12 25 23" src="https://user-images.githubusercontent.com/5106466/61287298-dd50cf00-a7c4-11e9-8238-a25a8dc48a98.png">

FYI, folder is not configurable, as per https://github.com/react-native-community/cli/blob/5199d6af1aa6dc5d8dfb4a98e675987272d68998/docs/dependencies.md#platforms

**Comment by ShaMan123** [comment]
Documentation is rather confusing.
But none the less `autolinking` is a major step forward!
Thanks for the follow up

**Comment by thymikee** [comment]
@ShaMan123 psst, we accept PRs to improve the docs 😉 it's a joined effort and every contribution counts.
