### ISSUE TITLE
Can't upgrade from 0.59.9 to 0.60.0 with `react-native upgrade`

### ISSUE THREAD

**Issue by maximedupre** [react-native-community/cli#531]
React Native version:

    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
      Memory: 2.94 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.6.0 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

## Steps To Reproduce

`react-native upgrade 0.60.0 --verbose`

	info Fetching diff between v0.59.9 and v0.60.0...
	error Cannot read property 'toLowerCase' of undefined
	debug TypeError: Cannot read property 'toLowerCase' of undefined
		at getPatch (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:108:121)
		at process.internalTickCallback (internal/process/next_tick.js:77:7)

I tried deleting my node_modules, package-lock.json and re-installing everything, but it didn't change anything.

Btw, do I need to add `@react-native-community/cli` in my package.json, or is it bundled with react-native?

**Comment by maximedupre** [comment]
Ah...it seems I needed to install @react-native-community/cli. Perhaps an old version is bundled with react-native?

**Comment by thymikee** [comment]
Here's how to update the CLI to the latest version compatible with your RN version: https://github.com/react-native-community/cli#updating-the-cli. You can also use a standalone using `npx @react-native-community/cli`, no need to install it as a dependency.

**Comment by maximedupre** [comment]
The upgrade process from my working application on `v0.59.9` to `v0.60.0` does not work.

Running `npx @react-native-community/cli upgrade 0.60.3` produces the following output:

	info Fetching diff between v0.59.9 and v0.60.3...
	info Applying diff...
	warn Excluding files that exist in the template, but not in your project:
	- App.js
	error Excluding files that failed to apply the diff:
	- .gitignore
	- android/app/build.gradle
	- android/app/src/main/java/com/awesomeproject/MainApplication.java
	- android/settings.gradle
	- ios/AwesomeProject.xcodeproj/project.pbxproj
	- ios/AwesomeProject/Info.plist
	Please make sure to check the actual changes after the upgrade command is finished.
	You can find them in our Upgrade Helper web app: https://react-native-community.github.io/upgrade-helper/?from=0.59.9&to=0.60.3
	info Installing "react-native@0.60.3" and its peer dependencies...
	info Running "git status" to check what changed...
	On branch master
	Your branch is up to date with 'origin/master'.

	Changes to be committed:
	(use "git reset HEAD <file>..." to unstage)

			new file:   .eslintrc.js
			modified:   .flowconfig
			modified:   android/app/proguard-rules.pro
			modified:   android/app/src/main/res/values/styles.xml
			modified:   android/build.gradle
			modified:   android/gradle.properties
			deleted:    android/keystores/BUCK
			deleted:    android/keystores/debug.keystore.properties
			modified:   ios/AwesomeProject-tvOS/Info.plist
			new file:   ios/AwesomeProject.xcworkspace/contents.xcworkspacedata
			new file:   ios/Podfile
			new file:   ios/Podfile.lock
			modified:   package-lock.json
			modified:   package.json

	success Upgraded React Native to v0.60.3 🎉. Now you can review and commit the changes

It seems like it failed, but then succeeded?

Anyway, when I run the app on my iphone using `npm start`:

	Looking for JS files in
	/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe 

	Loading dependency graph, done.
	error: bundling failed: Error: Unable to resolve module `metro/src/lib/bundle-modules/HMRClient` from `/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/react-native/Libraries/Utilities/HMRClient.js`: Module `metro/src/lib/bundle-modules/HMRClient` does not exist in the Haste module map

	This might be related to https://github.com/facebook/react-native/issues/4968
	To resolve try the following:
	1. Clear watchman watches: `watchman watch-del-all`.
	2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
	3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
	4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
		at ModuleResolver.resolveDependency (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
		at ResolutionRequest.resolveDependency (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
		at DependencyGraph.resolveDependency (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
		at Object.resolve (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/lib/transformHelpers.js:264:42)
		at dependencies.map.result (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
		at Array.map (<anonymous>)
		at resolveDependencies (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
		at /Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
		at Generator.next (<anonymous>)
		at asyncGeneratorStep (/Users/maximedupre/Desktop/Dropbox/Programming/iphone-app/fe/node_modules/@react-native-community/cli/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

I tried the 4 steps to resolve the issue, but they had no effect. 

[I also tried upgrading manually](https://react-native-community.github.io/upgrade-helper/?from=0.59.9&to=0.60.3), but the result was the same.

I also tried unlinking the two external libraries I use:

    react-native unlink @react-native-community/async-storage
    react-native unlink react-native-vector-icons

But still no success.

**Comment by thymikee** [comment]
@maximedupre this is completely different issue. Please open a new one. The upgrade command should return failure, indeed.
