### ISSUE TITLE
Metro Bundler doesn't start and consumes a lot of memory

### ISSUE THREAD

**Issue by Inovassist-dev** [react-native-community/cli#545]
## Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
    Memory: 2.43 GB / 7.89 GB
  Binaries:
    Node: 12.6.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Users\xades\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: 4.9.4 - C:\Users\xades\Documents\watchman\watchman.EXE
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

## Description

When I start my Metro Bundler with `react-native start` it gets stuck on "Loading Dependency Graph..." and starts to consume a lot of memory...

![image](https://user-images.githubusercontent.com/52457875/61325760-c4a7df80-a7eb-11e9-8f6a-09cf56a8091c.png)

![memory](https://user-images.githubusercontent.com/52457875/61325946-2ff1b180-a7ec-11e9-97e1-987f7e1c53ff.png)

## Reproducible Demo

This happens in every project I start in the latest version...

**Comment by Esemesek** [comment]
This is probably an issue with `metro` bundler. What version of `react-native` do you use? Was this issue happening with older versions of `react-native`?

**Comment by thymikee** [comment]
Known issue with latest Node https://github.com/react-native-community/cli/issues/485#issuecomment-509210382

**Comment by umuterc** [comment]
I have the same problem when i write react-native run-android it starts and in the middle of the proccess it stucks and using a lot of memory and then i cant even use my mouse my whole computer stucks.Could you find a solution?

**Comment by Inovassist-dev** [comment]
After downgrading Node to the latest stable version fixed for me...
Can you run run-android command in verbose mode to see if something pops out?

**Comment by umuterc** [comment]
Thank you i changed the version to v10.16.2.It is fixed.

**Comment by Inovassist-dev** [comment]
You're welcome! 😉

**Comment by yevhenii-bilyk** [comment]
@Inovassist-dev Thank you!
