### ISSUE TITLE
Disable sourcemap generation for release build

### ISSUE THREAD

**Issue by gShrey** [react-native-community/cli#549]
## Disable sourcemap generation for release build

Is there any argument to disable sourcemaps? We have js bundle size of 2mb and sourcemap size if around half mb. Disabling sourcemap can help in optimizing apk size further.

**Comment by thymikee** [comment]
Have you tried https://github.com/react-native-community/cli/blob/master/docs/commands.md#--sourcemap-output-string ?

**Comment by Titozzz** [comment]
Related to https://github.com/facebook/react-native/issues/25693#issuecomment-512723607.

**Comment by thymikee** [comment]
Fixed upstream
