### ISSUE TITLE
Cannot resolve symbol 'Main Application' - Android React Native

### ISSUE THREAD

**Issue by sandeepperkariappdev** [react-native-community/cli#558]
## Environment
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 42.71 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^2.6.0 => 2.6.2 
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3

## Description

1. Created a new react-native application, application was running fine in  Android
2. Added 3 dependencies 
    "appcenter": "^2.1.0",
    "appcenter-analytics": "^2.1.0",
    "appcenter-crashes": "^2.1.0",
3. Gradle build is sucessfull
4. Running the app fails with the following error - "Cannot resolve symbol MainApplication" in PackageList.java. Below is the code from PackageList.java file 

   new AppCenterReactNativePackage(MainApplication.this),
      new AppCenterReactNativeAnalyticsPackage(MainApplication.this, getResources().getString(R.string.appCenterAnalytics_whenToEnableAnalytics)),
      new AppCenterReactNativeCrashesPackage(MainApplication.this, getResources().getString(R.string.appCenterCrashes_whenToSendCrashes))

5. Below is the build output 

PackageList.java |  
-- | --
error: cannot find symbol class MainApplication |  
error: cannot find symbol variable appCenterAnalytics_whenToEnableAnalytics |  
error: cannot find symbol variable appCenterCrashes_whenToSendCrashes |  

6. Does any one out there facing this error, Can you help me out ?

## Reproducible Demo

1. Create a new React-Native project using React-Native CLI using the configuration mentioned above
2. Build and run the application
3. Add the below dependencies  to the project using npm or yarn
  "appcenter": "^2.1.0",
    "appcenter-analytics": "^2.1.0",
    "appcenter-crashes": "^2.1.0",
4. Below is my package.json file 
{
  "name": "RN603",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "appcenter": "^2.1.0",
    "appcenter-analytics": "^2.1.0",
    "appcenter-crashes": "^2.1.0",
    "react": "16.8.6",
    "react-native": "0.60.3"
  },
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "@babel/runtime": "^7.5.4",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.0.1",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by thymikee** [comment]
Hey! This happens because appcenter doesn't support autolinking yet. 

See my comment in appcenter repo on how to make it work: https://github.com/microsoft/appcenter-sdk-react-native/issues/613#issuecomment-512152876
