### ISSUE TITLE
Unrecognised font family - React Native 0.60.4

### ISSUE THREAD

**Issue by leech74** [react-native-community/cli#562]
I created a new project with react native 0.60.4 and found out rnpm is deprecated. I follow instruction to migrate to react-native.config.js but still getting error with 'Unrecognised font family'. Following is my react-native.config.js: 
module.exports = {
  project: {
    ios: {},
    android: {}, // grouped into "project"
  },
  	assets: ['./assets/fonts'], // stays the same
  };

**Comment by thymikee** [comment]
Now you need to run `yarn react-native link` to link assets

**Comment by leech74** [comment]
O thank you. I thought auto linking works for assets too. It is working now.

**Comment by Ravi448** [comment]
I am facing same issue in RN 0.60.4
I have tried `react-native link` & `yarn react-native link` both, but none of these are working.

My config file is ::
```javascript
module.exports = {
    dependency: {
      assets: ['./Source/Resources/Fonts/']
    },
  };
```

Please help 🆘

**Comment by Ravi448** [comment]
got the mistake,

Config should look like ::
```javascript
module.exports = {
      assets: ['./Source/Resources/Fonts/']
  };
```
###### Instead of 

```javascript
module.exports = {
    dependency: {
      assets: ['./Source/Resources/Fonts/']
    },
  };
```

This should be mentioned in the doc.
And both ```react-native link``` & ```yarn react-native link``` work fine
