### ISSUE TITLE
Could not open development server on Apple_Terminal

### ISSUE THREAD

**Issue by superchenwb** [react-native-community/cli#564]

**Comment by superchenwb** [comment]
## Environment

info Fetching system and libraries information...
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 3.50 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description
Could not open to development server. Because My terminal's name is Apple_Terminal.

I need to specify execution 'react-native run-android  --terminal=terminal'
it is work!

**Comment by sinodko** [comment]
same problem

**Comment by thymikee** [comment]
Closed via #601, published in v2.8.1
