### ISSUE TITLE
[PROPOSAL] allow custom package path to MainActivity

### ISSUE THREAD

**Issue by usrbowe** [react-native-community/cli#575]
## Describe the Feature
Add `--companyName` to set enable customise path to MainActivity. 

## Example
rn-cli will try to launch activity from: `com.packagename.dev/com.packagename.MainActivity`,
but actual activity is here: `com.companyname.app.dev/com.packagename.MainActivity`

**Comment by thymikee** [comment]
You can configure this through `project` config option: https://github.com/react-native-community/cli/blob/master/docs/projects.md#project-1, the thing you look to change is `packageName`.

**Comment by usrbowe** [comment]
> For reference, example config:
```react-native.config.js
module.exports = {
  project: {
    android: {
      packageName: 'companyname.app',
    },
  },
  dependencies: {},
};

```

**Comment by thymikee** [comment]
Thanks for sharing :) FYI, you don't have to declare `dependencies` if they're empty

**Comment by usrbowe** [comment]
@thymikee actually in my case, there should be an option to just override the `packageName` for MainActivity path, otherwise it will fail to `import companyname` during `compileJavaWithJavaC`, which doesn't exist.

**Comment by thymikee** [comment]
I think you could also play with `sourceDir` option, but not sure about that

Also, why would you have multiple MainActivity.java files? It's preferred to use variants (with `--variant` flag) to distinguish builds.

**Comment by usrbowe** [comment]
Ok, so basically I just need to set `--appID`, which is entire first part of the MainActivity.
Like this `--appId=com.companyname.app.dev`

So basically to customise the launch, we can use either `--appId` which overwrites entire first part (before `/`), or just `--appIdSuffix`, which appends `packageName.{appSuffix}`.

> Example - default behavior
`com.packagename.app/com.packagename.MainActivity`

> Example - appIdSuffix='dev'
`com.packagename.app.dev/com.packagename.MainActivity`

> Example - appId='my.company.app.beta'
`my.company.app.beta/com.packagename.MainActivity`
