### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by sbkl** [react-native-community/cli#581]
## Environment

System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 327.96 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.6.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    create-react-native-app: 0.0.6
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    react-native-vector-icons: 4.2.0

## Description

After running in the terminal `react-native run-ios`, the iOS simulator opens, the terminal window for the metro bundler opens. After a while, I get the error message: "Could not connect to the development server".
I have updated @react-native-community/cli to the latest version. When running `npm list @react-native-community/cli`, I get the version 2.8.

## Reproducible Demo

With a brand new project using `react-native init MyNewProject`
Then launch simulator using `react-native run-ios`

**Comment by thymikee** [comment]
It's likely an issue with Xcode 10.3 update. Can you reboot and try again?

**Comment by sbkl** [comment]
I've been experiencing this issue before upgrading to Xcode 10.3.
Thought upgrading Xcode would have helped but not. And yes I rebooted my machine and tried again.
I've been looking for a while on the web but can't find a resolution.
Any step I could take to try to debug?

**Comment by plouh** [comment]
Are the devices in the same network?  This usually happens when iOS device is not connected to the same wifi as the computer running metro bundler.

**Comment by sbkl** [comment]
Forgot to mention. Trying to run on iOS simulator.

**Comment by oleksandr-dziuban** [comment]
@sbkl @plouh 
I have the same issue. Simulator and MacBook connected to the same network, i'm using `cli@2.8.0`.
`react-native run-ios` doesn't run development server terminal window automatically.
 `react-native run-android` works as expected. Also want to mention that this issue was reproduced on `cli@2.7.0` too, on Xcode 10.2.1 and 10.3.0. So maybe issue is in cli settings

**Comment by sbkl** [comment]
Ok found the issue. Was thinking it might be watchman related issue and wanted to use the command `brew reinstall watchman` to reinstall it. By running this command, I found an error `Error: Xcode alone is not sufficient on Mojave.
Install the Command Line Tools:
  xcode-select --install`
Looks like the command line tools for xCode was not available anymore.
I launched the command `xcode-select --install` and then reinstalled watchman just in case. It is now working!

**Comment by oleksandr-dziuban** [comment]
> xcode-select --instal

Thanks a lot, I will check this flow.

**Comment by oleksandr-dziuban** [comment]
@sbkl, Nope, still doesn't work for me as expected

**Comment by oleksandr-dziuban** [comment]
@sbkl I have deleted all cache, deleted npm and watchman cache, removed react-native-* cache, reinstalled node_modules, deleted iOS build folder and reassembling everything - still nothing
