### ISSUE TITLE
AutoLinking can generate relative paths in Podfile.lock?

### ISSUE THREAD

**Issue by wygkzqa** [react-native-community/cli#582]
## AutoLinking can generate relative paths in Podfile.lock?

I'm using `react-native-webview` on my project.  When I execute `pod install`, `Podfile.lock` looks like this

```
......
DEPENDENCIES
  - React (from `../node_modules/react-native/`)
  - react-native-webview (from `/Users/machao/Desktop/seiue-projects/c3app/node_modules/react-native-webview`)
```

That's not what I wanted. So, is there any way to generate relative paths? like `../node_modules/react-native-webview`

Thanks.

**Comment by thymikee** [comment]
Yup! Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version and you'll see relative paths.

**Comment by muthudevendra** [comment]
@thymikee Thank you for the solution. But even after I update the @react-native-community/cli my Podfile.lock still uses relative path. It happens for auto linking libraries `RNGestureHandler` and  `RNLocalize`. Any solution? 

Thanks.
