### ISSUE TITLE
Fails: react-native init helloworld --version 0.59.10

### ISSUE THREAD

**Issue by mindlapse** [react-native-community/cli#586]
## Environment
```
> react-native --version
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory
```
## Description

```react-native init helloworld --version 0.59.10```

fails with:

```
...
├─ y18n@3.2.1
└─ yargs-parser@7.0.0
Done in 7.36s.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../../tools/PackageManager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/titan/shared/tera/cloud9/tmp/tar/helloworld/node_modules/@react-native-community/cli/build/commands/install/install.js:10:46)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

```

full log: https://gist.github.com/mindlapse/625ceece338c17954e32d96497290672

## Reproducible Demo

```react-native init helloworld --version 0.59.10```

**Comment by mindlapse** [comment]
Issue appears on multiple npm versions, including npm@next and npm@5.10.0, and with node 10.16.0 (LTS)

**Comment by ekwoodrich** [comment]
Really struggling with this, experienced the same error on node v10.16.0 and node v12.7.0 with npm@6.10.0.

**Comment by mindlapse** [comment]
Affects react-native `0.59.0` to `0.59.10` that have the `"@react-native-community/cli": "^1.2.1"` dependency.

Does not impact react-native `0.60.0` and above with the `"@react-native-community/cli": "^2.0.1"` dependency.

**Comment by mindlapse** [comment]
This just started happening within the past 24 hours

**Comment by LiWeiQiangAndroid** [comment]
Same problem

react-native-cli: 2.0.1
react-native: 0.59.10

Error: Cannot find module '../../tools/PackageManager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/data/jenkins/workspace/android-test-fm/node_modules/@react-native-community/cli/build/commands/install/install.js:10:46)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

**Comment by haohongwei** [comment]
we met with the same problem.

11:10:46 internal/modules/cjs/loader.js:638
11:10:46     throw err;
11:10:46     ^
11:10:46 
11:10:46 Error: Cannot find module '../../tools/PackageManager'
11:10:46     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
11:10:46     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
11:10:46     at Module.require (internal/modules/cjs/loader.js:690:17)
11:10:46     at require (internal/modules/cjs/helpers.js:25:18)
11:10:46     at Object.<anonymous> (/node_modules/@react-native-community/cli/build/commands/install/install.js:10:46)
11:10:46     at Module._compile (internal/modules/cjs/loader.js:776:30)
11:10:46     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
11:10:46     at Module.load (internal/modules/cjs/loader.js:653:32)
11:10:46     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
11:10:46     at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by thymikee** [comment]
Gonna fix that once I have access to my workstation. In the meantime (and generally in future, global cli is unnecessary now) use npx: `npx react-native init App -- version 0.59.10`. It will use the latest cli with 0.59 template.

**Comment by mindlapse** [comment]
Thank you for the fast response!  As expected, the same issue is appearing with `npx react-native init App --version 0.59.10`

**Comment by thymikee** [comment]
Bummer, looks like npx is taking some local RN of yours instead of from network

**Comment by thymikee** [comment]
Published a fix. Can you try again?

**Comment by mindlapse** [comment]
I'm seeing the same error

**Comment by thymikee** [comment]
Does it happen with yarn?

**Comment by abhrp-hs** [comment]
Resolved this currently by forcing **v1.10.0** of the library in package.json. Working fine with node v11.0.0 and npm v6.10.0

**Comment by haohongwei** [comment]
In a computer with ubuntu,  I met with this problem.
But in a Mac, it works well.
I do not know whether it is related with computer system.

**Comment by rmariscal13** [comment]
I do not use dependecy @react-native-community/cli and i have the same problem since i have donde rm -rf node_modules > npm install.
And i have other project that do not use @react-native-community/cli either and works.
(Or almost i do not see this dependency in my package.json)

**Comment by amitme0014** [comment]
We are facing the same issue, any hacks for now to get this running? I am on linux machine, using jenkins server to build a project.

**Comment by thymikee** [comment]
Fixed in 1.11.2

**Comment by amitme0014** [comment]
thanks it worked now

**Comment by pravin-maan** [comment]
same error  delete node_modules and package-lock.json  then update package.json
"dependencies": {
    "react":"16.0.3 to 
    "react": "16.8.6",} and in scritps { "test":"jest"  } => npm install --save , expo start it's working in my code
