### ISSUE TITLE
PackageManger module not found in 1.11.1

### ISSUE THREAD

**Issue by shanmuksrinu** [react-native-community/cli#587]
## Environment

~ @react-native-community/cli@current version
internal/modules/cjs/loader.js:638

throw err;^Error: Cannot find module '../../tools/PackageManager'at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)at Function.Module._load (internal/modules/cjs/loader.js:562:25)at Module.require (internal/modules/cjs/loader.js:690:17)at require (internal/modules/cjs/helpers.js:25:18)at Object.<anonymous> (/home/shanmuk/Desktop/mountblue-repo/AwesomeProject/node_modules/@react-native-community/cli/build/commands/install/uninstall.js:10:46)at Module._compile (internal/modules/cjs/loader.js:776:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)at Module.load (internal/modules/cjs/loader.js:653:32)at tryModuleLoad (internal/modules/cjs/loader.js:593:12)at Function.Module._load (internal/modules/cjs/loader.js:585:3)solution is ...it is correct file name : node_moduels/cli/build/tools/packageManager.jsbut everywhere you required /tools/PackageManger.jsfix it.. |   | Sanmukhsrinivas GandepalliJul 25, 01:35 PDT@react-native-community/cli@current versioninternal/modules/cjs/loader.js:638throw err;^Error: Cannot find module '../../tools/PackageManager'at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)at Function.Module._load (internal/modules/cjs/loader.js:562:25)at Module.require (internal/modules/cjs/loader.js:690:17)at require (internal/modules/cjs/helpers.js:25:18)at Object.<anonymous> (/home/shanmuk/Desktop/mountblue-repo/AwesomeProject/node_modules/@react-native-community/cli/build/commands/install/uninstall.js:10:46)at Module._compile (internal/modules/cjs/loader.js:776:30)at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)at Module.load (internal/modules/cjs/loader.js:653:32)at tryModuleLoad (internal/modules/cjs/loader.js:593:12)at Function.Module._load (internal/modules/cjs/loader.js:585:3)solution is ...it is correct file name : node_moduels/cli/build/tools/packageManager.jsbut everywhere you required /tools/PackageManger.jsfix it..
## Description
EveryWhere packageManger file is required in 'PackageManger'

and correct name of the file is packageManger

## Reproducible Demo

solution is ...

it is correct file name : node_moduels/cli/build/tools/packageManager.js

but everywhere you required ../../tools/PackageManger.js

fix it..

**Comment by thymikee** [comment]
Fixed in 1.11.2, thanks for pointing me in good direction (forgot to clean the build folder before publishing)

**Comment by PomegranateApps** [comment]
How do you fix this issue?

**Comment by shanmuksrinu** [comment]
solution is ...

it is correct file name : node_moduels/cli/build/tools/packageManager.js

but everywhere you required ../../tools/PackageManger.js

fix it..
