### ISSUE TITLE
A project with custom root fails at:  cli-platform-android/native_modules.gradle' line: 191

### ISSUE THREAD

**Issue by vladp** [react-native-community/cli#591]
I am trying to upgrade to 60.4, and introduced the 'autolinking' capability by modifying my  settings.gradle and app/build.gradle.
Platform is Linux, RN platform is android only, cli is 2.8.0.

With that change, however I cannot run any gradle commands (not even gradlew clean):

bash gradlew clean
```

FAILURE: Build failed with an exception.

* Where:
Script '/home/v/myproj/mob/rn.common/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 191

* What went wrong:
A problem occurred evaluating settings 'myapp1b'.
> Cannot get property 'packageName' on null object

```

The cli version is latest, 2.8.0
The line where it is failing, trying to parse json output from running react-native-config
Line 191:
`    this.packageName = json["project"]["android"]["packageName"]`

When I run 
`PATH=$(npm bin):$PATH react-native config`

I can see that in its output  ["project"]["android" is indeed null.
```
...
"platforms": {
    "ios": {},
    "android": {}
  },
  "haste": {
    "providesModuleNodeModules": [
      "react-native"
    ],
    "platforms": [
      "ios",
      "android"
    ]
  },
  "project": {
    "ios": null,
    "android": null
  }

```

_But why, and what do I need to do to fix it?_
It seems that applyNativeModulesSettingsGradle relies on it, and that's why my build completely stopped at the moment.

### Additional info:

cat react-native.config.js   <-- this is root of my RN code. this dir also has index.android.js
```
module.exports = {
  project: {
    ios: {},
    android: {},
  },
  assets: ['./src/js.app/img'],
};

```

cat settings.gradle
```
//do  npm install @react-native-community/cli@2.8.0 --save-dev
//in case this component is not installed directly by RN

rootProject.name = 'myapp1b' //this rootProjectName used by community cli. so I am setting to be what my gradle defined as project.name (which is directory name of my proj, or equal to rootProject.name that can only be set in this file) https://discuss.gradle.org/t/rootproject-name-in-settings-gradle-vs-projectname-in-build-gradle/5704

//this whole machinery (plus a change in app/build.gradle) is used to auto generate rn-community module names so that they can, indirectly be included in to app/build.gradle so that those modules can be used

apply from:file("${rootDir}/../../rn.common/node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings,"../../rn.common/") //note second arg, this is a must because I do not have a default location of node_modules (see custom root section at: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md )

include ':app', ':lint'
include ':react-native-vector-icons'

project(':react-native-vector-icons').projectDir = file("${rootDir}/../../../mob/rn.common/node_modules/react-native-vector-icons/android")

```

I did not even have, initially, the react-native.config.js   (because it was not noted as needed in rn-diff utility) , but even after adding it -- it did not help.

appreciate in advance any guidance.

**Comment by vladp** [comment]
I fixed the problem.
Because of custom paths (I have essentially a form of mono-repo with many sub projects)
`PATH=$(npm bin):$PATH react-native config`
could not find where my root android part of the project was (it was not in standard directory relative to the JS part of the project)


I am not sure this point is covered if this nuance is convered in
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
It talks about how to tell cli, in 'custom root' configuration  ,  about the location of JS part of the project, but does not tell how to tell the cli tools about the the location of android side of the project

So all I had to do, to fix this specific problem,  is to specify sourceDir and packageName in the react-native.config.js
```

module.exports = {
  project: {
    ios: {},
    android: {
    "sourceDir": "../a/myapp1b/app/src",
    "packageName":"com.myapp1b.myapp"
    
    },
  },
  assets: ['./src/js.app/img'],
};


```

**Comment by ldco2016** [comment]
can anyone assist on how this would relate to a build in Azure DevOps, this is where I get the error:

```
FAILURE: Build failed with an exception.
 
* Where:
Script 'D:\a\1\s\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 191
 
* What went wrong:
A problem occurred evaluating settings 'NFIBEngage'.
> Text must not be null or empty
 
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 
* Get more help at https://help.gradle.org
 
BUILD FAILED in 1m 42s
Error: The process 'D:\a\1\s\android\gradlew.bat' failed with exit code 1
 at ExecState._setResult (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.155.0\node_modules\azure-pipelines-task-lib\toolrunner.js:816:25)
 at ExecState.CheckComplete (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.155.0\node_modules\azure-pipelines-task-lib\toolrunner.js:799:18)
 at ChildProcess.<anonymous> (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.155.0\node_modules\azure-pipelines-task-lib\toolrunner.js:721:19)
 at emitTwo (events.js:106:13)
 at ChildProcess.emit (events.js:191:7)
 at maybeClose (internal/child_process.js:886:16)
 at Socket.<anonymous> (internal/child_process.js:342:11)
 at emitOne (events.js:96:13)
 at Socket.emit (events.js:188:7)
```

**Comment by cmcaboy** [comment]
@ldco2016 I am receiving the same error on App Center (should be same as Azure). Were you able to find a solution?

**Comment by vitalyiegorov** [comment]
If anyone still facing this problem when using the monorepo approach please pay attention to [android/settings.gradle](https://github.com/brunolemos/react-native-web-monorepo/blob/master/packages/mobile/android/settings.gradle):
```
apply from: file("../../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings, "../../..")
include ':app'
```
and [android/settings.gradle](https://github.com/brunolemos/react-native-web-monorepo/blob/master/packages/mobile/android/app/build.gradle):
```
apply from: file("../../../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project, "../../..")
include ':app'
```

`applyNativeModulesSettingsGradle` and `applyNativeModulesAppBuildGradle` has second parameter `root` (relative path to folder with settings) which is passed to gradle to find `react-native.config.js`

**Comment by ridvanaltun** [comment]
Cleaning gradle cache works for me

Stop gradlew on Windows:
`gradlew --stop`

Stop gradlew on Mac or Linux:
`./gradlew --stop`

Clean cache on Windows:
`gradle cleanBuildCache`

Clean cache on Mac or Linux:
`./gradlew cleanBuildCache`

**Comment by bkleef** [comment]
In my case `bash` was not installed in the Docker container.

**Comment by tarunvella** [comment]
> I fixed the problem.
> Because of custom paths (I have essentially a form of mono-repo with many sub projects)
> `PATH=$(npm bin):$PATH react-native config`
> could not find where my root android part of the project was (it was not in standard directory relative to the JS part of the project)
> 
> I am not sure if this nuance is covered in
> https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
> It talks about how to tell cli, in 'custom root' configuration , about the location of JS part of the project, but does not tell how to tell the cli tools about the the location of android side of the project
> 
> So all I had to do, to fix this specific problem, is to specify sourceDir and packageName in the react-native.config.js
> 
> ```
> 
> module.exports = {
>   project: {
>     ios: {},
>     android: {
>     "sourceDir": "../a/myapp1b/app/src",
>     "packageName":"com.myapp1b.myapp"
>     
>     },
>   },
>   assets: ['./src/js.app/img'],
> };
> ```
@vladp How do i perform PATH=$(npm bin):$PATH react-native config in windows, and where can i keep react-native.config.js in my project.

**Comment by vladp** [comment]
@tarunvella 
I do not think your questions are particuarly related to the problem I reported.
Because it is not clear from your note,  that your custom RN root is, indeed, outside of the repository structure
expecatation of the new CLI release.  May be it is , but it is was not clear.

Because the support for `root: ` directive in app/build.gradle `project.ext.react`  is now removed from this cli build, we cannot migrate to RN 0.61
as Autolinking feature of the CLI errors out (because our RN root is not above or below android app root).

Which is why I asked the designers to see if they could help either disable the autolinking feature, or bring back functionality that respectes the `root: ` setting.

Have not heard back yet, so if you are running into same problem, I do not think I have a solution.
I am not sure why this issue is closed, no solution was provided.
cleaning gradle has nothing to do with, as I pointed out the actuall functionality for handling custom roots was removed from CLI source.


---

Having said the above, let me see if I can help with some of your questions (but, again, I think, they may be  outside of the problem I reported, so cli dev may ask to move this somewhere else).


>  How do i perform PATH=$(npm bin):$PATH react-native config in windows, 

On windows
cd <your RN project root>  
./node_modules/.bin react-native config

> and where can i keep react-native.config.js in my project.
This answer is much more involved.

In short, has to be in the directory where your node_modules is

This directory needs to be referenced from your
android's app/build.gradle  in project.ext.react
```
Here is mine:
project.ext.react = [

        entryFile: "index.android.js",
        // whether to bundle JS and assets in debug mode
        bundleInDebug: false,
        // whether to bundle JS and assets in release mode
        bundleInRelease: true,
        // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
        bundleCommand: "ram-bundle",
        enableHermes: false,  // clean and rebuild if changing

        // the root of your RN project, i.e. where "package.json" lives
        // due to CLI change, this now does not work with RN 0.61
        root: "${myRnAppRootDir_abs}"
]

```
the myRnAppRootDir_abs is an absolute path that points to the directory where your node_modules are.

But you really need to recognize 2 other you expected to make in your app/build.gradle and in settings.gradle to enable autolinking.

Best way to do it, is to use
https://github.com/react-native-community/rn-diff-purge
to find all the changes you need to make in above 2 files (the diff purge will show the diff lines between whatever RN version you are on now  and 0.60 ).

I do not think, I had seen an explicit readme or migration docs on how do that, so I used the diff tool

**Comment by vladp** [comment]
Please note, that
react-native-community/cli in RN 0.61 had remove the functionality where we can specify the custom RN root using  app/build.gradle `root:` directive in  `project.ext.react`

```
project.ext.react = [

        entryFile: "index.android.js",
        // whether to bundle JS and assets in debug mode
        bundleInDebug: false,
        // whether to bundle JS and assets in release mode
        bundleInRelease: true,
        // https://facebook.github.io/react-native/docs/performance#enable-the-ram-format
        bundleCommand: "ram-bundle",
        enableHermes: false,  // clean and rebuild if changing

        // the root of your RN project, i.e. where "package.json" lives
        root: "${myRnAppRootDir_abs}"
]
```

So starting from RN 0.61 if you have RN root folder located as a sibling or underneath of a sibling of your Android app directory, the CLI will not find it and Autolinking will fail

See my bug report at
https://github.com/react-native-community/cli/issues/804

--- 

@tarunvella 
> how do I  perform PATH=$(npm bin):$PATH react-native config
on windows, just 
cd < your react native root, where node_modules in installed>
and do
node_modules/.bin/react-native config

You do not need to this manually, as CLI's autolinking code does that.
The code knows where to go, because you had to specify your RN root in 
in app/buid.gradle  project.ext.react 
variable.

The best guide for this, unfortutely, is just to carefull follow diff report  between your current version
and RN 0.60
https://github.com/react-native-community/rn-diff-purge

**Comment by Alcionei** [comment]
I deleted my build folder and it worked.

**Comment by Cuadros99** [comment]
> Cleaning gradle cache works for me
> 
> Stop gradlew on Windows:
> `gradlew --stop`
> 
> Stop gradlew on Mac or Linux:
> `./gradlew --stop`
> 
> Clean cache on Windows:
> `gradle cleanBuildCache`
> 
> Clean cache on Mac or Linux:
> `./gradlew cleanBuildCache`

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\danie\OneDrive\┴rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\CapacitaþÒo\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 195

* What went wrong:
A problem occurred evaluating script.
> internal/modules/cjs/loader.js:1032  throw err;  ^Error: Cannot find module 'C:\Users\danie\OneDrive\├â´┐¢rea de Trabalho\IME\Iniciativas\IME Jr\BECOMP\Capacita├â┬º├â┬úo\React Native\Curso_React_Native\final_chance\node_modules\@react-native-community\cli\build\bin.js'    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)    at Function.Module._load (internal/modules/cjs/loader.js:898:27)    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    at internal/main/run_main_module.js:17:47 {  code: 'MODULE_NOT_FOUND',  requireStack: []}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s


This was the error that appear to me when I wrote  this commands.

**Comment by mohammadPezesh1994** [comment]
@Cuadros99  i got this error too but in linux when i init new react-native project in react-native-cli i've faced with this error every time 

Could not load compiled classes for script '.../node_modules/@react-native-community/cli-platform-android/native_modules.gradle' from cache.

**Comment by kuldeep-IT** [comment]
> 



> @Cuadros99 i got this error too but in linux when i init new react-native project in react-native-cli i've faced with this error every time
> 
> Could not load compiled classes for script '.../node_modules/@react-native-community/cli-platform-android/native_modules.gradle' from cache.

@mohpezeshki, I'm also facing the same issue in RN 0.72.4

**Comment by Cuadros99** [comment]
> > 
> 
> 
> 
> > @Cuadros99 i got this error too but in linux when i init new react-native project in react-native-cli i've faced with this error every time
> > 
> > Could not load compiled classes for script '.../node_modules/@react-native-community/cli-platform-android/native_modules.gradle' from cache.
> 
> @mohpezeshki, I'm also facing the same issue in RN 0.72.4
> 

What worked for me at the time was put the project directory in a place where it didnt have any blank space in its path. Like in my case the path has "/┴rea de Trabalho/".

**Comment by akls20** [comment]
A simple `npm prune` worked for me.

**Comment by Sushmanighthack** [comment]
Can anyone suggest this how to resolve this error                                                                                                                         
  Could not read script 'C:\code\ViveRN\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' as it does not exist.

**Comment by szymonrybczak** [comment]
@Sushmanighthack please make sure thatn you have `node_modules` installed and than in `android/` project is pointing to correct `node_modules` path 👍
