### ISSUE TITLE
 Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function 

### ISSUE THREAD

**Issue by wuxiii** [react-native-community/cli#592]
## Environment
    Binaries:
      Node: 12.5.0 - /usr/local/bin/node
      Yarn: 1.16.0 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 22, 23, 27, 28, 29
        Build Tools: 27.0.3, 28.0.3, 29.0.0
        System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description

I upgraded rn 0.52 to 0.59.10, when i use `react-native link` ,some error occurred
`error Something went wrong while linking. Error: buildSettings.LIBRARY_SEARCH_PATHS.push is not a function 
`

**Comment by thymikee** [comment]
Can you share more details about it? How does the error look with `--verbose` flag passed to the `link` command?

**Comment by wuxiii** [comment]
![image](https://user-images.githubusercontent.com/28565020/63309208-8b9de600-c328-11e9-830b-a4fad89992ca.png)

**Comment by thymikee** [comment]
`link` is going to be removed soon, replaced by autolinking which should _just work_
