### ISSUE TITLE
Can't init RN project inside existing npm project directory

### ISSUE THREAD

**Issue by gitowiec** [react-native-community/cli#594]
## Environment

System:
    OS: Linux 5.1 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
    Memory: 422.88 MB / 15.52 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-28 | Intel x86 Atom_64
  npmPackages:
    @react-native-community/cli: ^2.8.0 => 2.8.0

## Description
I created a folder and npm-initialized it, then I installed @react-native-community/cli locally in it. Next I wanted to call `npx react-native init special_top_secret_project --template react-native-template-typescript --npm --directory .` to init new RN project but I got nothing saying error
```
error Error occurred while trying to create project directory.
```
## Reproducible Demo
```
mkdir my_project
cd my_project
npm init -y
npm install @react-native-community/cli -D
npx react-native init special_top_secret_project --template react-native-template-typescript --npm --directory .
```

## Purpose

I just wanted to have RN and RN Cli as a dependencies of a project. I don't want to install @react-native-community/cli globally nor react-native-cli because it is deprecated.

**Comment by thymikee** [comment]
There's no `--directory` flag that creates directory. Also, `react-native-template-typescript` supports new init on a `next` tag for now:

```
npx react-native init --template react-native-template-typescript@next special_top_secret_project
```
