### ISSUE TITLE
Can a package be instantiated with an arg in PackageList.java?

### ISSUE THREAD

**Issue by spasecadet** [react-native-community/cli#599]
I'm using `react-native-google-fit` and it requires that the package be instantiated with `BuildConfig.APPLICATION_ID` eg: `new GoogleFitPackage(BuildConfig.APPLICATION_ID)`.  I have not been able to figure out if this is possible using react-native.config.js.  I've read the docs here https://github.com/react-native-community/cli/blob/master/docs/platforms.md and https://github.com/react-native-community/cli/blob/master/docs/autolinking.md, but neither of them goes into the kind of detail I need since I don't have much experience with this.  Is there a way to provide an arg to a package constructor in PackageList.java?

Thank you!

**Comment by forsen** [comment]
You can try to configure your `react-native.config.js` like this:

```JavaScript
module.exports = {
  dependencies: {
    'react-native-google-fit': {
      platforms: {
        android: {
          packageInstance: "new GoogleFitPackage(BuildConfig.APPLICATION_ID"
        },
      },
    },
  },
};
```

**Comment by spasecadet** [comment]
Thank you, will give it a try.

**Comment by thymikee** [comment]
Yup, that will do, we import `BuildConfig` in `PackageList.java` so it's available

**Comment by spasecadet** [comment]
That worked perfectly, thanks!
