### ISSUE TITLE
Template auto-prefix does not respect npm scopes

### ISSUE THREAD

**Issue by jounii** [react-native-community/cli#605]
## Environment

> react-native --version
react-native-cli: 2.0.1
react-native: n/a - not inside a React Native project directory

Right now the --template parameter takes in template name, or other template source as parameter. Unfortunately due private environments the direct git repository url is not working (archive not supported in Azure Devops). Alternative here was to use private npm repository. The way it is configured is through npm package scope prefix.

Currently cli prefixes the npm template name with "react-native-template-" and does not respect scopes. So running command:

`react-native init --template @privatescope/mytemplatename`

results in fetch from `react-native-template-@privatescope/mytemplatename` and not from `@privatescope/react-native-template-mytemplatename` as probably would expect to allow scoped private repository to be chosen as configured in .npmrc

**Comment by thymikee** [comment]
Please use new init (available e.g. through `npx react-native`) for such cases:
```
npx react-native init --template @privatescope/react-native-template-mytemplatename
```
You'll need to update your template as well, see: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

**Comment by jounii** [comment]
Yes, sorry. I did not include the npx here in the report which I was using (version is still the latest). Also the template.config.js is in the template. However does not change the problem with the scoped template name.

The output shows:

`info Fetching template react-native-template-@privatescope/react-native-template-mytemplatename...`

and this fails as it is trying to fetch from public npm registry and for some reason execute git command to github even though repository is not there.

`Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/privatescope/react-native-template-mytemplatename.git`

`warn Failed to clean up template temp files in node_modules/react-native-template-@privatescope/react-native-template-mytemplatename. This is not a critical error, you can work on your app.`

`(node:31415) UnhandledPromiseRejectionWarning: Error: Command failed: yarn add react-native-template-@privatescope/react-native-template-mytemplatename`

**Comment by thymikee** [comment]
The new init doesn't support shorthand templates, you need to pass full name of the package/repo/path

**Comment by thymikee** [comment]
Also, it's possible that when using `npx react-native` you still use the old version (npx is weird). Try `npx react-native@0.60` just to be sure.

**Comment by jounii** [comment]
Does not help. Are you sure this line of code is not anymore used in the cli latest version (master branch)?

https://github.com/react-native-community/cli/blob/8c2d5b5f337db02c8868c627d9e4a3b39e0af329/packages/cli/src/tools/generator/templates.js#L74

**Comment by thymikee** [comment]
I'm sure `generator/*` files are only used by a legacy init, which runs when you do `react-native init`. Where `react-native` is a global binary installed while doing `yarn global add react-native-cli` or similar.

Can you try `npx @react-native-community/cli init` then?

**Comment by jounii** [comment]
Seems there was react-native-cli (2.0.1) in the ~/.npm cache. `yarn global remove react-native-cli` fixed that and more recent version of cli is now found.

Now having other issue .npmrc config from the template not being respected (local private repo configuration used by template), maybe it's in incorrect place, but have to debug this a bit.

**Comment by jounii** [comment]
Okay thans @thymikee for your help pointing to right direction. I think the problem with .npmrc is that seems to be missing from my package right now, so have to see that one. Otherwise template installation works now with scoped template name as intended.
