### ISSUE TITLE
are there plans to link arbitrary assets?

### ISSUE THREAD

**Issue by mmerickel** [react-native-community/cli#608]
## Ask your Question

It looks like the CLI only supports linking specific file types, and inconsistently across platforms. On iOS images and fonts are supported, and on Android only fonts. What is the path forward here to link arbitrary files into the app? Is it better as an application developer to extend the metro bundler with custom `require()` file types than to expect the linking to support arbitrary files?

**Comment by thymikee** [comment]
We'd like to make it better, thanks for asking. Do you have any ideas maybe?

**Comment by mmerickel** [comment]
Doing it via `require()` isn't the end of the world but there's definitely some blobular data that I need only accessible to native modules and right now I just need to manually copy it into the project for each platform and make sure it's up to date when I upgrade the modules. Being able to re-link those modules after upgrade and have the assets copied would be nice, or even nicer if instead of copying there were some way for the assets to only live in their respective package folders without copying them. Certainly on iOS this is possible, I'm less familiar with gradle and how it handles assets.

At least on iOS I suppose it can be done directly in the podspec via `resource_bundle` directive etc, so maybe that's a good solution there. Is there a good way to do it in gradle?

I'm closing this issue to avoid it lingering too long as it's not a specific action item. Thanks for any responses!

**Comment by thymikee** [comment]
cc @Salakar @dulmandakh

**Comment by gauthierm** [comment]
I want to add some pre-bundled assets (CSS,JS,HTML) for use in a webview and the `assets` config looked like the right way forward until I realized it only copies images and fonts.

If I add:

```
  addResourceFile(assets.text);
```

To the copyAssets then it works fine. I'm able to load the CSS file in the webview and take advantage of local caching.

I can do this manually each time I rebuild these assets but it would be less error prone and nicer to have `react-native link` update things automatically.

**Comment by liamjones** [comment]
@gauthierm Not sure if it'll be added to the CLI but FYI https://github.com/unimonkiez/react-native-asset will do all types of files (and also unlinks automatically when necessary).
