### ISSUE TITLE
Specify CI to be integrated while initing a new project

### ISSUE THREAD

**Issue by gengjiawen** [react-native-community/cli#61]
Provide command line to make them easily integrate ci system.

CI file can check here https://github.com/react-native-community/ci-sample.

Related: https://github.com/facebook/react-native/issues/22779.

**Comment by Esemesek** [comment]
@gengjiawen So basically you want to have an additional command line flag passed to `init` command that will indicate if the user wants integration for chosen `ci` platform? For example:
```sh
# This will initialize project with default template and add travis.yml
react-native init --ci travis
```
Correct me if I misunderstood you C:

**Comment by gengjiawen** [comment]
Not just that. He can still add or update any ci after the project is created.
