### ISSUE TITLE
react-native init doesnt seem to be using the latest template files

### ISSUE THREAD

**Issue by Darkle** [react-native-community/cli#610]
## Environment

System:
    OS: Linux 4.14 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (1) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 274.50 MB / 1.65 GB
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 10.14.2 - /usr/local/nvm/versions/node/v10.14.2/bin/node
    npm: 6.4.1 - /usr/local/nvm/versions/node/v10.14.2/bin/npm
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description

`react-native init` seems to be using old versions of some (all?) of the template files. 

## Reproducible Demo

1. Go to https://console.cloud.google.com/cloudshell/editor?pli=1&shellonly=true and create a shell.
2. Run `npm i -g react-native-cli`
3. Run `react-native init TestApp`
4. Run `cat ./TestApp/.flowconfig`
5. The output of running cat is: https://gist.github.com/Darkle/b70d905f34ec18908b72949c531f6e41 but the latest version of that file looks like this: https://github.com/facebook/react-native/blob/master/template/_flowconfig

Possibly related: https://github.com/react-native-community/cli/pull/84

**Comment by thymikee** [comment]
RN master branch is not published. `init` uses `latest` npm published tag, which is 0.60.4 at the moment. See how you can use local RN version as a template here: https://github.com/react-native-community/cli/blob/master/CONTRIBUTING.md#running-cli-with-react-native-from-the-source
