### ISSUE TITLE
react-native link on Windows uses incorrect path separator for xcode

### ISSUE THREAD

**Issue by qwertzguy** [react-native-community/cli#615]
## Environment

info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
      Memory: 5.49 GB / 15.89 GB
    Binaries:
      Yarn: 1.17.3 - C:\Users\gaspa\AppData\Roaming\npm\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.3.0.0 AI-182.5107.16.33.5314842

## Description

Running react-native link on windows will use backslashes in the xcode project file project.pbxcode in the HEADER_SEARCH_PATHS.

Resulting in strings like these:
"$(SRCROOT)..\node_modules\neact-native-fs/**",

These will not be parsed correctly by xcode.

The issue is in /packages/platform-ios/src/link/getHeaderSearchPath.js. It should not use the platform path.sep, instead it should always uses forward slashes, regardless of the current platform since xcode only runs on MacOS.

## Reproducible Demo

create new project
add library that needs linking, such as react-native-fs
run react-native link react-native-fs on a windows machine
observe result in project.pbxcode file under HEADER_SEARCH_PATHS.

**Comment by thymikee** [comment]
Would you like to send a PR with a fix? :)

**Comment by Taym95** [comment]
I would like to submit PR for this issue.
