### ISSUE TITLE
run react-native run-android issue 

### ISSUE THREAD

**Issue by JackyChar** [react-native-community/cli#619]
I  try to upgrade my project from 56.0 to 60.4.
Run "react-native run-android" have issue.

show error:
FAILURE: Build failed with an exception.

* What went wrong:
Project 'app' not found in root project 'myProjectName'.

Android studio not have "module app"

<img width="484" alt="android_app_no_show" src="https://user-images.githubusercontent.com/42757503/62454112-46b17580-b7a6-11e9-8156-cead6a9c219a.png">

**Comment by thymikee** [comment]
Can you share more details about your project? It's structure, deps, system used, anything that can help us diagnose it? Ideally a repro we can download

**Comment by theweavrs** [comment]
@JackyChar show your `settings.gradle` file. Should be in the `android` folder.

**Comment by grabbou** [comment]
Going to close because there's no reproduction provided. Could've been an issue with the upgrade itself. Please feel free to reopen once more information has been provided.
