### ISSUE TITLE
react-native run-ios --scheme issue

### ISSUE THREAD

**Issue by ZsKLiQuid** [react-native-community/cli#622]
## Environment

React Native Environment Info:
    System:
      OS: macOS 10.15
      CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
      Memory: 5.83 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.16.0 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.10.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.3, 28.0.0, 28.0.2, 28.0.3
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.2 => 16.8.2
      react-native: ^0.59.10 => 0.59.10
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-touch-id: 4.0.0
      react-native: 0.60.4

## Description

Hello,

In my project i have two targets with two differents schemes carrefourMQ and carrefourRU.

When i run : 

```
node ./node_modules/.bin/react-native run-ios --simulator 'iPhone 8' --scheme 'carrefourRU'
```

This command build the good scheme "carrefourRU" but open/launch (in simulator) the bad one (carrefourMQ)

I found a solution to resolve this issue, i switch the resolve line 235 (runIOS.js)

``` 
resolve(getProductName(buildOutput) || scheme);
```
 to 

``` 
resolve(scheme || getProductName(buildOutput));
```

Everything work good now, but maybe is not the best solution.

Let me know if you have a better solution.

Thank you.

**Comment by grabbou** [comment]
Thanks for digging into it! The solution looks great! I'll send a quick PR right now

**Comment by grabbou** [comment]
Unfortunately, this solution is not really "good", because `scheme` in that context is always defined. 

In line 60, we assign it a default value:
```js
const scheme = args.scheme || inferredSchemeName;
```

**Comment by grabbou** [comment]
Before proceeding, we need to take a look at the historical commit that implemented the product name extraction from the build output: https://github.com/facebook/react-native/commit/8b55e50d1da91dbeadddd7a5a40cc6e4532f9551

We can't change the product name per schema, so I think we should change this logic to be:
```
args.schema || getProductName(buildOutput) || inferredSchema
```

What you think? Or shall we replace the `getProductName` with a better alternative?

**Comment by ZsKLiQuid** [comment]
Hum,

In my case buildOutput has many "FULL_PRODUCT_NAME".

```
const productNameMatch = /export FULL_PRODUCT_NAME="?(.+).app"?$/m.exec(buildOutput);
```

This line take the first occurence but the good one is the last occurence.

What do you think ?

**Comment by grabbou** [comment]
Closing as related to #211. Going to work on a fix.
