### ISSUE TITLE
Just create a project by expo and then just upgrade and Cannot read property 'toLowerCase'

### ISSUE THREAD

**Issue by openmaya** [react-native-community/cli#627]
## Environment
mac, zsh
react-native-cli: 2.0.1
react-native: 0.59.8
npm 6.9.0
expo: 3.0.9

## Description
I just create a project by expo using expo-template-blank-typescript
and right then upgrade 

## Reproducible Demo

expo init MyProject
cd MyProject
react-native upgrade   

info No version passed. Fetching latest...
info Fetching diff between v0.59.8 and v0.60.4...
error Cannot read property 'toLowerCase' of undefined
debug TypeError: Cannot read property 'toLowerCase' of undefined
    at getPatch (/Users/asdf/MyProject/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:109:121)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Object.upgrade [as func] (/Users/asdf/MyProject/node_modules/@react-native-community/cli/build/commands/upgrade/upgrade.js:238:17)

**Comment by Andrea-Arguello** [comment]
I am having this same issue, I am trying to work with a component that requires react-native to be 0.60.4 or greater and my project is 0.59, but I cannot upgrade because of this error

**Comment by maciejsimka** [comment]
I take it that you haven't ejected?

[Upgrading Expo projects](https://facebook.github.io/react-native/docs/upgrading#expo-projects) works a bit differently and [latest SDK version supports RN 0.59.8](https://docs.expo.io/versions/latest/sdk/overview/#sdk-version), so your best bet is to wait for the next SDK version which is planned for September, I think.

If you have ejected, you're probably missing `name` field in `package.json`.

**Comment by openmaya** [comment]
@maciejsimka Thanks. I will keep the 0.59.8 and wait until Sep.

**Comment by grabbou** [comment]
I am going to close this issue because the code responsible for this failure is no longer part of the CLI.

`toLowerCase()` has been removed (and likely other logic has been changed).
