### ISSUE TITLE
Auto-linking with 0.60 and custom maven url in root build.gradle

### ISSUE THREAD

**Issue by christocracy** [react-native-community/cli#636]
## Ask your Question

I'm a plugin author.  My plugin includes a custom `.aar` library in much the same way that `react-native` itself is imported, by adding a custom `maven url` to the root `build.gradle`

```diff
+     maven {
+	    url "$rootDir/../node_modules/react-native-my-custom-library/android/libs"
+     }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }
```

In the past with `react-native link`, I had used a custom `postlink` script to automatically open and write this required `maven url` to `build.gradle` (and corresponding `postunlink` script to remove it when the package is removed).

However, with auto-linking, `hooks` scripts no longer run.

How might I automatically write my library's required `maven url` to the app's root `build.gradle` with auto-linking?

In addition, my custom hook-scripts had also added required Gradle `ext` vars:
```diff
buildscript {
    ext {
+      googlePlayServicesLocationVersion = "17.0.0"
+      appCompatVersion = "1.0.2"
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "1.0.2"
    }
.
.
.
}
```

**Comment by christocracy** [comment]
I found another way.

**Comment by lenoirzamboni** [comment]
@christocracy Hello! I am having the same problem. How did you handle writing the custom maven url to build.gradle?

**Comment by christocracy** [comment]
@lenoirzamboni Please post an issue at my plugin repo.  I will answer there.
