### ISSUE TITLE
@babel/runtime devDependencies -> dependencies?

### ISSUE THREAD

**Issue by gpfunk** [react-native-community/cli#637]
## Environment

System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.61 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5

## Description

I couldn't find anything documenting this at all anywhere, so apologies if this has been answered before, but should @babel/runtime not be a production dependency? 

https://github.com/react-native-community/cli/blob/5d23c71f186e6d8739cfa57b378526f8146e9c0b/packages/cli/src/commands/init/initCompat.js#L70

https://github.com/facebook/react-native/commit/458d56c0a1ac73c088660830a8bf2db65de7d9a2

**Comment by thymikee** [comment]
Looks like we don't need it at all, since we don't use `@babel/plugin-transform-runtime`: https://babeljs.io/docs/en/babel-runtime#usage.

**Comment by thymikee** [comment]
Ah, didn't notice this is for init compat. It's a dev dep inside RN defaut template: https://github.com/facebook/react-native/blob/0.60-stable/template/package.json#L15. Please ask on RN core repo and come back if you turn out moving this to "dependencies". Closing for now :)
