### ISSUE TITLE
UNMET PEER DEPENDENCY react-native@0.60.4

### ISSUE THREAD

**Issue by ldco2016** [react-native-community/cli#643]
## Environment

```
iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.2, 27.0.3, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 2.9.0 => 2.9.0
    react: 16.8.6 => 16.8.6
    react-native: 0.60.4 => 0.60.4
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
```

## Description

I wanted to look into `native_modules` file inside of `@react-native-community/cli` and I noticed that the folder did not exist in my `node_modules`.

So I did an `npm ls @react-native-community/cli` and I got this readout:

```
├── @react-native-community/cli@2.9.0
└─┬ UNMET PEER DEPENDENCY react-native@0.60.4
  └── @react-native-community/cli@2.9.0  deduped
```

I have removed package-lock file I have removed and reinstalled node_modules and I continue to get the above error.

This is my `package-lock.json` file:

```
"react-native": {
      "version": "0.60.4",
      "resolved": "https://registry.npmjs.org/react-native/-/react-native-0.60.4.tgz",
      "integrity": "sha512-WE41lbGQjnzM9srIFtMDtMJkQAvk95iZwuFvAxl68s80bkYa7Ou9sGFHpeYIV6cY8yHtheCSo5q6YMxhdfkdOw==",
      "requires": {
        "@babel/runtime": "^7.0.0",
        "@react-native-community/cli": "^2.0.1",
        "@react-native-community/cli-platform-android": "^2.0.1",
        "@react-native-community/cli-platform-ios": "^2.0.1",
```

## Reproducible Demo

You can clone and `npm install` this project and attempt an `npm ls @react-native-community/cli`:

https://github.com/ldco2016/NFIBEngage

**Comment by thymikee** [comment]
It's inside `@react-native-community/cli-platform-ios/native_modules.rb` for iOS and `@react-native-community/cli-platform-android/native_modules.gradle` for Android.

**Comment by ldco2016** [comment]
@thymikee , I do have `@react-native-community` now, but why am I getting:

```
├── @react-native-community/cli@2.9.0
└─┬ UNMET PEER DEPENDENCY react-native@0.60.4
  └── @react-native-community/cli@2.9.0  deduped
```

regardless of what I try to remove it?

**Comment by thymikee** [comment]
Because you don't have `react-native` installed? Or npm fails to do its job. It's just a warning anyway.

**Comment by ldco2016** [comment]
`react-native` is installed. Not a `react-native-community/cli` issue, understood.

**Comment by thymikee** [comment]
Yup 🙂 This project you linked use Yarn, so I'd use that. It's better in my experience and I always recommend it.

**Comment by avesus** [comment]
> Yup slightly_smiling_face This project you linked use Yarn, so I'd use that. It's better in my experience and I always recommend it.

Thank you, @iarna

I wonder how on Earth npm has a total unmet and incompatible dependencies mess but at the same time yarn works and fixes everything? Feels scary about the state of dependencies in the node and React world today.

@thymikee in what way yarn is better than npm?

**Comment by thymikee** [comment]
@avesus it's been 2 years since that message and npm improved by a lot in terms of reliability (npm 7 specifically). However it introduced some controversial features, like auto-install of peer dependencies. Anyway, I still prefer yarn v1 (v2+ is harder to work with RN, but haven't tried in a while).
