### ISSUE TITLE
App init does not work with directory option

### ISSUE THREAD

**Issue by ddeath** [react-native-community/cli#645]
## Environment

```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1021.16 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.0
      System Images: android-27 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
```

## Description

```
 me@MacBook-Pro  ~/Projects/MyApp   feature/mobile-basic-setup ✚  react-native init MyApp --directory ./mobile

               ######                ######
             ###     ####        ####     ###
            ##          ###    ###          ##
            ##             ####             ##
            ##             ####             ##
            ##           ##    ##           ##
            ##         ###      ###         ##
             ##  ########################  ##
          ######    ###            ###    ######
      ###     ##    ##              ##    ##     ###
   ###         ## ###      ####      ### ##         ###
  ##           ####      ########      ####           ##
 ##             ###     ##########     ###             ##
  ##           ####      ########      ####           ##
   ###         ## ###      ####      ### ##         ###
      ###     ##    ##              ##    ##     ###
          ######    ###            ###    ######
             ##  ########################  ##
            ##         ###      ###         ##
            ##           ##    ##           ##
            ##             ####             ##
            ##             ####             ##
            ##          ###    ###          ##
             ###     ####        ####     ###
               ######                ######


                  Welcome to React Native!
                 Learn Once Write Anywhere

✔ Downloading template
✔ Copying template
✔ Processing template
✔ Installing dependencies
⠴ Installing CocoaPods dependencies (this may take a few minutes)
[!] Invalid `Podfile` file: cannot load such file -- /Users/me/Projects/MyApp/mobile/node_modules/@react-native-community/cli-platform-ios/native_modules.

 #  from /Users/me/Projects/MyApp/mobile/ios/Podfile:2
 #  -------------------------------------------
 #  platform :ios, '9.0'
 >  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #
 #  -------------------------------------------

✖ Installing CocoaPods dependencies (this may take a few minutes)
error Error: Failed to install CocoaPods dependencies for iOS project, which is required by this template.
Please try again manually: "cd ./MyApp/ios && pod install".
CocoaPods documentation: https://cocoapods.org/
```

## Reproducible Demo

`react-native init MyApp --directory ./mobile`

If you run command without directory option it works

**Comment by ddeath** [comment]
Ok this is probably because I use yarn workspaces so and rn does not know how to work with it...

**Comment by Esemesek** [comment]
Is your project initialized properly? It seems like only `pod install` is failing.

**Comment by ddeath** [comment]
What do you mean if it is initialized properly? The init command failed. Also it has an issue to build an android app.

But as I said it is an issue with yarn workspaces - I mean they are working properly, just react do not know how to handle them. Basically what will happen when you are using workspaces, the packages get hoisted to the root `node_modules` directory so react-native cannot find them anymore, because it will look only to the current dir but not to the root dir...

This can be somehow solved by adding noHoist to the package.json ...

It would be nice if the react-native will work with workspaces out of the box. But I guess it is more feature request then bug?

**Comment by Esemesek** [comment]
Can you please read error message you posted? Init command failed on pod installation, but project should be initialized without pods installed.

**Comment by ddeath** [comment]
yes but think is you are not able to build the android and ios app either... and usually when you run the init command you expect the success and not failure. How the user should know that it is ok to fail like this? What if there were 20 more steps in init process? It is not clear from that error message...

Anyway... I found my solution to it...

**Comment by Esemesek** [comment]
@ddeath You titled your issue that `init` is not working correctly, that is why I am asking about it. You didn't mention any other commands not working. If you read the error message instead of posting an issue here, you would most probably find another ticket, where we track this exact [issue](https://github.com/react-native-community/cli/issues/633).
