### ISSUE TITLE
`react-native upgrade` No conflicts delimiter for "project.pbxproj"

### ISSUE THREAD

**Issue by maximedupre** [react-native-community/cli#652]
The struggle to upgrade react-native in my project has arrived once again.

	$ react-native upgrade
	info No version passed. Fetching latest...
	info Fetching diff between v0.60.4 and v0.60.5...
	info Applying diff...
	warn Excluding files that exist in the template, but not in your project:

	error Excluding files that failed to apply the diff:
	- ios/my-project.xcodeproj/project.pbxproj
	Please make sure to check the actual changes after the upgrade command is finished.
	You can find them in our Upgrade Helper web app: https://react-native-community.github.io/upgrade-helper/?from=0.60.4&to=0.60.5
	info Installing "react-native@0.60.5" and its peer dependencies...
	info Running "git status" to check what changed...
	On branch master
	Your branch is up to date with 'origin/master'.

	Changes to be committed:
	(use "git reset HEAD <file>..." to unstage)

			new file:   .prettierrc.js
			modified:   ios/Podfile
			modified:   package-lock.json
			modified:   package.json

	success Upgraded React Native to v0.60.5 🎉. Now you can review and commit the changes

Almost everything went right, except for "ios/my-project.xcodeproj/project.pbxproj". Not bad, with the exception that there are no conflict delimiters in the file.

How am I supposed to apply the changes of "project.pbxproj"? I don't understand any of this:

![Screen Shot 2019-08-27 at 9 25 10 PM](https://user-images.githubusercontent.com/5158181/63864930-abfc1f00-c97e-11e9-8305-50c6119dd468.png)

Does this mean I need to learn what a "project.pbxproj" file is, it's syntax and how to debug it in order to be able to upgrade my react-native project?

How important is this file? Can I simply ignore the changes?

If this file can be generated by the Xcode GUI, are there manual step to reproduce the changes?

is the only option to always start from a new project and transfer everything over?

Cheers!

**Comment by thymikee** [comment]
The rule of thumb is: you don't. 
Changes in `*.pbxproj` are usually because different versions of Xcode producing results that are ordered differently. 
If there is something that requires your attention, we will tell you inside https://react-native-community.github.io/upgrade-helper/ as a comment to this very file.

**Comment by thymikee** [comment]
@maximedupre I've edited the comment

**Comment by andidev** [comment]
> If there is something that requires your attention, we will tell you inside https://react-native-community.github.io/upgrade-helper/ as a comment to this very file.

Please document this in the https://facebook.github.io/react-native/docs/upgrading page. This is not that obvious.

**Comment by ThinkSalat** [comment]
So I went through and changed everything in project.pbxproj when updating from 0.62.2 to 0.63.4. Should I have just left it the same?
