### ISSUE TITLE
react-native.config.js not working

### ISSUE THREAD

**Issue by rendomnet** [react-native-community/cli#654]
## Environment

System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 1.61 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.13.0 - ~/.nvm/versions/node/v8.13.0/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.3, 28.0.2, 28.0.3
      System Images: android-23 | Intel x86 Atom, android-23 | Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.3 AI-182.5107.16.33.5264788
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.60.5 => 0.60.5
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description

I have react-native.config.js file in root of my project in the same directory where package.json. 
```
module.exports = {
  assets: ['react-native-vector-icons'],
  dependencies: {
    'react-native-code-push': {
      platforms: {
        ios: null,
        android: null,
      },
    },
  },
};
```

But for some reason it tries to autolink code-push.

**Comment by thymikee** [comment]
Can you please provide a repro? Also, you don't need the `assets` entry if you use `react-native-vector-icons`, it's already been handled

**Comment by rendomnet** [comment]
> Can you please provide a repro? Also, you don't need the `assets` entry if you use `react-native-vector-icons`, it's already been handled

@thymikee repo is very big sorry can't provide it. I'm moving my project from 0.59.9 to 0.60.5.
I tried to find documentation for react-native.config.js settings but could not.
As I understand it suppose to be in the root of react-native project and will be handled automatically if we use 0.60+.

I followed this steps https://github.com/microsoft/react-native-code-push/issues/1668#issuecomment-524829723
to solve issue with ios.

**Comment by thymikee** [comment]
Documentation can be found here: https://github.com/react-native-community/cli/tree/master/docs

**Comment by rendomnet** [comment]
@thymikee Sorry i'm trying to understand the issue. Right now in RN 0.60> CodePush conflicting with SSZipArchive on 0.59.9 it was not. Setting CodePush to NOT be autolinked using **react-native.config.js** should resolve the issue?

**Comment by thymikee** [comment]
If you disable code push from linking, it's not gonna be autolinked. It will also not work with `react-native link <package>` – you'll need to either link manually or first run `link`, then disable linking in config file.

**Comment by grabbou** [comment]
Going to close until we have a bare bones reproduction (at least file and folder structure). Please open a new issue in case you encounter any other problems. Thank you!

**Comment by luskin** [comment]
@rendomnet were you able to get code-push working on iOS on RN 0.60+? We are on RN 0.61.4 and are unable to get iOS working.

**Comment by babybear1122** [comment]
You will be able to make react-native.config.js as following:
module.exports = {
    project: {
        ios: {},
        android: {}, // grouped into "project"
    },
    assets: ["./node_modules/react-native-vector-icons/Fonts"], // stays the same
};
