### ISSUE TITLE
bug: react-native run-ios cannot find any simulator (after installing Xcode 11 beta)

### ISSUE THREAD

**Issue by jaysbytes** [react-native-community/cli#658]
## Environment
```
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
      Memory: 44.71 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.12.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        Build Tools: 27.0.3, 28.0.3, 29.0.1
        API Levels: 22, 23, 24, 25, 26, 27, 28, 29
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5522156
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      @types/react: 16.8.1 => 16.8.1
      @types/react-native: 0.57.32 => 0.57.32
      react: 16.8.3 => 16.8.3
      react-native: 0.59.2 => 0.59.2
```

`xcrun simctl --version`

@(#)PROGRAM:simctl  PROJECT:CoreSimulator-675

## Description

After installing a beta version of Xcode 11 command-line tool `simctl` was upgraded. 
It results in a different list of ios simulators and inability to use `react-native run-ios` since invocations claim that there is not `iPhone X` simulator. Actually it's impossible to use command even with `--simulator` flag. 

The bug is caused by the different output of `xcrun simctl list --json`. There is missing `accesibilty` field in the result.

Xcode 10.x, `xcrun simctl --version` -> @(#)PROGRAM:simctl  PROJECT:CoreSimulator-581.2

```
// one of devices in a list
{
        "availability" : "(unavailable, runtime profile not found)",
        "state" : "Shutdown",
        "isAvailable" : false,
        "name" : "Apple TV",
        "udid" : "7F9FD9C5-0A4E-43EB-8351-2FAE3FD24662",
        "availabilityError" : "runtime profile not found"
      },
```

Xcode 11.x, `xcrun simctl --version` -> @(#)PROGRAM:simctl  PROJECT:CoreSimulator-675
```
// one of devices in a list
{
        "state" : "Shutdown",
        "isAvailable" : true,
        "name" : "iPhone 6s Plus",
        "udid" : "C189341A-2873-48C0-A1C8-1D6151BCF557"
      },
```

Each simulator is skipped because of this condition 

```js
for (const i in device) {
      const simulator = device[i]; // Skipping non-available simulator
      if (simulator.availability !== '(available)' && simulator.isAvailable !== 'YES') {
        continue;
      }
      / * *** */
}
```
`simulator.availability !== '(available)' ` because it is undefined
`simulator.isAvailable !== 'YES'` is actually a Boolean value so it also can be fixed since it seems to be some legacy code

transforming condition to 
`if (!simulator.isAvailable)` 
should fix the issue

I'm opening an issue, not a PR because I'm not sure if it can be considered as a bug since it is still beta version of Xcode 11.
I would be happy to fix it in the future :) 

I'm also not sure about the backward compatibility of the script. Should we support older versions of `simctl` where there is `YES` in the output

## Reproducible Demo

You should install beta Xcode 11 and run `react-native run-ios`

**Comment by thymikee** [comment]
Looks like we need to check if `availability` is `(available)` or `undefined`. Can you send a PR? Xcode changes their output all the time, but if we can fix it by adding one extra case, I'm down with that

**Comment by jaysbytes** [comment]
Yes, I will send a PR probably today

**Comment by jaysbytes** [comment]
I've got this issue in a project with 1.x version of CLI, It is fixed in 2.x so I will close the issue 🙃 🤦‍♂
