### ISSUE TITLE
init project with template

### ISSUE THREAD

**Issue by M45ter** [react-native-community/cli#666]
## Ask your Question

when I use template in local folder, it works, but I want to use template in my github like npm install git files as [npm install \<git remote url\>](https://www.npmjs.cn/cli/install), that is more convenient then local folder and npm package, and switch branch is useful when manage some templates  , but it's not works, throw error...

```
react-native init templateTest --version 0.59.10 --template git://github.com/xxx/react-native-template.git
```

**Comment by thymikee** [comment]
You're using legacy init, which we don't maintain anymore. Please use the new one:
```
npx react-native init templateTest --template git://github.com/xxx/react-native-template.git
```
Notice `npx` and using either `version` or `template`, not both. Also, template needs to conform to a new, simpler format: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

In case `npx react-native` gives the same results, you should be able to fix it by running `npx react-native@0.60` or `npx @react-native-community/cli` instead.
