### ISSUE TITLE
Init project with template typescript error on RC version of RN

### ISSUE THREAD

**Issue by bartolkaruza** [react-native-community/cli#668]
Moved from https://github.com/facebook/react-native/issues/26303 by @GreatAuk

Original issue
---

React Native version: 0.61.0-rc.0

## Steps To Reproduce

excute ```npx react-native@0.61.0-rc.0 init RNTest --template typescript```

but ```npx react-native init RNTest --template typescript``` is ok.

Snack, code example, screenshot, or link to a repository:
![image](https://user-images.githubusercontent.com/20253809/64147559-3f3bc580-ce53-11e9-965f-f271ea876fcb.png)

**Comment by Esemesek** [comment]
In the latest version, we dropped support for template name shortcuts. 

`--template typescript` was resolved to `react-native-template-typescript`, now it will be resolved just to `typescript`.

You will need to use `next` version on `react-native-template-typescript` which is available on the separate branch https://github.com/react-native-community/react-native-template-typescript/tree/master-cli-v2.

You need to init your project with:
```sh
npx react-native@0.61.0-rc.0 init RNTest --template react-native-template-typescript@next
```
