### ISSUE TITLE
Doctor command

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/cli#694]
## Describe the Feature

This lists the work that we still need to do in order to get `react-native doctor` ready to ship.

⚠️ This list will be kept up-to-date with whatever issue I encounter. ⚠️

➡️ **If you want to work on any of this just comment what you want to work on to be assigned.**

<details>
  <summary>Specify why a health check is showing status as failed - #763</summary>

  Be more specific about the statuses:

  ```
	x Node.js Required version 10 is not installed (found Node.js 7)
	x ANDROID_HOME: The specified path doesn't exist
	x Android NDK: Required version 20 is not installed
  ```

   Suggestion by @satya164.
</details>

<details>
  <summary>Add tests (@thib92) - #728 #742</summary>
  
  Some stuff is pretty complicated on this flow and we should add tests before we forget how they were implemented 😅
</details>

### Done

<details>
  <summary>Change `Fix all issues` to `Try to fix issues automatically` - #763</summary>

  `Fix all issues` sounds too good to be true and sometimes a health check won't work, better to be safe on wording.

  Suggestion by @satya164.
</details>

<details>
  <summary>Agree on version ranges</summary>

  With the `doctor` command we will have to officially support specific version ranges, we need to agree on which ones those will be and how we will decide when to bump them, the current version ranges are listed [here](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/doctor/versionRanges.ts).

  Keep in mind that I have put the version ranges that I think that should be supported based on my environment, all those versions are up for discussion.
</details>

<details>
  <summary>Errors being thrown should be consistent - #746</summary>

  Currently the errors that are being thrown are not consistent, for instance the `CocoaPods` installation error is much larger than `ios-deploy`, some of them also have indentation to match with the whole "`doctor`" template and some don't.

  An idea to fix this is to have helpers to log errors to the screen.
</details>

<details>
  <summary>Add description to each software that needs to be installed - #743</summary>

  Currently we show this:

  ![Current state](https://user-images.githubusercontent.com/6207220/64615864-a4576400-d3db-11e9-8e9b-6c07184c5553.png)

  It would be nicer to have a `description` field on each healthcheck so they can give better info about why it's needed.
</details>

<details>
  <summary>Don't show the "usage" section if everything is good - #729</summary>

  The usage section shouldn't be shown if there are no error nor warnings.
</details>

<details>
  <summary>Recognition of which package manager the user is using is not 100% - #726</summary>

  [This implementation](https://github.com/react-native-community/cli/blob/master/packages/cli/src/commands/doctor/healthchecks/packageManagers.js#L15-L25) only works if you are in the root of your project, if you are running it somewhere else then it fails.

  If we can't identify which package manager the user is using then we should print a question asking with which package manager we must install `ios-deploy` (the only healthcheck that uses npm registry).
</details>

<details>
  <summary>The UI of CocoaPods installation doesn't really match the rest - #718</summary>
  
  It would be nice to perhaps hide the question after the user chooses it and maybe put the answer into parentheses, something like `✅ CocoaPods (Installing with gem)`, the indentation of the question also doesn't match the other fixes.

  ![image](https://user-images.githubusercontent.com/6207220/64595433-3a769480-d3b2-11e9-8c9a-f92a1b94953e.png)
</details>

<details>
  <summary>CocoaPods question gets buggy if the previous healthcheck failed to install - #699</summary>

  This is probably because the loader remains running even after the healthcheck fails to install, perhaps calling `loader.fail()` fixes it.
 
  ![image](https://user-images.githubusercontent.com/6207220/64596193-c0dfa600-d3b3-11e9-8c03-58f1662cc216.png)
</details>

<details>
  <summary>Improve errors UI - #699</summary>
  
  The loader of the healthcheck that failed must be `loader.fail`, instead if keeps the same loading state, it would also be nice to have those messages below the name of the healthcheck, something like:
  ```
    ❌ ios-deploy
       There was an error while installing this software, please install it
       by running yarn global add ios-deploy.
  ```
 
  ![image](https://user-images.githubusercontent.com/6207220/64595896-297a5300-d3b3-11e9-9597-abb9c49f7128.png)

  There's also this issue with errors being thrown:

  ![image](https://user-images.githubusercontent.com/6207220/64611779-80dbeb80-d3d2-11e9-964e-c4f04134cf13.png)
</details>

**Comment by thib92** [comment]
For the recognition of the package manager, we could use [`npx prefix`](https://docs.npmjs.com/cli/prefix) to find the closest directory with a `package.json`. I'm guessing that the `yarn.lock` and `package-lock.json` will always be in the same directory than `package.json`. Though running `npm prefix` required to have NPM installed, even if the repo uses Yarn. WDYT?

**Comment by lucasbento** [comment]
@thib92: that can be a solution, yeah.

I'm already working on that and I did something simpler, I try to identify the lockfile, if there's none then I just print a question asking the user which package manager to use and do the same as in #718.

**Comment by thib92** [comment]
@lucasbento sounds good too, simpler indeed!

**Comment by thib92** [comment]
I'll try adding some tests, starting with the individual healthchecks if that's ok

**Comment by lucasbento** [comment]
@thib92 thank you!

**Comment by lucasbento** [comment]
@thymikee @thib92: we are looking good in terms of what is left to do, do you both think that adding more tests is required for shipping this to production?

Any ideas on how we can do the `Agree on version ranges` point? do you see any version range in there that must be different?

**Comment by thib92** [comment]
More tests would be nice to have, but I think it's pretty safe to ship it as is.

When I rewrote the command to TS, I didn't find anything too weird, and TS definitely gives confidence already.

For the `Agree on version ranges`, I don't have any background on what exactly are needed from RN core. Is this info coming from the core team?

**Comment by thymikee** [comment]
I'm good with shipping it as is. I'll hopefully be back to do a proper release next week :)

**Comment by lucasbento** [comment]
> For the Agree on version ranges, I don't have any background on what exactly are needed from RN core. Is this info coming from the core team?

We don't really have anyone to tell what version should be good or not, we just need to make sure that whenever we implement something new, it must be tested against that version range or the range itself must be changed.

> I'm good with shipping it as is. I'll hopefully be back to do a proper release next week :)

Let's hold this a little bit as I want to do a little bit more testing next week if that's okay, I'll update here once I am done.

**Comment by thib92** [comment]
> Let's hold this a little bit as I want to do a little bit more testing next week if that's okay, I'll update here once I am done.

I'll probably have some time to add more tests in the meantime!

**Comment by globe21** [comment]
has anyone had this error? "Running diagnostics...error Cannot read property '0' of undefined."
This happens when diagnostics is about to start running.
<img width="1320" alt="Screen Shot 2019-11-21 at 11 14 41 AM" src="https://user-images.githubusercontent.com/1266746/69355655-296abf00-0c50-11ea-9433-d814dd4841c3.png">

**Comment by lucasbento** [comment]
Hi @globe21, can you please open a new issue for this? It seems like a bug so we would like to fix it.

**Comment by lucasbento** [comment]
I'm closing this issue as `doctor` has been released 🙂
