### ISSUE TITLE
Glitch when opening multiple debugger tabs

### ISSUE THREAD

**Issue by thecodrr** [react-native-community/cli#721]
## Environment
```
System:
    OS: Linux 4.19 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.02 GB / 15.55 GB
    Shell: 5.0.9 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.11.2 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2
      System Images: android-19 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```
## Description
There's a glitch in the `debugger-ui` if multiple `debugger` tabs are open. The text `Another debugger is already connected` keeps refreshing like crazy. Also, there are continuous output in the `Dev Console`.

## Reproducible Demo
1. Start metro using `react-native start`
2. Open two tabs with the `debugger-ui`

**Comment by thymikee** [comment]
cc @Esemesek, as he's working on extracting the debugger-ui to a separate package

**Comment by thymikee** [comment]
To fix the problem immediately, it's a matter of nulling debuggerSocket here:
https://github.com/react-native-community/cli/blob/f497f5a9f1bb0980488b989034d96b30ffd08747/packages/cli-server-api/src/websocket/debuggerProxyServer.ts#L56-L57
by adding `debuggerSocket = null;` on line 58. 

This will cause the new debugger window to overtake the session and previous one will be closed. Question – if this is the behavior we want? Maybe it's better to keep the initial session persistent and refuse adding another one? I'm not sure what are the well established practices at such scenario. Maybe we can have 2 debuggers connected and that's not bad? 

Let's discuss :)
