### ISSUE TITLE
react-native link Linking issues

### ISSUE THREAD

**Issue by subashtimalsina** [react-native-community/cli#734]
I am using react-native 0.59 on my project but i am facing react-native linking issue.
error Something went wrong while linking. Error: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "<" found.

This was the actual problem.

**Comment by thymikee** [comment]
You likely have merge conflicts somewhere that result in a Xcode project not being parsed (but maybe you have issue on Android? I don't know because you didn't tell me). Also, please follow the issue template and provide more information.
