### ISSUE TITLE
Correct way to link assets?

### ISSUE THREAD

**Issue by dotconnor** [react-native-community/cli#745]
## Ask your Question

With the new addition of auto-linking to the cli, what is the correct way to link assets without running `react-native link --all`?

I have tried creating a `react-native.config.js` with the following but it still doesn't link the assets correctly, unless there is a command I'm missing. Thanks.

```js
module.exports = {
  assets: [`./assets/fonts`],
};
```

**Comment by thymikee** [comment]
Just `react-native link` without any extra arguments links assets only.
