### ISSUE TITLE
init project get a fault version

### ISSUE THREAD

**Issue by GreatAuk** [react-native-community/cli#747]
## Environment

```
    OS: macOS Mojave 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 731.64 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.15.0 - ~/.nvm/versions/node/v11.15.0/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.7.0 - ~/.nvm/versions/node/v11.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.1, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.3 => 0.60.3
```

## Description
Type 
```npx react-native@0.61.0 init RNBlog --template react-native-template-typescript@next``` or ```npx react-native@next init RNBlog --template react-native-template-typescript@next```

Get version
![image](https://user-images.githubusercontent.com/20253809/65564081-5ff0ca00-df7e-11e9-81b6-8342166bbe4c.png)

**Comment by thymikee** [comment]
It's because the `--template` (here `react-native-tempate-typescript`) is a source of truth and it targets 0.60.3. That's expected behavior. You'll need to either manually adjust the numbers in package.json for now, or wait for the maintainers to release a new version, e.g. v2.0 tagged additionally on npm as `rn-0.61`. cc @radko93

**Comment by radko93** [comment]
@GreatAuk sorry for the delay, a new version is going to be releases soon

**Comment by radko93** [comment]
@GreatAuk it's up and running now, but you don't have to use`@next`. If you're using latest RN you don't need to point to template version.

**Comment by lucasbento** [comment]
@thymikee: perhaps this deserves a small message printed out when doing `react-native init` with a template?

We could check the latest version published against the version on the template and just print a small warning.

**Comment by thymikee** [comment]
But if you run `--template template-npm-package` it's gonna take the `latest`. If there's anything we could improve though, I'm happy to add it.

**Comment by lucasbento** [comment]
I meant that we can check the latest version of `react-native` against the `react-native` version specified on the template and then, if needed, show a warning.

**Comment by thymikee** [comment]
Not really sure about it. Would it make a real difference for a user to warn that this is not the latest version? @GreatAuk what do you think, is there anything more we can do for template users to feel less confused?

**Comment by GreatAuk** [comment]
@thymikee Sorry, I just a newbie, I don't have any good options😭

**Comment by radko93** [comment]
It makes some sense, as it's confusing right now when template is not up to date.
Maybe something like
> React Native version used to init this project is different than the one used by the template. If you think this is not correct create an issue on the template repo <repo_url>

**Comment by thymikee** [comment]
PR welcome then!
