### ISSUE TITLE
Hi how can i use this state in my render item?

### ISSUE THREAD

**Issue by rezamn21** [react-native-community/cli#751]
default class page1 extends Component {

  state = {
    
      paused : true,
    markers: [
      {

        title: "vidoe 1",
        Video: Videos[0],
      },
      {

        title: "video 2",
        Video: Videos[1],
      },
      {

        title: "video 3",
        Video: Videos[2],
      },
      {

        title: "video 4",
        Video: Videos[3],
      },
      {

        title: "video 5",
        Video: Videos[4],
      },
    ],
    paused: true,
  };

  _renderItem({ item, index }) {
     console.log(this.state);
    return (
      <View style={styles.card}>
        <View style={styles.cardImage1}>
          <Text style={styles.title}>{item.title}</Text>
        </View>

        <View style={styles.cardImage2}>
          <Video
            source={item.Video}
            style={styles.cardImage}
            resizeMode="contain"
            paused={this.state.paused}
            controls={true}
          />
        </View>

      </View>
    );
  }

  render() {
    console.log(CARD_HEIGHT);
    console.log(CARD_WIDTH);
    console.log(this.state);
    return (
      <View style={styles.container}>

        <View style={{
          height: CARD_HEIGHT,
          width: width,
          position: 'absolute',
          bottom: 15,
        }}>

          <Carousel

            slideStyle={{ marginHorizontal: 10 }}
            ref={(c) => { this._carousel = c; }}
            data={this.state.markers}
            renderItem={this._renderItem}
            sliderWidth={width}
            itemWidth={CARD_WIDTH}
            itemHeight={CARD_HEIGHT}
            sliderHeight={CARD_HEIGHT}
            // activeSlideOffset={20}
            // callbackOffsetMargin={50}
            // enableSnap={true}
            // activeAnimationOptions={1}
            // activeAnimationType={'spring'}
            inactiveSlideScale={0.9}

          // onSnapToItem={(index) => {
          //     this.animate(index)

          // }}

          />

        </View>
      </View>
    );

  }
}
 your question --> i cannot use this.state.paused in my render item of carousel

**Comment by thymikee** [comment]
Hey! I'm sorry, but this repo is for the CLI of React Native, not React Native. Please ask this question on StackOverflow or on some support forum, but it's not here.
