### ISSUE TITLE
React Native 0.61 - Autolinking

### ISSUE THREAD

**Issue by nar213** [react-native-community/cli#753]
## Are we no longer able to use modules that are unable to be auto linked in iOS? 

In the React-Native 0.61 blog post it stated that ```Remove React .xcodeproj. In 0.60, we introduced auto-linking support via CocoaPods. We have also integrated CocoaPods into the e2e tests runs, so that from now on, we have a unified standard way of integrating RN into iOS apps. This effectively deprecates the React .xcodeproj support, and the file has been removed starting 0.61. Note: if you use 0.60 auto-linking already, you shouldn't be affected.```

Does this suggest using react-native.config.js no longer works for iOS for packages that don't yet support autolinking? When I upgrade I continually run into missing RCT files or missing libraries based on linker flag. Thanks.

**Comment by thymikee** [comment]
No, you can use other libraries without CocoaPods , but React itself will be consumed only from CocoaPods.
