### ISSUE TITLE
Template: config not found

### ISSUE THREAD

**Issue by artyorsh** [react-native-community/cli#755]
Hi guys. I'm really confused about why this occurs, but:
I have two template packages with absolutely same structure. [One](https://github.com/akveo/react-native-ui-kitten/tree/master/src/templates/template-ui-kitten) and [two](https://github.com/artyorsh/react-native-template-ui-kitten)
Both of them are published on npm, but for any reason I'm not able to use the first one, while the second is working. Please, see [screenshot](https://monosnap.com/file/wXJftE9pz5yHGFRqW6rwWY5KH3LCBN)

Appreciate your help, thanks

**Comment by thymikee** [comment]
Maybe it's a permission issue with the temp directory?

**Comment by artyorsh** [comment]
Got this working. The issue was on my side :) Anyway, thanks for the reply
