### ISSUE TITLE
Addition of a `postInstallScript` for running scripts after dependencies are installed

### ISSUE THREAD

**Issue by cball** [react-native-community/cli#756]
## Describe the Feature
We have been manually running a setup script after `react-native init` on projects. The new `postInit` script is great! For our needs though, we're relying on a package that we list in `devDependencies`, and `postInit` runs before dependencies are installed.

I'd like to add a `postInstallScript` option that is run after dependencies are installed.

## Possible Implementations
I would take the exact same approach of `postInitScript`, but call a `postInstallScript` if defined in `template.config.js`.

## Related Issues
(none I can find)

Happy to tackle the implementation of this, I just wanted to get approval before I do so.

**Comment by thymikee** [comment]
Um, you can define a "postinstall" step in the package.json?

**Comment by cball** [comment]
🤦‍♂ Ha! I have no idea why that didn't occur to me.

**Comment by cball** [comment]
Hey @thymikee, turns out this isn't going to work.

Our setup script collects input from the user to perform certain actions. Unless the `--verbose` flag is used, that input is hidden, and the cli appears to be stuck on `installing dependencies`. We also output a few additional info lines on what we're doing which would also be hidden.

On top of that, we only want this script to run a single time (during the `react-native init` process). Using `postinstall` in the template's package.json, we would have to remove that line from `package.json` after it runs. Certainly doable, but not ideal.

Looking at my original issue, I realize I wasn't very clear about what we were doing. Here are some examples:
- run solidarity to ensure system dependencies like Ruby, Node, GraphicsMagick are present
- prompt the user for the app display name and bundle (this is automated somewhat via the template, but we just want to confirm
- prompt to initialize a git repo
- setup default app icons and splash screens
- set a proper semver version

We use a few external tools like `hygen`, `enquirer`, and `solidarity`, so we want to ensure those are installed before our setup script runs.
