### ISSUE TITLE
Get rid of a global "react-native-cli" package

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#76]
Waiting for the detailed write-up from @thymikee on this one.

**Comment by cpojer** [comment]
One thing to consider is that `npx` and `yarn` use separate caches, so if you were using both, the cache has to be warmed up twice.

**Comment by pvinis** [comment]
do you mean npx or npm?

**Comment by cpojer** [comment]
They use the same cache for global modules.

**Comment by thymikee** [comment]
@cpojer is there a proposal for `npx` equivalent for yarn? there was `yarn create` but I don't think it covers this use case?

**Comment by cpojer** [comment]
I don't think there is but since the logic is already there with `create`, it should be easy to propose a new command and send a PR with the same feature.

**Comment by thymikee** [comment]
Time to prepare a RFC for this then. I'll try to set this up this week, but if anybody willing to work on it earlier, feel free to do so and make us know :)

**Comment by thymikee** [comment]
FYI I've spoken to @arcanis and I plan to PR a new `yarn gx` command (global execute) that would install the package globally populating the cache (would most likely base on `yarn create` code).

So, if you're npm fan you'll use 
```
npx react-native init MyApp
```
And for Yarn lovers:
```
yarn gx react-native init MyApp
```

How does that sound?

**Comment by cpojer** [comment]
I think that's good. We could make it so that `react-native-cli` gets updated and just calls either of the two.

**Comment by thymikee** [comment]
You mean for the back compat? I thought about ditching that package and don't mention it in official docs

**Comment by cpojer** [comment]
Yeah, for backwards compat we should probably do it.

**Comment by pvinis** [comment]
isn't `yarn bla` looking for a script called `bla` first, and then looking for a local bin called `bla`?

**Comment by rickhanlonii** [comment]
@thymikee I'm not in love with it - it seems to do the same as `yarn create` but doesn't have most of the advantages of `npx`. If you put in an RFC, I can leave some thoughts

**Comment by thymikee** [comment]
I'll let you all know once I make RFC, I didn't post everything in my comment :D

**Comment by thymikee** [comment]
FYI https://github.com/yarnpkg/rfcs/pull/113

**Comment by thymikee** [comment]
We're not getting rid of it, however some day we'll remove the legacy `init` living there and make it to be only a proxy to the actual CLI for convenience if some prefer global packages.
