### ISSUE TITLE
Handle Work Profile / Several Android Users

### ISSUE THREAD

**Issue by adrienthiery** [react-native-community/cli#765]
## Describe the Feature

We are using [Android for Work](https://www.android.com/enterprise/employees/) in our company, which makes a nice "sandbox" and makes sense in the context of our jobs.

A great feature would be to be able to install  the project ONLY in that profile and run it in that profile, instead of in the "first" profile.

In addition to a feature request, it is actually a feature proposition, as I would like to implement it.

## Possible Implementations

The idea would be that when running on Android (`react-native run-android`) : 
* a check on the user profiles (`adb shell pm list users`) could be run
* if several users are detected, propose a choice to the user : 
   * Choose a user workspace to install in (with an option `all`)
   * Choose a user to launch it in
* Propose to save that as a default for that project.

When running the app subsequently, use the default.

This could come with a setting in `react-native.config.js` and/or a flag to clear the default when running `run-android`

## Related Issues

None that I know of

## Relevant links

- https://stackoverflow.com/questions/43344576/appium-how-to-launch-app-from-android-for-work-work-profile
- https://stackoverflow.com/questions/20746422/how-to-use-adb-to-install-development-apps-for-one-user-only

**Comment by thymikee** [comment]
Sounds like a good idea. We can start with an interactive behavior + a flag for non-interactive mode and see how that works. Not yet sure what would be the most ergonomic way of configuring commands through the configuration. Let's leave that for a separate discussion.

One more thing, we'll likely make choosing an emulator interactive as well (on master there's a feature that it picks the first available). Please take that into consideration when picking the best DX for this – answering 2 or more questions for every `run-android` may be a chore, but maybe not.

**Comment by adrienthiery** [comment]
Hi @thymikee, I started to work on that but I can't seem to find how to test my changes.

I initialized a new RN App, and in it I tried :
* To `yarn add <local-path-of-cli-repo>/packages/cli` or `yarn link <local-path-of-cli-repo>/packages/cli` and then in my project `yarn link @react-native-community/cli`
* To `yarn add <local-path-of-cli-repo>/packages/platform-android` or `yarn link <local-path-of-cli-repo>/packages/platform-android` and then in my project `yarn link @react-native-community/platform-android`

I also tried to modify the `node_modules/.bin/react-native` with no luck.

How can I run my local version of the CLI packages? 🤔

**Comment by homersimpsons** [comment]
Is there any news on this one ? Adding a cli options should be the first step, I don't think having an interactive behavior is desirable at first.

**Comment by homersimpsons** [comment]
FTR I do not have the need anymore as I am manually updating the code to install the app to the right user id. But this could be a real quality of life change. I still think that adding a `--userId` (along with the `--deviceId`) should be easy enough.

**Comment by homersimpsons** [comment]
Exactly, for my specific case I did update the following line:

https://github.com/react-native-community/cli/blob/9d177288d8967039e654d8b0044f6c7219abffe1/packages/cli-platform-android/src/commands/runAndroid/tryInstallAppOnDevice.ts#L48

```diff
-     const adbArgs = ['-s', device, 'install', '-r', '-d', pathToApk];
+     const adbArgs = ['-s', device, '--user', '10', 'install', '-r', '-d', pathToApk];
```

Here the user '10' corresponds to the one for my work profie.

To find the user I had to manually list them with `adb shell pm list users`.

Note that @adrienthiery did start a similar work few years ago there https://github.com/react-native-community/cli/pull/807 that may be relevant.

**Comment by adamTrz** [comment]
Wow, have not seen #807, seems is way back before my times in CLI 😉 
I'll try to implement requested feature soon, mind helping me with testing it then @homersimpsons ? 🙏

**Comment by homersimpsons** [comment]
> mind helping me with testing it then @homersimpsons ?

Yes definitey !

**Comment by adamTrz** [comment]
@homersimpsons mind taking a look at #1869 ? :)

**Comment by homersimpsons** [comment]
Thank you for this addition, sorry I did not take more time to test it.
