### ISSUE TITLE
Babel issue for android build

### ISSUE THREAD

**Issue by id-ilych** [react-native-community/cli#772]
## Environment

System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 258.95 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description

1. `react-native init`
2. Use ternary operator to show different text depending on state toggled by a button
3. `yarn add --dev @babel/cli babel-plugin-jsx-control-statements`
4. Update `babel.config.js` to use installed plugin
5. Replace ternary operator with `Choose/When/Otherwise`
6. `react-native run-android` (or run using Android Studio)
7. Observe `ReferenceError: Can't find variable: Choose`

Important:
1. iOS version seems to works just fine.
2. Using `npx babel App.js` I get almost identical results at steps 4 and at 6 (the only difference is in `lineNumber` parameter as expected)

So I presume the problem is in an Android build configuration produced by `react-native init`

## Reproducible Demo

https://github.com/id-ilych/rn_babel_issue

**Comment by grabbou** [comment]
This is not a CLI issue. Please open this in either React Native or Metro. Thank you!
