### ISSUE TITLE
Less Gradle paths tied to React Native

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#776]
Can we replace:
```
maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../../../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../../../node_modules/jsc-android/dist")
        }

```
with a CLI-generated code? CLI is able to detect the path to `react-native` dynamically, would require fewer changes to be applied by users when dealing with a `mono repo`.

It would be great if we could also replace:
```
apply from: "../../../../node_modules/react-native/react.gradle"
```
with
```
apply from: {dynamicallyResolvedReactNativePath}
```
(e.g. previously set by the CLI global variable).

**Comment by sibelius** [comment]
related to https://github.com/react-native-community/cli/issues/865

**Comment by kennym** [comment]
is this not possible?
