### ISSUE TITLE
Run ios failing on new project

### ISSUE THREAD

**Issue by zRelux** [react-native-community/cli#778]
## Description

I used this command to setup a new project `npx react-native init MyApp --template react-native-template-typescript` then after installation I ran `yarn ios` the simulator got opened but the app was not able to do so because my antivirus blocks port 8081, I tried to follow [change](https://facebook.github.io/react-native/docs/0.60/troubleshooting) but I coulnd't find `node_modules/react-native/React/React.xcodeproj/project.pbxproj` in vscode it seems that it didn't install so I tried to delete `node_module` and installed again but no luck. Any help?

**Comment by thymikee** [comment]
Ah yes, this is something I bumped a while ago as well. Custom port works on Android, but has issues on iOS. Would you like to investigate the fix? :)

**Comment by zRelux** [comment]
Yes i'll keep you updated if I find something, may I know what we have tried just so I don't waste time retrying stuff?

**Comment by thymikee** [comment]
Didn't try anything, but the code will be inside `packages/platform-ios`, I'm sure you can make it :)

**Comment by zRelux** [comment]
Update using `react-native run-ios --port 3000` will make the app instance in the simulator but will run the metro bundler on `8081`, I can't find where the metro instance is instantiated any help?

**Comment by zRelux** [comment]
Still can't figure out how to fix, may I know what you tried for android?

**Comment by zRelux** [comment]
Made it work by adding 
```
  server: {
    port: 3000,
  },
```

and `export RCT_METRO_PORT=3000; react-native run-ios` to package json

**Comment by zRelux** [comment]
Still wanna see if I can update it in a better way

**Comment by scarcoco** [comment]
```
server: {
    port: 8888
}
```
```
react-native run-ios 
```

simulator -> No Bundle URL
