### ISSUE TITLE
[Monorepo] Android bundle release - Process 'command 'node'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by k3nda** [react-native-community/cli#779]
## Environment

System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 9.62 GB / 31.21 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v10.5.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.5.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    **react: 16.9.0 => 16.9.0** 
  npmGlobalPackages:
    **react-native-cli: 2.0.1**

**"react-native": "0.61.2" and "react-native": "^0.60.5"**
Android studio: 3.5.1
## Description

1. Run `react-native init AwesomeProject` (now it is NOT monorepo yet)
2. Run in android studio Generate signed bundle (`:app:bundleReleaseJsAndAssets`)
3. Everything is ok, app is released
4. **Convert project to monorepo** (update structure and all paths e.g. in `settings.gradle` or `build.gradle`):
![image](https://user-images.githubusercontent.com/12560054/66595618-9d1ea400-eb9b-11e9-86ca-c1d7300577c7.png)
5. Fixed issue `Text must not be null or empty` by updating `node_modules/@react-native-community/cli-platform-android/native_modules.gradle` with `def command = "../node_modules/.bin/react-native config"` (as mentioned / resolved in other issues there)
6. Run again Generate signed bundle and ends up with error:
![image](https://user-images.githubusercontent.com/12560054/66596048-73b24800-eb9c-11e9-9461-8379642bcbab.png)

Before updating my project to RN 0.60.5 and creating it newly via CLI, I used to use RN 0.59 with same monorepo structure (project was NOT created by CLI) and everything worked fine.
Now I created new empty project with CLI and RN 0.60.5 (or 0.61.2, both same issue), started slowly adding source code (actually nearly empty project) and tried to do release for android and it failed with mentioned error.
## Reproducible Demo

Described above, nothing special. Just empty project created with React Native CLI and converted to monorepo, trying to do release of android AAB or APK. If someone really need whole source let me know and I will put it into github.

**Comment by grabbou** [comment]
This will be fixed with another release by #768.

**Comment by k3nda** [comment]
in which version and when it will be please?
