### ISSUE TITLE
Unable to resolve module

### ISSUE THREAD

**Issue by guhyeon** [react-native-community/cli#784]
## Environment

System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
    Memory: 694.41 MB / 7.95 GB
  Binaries:
    Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.11.3 - C:\Users\guhyeon\AppData\Roaming\npm\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28
      Build Tools: 19.1.0, 20.0.0, 21.1.2, 22.0.1, 23.0.1, 23.0.2, 23.0.3, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.0, 28.0.0, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.2
      System Images: android-19 | ARM EABI v7a, android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom_64, android-24 | Google Play Intel x86 Atom, android-25 | Google APIs ARM 64 v8a, android-25 | Google APIs ARM EABI v7a, android-25 | Google APIs Intel x86 Atom, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2

## Description

error: bundling failed: Error: Unable to resolve module `./C:/Users/guhyeon/AppData/Roaming/npm/node_modules/@react-native-community/cli/node_modules/react-transform-hmr/lib/index.js` from `E:\Project\RN\practice\todolistP1\node_modules\react-native\Libraries\Components\CheckBox\CheckBox.android.js`: The module `./C:/Users/guhyeon/AppData/Roaming/npm/node_modules/@react-native-community/cli/node_modules/react-transform-hmr/lib/index.js` could not be found from `E:\Project\RN\practice\todolistP1\node_modules\react-native\Libraries\Components\CheckBox\CheckBox.android.js`. Indeed, none of these files exist:
  * `E:\Project\RN\practice\todolistP1\node_modules\react-native\Libraries\Components\CheckBox\C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\react-transform-hmr\lib\index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `E:\Project\RN\practice\todolistP1\node_modules\react-native\Libraries\Components\CheckBox\C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\react-transform-hmr\lib\index.js\index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)
    at Object.resolve (C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\lib\transformHelpers.js:264:42)
    at C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)
    at C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\guhyeon\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 BUNDLE  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 2.0% (17/190), failed.

## Reproducible Demo

`npm uninstall -g react-native-cli`
`npm i -g @react-native-community/cli`
`react-native start`

**Comment by thymikee** [comment]
Do you have some of the native libraries linked by `npm link` or `yarn link`? Anyway, this is not an issue with CLI, but likely Metro bundler. Try clearning up its cache: `react-native start --reset-cache` or go to tmp dir and remove all references to "metro" or "haste".
