### ISSUE TITLE
Unable to determine the current character, it is not a string, number, array, or object

### ISSUE THREAD

**Issue by caro-li** [react-native-community/cli#785]

**Comment by alviankosim** [comment]
hello, in my case, it's because of my mistake. unfortunately i remove closing tag `>` inside `AndroidManifest.xml`. After i put it again, it works with no error.

But, before i find out the problem. On the internet, they suggest me to delete `android/app/build` folder.

hope it helps :)

**Comment by topsion-12345** [comment]
How to fix this bug?
Solution 1: run npm i --save @react-native-community/cli-platform-android
Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json

Works! Thnx

**Comment by ufukucar** [comment]
> 
> 
> How to fix this bug?
> Solution 1: run npm i --save @react-native-community/cli-platform-android
> Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json
> 
> Works! Thnx

Thanks man. 
Solution-2 worked for me!

**Comment by sarykemmoun** [comment]
> hello, in my case, it's because of my mistake. unfortunately i remove closing tag `>` inside `AndroidManifest.xml`. After i put it again, it works with no error.

@alviankosim 
Thanks!
It was my problem too.

**Comment by aliahmedbd** [comment]
> How to fix this bug?
> Solution 1: run npm i --save @react-native-community/cli-platform-android
> Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json
> 
> Works! Thnx

Thanks, man. The solution is worked for me.

**Comment by matyneKnight** [comment]
> How to fix this bug?
> Solution 1: run npm i --save @react-native-community/cli-platform-android
> Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json
> 
> Works! Thnx

Thanks man,
when I tried solution 2, it didn't work but when i delete app\build\intermediates\signing_config\release\out\signing-config.json, it worked!

**Comment by shani-maini** [comment]
In my case I don't have signing-config.json on my react-native project still facing an issue.

**Comment by shani-maini** [comment]
Hey guys,

I found a solution 

step 1: delete your app/build folder
step 2: goto your project/android>gradlew clean
step 3: project>npx react-native run-android

**Comment by Raheelbutt786** [comment]
> How to fix this bug?
> Solution 1: run npm i --save @react-native-community/cli-platform-android
> Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json
> 
> Works! Thnx

worked for me thanku

**Comment by infinitbility** [comment]
I Follow Below blog and it's work for me

https://medium.com/@tiwarishani/unable-to-determine-the-current-character-it-is-not-a-string-number-array-or-object-in-react-f34c80d96e8e

**Comment by hadpro24** [comment]
> How to fix this bug?
> Solution 1: run npm i --save @react-native-community/cli-platform-android
> Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json
> 
> Works! Thnx

Thanks. The first method works for me

**Comment by adnan1234-ad** [comment]
I have no app/build folder in the project but getting the same error 
I tried the same solution but did not fix it 
Solution 1: run npm i --save @react-native-community/cli-platform-android
Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json

**Comment by vincentmegia** [comment]
in my case after upgrading grade plugin in android studio, I've noticed that package in AndroidManifest.xml was removed. Putting it back solved it

**Comment by abdulbari149** [comment]
> in my case after upgrading grade plugin in android studio, I've noticed that package in AndroidManifest.xml was removed. Putting it back solved it

Thanks Man, It really helped me solve my issue

**Comment by arslanafzal077** [comment]
i have this issue with react-native 0.69 also add the @react-native-community/cli-platform-android but still got the same error

**Comment by szymonrybczak** [comment]
@arslanafzal077 please see https://github.com/react-native-community/cli/issues/1981#issuecomment-1637890468

**Comment by ahaseeb001** [comment]
> How to fix this bug? Solution 1: run npm i --save @react-native-community/cli-platform-android Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json
> 
> Works! Thnx

worked for me 
for me no need to del this file : platform-android Solution 2:Try deleting app\build\intermediates\signing_config\debug\out\signing-config.json

**Comment by deathook007** [comment]
For me, the problem was located within the file at `node_modules/@react-native-camera-roll/camera-roll/android/src/main/java/AndroidManifest.xml`

The absence of this attribute was causing complications during the build process.

The original content of the AndroidManifest.xml file appeared as follows:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android">`

I added the missing package attribute to the manifest element as shown below:
`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.reactnativecommunity.cameraroll">
`

**Comment by longnc100500** [comment]
> For me, the problem was located within the file at `node_modules/@react-native-camera-roll/camera-roll/android/src/main/java/AndroidManifest.xml`
> 
> The absence of this attribute was causing complications during the build process.
> 
> The original content of the AndroidManifest.xml file appeared as follows: `<manifest xmlns:android="http://schemas.android.com/apk/res/android">`
> 
> I added the missing package attribute to the manifest element as shown below: `<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.reactnativecommunity.cameraroll"> `

same as "react-native-wheel-pick"

**Comment by FlowerbeanAnsh** [comment]
I was facing the same issue, just added package in the below file and it just worked !!

/android/app/src/main/AndroidManifest.xml

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.rnmaps.maps" >
</manifest>
