### ISSUE TITLE
Confusing error message when Xcode wants to install extra components

### ISSUE THREAD

**Issue by gaearon** [react-native-community/cli#786]
## Environment

```
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Memory: 1.40 GB / 16.00 GB
    Shell: 2.6.0 - /usr/local/bin/fish
  Binaries:
    Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
    Yarn: Using globally installed version of Yarn
1.12.1 - /opt/facebook/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.10.0/bin/npm
    Watchman: 4.9.4 - /opt/facebook/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2
```

## Description

Tried to run `yarn ios`. Got this:

<img width="886" alt="Screen Shot 2019-10-14 at 3 30 46 PM" src="https://user-images.githubusercontent.com/810438/66760066-436af200-ee99-11e9-9657-0ce063b545e1.png">

The actual problem was that when I started Xcode, it asked to install "missing components".

## Reproducible Demo

I suppose, run any projects when Xcode has "missing components".

## So What?

If we can detect this particular problem, we can show a better message than "could not parse JSON". Ideally we should launch the command that prompts to install those Xcode "missing components" automatically.

**Comment by rickhanlonii** [comment]
Looks like this comes from a basic try/catch [here](https://github.com/react-native-community/cli/blob/77af4934049846c308c94d58817931ec30a9c494/packages/platform-ios/src/commands/runIOS/index.ts#L128).

To fix, as you said, we could print a message like:

> Could not get simulator list from Xcode. Xcode reported this issue: <print CLI response>

Seems like a great first issue for Hacktoberfest, I'm happy to help out anyone who is interested

**Comment by iansu** [comment]
I’m interested in working on this if it’s still available.

**Comment by rickhanlonii** [comment]
Thanks @iansu, @SBinLondon is going to tackle this!

**Comment by grabbou** [comment]
Thanks for reporting. We can say something similar to: "Could not get simulator list from Xcode. Please open Xcode and try running project directly from there to resolve remaining issues". 

Alternatively, we can also detect this particular "missing components" issue and prompt about it. Are you setting up a new machine @gaearon?

**Comment by gaearon** [comment]
It was an existing machine. Maybe I did a system update or something.

**Comment by Taym95** [comment]
I had the same issue fixed with starting the Xcode application and it starts to install some pending tools update. After Xcode updates, my app started working normally.
