### ISSUE TITLE
Configure babel config

### ISSUE THREAD

**Issue by pturchik** [react-native-community/cli#796]
How I can use different babel config for debug and release builds?

I generated base project using `npx react-native init MyApp` and then replace default `babel.config.js` content to 
```javascript
module.exports = {
  env: {
    development: {
      presets: ['module:metro-react-native-babel-preset']
    },
    production: {
      presets: ['module:metro-react-native-babel-preset']
    }
  }
}
```

Debug build works fine, but release build (`yarn ios --configuration=Release`) throw an error `Error: Import statement may only appear at top level in file node_modules/react-native/Libraries/NewAppScreen/index.js`.

Can anyone help me ?

**Comment by grabbou** [comment]
Your Babel configuration looks good to me and production/development keys should be picked based on the `react-native start` environment (start server in release/dev mode) or, for example, configuration for iOS build.

I would suggest opening an issue in the React Native / Metro repository or googling for an answer - this "import statement" error has been quite common case.

CLI itself works "just fine", the app is built and the project starts. We do not process your files. That's what Metro does :)

**Comment by pturchik** [comment]
> Your Babel configuration looks good to me and production/development keys should be picked based on the `react-native start` environment (start server in release/dev mode) or, for example, configuration for iOS build.
> 
> I would suggest opening an issue in the React Native / Metro repository or googling for an answer - this "import statement" error has been quite common case.
> 
> CLI itself works "just fine", the app is built and the project starts. We do not process your files. That's what Metro does :)

Thanks)
