### ISSUE TITLE
[run-ios] Wrong .app file path while installing on simulator

### ISSUE THREAD

**Issue by Kdoherty11** [react-native-community/cli#798]
I am able to build/run my app through Xcode but not through `react-native run-ios`. It looks like it gets through the build step successfully, but then doesn't use the correct `.app` path when actually installing on the simulator. 

<img width="1019" alt="Screen Shot 2019-10-15 at 10 59 13 PM" src="https://user-images.githubusercontent.com/1815585/66884505-6e3f6e00-ef9f-11e9-85bd-1ff2db9e9e8c.png">

It looks like https://github.com/react-native-community/cli/pull/758 was solving a similar problem. However, if this is the same issue I'd be happy to submit a PR with a more general solution. Something like:
- Change the existing logic to use an array of potential `.app` paths and use the first one which is found
- If none are found, exit with a useful error message
- Add a `buildPath` override flag so users can unblock themselves if they hit the above error

```
~/d/j/w/workout-log-native ❯❯❯ react-native info                                                             upgrade-react-native-58-to-59 ✭ ✱ ◼
info
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
      Memory: 204.96 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.10.1 - ~/.nvm/versions/node/v11.10.1/bin/node
      Yarn: 1.19.1 - /usr/local/bin/yarn
      npm: 6.7.0 - ~/.nvm/versions/node/v11.10.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 21, 22, 23, 24, 25, 26
        Build Tools: 21.1.2, 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-25 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.10 => 0.59.10
~/d/j/w/workout-log-native ❯❯❯ react-native --version
react-native-cli: 2.0.1
react-native: 0.59.10
```
[Xcode workplace settings](https://user-images.githubusercontent.com/1815585/66884140-3d126e00-ef9e-11e9-9b05-4c81255fd05a.png)
[Xcode workplace settings build location](https://user-images.githubusercontent.com/1815585/66884205-7cd95580-ef9e-11e9-8db0-5562908fccbd.png)

Thanks for looking into it and please let me know if you need any more info!

**Comment by thymikee** [comment]
AFAIK, cfbundleidentifier is fixed in the RN 0.60+. Please upgrade :)
