### ISSUE TITLE
Command to link only assets

### ISSUE THREAD

**Issue by ferrannp** [react-native-community/cli#8]
Something like `react-native link --assets` ? Right now I cannot find a way to do this and it's not good in my project to run the whole `react-native link`.

Another interesting stuff is that you can run `react-native link anyPackage` and it will also link all the assets too. Is that desirable ?

**Comment by grabbou** [comment]
> Another interesting stuff is that you can run react-native link anyPackage and it will also link all the assets too. Is that desirable ?

That is a bug. It should link only assets from that project.

**Comment by punksta** [comment]
https://github.com/unimonkiez/react-native-asset this thing can link only assets

**Comment by thymikee** [comment]
Since v2 `link` only affects assets by default. Closing :)
