### ISSUE TITLE
There are two packages miss version 3.0.0-alpha.7

### ISSUE THREAD

**Issue by xxapp** [react-native-community/cli#803]
## Environment

System:
    OS: macOS Mojave 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 1.28 GB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.3 - ~/.nvm/versions/node/v10.13.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.13.0/bin/npm
    Watchman: 4.7.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 22, 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
  IDEs:
    Android Studio: 3.1 AI-173.4720617
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description

The `cli` and `cli-platform-ios` had released version 3.0.0-alpha.7，but the `cli-tools` and `cli-platform-android` still be version 3.0.0-alpha.6

## Reproducible Demo

``` bash
$ npm info @react-native-community/cli@next version
> 3.0.0-alpha.7
$ npm info @react-native-community/cli-platform-ios@next version
> 3.0.0-alpha.7
$ npm info @react-native-community/cli-tools@next version
> 3.0.0-alpha.6
$ npm info @react-native-community/cli-platform-android@next version
> 3.0.0-alpha.6
```

**Comment by xxapp** [comment]
@thymikee Please take a look at this

**Comment by thymikee** [comment]
Looks like the npm network cache or your lock file? They're all published:
https://www.npmjs.com/package/@react-native-community/cli-platform-android/v/3.0.0-alpha.7
https://www.npmjs.com/package/@react-native-community/cli-tools/v/3.0.0-alpha.7
