### ISSUE TITLE
How can I regenerate ios folder in React Native project?

### ISSUE THREAD

**Issue by joaodematejr** [react-native-community/cli#808]
## Ask your Question

How can I regenerate ios folder in React Native project?

react-native-cli: 2.0.1
react-native: 0.61.2

❯ react-native eject
error Unrecognized command "eject".
info Run "react-native --help" to see a list of all available commands.

❯ react-native upgrade --legacy true
error: unknown option `--legacy'

**Comment by thymikee** [comment]
You can init a new project that's named the same in another folder and copy ios dir over:
```sh
# inside YourProjectName directory
npx react-native init YourProjectName
mv YourProjectName/ios ios
rm -rf YourProjectName
```
Make sure you have clean git history before doing so, in case you need to revert

**Comment by joaodematejr** [comment]
thanks

**Comment by KaneNguyen** [comment]
> You can init a new project that's named the same in another folder and copy ios dir over:
> 
> ```shell
> # inside YourProjectName directory
> npx react-native init YourProjectName
> mv YourProjectName/ios ios
> rm -rf YourProjectName
> ```
> 
> Make sure you have clean git history before doing so, in case you need to revert

Omg, Why do that?, Can we use "react-native upgrade --legacy true or react-native eject" ?

**Comment by socialty** [comment]
think there should be an command like **eject**

**Comment by thymikee** [comment]
@socialty If you feel like it, please create a detailed feature request with a motivation for why it's worth to spend time implementing such a feature, when you can do so manually without too much hassle (no great DX, but possible).

**Comment by frederickjjoubert** [comment]
> > You can init a new project that's named the same in another folder and copy ios dir over:
> > ```shell
> > # inside YourProjectName directory
> > npx react-native init YourProjectName
> > mv YourProjectName/ios ios
> > rm -rf YourProjectName
> > ```
> > 
> > 
> > Make sure you have clean git history before doing so, in case you need to revert
> 
> Omg, Why do that?, Can't we use "react-native upgrade --legacy true or react-native eject"?

It appears the latest version of react native got rid of those commands :(

**Comment by panda6412** [comment]
> think there should be an command like **eject**

As above react-native version, it seems like have been removed

**Comment by manusans** [comment]
> You can init a new project that's named the same in another folder and copy ios dir over:
> 
> ```shell
> # inside YourProjectName directory
> npx react-native init YourProjectName
> mv YourProjectName/ios ios
> rm -rf YourProjectName
> ```
> 
> Make sure you have clean git history before doing so, in case you need to revert

thanks... I was getting crazy. Is this the only way? really??!!

**Comment by supreme** [comment]
> You can init a new project that's named the same in another folder and copy ios dir over:
> 
> ```shell
> # inside YourProjectName directory
> npx react-native init YourProjectName
> mv YourProjectName/ios ios
> rm -rf YourProjectName
> ```
> 
> Make sure you have clean git history before doing so, in case you need to revert

Although not ideal, seems to be the best option for now. Thanks!

**Comment by juzerdhinoj** [comment]
Add command to regenerate iOS or Android file incase of a mess up

**Comment by joaodematejr** [comment]
Command already existed in previous versions of RN, but has been removed.

**Comment by Dalcio** [comment]
I solve this on ubuntu 20.04 running:
sudo npx react-native run-android

**Comment by chiragbaraliya** [comment]
> You can init a new project that's named the same in another folder and copy ios dir over:
> 
> ```shell
> # inside YourProjectName directory
> npx react-native init YourProjectName
> mv YourProjectName/ios ios
> rm -rf YourProjectName
> ```
> 
> Make sure you have clean git history before doing so, in case you need to revert

This one is great option!!

**Comment by yangxyo** [comment]
```sh
ln -s /opt/homebrew/opt/node@16/bin/node /opt/homebrew/bin/node
```

**Comment by Sushil-Takkekar** [comment]
> ## Ask your Question
> How can I regenerate ios folder in React Native project?
> 
> react-native-cli: 2.0.1 react-native: 0.61.2
> 
> ❯ react-native eject error Unrecognized command "eject". info Run "react-native --help" to see a list of all available commands.
> 
> ❯ react-native upgrade --legacy true error: unknown option `--legacy'

Answer --

No need to copy/rename a new project. You can simply try below commands. It worked for me.
1. Install eject module : ❯ npm i react-native-eject
2. Run eject command : ❯ npx react-native eject

This will create ios & android folder inside your project.

**Comment by smithkashyapdev** [comment]
> 2\. npx react-native eject

Error: Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'

**Comment by dstamou** [comment]
> > 2. npx react-native eject
> 
> Error: Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'

Same here. :-(

**Comment by yorlandmurillo** [comment]
I was able to create a new folder for android and iOs.

I was installing the latest version of react-native-community, and after several tries failing, I decided to install a lower version:

`npm i @react-native-community/cli@8.0.6`

Remember to create an app.json file with these two lines:

`{
    "name":"YourProyect",
    "displayName":"YourProyect"
}`

And then, run the command 'react-native eject' and you'll have your folders.

**Comment by godfredakpan** [comment]
> > 2. npx react-native eject
> 
> Error: Cannot find module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'

For this to work you have to install react-native-eject `yarn add react-native-eject`

if you get this error; `error You need to install `@react-native-community/template@0.75.1` before ejecting.`

then do this `yarn add @react-native-community/template@0.75.1`

and run this `npx react-native eject`

IT WORKED FOR ME
