### ISSUE TITLE
Run instructions should be prefixed with `npm run`, `npx`, or `yarn`.

### ISSUE THREAD

**Issue by wvteijlingen** [react-native-community/cli#813]
## Environment

```
  Binaries:
    Node: 12.12.0 - /var/folders/1d/5gcf_ld56y56ly819fxg9ys40000gn/T/yarn--1571480379347-0.9331870332298509/node
    Yarn: 1.19.1 - /var/folders/1d/5gcf_ld56y56ly819fxg9ys40000gn/T/yarn--1571480379347-0.9331870332298509/yarn
    npm: 6.11.3 - ~/.nodenv/shims/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2
```

## Description

After initialising a new project, the run instructions tell you to run `react-native run-ios` or `react-native run-android` in the project directory. This doesn't work, because these commands need to be prefixed with `npm run`, `npx`, or `yarn`.

## Reproducible Demo

```
npx react-native init MyProject
cd MyProject && react-native run-ios
```

results in: `-bash: react-native: command not found`

**Comment by Taym95** [comment]
I think this `-bash: react-native: command not found` means you don't have `react-native` globally installed?!

**Comment by thymikee** [comment]
> I think this -bash: react-native: command not found means you don't have react-native globally installed?!

That's a good thing! Yes, run instructions should be prefixed with `npx` or `yarn`  to get the local `react-native` binary exposed by `@react-native-community/cli`

**Comment by Taym95** [comment]
Something like that `cd ${projectDir} && npx react-native run-ios` ?

**Comment by thymikee** [comment]
Yup
