### ISSUE TITLE
"name" field in generated package.json can contain invalid characters

### ISSUE THREAD

**Issue by wvteijlingen** [react-native-community/cli#814]
## Environment

```
  Binaries:
    Node: 12.12.0 - /var/folders/1d/5gcf_ld56y56ly819fxg9ys40000gn/T/yarn--1571480379347-0.9331870332298509/node
    Yarn: 1.19.1 - /var/folders/1d/5gcf_ld56y56ly819fxg9ys40000gn/T/yarn--1571480379347-0.9331870332298509/yarn
    npm: 6.11.3 - ~/.nodenv/shims/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 28.0.3
      System Images: android-23 | Intel x86 Atom_64, android-23 | Google APIs Intel x86 Atom_64, android-25 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2
```

## Description

When initialising a new project, the "name" field of package.json is populated with the project name. This can result in an invalid name being used because npm imposes some rules on the allowed names. See https://docs.npmjs.com/files/package.json#name.

A solution would be to "slugify" the name, turning `MyCoolPackage` into `my-cool-package` for example.

## Reproducible Demo

```
npx react-native init MyCoolProject
```

See that name in package.json is not valid.

**Comment by Usamaliaquat123** [comment]
@wvteijlingen  in cli try using this `npx react-native init mycoolproject` instead if `npx react-native init MyCoolProject`

**Comment by wvteijlingen** [comment]
Yeah, that is a workaround. But I think since initialising a project with capitals is allowed, it should make sure that it doesn't product an invalid package.json.

**Comment by nnajiabraham** [comment]
Curious if anyone has taken this issue, if not can I take it? 

Also, my first time contributing to this project, have contributed to the React native docs before but I will appreciate a guide on this 🥺 🙏

**Comment by thymikee** [comment]
@nnajiabraham sure, go for it!

**Comment by StasD** [comment]
It's 2026 already! And the issue still hasn't been fixed!
