### ISSUE TITLE
Gradle sync failed `cannot invoke getErrorStream()`

### ISSUE THREAD

**Issue by mattdamon108** [react-native-community/cli#816]
## Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.66 GB / 32.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    npm: 6.12.0 - ~/.npm-global/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
```

## Description

Android Studio failed to sync the gradle.
The error message `cannot invoke the method getErrorStream()`

## Reproducible Demo

```
npx react-native init myProject

open /android directory with Android Studio
```

I found out the solution after I've been investigating a while. This command can not be executed in Android Studio.

```js
    def cmdProcess
    def npx = Os.isFamily(Os.FAMILY_WINDOWS) ? "npx.cmd" : "npx"
// Android Studio can't run npx
    def command = "${npx} --quiet react-native config"
    def reactNativeConfigOutput = ""

    ...
    cmdProcess = Runtime.getRuntime().exec(command)
    ...
    def bufferedErrorReader = new BufferedReader(new InputStreamReader(cmdProcess.getErrorStream()))
    ...
```

I found a workaround to run the Android Studio in terminal with command `/Applications/Android\ Studio.app/Contents/MacOS/studio` then it's working.

I'm not sure that my Android Studio should be installed under `$HOME/` to avoid this issue, but my case is installed in `/` and failed to sync the gradle.

**Comment by thymikee** [comment]
cc @ifyapishore I think this may be related to your issue?: https://github.com/react-native-community/cli/issues/793#issuecomment-543759428

**Comment by thymikee** [comment]
For now, please build android using `react-native run-android` command

**Comment by ifyapishore** [comment]
> cc @ifyapishore I think this may be related to your issue?: [#793 (comment)](https://github.com/react-native-community/cli/issues/793#issuecomment-543759428)

Definitely, Runtime.getRuntime().exec(command) do not inherit PATH variable under OSX. As result npx command can't be found. I faced same issue.

My temp workaround is simple (have no time to find how to get desired PATH and execution dir in gradle):

1. Hardcode execution dir
2. Hardcode PATH variable

```
      def jenv = new String[1]
      jenv[0] = "PATH=/usr/local/bin:/usr/bin:/ etc."
      cmdProcess = Runtime.getRuntime().exec(command, jenv, new File("/PROJECTS/MY PRJ DIR"))
```

**Comment by thymikee** [comment]
Dug a bit, and it's likely an environmental issue with your Android Studio. See: https://discuss.gradle.org/t/exec-execute-in-gradle-doesnt-use-path/25598/4

Make sure you're using Android Studio 3.5 or later, open:
```
Run > Edit Configurations... > Templates > Gradle
```

Also, make sure the "Include system environment variables" box is checked, like here:

![image](https://user-images.githubusercontent.com/5106466/67204972-f940be00-f40e-11e9-9832-7a658d81ad54.png)

It should include PATH, HOME, ANDROID_HOME, etc. If not, set it manually.

**Comment by mattdamon108** [comment]
I've checked the version of Android Studio 3.5.1 and the include system environment variables checked. But still have same error.

I'm opening the Android Studio in terminal to avoid the error.

![image](https://user-images.githubusercontent.com/36963424/67258516-0e2f5700-f4cc-11e9-8edc-1e85501bff35.png)

**Comment by mattdamon108** [comment]
![image](https://user-images.githubusercontent.com/36963424/67265825-a982f500-f4e9-11e9-8efb-4990b012e710.png)

It seems my Android Studio can't get a npx path actually. The location of `npx` is `/Users/arnold/.npm-global/bin/npx`. How can I set a path in the Android Studio?

**Comment by AndreiCalazans** [comment]
I have Env Variables set up. I had this is all working on previous React Native versions, started happening after updating to latest CLI. 

![Screen Shot 2019-10-22 at 09 23 31](https://user-images.githubusercontent.com/20777666/67285333-bbdf3d80-f4ad-11e9-8d91-5d87c0bcfc73.png)
![Screen Shot 2019-10-22 at 09 22 58](https://user-images.githubusercontent.com/20777666/67285335-bbdf3d80-f4ad-11e9-9c6b-d8e3f10f6dff.png)
![Screen Shot 2019-10-22 at 09 22 50](https://user-images.githubusercontent.com/20777666/67285337-bbdf3d80-f4ad-11e9-8065-af09b232041b.png)

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/Andrei/.nvm/versions/node/v12.13.0/bin:/Users/Andrei/Library/Android/sdk//emulator:/Users/Andrei/Library/Android/sdk//tools:/Users/Andrei/.fastlane/bin:~/Documents/flutter/bin:/Users/Andrei/Library/Python/2.7/bin:/Users/Andrei/Library/Android/sdk//tools/bin:/Users/Andrei/Library/Android/sdk//platform-tools
