### ISSUE TITLE
Allow initializing app in kebab case

### ISSUE THREAD

**Issue by Naturalclar** [react-native-community/cli#818]
## Describe the Feature

This is a Feature Request, and if people are interested, I'd like to try implementing this feature.

Currently, when we try to initialize an app in kebab-case (e.g. `my-awesome-app`), it will fail to initialize due to invalid name.

I understand this is due to ios and android build files requiring alpha numeric name for a project.

This is just a personal preference, but I like to keep my react-native project name (repository name and package.json) in kebab-case, since most react-native related packages seems to use kebab-case and I want to stick to that.

It would be nice if cli detects a kebab-case and make necessary changes in built folder names so that kebab-case for project name is allowed.

## Possible Implementations

On `init`, if kebab-case is entered, convert it to camel case for files that requires alphanumeric values, and leave the rest as kebab-case.

## Related Issues

https://github.com/react-native-community/discussions-and-proposals/issues/134#issuecomment-527823827

**Comment by thymikee** [comment]
Similar scope to https://github.com/react-native-community/cli/issues/814

**Comment by Esemesek** [comment]
During the initialization process, we rename files, change package names and other strings in the template. `Kebab-case` is not supported, because those names/file cannot use `-` character. If we want to support this type of casing we should investigate where it is appropriate to use certain names and make replacing login more complex.

**Comment by grabbou** [comment]
I think we should definitely allow that, but convert to `camelCase` by default for iOS and Android.
