### ISSUE TITLE
Unable to build a new react native project

### ISSUE THREAD

**Issue by darrenmuliawan** [react-native-community/cli#820]
## Environment
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 162.21 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 3.10.10 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.3, 25.0.0, 26.0.0, 26.0.2, 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1

## Description
Hi, I am new to React Native and I was unable to build a newly made react native project
What I did was
`react-native init myapp`
`cd myapp`
`react-native run-android`

![image](https://user-images.githubusercontent.com/31380437/67449101-d7416a00-f5cd-11e9-8e8d-e0902c459646.png)

I have been looking for an answer to this issue from GitHub and tried different things that people suggested on other threads, but still no luck. Any help is really appreciated. Thank you.

Attached is the structure of my application directory.
[structure.txt](https://github.com/react-native-community/cli/files/3765474/structure.txt)

**Comment by mrwisu** [comment]
I have the same output, but only in Android Studio.
When I run it in terminal (Ubuntu 18.04) it works fine.

Note that, you shouldn't be using global installation of react-native.
Try:
npx react-native init myapp
npx react-native run-android

**Comment by thymikee** [comment]
Should be resolved by now.
