### ISSUE TITLE
App Package and BundleID

### ISSUE THREAD

**Issue by carlosroberto555** [react-native-community/cli#825]
## Describe the Feature
The CLI change the app package and bundle id, because is a boring work change this info always on create a app.
This feature reduce a lot of time and errors, I published 3 apps with wrong package name on Google Play, because the Google Play not alert you it like the Apple Store.

## Possible Implementations
For new projects
`npx react-native init ExampleApp --package com.exampleapp`

And for existing projects
`npx react-native change-package com.exampleapp`

**Comment by thymikee** [comment]
I'm not really sure what's the use case for this. If you have multiple apps, you'll still need to configure that manually. I don't see this is as a typical use case, so it's likely not going to be implemented in the core. However, you can write a plugin, here's how: https://github.com/react-native-community/cli/blob/master/docs/plugins.md
