### ISSUE TITLE
Updating Cli section uses instruction removed "@react-native-community/cli" still project not working

### ISSUE THREAD

**Issue by detroit007** [react-native-community/cli#827]
## Ask your Question
when I'm running react-native run-android it shows "node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 206 "

Cannot get property 'packageName' on null object

need help!

**Comment by mrwisu** [comment]
Are you using the newest version of CLI?
Note that, you shouldn't be using global installation of react-native. Try to run in your project directory:
npx react-native run-android

**Comment by detroit007** [comment]
@mrwisu I tried your method " npx react-native run-android " in project directory but nothing change, facing same error.

**Comment by mrwisu** [comment]
What version of react-native cli are you using?
$ npx react-native --version
3.0.0-alpha.7

See:
https://github.com/react-native-community/cli#updating-the-cli

**Comment by detroit007** [comment]
by updating the Cli I got:
GuessNum@0.0.1 /home/hami/GuessNum
└─┬ react-native@0.61.2
  └── @react-native-community/cli@3.0.0-alpha.2

**Comment by detroit007** [comment]
@thymikee error still exists it is'nt reoslve yet

**Comment by thymikee** [comment]
Please follow the instructions and update the CLI to point to version alpha.7. I can't fix your lock file.

**Comment by detroit007** [comment]
yes I updated to the latest version but it still showing the old one

**Comment by thymikee** [comment]
Maybe you're behind a proxy, where the version is not updated yet? `alpha.7` is published to npm, so it's definitely some kind of network caching.

**Comment by detroit007** [comment]
last time I update from this source "https://www.npmjs.com/package/@react-native-community/cli-platform-android/v/3.0.0-alpha.7 ", so what should I do now to update this to the latest version?

**Comment by thymikee** [comment]
Please regenerate your lock file (e.g. remove it and run again) if you have issues. It's not this package fault, that npm can't fetch it for you, can't do anything about that.
