### ISSUE TITLE
npx react-native init Demo --template react-native-template-typescript  FAIL

### ISSUE THREAD

**Issue by sophister** [react-native-community/cli#830]
## Environment

System:
    OS: macOS Mojave 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 1.32 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
    Watchman: 4.4.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 24, 28
      Build Tools: 23.0.1, 24.0.0, 24.0.1, 24.0.2, 24.0.3, 26.0.2, 27.0.3, 28.0.3
      System Images: android-24 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.2/10E125 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.2 => 0.61.2
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-tinker-cli: 1.7.0

## Description

I'm creating a new App, and want to use `typescript` template. According to the [init doc](https://github.com/react-native-community/cli/blob/master/docs/init.md#initializing-project-with-custom-template), I tried the following :

```shell
# This does NOT work
npx react-native init Demo --template react-native-template-typescript
```

Then I tries this

```shell
# It works
npx react-native init Demo --template typescript
```

**Comment by thymikee** [comment]
Looks like `npx react-native` resolves to a globally installed `react-native-cli`. Please remove it, it's not needed anymore.

**Comment by youngjuning** [comment]
same issues

**Comment by troZee** [comment]
@youngjuning 

Please run below commands 
- npm list -g --depth=0
- yarn global list 

and paste the result here, bc probably you have installed old version of RN cli. 
In my case I needed to use below commands to uninstall wrong version of cli
```
npm uninstall -g react-native
npm uninstall react-native-cli -g
yarn remove global react-native-cli
```

and then run 
```
npx react-native init MyApp --template react-native-template-typescript
```

**Comment by jacklj** [comment]
@troZee's solution worked for me, just correcting their typo to save people a few googles (the `global` command must immediately follow `yarn`):

```bash
npm uninstall -g react-native
npm uninstall -g react-native-cli
yarn global remove react-native-cli
```
