### ISSUE TITLE
Upgrade task never seems to work

### ISSUE THREAD

**Issue by andrewhavens** [react-native-community/cli#833]
## Environment

```
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 165.51 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 26.0.2, 27.0.3, 28.0.3
  IDEs:
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5
```

## Description

I've tried using the upgrade tool on several upgrades, but every time, it never seems to work and I have to manually upgrade every file. It always fails with some sort of "git apply failed" error. I think this might have to do with the fact that we have removed the `ios` directory and are only using this for our Android app.

For example I am attempting to upgrade from 0.60.5 to 0.60.6, which is a [very simply upgrade](https://react-native-community.github.io/upgrade-helper/?from=0.60.5&to=0.60.6). Here is the scrollback on what happened:

```
$ react-native upgrade 0.60.6 --verbose
info Fetching diff between v0.60.5 and v0.60.6...
info Applying diff...
warn Excluding files that exist in the template, but not in your project:
  - my_app/ios/RnDiffApp.xcodeproj/project.pbxproj
debug "git apply" failed. Error output:
error: my_app/ios/RnDiffApp.xcodeproj/project.pbxproj: does not exist in index

error Automatically applying diff failed. We did our best to automatically upgrade as many files as possible
error Patch failed to apply for unknown reason. Please fall back to manual way of upgrading
warn After resolving conflicts don't forget to run "pod install" inside "ios" directory
info You may find these resources helpful:
• Release notes: https://github.com/facebook/react-native/releases/tag/v0.60.6
• Manual Upgrade Helper: https://react-native-community.github.io/upgrade-helper/?from=0.60.5&to=0.60.6
• Git diff: https://raw.githubusercontent.com/react-native-community/rn-diff-purge/diffs/diffs/0.60.5..0.60.6.diff
error Upgrade failed. Please see the messages above for details
```

I would really like to be able to use the upgrade tool. Is there some additional configuration/setup that needs to be done in order to get this to work? Or is this a bug in the upgrade tool?

**Comment by thymikee** [comment]
`ios/RnDiffApp.xcodeproj/project.pbxproj` file diff doesn't seem "simple". Also, because of the way patches are created by `rn-diff-purge` project, they're very fragile to apply for `git apply`, so we often point users to Upgrade Helper for manual upgrade instructions. 

What's interesting in your case is that `RnDiffApp.xcodeproj` was not replaced with your app name (unless your app is called RnDiffApp). Can you share a bit more about your setup, file structure, etc?

**Comment by andrewhavens** [comment]
Our project is Android only, so we removed the `ios` directory (which is probably why the message says ".../project.pbxproj: does not exist in index".

**Comment by thymikee** [comment]
Oh, that makes sense. Then you should be fine. Please remember the `upgrade` command _tires its best_, but is not super smart. I hope we can iterate on it, but if it fails, it points you Upgrade Helper where you can manually verify missing pieces. I still think it's better than nothing.
