### ISSUE TITLE
Cannot get property 'packageName' on null object

### ISSUE THREAD

**Issue by gagandeep** [react-native-community/cli#835]
Reopening https://github.com/react-native-community/cli/issues/827 as I am also facing same issue. My point is it is this library assumption that broke the build not any other library.

Command output -

```
* Where:
Script 'node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 206

* What went wrong:
A problem occurred evaluating script.
> Cannot get property 'packageName' on null object

```

Let see Line 206 of native_modules.gradle
https://github.com/react-native-community/cli/blame/master/packages/platform-android/native_modules.gradle#L206

The statement `json["project"]["android"]["packageName"]` clearly assumes that every project will have android and packageName present. However, this is not enforced by anyone in the wild. 

I know that this fixes other issues but regression is clearly failing for this one. 

I am not able to figure out which package is causing this issue in my setup. However, Its clear that this is coming from this package only.

**Comment by gagandeep** [comment]
In my case, `react-native-community/async-storage` was referring to `@react-native-community/cli-tools": "^3.0.0-alpha.7"` that caused the problem.

**Comment by gagandeep** [comment]
Downgrading the package `cli-platform-android` solved the issue for me.

```npm install @react-native-community/cli-platform-android@2.9 --save-dev```

**Comment by artemkovalyov** [comment]
> Downgrading the package `cli-platform-android` solved the issue for me.
> 
> `npm install @react-native-community/cli-platform-android@2.9 --save-dev`
> 
> This needs to be fixed by this library only.

Worked perfectly for me after building collapsed because of this update.

**Comment by gagandeep** [comment]
@grabbou & @thymikee any update on this one.

**Comment by grabbou** [comment]
Thanks for reporting. Please paste or send me `react-native config` output - I need to investigate the structure a bit more.

CLI didn't recognize your Android project. This shouldn't never happen, because in that case, you wouldn't have a Gradle file.

A dump of your directory hierarchy would be good to see as well. Please provide that and I'll try to resolve this right away.

**Comment by thymikee** [comment]
Please [update the `@react-native-community/cli`](https://github.com/react-native-community/cli#updating-the-cli) to the latest version and let me know if that solves the issues. Closing for now, as there's no repro and it's likely fixed
