### ISSUE TITLE
adb error on windows

### ISSUE THREAD

**Issue by david-laurentino** [react-native-community/cli#840]
## Environment

System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 2700 Eight-Core Processor
    Memory: 16.85 GB / 31.96 GB
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: ^0.61.3 => 0.61.3

## Description

Even if real device is connected via USB, the emulator is launched. It occurs when adbPath (see file adb.js, line 52) contains spaces. 
I suspect that another errors that occurs while run-android on windows are related:

Could not read path 'C:\Users\David Laurentino\...\debug\0\lib\armeabi-v7a' 
Failed to delete: C:\Users\David Laurentino\...\app\build\generated\res\google-services\debug

I need to delete build dir in each run.

**Comment by grabbou** [comment]
It looks like a good first issue to handle whitespaces. Thanks for reporting!

**Comment by grabbou** [comment]
Closed via https://github.com/react-native-community/cli/pull/969 a while back ago.
