### ISSUE TITLE
placeholderName not replaced on generated project with template

### ISSUE THREAD

**Issue by Gerlison** [react-native-community/cli#841]
![image](https://user-images.githubusercontent.com/28146931/68516119-ec6ef780-0261-11ea-894c-a37669442c45.png)

I created this template, configured it as cli's doc recommends. When I create a new project using it, package.json 'name' and android/ and ios/ folders has not their names changed to name passed on init.

What am I doing wrong?
Did I forget some config?
How do I change some code in MainApplication.java and keep it on template?

**Comment by thymikee** [comment]
You're likely using a globally installed `react-native` or `react-native-cli`? Please remove these. Can you provide a repro with instructions on how you use this template? I'm going to close this for now, because it's unlikely an issue with the CLI.
