### ISSUE TITLE
Please bump metro version to 0.57.0 to solve issues on Windows with Node v12.x.x

### ISSUE THREAD

**Issue by tad3j** [react-native-community/cli#853]
Bug is described and fixed with https://github.com/facebook/metro/commit/7c6f30b592b2fb23cee55b54f1aa4b7a522dec18. Commit was accepted and released under metro v0.57.0.

**Comment by grabbou** [comment]
Sounds like a plan. Would you mind sending over a PR? If there's no breaking changes, we can distribute it to existing React Native versions.

**Comment by tad3j** [comment]
> 
> 
> Sounds like a plan. Would you mind sending over a PR? If there's no breaking changes, we can distribute it to existing React Native versions.

I've created a PR here: https://github.com/react-native-community/cli/pull/864

Not sure if new version of metro breaks anything, but seems like some tests are failing.

**Comment by thymikee** [comment]
This is fixed in Metro 0.56 now: https://github.com/facebook/metro/releases/tag/v0.56.4. You'll need to regenerate lock file (e.g. remove metro entries from yarn.lock). Closing
