### ISSUE TITLE
ERROR: cannot find module : template.config

### ISSUE THREAD

**Issue by Work90210** [react-native-community/cli#861]
After running "npx react-native init MyApp --template react-native-template-ui-kitten"

I am presented with an error.

× Copying template
error Error: Cannot find module 'C:\Users\kylef\AppData\Local\Temp\rncli-init-template-Qq6OrG\node_modules\react-native\template.config'
Require stack:
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\init\template.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\init\init.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\init\index.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\commands\index.js
- C:\Users\kylef\node_modules\@react-native-community\cli\build\index.js
- C:\Users\kylef\node_modules\react-native\cli.js

I am running VS Code latest on windows

**Comment by thymikee** [comment]
Looking at the repo here: https://github.com/akveo/react-native-ui-kitten, there's no `template.config.js` which is mandatory for init to work.

**Comment by thymikee** [comment]
However, seeing the error message is ugly, I'd be happy if you'd like to contribute a better one. Something like this would do:
> Couldn't find "template.config.js" file, which is mandatory for a custom React Native template "react-native-template-ui-kitten". Please make sure you use correct version of the template and contact its maintainers if necessary. Docs: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

**Comment by Work90210** [comment]
Hi @thymikee thank you for your response.

I have already spoken with react-native-template-ui-kittens team and they say they were unable to replicate the issue.

I then tried running npx react-native init MyApp, I was presented with the same issue.

Is this an issue on my side? How would one go about fixing it? I have tried uninstalling react and reinstalling it. I have updated it a few times and I currently don't know how to resolve the issue.

Thank you in advance

**Comment by artyorsh** [comment]
@thymikee the problem is that we have template.config - https://github.com/akveo/react-native-ui-kitten/tree/master/src/templates/template-ui-kitten

And running both Mac and win10 I was not able to reproduce it

**Comment by thymikee** [comment]
Oh, I see, so the template is fine. Can you show output of `npx react-native --version`? Make sure to uninstall global `react-native-cli` and `react-native` if you have such.

**Comment by artyorsh** [comment]
Yes, as a maintainer I have the latest versions (I have `@react-native-community/cli` installed globally). However, I'm not able to reproduce this running both `npx react-native init blah` and `npx @react-native-community/cli init blah`

**Comment by artyorsh** [comment]
For any reason this still occur for reporter even after running this command, as I suggested [here](https://github.com/akveo/react-native-ui-kitten/issues/734#issuecomment-556032259)

**Comment by Work90210** [comment]
Hi @artyorsh @thymikee 
I am still running into the issue.  Does anybody have any suggestions for a fix?
I am unable to replicate anything without running into an issue. 
When I run
`npx react-native init MyApp` 

I get the same error message.

**Comment by thymikee** [comment]
Thanks @artyorsh. The question was for @Work90210 because his environment is an issue.

**Comment by Work90210** [comment]
@thymikee I am running react-native v3.0.4

**Comment by Work90210** [comment]
> Oh, I see, so the template is fine. Can you show output of `npx react-native --version`? Make sure to uninstall global `react-native-cli` and `react-native` if you have such.

To confirm, it is `npm un -g react-native` to uninstall?

**Comment by thymikee** [comment]
Yes

**Comment by Work90210** [comment]
when i run `npm un -g react-native`
I get 

> up to date in 0.024s

**Comment by se22as** [comment]
I am also seeing this issue.  I have made sure i have uninstalled globals of `react-native` and `react-native-cli` by running

```
npm un -g react-native
npm un -g react-native-cli
```

I have updated to the latest node and npm
```
$ node --version
v12.16.0

$ npm -v
6.13.7
```

The only way I can successfully create a new bare app is to install "react-native-cli" globally. But the docs say you shouldn't install globally (as well as stackoverflow comments to other issues I have seen)

**Comment by OPerel** [comment]
I'm having the same problem. Running on Windows 10.
I confirmed `react-native` is not installed globally:
```
$ npm uninstall -g react-native
$ react-native --version
'react-native' is not recognized as an internal or external command,
operable program or batch file.
```

Then, when running `npx react-native init myApp` I got:
```
√ Downloading template
× Copying template
error Error: Couldn't find the "C:\Users\Ori\AppData\Local\Temp\rncli-init-template-81lnDJ\node_modules\react-native\template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template
```
Maybe it's worth mentioning that after running `npx react-native init` I do have RN installed globaly:
```
$ react-native --version
3.1.0
```

**Comment by badnutz** [comment]
Is there a solution i have the same issue, maybe the native templates are broken?

**Comment by cyphire** [comment]
Same problem

**Comment by OPerel** [comment]
Try removing any node_modules folders and/or package.json files you may have in the folder you're trying to run `init` in.

**Comment by HeZhanHeng** [comment]
Error: Couldn't find the "C:\Users\ADMINI~1\AppData\Local\Temp\rncli-init-template-LnsCSY\node_modules\react-native\template.config.js file inside "react-native" template.So how can i resolve this problem?

**Comment by mrrfly** [comment]
> Im Using Win 10 Pro

I just fix that error using:

open CMD,

`yarn global add react-native-cli`

then

`react-native yourProject`

**Comment by randomprogramming** [comment]
Running CMD/Powershell as admin on Windows fixed this issue for me.

**Comment by icefee** [comment]
I fix it by running `npx react-native init <projectName> --template react-native-template-typescript --npm`
add --npm at the end of your command, It's maybe a bug of yarn.

**Comment by chapagd** [comment]
same issue
