### ISSUE TITLE
Support for network connected devices on Xcode

### ISSUE THREAD

**Issue by pvinis** [react-native-community/cli#87]
Xcode can connect and run apps on devices that are connected with wifi. It would be very useful to be able to run `react-native run-ios --device` and the app runs on a device that's connected with wifi, and not necessarily with a cable to Xcode.

I can try to make this happen. Is that alright? Would this be accepted?

**Comment by grabbou** [comment]
Yeah, sure, that sounds like a good option! Please feel free to do it. I think we already support '--device' flag, you should be able to use it, right?

**Comment by pvinis** [comment]
yes, basically I want to expand that so it supports network devices too. cool.

**Comment by grabbou** [comment]
Let me know if you need any help - fingers crossed!

**Comment by pvinis** [comment]
Alright, so two things:
- This repo is not yet integrated with the `react-native` repo right?
- I actually tried to `run-ios --device` using this repo for the local-cli, and it did find my network phone, but then `ios-deploy` doesn't support it. https://github.com/ios-control/ios-deploy/issues/370 and https://github.com/ios-control/ios-deploy/issues/320

**Comment by SukritGupta17** [comment]
> Alright, so two things:
> 
> * This repo is not yet integrated with the `react-native` repo right?
> * I actually tried to `run-ios --device` using this repo for the local-cli, and it did find my network phone, but then `ios-deploy` doesn't support it. [ios-control/ios-deploy#370](https://github.com/ios-control/ios-deploy/issues/370) and [ios-control/ios-deploy#320](https://github.com/ios-control/ios-deploy/issues/320)

Hey, are you working on integrating this feature?

**Comment by pvinis** [comment]
No, I just found the issues in `ios-deploy`. I don't have time to do this now, I just use xcode, that supports wifi.

**Comment by thymikee** [comment]
@pvinis is this still an issue? I'll close for now, since it's an upstream bug

**Comment by pvinis** [comment]
I just tried it, worked. 👍
