### ISSUE TITLE
Simplify setup for monorepos

### ISSUE THREAD

**Issue by sibelius** [react-native-community/cli#877]
## Describe the Feature

On iOS, you need to set `PROJECT_ROOT` in order to make CLI work in a monorepo. On Android, same set of configuration is required.

## Possible Implementations

- [ ] Get rid of `PROJECT_ROOT` on iOS because it's not needed anymore
- [ ] Figure out strategy for Android.

## Related Issues

related to https://github.com/react-native-community/cli/issues/865 https://github.com/react-native-community/cli/issues/656

**Comment by sibelius** [comment]
this is my error when building 

```jsx
Error: Cannot find module '/app/packages/app/node_modules/react-native/cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

as it searches for react-native in the wron glocation

**Comment by sibelius** [comment]
I've got this working like this

```diff
project.ext.react = [
    entryFile: "index.js",
    bundleInStaging: true,
    devDisabledInStaging: true,
    bundleInAlpha: true,
    devDisabledInAlpha: true,
    enableHermes: false,  // clean and rebuild if changing
+    root: "../../../../"
]
```

modifying `root` path on app/build.gradle

but this raised another issue

```jsx
error Invalid platform "android" selected.
info Available platforms are: "native". If you are trying to bundle for an out-of-tree platform, it may not be installed.
```

it only shows the `android` command inside react-native packages inside our monorepo (like here https://github.com/entria/entria-fullstack/tree/master/packages/app), but fails on root

what is the proper solution for this?

**Comment by sibelius** [comment]
fixed android like this

```jsx
project.ext.react = [
   cliPath: "../../node_modules/react-native/cli.js",
]
```

**Comment by sibelius** [comment]
ios also need this

```jsx
export NODE_BINARY=node
export PROJECT_ROOT="$PROJECT_DIR/.."

../../../node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by grabbou** [comment]
Yeah, in my experience, this is the major root cause for all of the monorepo issues that a lot of people are facing these days.

Any idea how we could plug into it? Setting dynamically variables?

**Comment by sibelius** [comment]
this is a hard one, maybe a monorepo documentation guide could be good enough

**Comment by yuzhakovvv** [comment]
> fixed android like this
> 
> ```js-jsx
> project.ext.react = [
>    cliPath: "../../node_modules/react-native/cli.js",
> ]
> ```

In my case it was
```
project.ext.react = [
    ...
    entryFile: "index.js",
    cliPath: "../node_modules/react-native/cli.js",
]
```

Because project structure is:
```
node_modules/
- react-native/
mobile/
- node_modules/
- index.js
shared/
web/
```

**Comment by grabbou** [comment]
@sibelius, following up to my discussions https://github.com/react-native-community/cli/issues/656#issuecomment-601097688, we should be able to safely remove `PROJECT_ROOT`.

In theory, we always want it to be `ios/..` and even if it ends up being deeper in the hierarchy, CLI knows what to do.

**Comment by grabbou** [comment]
If you look at the details of the commit that introduced this change - https://github.com/facebook/react-native/commit/9ccde378b6e6379df61f9d968be6346ca6be7ead, I believe its assumptions are no longer true and we can get rid of it.

Waiting for Janic to get back to me whether this is right and I believe we can follow up with a PR. This particular change shouldn't require anything on the CLI side.

**Comment by grabbou** [comment]
The ideal for me is this on iOS:

```
export NODE_BINARY=node
../../../node_modules/react-native/scripts/react-native-xcode.sh
```

**Comment by grabbou** [comment]
As per [Janic's comment](https://github.com/facebook/react-native/commit/9ccde378b6e6379df61f9d968be6346ca6be7ead#commitcomment-37919590), we're good to go with the suggested changes.

I will proceed with them soon and link a PR that is landing in React Native as a result.

**Comment by grabbou** [comment]
Just filled in React Native PR - https://github.com/facebook/react-native/pull/28354. Appreciate your review and support in additional explanations :)

**Comment by casperan** [comment]
Since react native 0.63 with the PR will not be released anytime soon (6 months between 0.61 and 0.62)

Would it be possible to wrap up a react-native guide for lerna yarn workspaces monorepo/multi-package? that works with the current releases and source repos to stay up to date ?

This way it would also be possible to clarify use cases in the wild.

**Comment by tad3j** [comment]
Did anyone got build working with hermes in a monorepo?

I've got hermes to work by telling react where it's files are:
`hermesCommand: "/mnt/c/Users/user/WebstormProjects/project/node_modules/hermes-engine/%OS-BIN%/hermes",`

This solved the initial issue of not being able to build, however, with this in place build is still failing with: 
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/mnt/c/Users/user/WebstormProjects/project/packages/mobile/node_modules/react-native/scripts/compose-source-maps.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

> Task :app:bundleReleaseJsAndAssets FAILED
```
...because it is looking for `node_modules` folder in wrong location.

Building works with `enableHermes: false`, so it only fails with hermes enables.

Any suggestion how to get around this?

**Comment by CelsoTeixeira** [comment]
Following @tad3j answer, using react-native 0.63.2 I had to change hermesCommand.

```
hermesCommand: "../../../../node_modules/hermes-engine/%OS-BIN%/hermes",
```

Changed to:
```
hermesCommand: "../../../../node_modules/hermes-engine/%OS-BIN%/hermesc",
```

I still need to pass all other configuration, composeSourceMapsPath, cliPath and hermesCommand. Not passing composeSourceMapsPath was throwing a error.

My monorepo configuration is more or less, trying to not use nohoist at all.
```
monorepo
  - node_modules
     - react-native
  - packages
      - app
      - web
      - any other shared package
```

My final build.gradle project.ext.react is the following:
```
project.ext.react = [
    entryFile: "packages/app/index.js",
    enableHermes: true,  // clean and rebuild if changing,
    hermesCommand: "../../../../node_modules/hermes-engine/%OS-BIN%/hermesc",
    composeSourceMapsPath: "../../node_modules/react-native/scripts/compose-source-maps.js",
    cliPath: "../../node_modules/react-native/cli.js",
]
```

**Comment by eliw00d** [comment]
Has anyone that uses monorepos been able to get Sentry to work? I posted [there](https://github.com/getsentry/sentry-react-native/issues/1765) but figured I'd ask here as well. I followed the examples in here for project.ext.react and it has solved everything except Sentry source maps.

**Comment by liamjones** [comment]
@eliw00d Yes, we do, I'll post on the Sentry ticket since it's specific to that.

**Comment by IljaDaderko** [comment]
To get ios working in freshly set up monorepo using react-native 67, I had to add these to exports to build step

```
export PROJECT_ROOT=$PROJECT_DIR/..
export ENTRY_FILE=app/index.js
```

**Comment by IljaDaderko** [comment]
Had issues with ios not finding index.js entry with solutions above, what ended up working is

```
export PROJECT_ROOT=$PROJECT_DIR/..
export ENTRY_FILE=$PROJECT_ROOT/index.js
```

**Comment by sibelius** [comment]
good enough for me
