### ISSUE TITLE
init fails on new projects with latest CLI

### ISSUE THREAD

**Issue by stevelizcano** [react-native-community/cli#878]
## Environment

info Fetching system and libraries information...
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 544.92 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.2.1/11B53 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4

## Description

Starting a project fails using the latest CLI.
![image](https://user-images.githubusercontent.com/25097587/70156865-dca5d000-16b4-11ea-91bd-68b6059ee041.png)

`npx react-native --version`
shows `3.0.4`

## Reproducible Demo

`npx react-native init test_rn && cd rest_rn && react-native run-ios`

**Comment by thymikee** [comment]
Did you install pods? Maybe they failed to install when initing. Try `cd ios && pod install`

**Comment by stevelizcano** [comment]
Yup! Same issue.

**Comment by stevelizcano** [comment]
Fixed. An uninstall and reinstall of cocoapods solved the issue.
