### ISSUE TITLE
"doctor" doesn't work with spaces in username

### ISSUE THREAD

**Issue by pstanton** [react-native-community/cli#888]
## Environment

c:\MyProject>react-native info
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.33 GB / 15.78 GB
  Binaries:
    Node: 13.0.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.5 => 0.60.5

## Description

c:\MyProject>npx @react-native-community/cli doctor
npm ERR! code ENOLOCAL
npm ERR! Could not install from **"Lastname**\AppData\Roaming\npm-cache\_npx\22256" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Firstname Lastname\AppData\Roaming\npm-cache\_logs\2019-12-13T05_54_02_642Z-debug.log
Install for [ '@react-native-community/cli@latest' ] failed with code 1

**Comment by Esemesek** [comment]
It seems to be related to https://github.com/npm/npx/issues/6. This error should go away when we hopefully ditch `npx` in the near future.
