### ISSUE TITLE
react-native init does not work with react-native-tvos repo

### ISSUE THREAD

**Issue by dlowder-salesforce** [react-native-community/cli#889]
## Environment

Mac desktop
@react-native-community/cli version: 3.0.4

## Description and Reproducible Demo

When using the `react-native-cli` package, the following works correctly:

```
react-native init TestApp --version=react-native@npm:react-native-tvos@latest
```

When this command is used with `@react-native-community/cli`, I get this error:

```
✖ Downloading template
error Error: Command failed: yarn add react-native@react-native@npm:react-native-tvos@0.61.5-0
```

Modifying the command as follows:

```
react-native init TestApp --version=npm:react-native-tvos@0.61.5-0
```

successfully downloads the template, but then has this error:

```
✖ Copying template
error Error: Cannot find module '/var/folders/wx/d0rry04n0qj6yl6ltg77llf9lnm333/T/rncli-init-template-O0xLE3/node_modules/react-native@npm:react-native-tvos/template.config'
```

**Comment by dlowder-salesforce** [comment]
I also tried using `--template` flag, but had similar problems.

**Comment by dlowder-salesforce** [comment]
Interestingly

```
react-native init TestApp --template=react-native@https://github.com/react-native-community/react-native-tvos#tvos-v0.61.2
```

does seem to work.  Investigating.

**Comment by dlowder-salesforce** [comment]
Initial hacky fix for the issue at https://github.com/dlowder-salesforce/cli/commit/ad529c01264c15f5188cfa671ee6af7153b15e68 -- will keep working on this

**Comment by thymikee** [comment]
@dlowder-salesforce `react-native init` (legacy init) and `npx react-native init` (new init) are 2 different commands. TVOS needs to implement `template.config.js` file to be compatible with the new format. Check https://github.com/react-native-community/cli/blob/master/docs/init.md for details :)

**Comment by dlowder-salesforce** [comment]
@thymikee thanks for pointing me to the correct doc.  In fact, the `react-native-tvos` repo is a fork of RN core, and does have the required `template.config.js`.

Using the correct command (`npx react-native init`) still leads to an error unless my fix is applied.  Reopening this and will continue to work on this issue.

**Comment by dlowder-salesforce** [comment]
Thanks @thymikee for pointing me to the correct command:

```
npx react-native init TestApp --template=react-native-tvos@latest
```

No fix needed, just need to document this :)
