### ISSUE TITLE
React native 0.61 app not running on ios device from mac

### ISSUE THREAD

**Issue by mehdihussain9** [react-native-community/cli#891]
## Environment

MAC with iPhone 6s

## Description

 I Created React native 0.61 ver app and it is running well in the simulator but not running in my physical device.
## Reproducible Demo
![Screenshot 2019-12-17 at 11 06 11 AM](https://user-images.githubusercontent.com/56829236/70967858-a0fc0480-20bd-11ea-8588-218e14f69cec.png)

**Comment by thymikee** [comment]
Can you clear your DerivedData directory, run `pod install` and try again?

**Comment by grabbou** [comment]
This is not an issue with the CLI, at least from the screenshot presented. Please raise this in React Native repository, if you believe it's a bug.

Looks like configuration of the iOS project might be corrupted - I would google this error. There's been a lot of issues like this before.
