### ISSUE TITLE
auto detect mainActivity from AndroidManifest.xml

### ISSUE THREAD

**Issue by kagawagao** [react-native-community/cli#896]
## Describe the Feature

auto detect `MainActivity` from `AndroidManifest.xml`
## Possible Implementations

parse `AndroidManifest.xml` and get `MainActivity`

```xml
<activity android:name=".module.MyActivity">
  <intent-filter>
    <action android:name="android.intent.action.MAIN" />
    <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity>
```

**Comment by thymikee** [comment]
Can you describe your use case in detail?

**Comment by kagawagao** [comment]
as the [doc](https://github.com/react-native-community/cli/blob/master/docs/commands.md#--main-activity-string) say, `react-native run android` support custom `MainActivity`, but it need to input argument,  we can get `MainActivity` easily by parse `AndroidManifest.xml` and no argument need

**Comment by thymikee** [comment]
And that's more like it. Please mind that there may be people interested in contributing this feature and providing less detail may discourage them :) 

Anyway, I support the idea.

**Comment by kagawagao** [comment]
I'll try to implement this feature

**Comment by grabbou** [comment]
Thanks for sending over the PR! Currently a bit on hold, going to upgrade the branch and merge the PR!

**Comment by thymikee** [comment]
@adamTrz can you take a look? :)
