### ISSUE TITLE
Warnings when starting metro on 0.62 branch

### ISSUE THREAD

**Issue by rickhanlonii** [react-native-community/cli#900]
## Environment

<details>
<pre>
System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 10.47 GB / 32.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 20191102.030014 - /opt/facebook/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 28.0.3, 29.0.2
      System Images: android-24 | Intel x86 Atom, android-24 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.2.1/11B500 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^3.0.0 => 3.0.1 
    react: 16.11.0 => 16.11.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
</pre>
</details>

## Description

Running `./scripts/packager.sh` prints two different warnings for unknown configs.

## Reproducible Demo

- Clone react-native
- Checkout 0.62-stable branch
- `./scripts/packager.sh

<img width="854" alt="Screen Shot 2019-12-19 at 9 29 49 AM" src="https://user-images.githubusercontent.com/2440089/71181715-aa62a980-2242-11ea-8862-4e8d1375a650.png">

**Comment by thymikee** [comment]
Thanks for the report! I think we fixed this in `next` branch. Might be a good idea to bump Metro to 0.57 there and officially use cli v4 for 0.62. But people report that Metro 0.57 works with 0.61, so maybe we can upgrade there. Needs investigation and lots of testing.

**Comment by thymikee** [comment]
FYI https://github.com/react-native-community/cli/pull/864

**Comment by thymikee** [comment]
Also, I think I've seen these options in RN's (or RNTester's) own metro.config.js. Can you double check that?

**Comment by rickhanlonii** [comment]
Oh yeah, this is an issue in RNTester then 👍

**Comment by rickhanlonii** [comment]
Submitted issue in react-native here: https://github.com/facebook/react-native/issues/27620
