### ISSUE TITLE
npx horror

### ISSUE THREAD

**Issue by ShaMan123** [react-native-community/cli#902]
## Environment

npm@6.13.4
node@12.14.0
OS: WINDOWS
package manager: yarn

no global `react-native` packages

## Description
After running `npx react-native start` in a `react-native` project I can no longer use the local bin file located in `node_modules`. The commands are intercepted by some global `react-native` bin I cannot locate or delete.
Cleaning cache for yarn, npm didn't work, nor do restarting my machine or deleting `node_modules` dir and lock file.
This is horrible.

**Comment by ShaMan123** [comment]
<details><summary>npm error log</summary>

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\DELL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle CanvasExample@0.0.1~prestart: CanvasExample@0.0.1
6 info lifecycle CanvasExample@0.0.1~start: CanvasExample@0.0.1
7 verbose lifecycle CanvasExample@0.0.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle CanvasExample@0.0.1~start: PATH: C:\Users\DELL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\DELL\.windows-build-tools\python27\;C:\Users\DELL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\DELL\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\DELL\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;C:\Users\DELL\AppData\Local\GitHubDesktop\bin;C:\Users\DELL\AppData\Local\Yarn\bin;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\DELL\AppData\Roaming\npm;C:\Program Files\nodejs\;
9 verbose lifecycle CanvasExample@0.0.1~start: CWD: C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample
10 silly lifecycle CanvasExample@0.0.1~start: Args: [ '/d /s /c', 'react-native start' ]
11 silly lifecycle CanvasExample@0.0.1~start: Returned: code: 1  signal: null
12 info lifecycle CanvasExample@0.0.1~start: Failed to exec start script
13 verbose stack Error: CanvasExample@0.0.1 start: `react-native start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\DELL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\DELL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid CanvasExample@0.0.1
15 verbose cwd C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\DELL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v12.14.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error CanvasExample@0.0.1 start: `react-native start`
22 error Exit status 1
23 error Failed at the CanvasExample@0.0.1 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

</details>

**Comment by ShaMan123** [comment]
```bash
npm i -g @react-native-community/cli
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
C:\Users\DELL\AppData\Roaming\npm\react-native -> C:\Users\DELL\AppData\Roaming\npm\node_modules\@react-native-community\cli\build\bin.js

> core-js@2.6.11 postinstall C:\Users\DELL\AppData\Roaming\npm\node_modules\@react-native-community\cli\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"
```

**Comment by ShaMan123** [comment]
running
```
```

```
 An unexpected error occurred: "EBUSY: resource busy or locked, rmdir 'C:\\Users\\DELL\\Autodidact\\react-native-reanimated-canvas\\CanvasExample\\node_modules\\.bin'".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\DELL\\Autodidact\\react-native-reanimated-canvas\\CanvasExample\\yarn-error.log".
```

<details><summary></summary>

```
Arguments: 
  C:\Program Files\nodejs\node.exe C:\Program Files (x86)\Yarn\bin\yarn.js --production=false

PATH: 
  C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\nodejs\;C:\Users\DELL\.windows-build-tools\python27\;C:\Users\DELL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\DELL\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\DELL\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Java\jdk1.8.0_172\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\DELL\AppData\Local\Programs\Python\Python36-32\;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;C:\Users\DELL\AppData\Local\GitHubDesktop\bin;C:\Users\DELL\AppData\Local\Yarn\bin;C:\Users\DELL\AppData\Local\Microsoft\WindowsApps;C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\DELL\AppData\Roaming\npm;C:\Program Files\nodejs\;

Yarn version: 
  1.17.3

Node version: 
  12.14.0

Platform: 
  win32 x64

Trace: 
  Error: EBUSY: resource busy or locked, rmdir 'C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\.bin'

npm manifest: 
  {
    "name": "CanvasExample",
    "version": "0.0.1",
    "private": true,
    "scripts": {
      "start": "react-native start",
      "test": "jest",
      "lint": "eslint .",
      "postinstall": "npx jetify"
    },
    "dependencies": {
      "@react-navigation/web": "^1.0.0-alpha.9",
      "react": "16.8.6",
      "react-native": "^0.61.5",
      "react-native-gesture-handler": "^1.3.0",
      "react-native-reanimated": "github:ShaMan123/react-native-reanimated#android-cwd",
      "react-native-view-shot": "^3.0.2",
      "react-navigation": "^4.0.10",
      "react-navigation-stack": "^1.10.3",
      "typescript": "^3.7.2"
    },
    "devDependencies": {
      "@babel/core": "^7.5.5",
      "@babel/plugin-transform-modules-commonjs": "^7.7.0",
      "@babel/runtime": "^7.5.5",
      "@react-native-community/eslint-config": "^0.0.5",
      "@types/jest": "^24.0.22",
      "@types/react": "^16.9.11",
      "@types/react-native": "^0.60.22",
      "@types/react-navigation": "^3.4.0",
      "@types/react-test-renderer": "^16.9.1",
      "babel-jest": "^24.9.0",
      "babel-plugin-module-resolver": "^3.2.0",
      "eslint": "^6.2.0",
      "jest": "^24.9.0",
      "metro-react-native-babel-preset": "^0.56.0",
      "react-test-renderer": "16.8.6"
    },
    "jest": {
      "preset": "react-native"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

```
</details>

**Comment by ShaMan123** [comment]
getting this too:
```
Failed to parse React Native CLI configuration. Expected running 'npx.cmd --quiet --no-install react-native config' command from 'C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample' directory to output valid JSON, but it didn't. This may be caused by npx resolving to a legacy global react-native binary. Please make sure to uninstall any global 'react-native' binaries: 'npm uninstall -g react-native react-native-cli' and try again
```

**Comment by ShaMan123** [comment]
I am helpless.
I even re-installed node and yarn with no success.
I can't work with react-native on y computer.

**Comment by ShaMan123** [comment]
This bug was **exhausting.**
It was caused because of a script that was executed during `npm start` from `metro.config.js`. The script wrote a file to the directory.
This somehow disrupted bin files or node_modules. Running again resolves to non local react native bin.
Better logging is much appreciated.
BTW I now face a different bug (I guess due to upgrading node to v12 as part of endless attempts to fix the current bug)
```
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class. Run CLI with --verbose flag for more details.
SyntaxError: Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class
    at new RegExp (<anonymous>)
    at blacklist (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\metro-config\src\defaults\blacklist.js:34:10)
    at getBlacklistRE (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:66:59)
    at getDefaultConfig (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:82:20)
    at load (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\@react-native-community\cli\build\tools\loadMetroConfig.js:118:25)
    at Object.runServer [as func] (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\@react-native-community\cli\build\commands\server\runServer.js:82:58)
    at Command.handleAction (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\@react-native-community\cli\build\index.js:164:23)
    at Command.listener (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\commander\index.js:315:8)
    at Command.emit (events.js:210:5)
    at Command.parseArgs (C:\Users\DELL\Autodidact\react-native-reanimated-canvas\CanvasExample\node_modules\commander\index.js:651:12)
```

commenting the lines does the job.

**Comment by grabbou** [comment]
Where is that regex comming from? I don't see it in our project. If that's something you have in your project, maybe it's incompatible with latest Metro version?

I would look in there, because that's clearly where the error is thrown.

**Comment by grabbou** [comment]
Thanks for filling the issue and doing digging on your own, this is much appreciated!

> It was caused because of a script that was executed during npm start from metro.config.js. The script wrote a file to the directory.
This somehow disrupted bin files or node_modules. Running again resolves to non local react native bin.

What is the script? Is this something you have done in your project? Would love to learn more about it and see if other users could be affected by this behaviour as well.

> Better logging is much appreciated.

Of course. Is there anything you'd improve in particular here?

**Comment by grabbou** [comment]
Meanwhile, I am going to close this issue as the original bug report has been resolved. Let's continue the discussion anyway.

**Comment by ShaMan123** [comment]
The script generates a file in the root directory using `fs`, I wrote it.
The regex is in your code: `metro-config\src\defaults\blacklist.js:34`
If I remove the bad regex metro bundles.
