### ISSUE TITLE
React Native build failed in android, @react-native-community/cli-platform-android /native_modules.gradle' line: 130

### ISSUE THREAD

**Issue by Yashwa** [react-native-community/cli#906]
## Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 7.80 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: 3.0.4 => 3.0.4 
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

## Description

I've upgraded my ReactNative project from 0.59 to 0.61.2 iOS is building fine but in android i'm facing the issue in @react-native-community/cli-platform-android module.

My settings.gradle file:
`apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
`
My build.gradle file
`apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)`

I get the following error while building the app.

```
Task :app:generatePackageList FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/Users/yashwanth_c/Documents/projects/MobileApp/node_modules/@react-native-community/cli-platform-android
/native_modules.gradle' line: 130

* What went wrong:
Execution failed for task ':app:generatePackageList'.
 ReactNativeModules$_generatePackagesFile_closure3

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 21s
4 actionable tasks: 4 executed

```
As always i've cleaned the cache and deleted the node_module folder, tried many times but no luck. Also googled for more than a week but still not able to find a fix, any advice is appreciated.

I've asked a question in [stackoverflow](https://stackoverflow.com/questions/59422584/react-native-build-failed-in-android-react-native-community-cli-platform-andro)

**Comment by grabbou** [comment]
Hey,

To get things started, could you please share your `settings.gradle`, `build.gradle` and output of `react-native config` command (run in the root of your project)? 

Please keep in mind that the `config` command will print your paths etc., we haven't implemented the obfuscation yet. With that in mind, you can share it with me via email (it's in my profile) or replace the paths with something.

**Comment by altany** [comment]
Try deleting the `android/app/build` folder.

**Comment by SERGEIBARATS** [comment]
Hi,
same issue,
I tried to remove build and run again.. unfortunately failed again.

**Comment by grabbou** [comment]
I am going to close this. Please open new issue following my reproduction requirement https://github.com/react-native-community/cli/issues/906#issuecomment-573644833. Otherwise, we can't really help.

**Comment by Vasault** [comment]
please someone help, having the same issue after cleaning node modules and cache

**Comment by caranid** [comment]
great its closed -_- thanks dude
