### ISSUE TITLE
Unable to load script. Make sure.... message.

### ISSUE THREAD

**Issue by darshanaprasad** [react-native-community/cli#907]
I am new to react native.
I am just starting to learn react native.
I installed JDK, node.js, python 2, and android studio to start practicing react native according to tutorial I refer.
After initializing a project with command "react-native init project_name", I ran the command "react-native run-android" inside project folder.
I get the message "Unable to load script. Make sure...." after finish running above command and some java errors.
I have attached a screenshot of that error message.
Please let me know what are my faults.
Thanks in advance.
![Screenshot_20191227-213250](https://user-images.githubusercontent.com/20695783/71643366-dcfab080-2cde-11ea-9fe2-e23c92c81a4a.jpg)

**Comment by Naturalclar** [comment]
@darshanaprasad 
:wave: You may need to run `react-native start` on a separate terminal before running `react-native run-android`

**Comment by darshanaprasad** [comment]
Thanks for quick response.
I ran `react-native start` in same terminal. I,ll try it in separate window.

**Comment by darshanaprasad** [comment]
I tried running above commands in separate terminals. But, no luck. So, I think you can find any error by looking at terminal. So, I post it below.

> D:\web\projects\reactnative\Albums>react-native run-android
> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
> Jetifier found 864 file(s) to forward-jetify. Using 4 workers...
> info Starting JS server...
> info Installing the app...
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> > Task :app:stripDebugDebugSymbols UP-TO-DATE
> Compatible side by side NDK version was not found.
> 
> > Task :app:installDebug
> 07:18:37 V/ddms: execute: running am get-config
> 07:18:38 V/ddms: execute 'am get-config' on '8UE5T17A25003238' : EOF hit. Read: -1
> 07:18:38 V/ddms: execute: returning
> Installing APK 'app-debug.apk' on 'RNE-L22 - 8.0.0' for app:debug
> 07:18:38 D/app-debug.apk: Uploading app-debug.apk onto device '8UE5T17A25003238'
> 07:18:38 D/Device: Uploading file onto device '8UE5T17A25003238'
> 07:18:38 D/ddms: Reading file permision of D:\web\projects\reactnative\Albums\android\app\build\outputs\apk\debug\app-debug.apk as: rwx------
> 07:18:39 V/ddms: execute: running pm install -r -t "/data/local/tmp/app-debug.apk"
> 07:18:44 V/ddms: execute 'pm install -r -t "/data/local/tmp/app-debug.apk"' on '8UE5T17A25003238' : EOF hit. Read: -1
> 07:18:44 V/ddms: execute: returning
> 07:18:44 V/ddms: execute: running rm "/data/local/tmp/app-debug.apk"
> 07:18:44 V/ddms: execute 'rm "/data/local/tmp/app-debug.apk"' on '8UE5T17A25003238' : EOF hit. Read: -1
> 07:18:44 V/ddms: execute: returning
> Installed on 1 device.
> 
> BUILD SUCCESSFUL in 55s
> 27 actionable tasks: 2 executed, 25 up-to-date
> info Connecting to the development server...
> info Starting the app on "8UE5T17A25003238"...
> Starting: Intent { cmp=com.albums/.MainActivity }

**Comment by grabbou** [comment]
Hey,

Thank you for filling this issue. Unfortunately, this is not a CLI issue. It looks to me more like a configuration problem of your machine or just Metro not being able to load and process your entry file.

Please consider opening this issue in React Native repository (if you believe it's a bug) or filling a question on StackOverflow.

Please understand that due to the nature of our Open Source project, we don't have the bandwidth to read through your issue request and help solve it.

**Comment by manojpatel** [comment]
@darshanaprasad are able to resolve the issue. I am facing the same issue.
