### ISSUE TITLE
Automatically adding child dependency pods in React Native

### ISSUE THREAD

**Issue by irohitb** [react-native-community/cli#914]
## Ask your Question

I made a repo sometime back https://github.com/irohitb/react-native-smart-statusbar 

Earlier I was using `react-native-device-info` as a peer Dependency but recently I moved it to the dependencies

Now, When I install this npm repo, the pods associated with the ``react-native-device-info` aren't added to the project and hence it throws following error 

```
    Error: @react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null. To fix this issue try these steps:
      • For react-native <= 0.59: Run `react-native link react-native-device-info` in the project root.
      • Rebuild and re-run the app.
      • If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
      If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-device-info
   ```
Can someone help me in figuring out a way when a user installs the repo, pods for `react-native-device-info`also get added?

**Comment by thymikee** [comment]
Currently CLI doesn't support native deps depending on other native deps (whether as peer or direct). 

The process we have today is:
- declare `react-native-device-info ` as peer dependency
- instruct users to install `react-native-device-info` alongside your library

Please see https://github.com/react-native-community/cli/issues/870 where we discuss on how to make it easier for everybody.
