### ISSUE TITLE
`yarn react-native upgrade` uses npm, not yarn

### ISSUE THREAD

**Issue by IanVS** [react-native-community/cli#926]
## Environment

```
  React Native Environment Info:
    System:
      OS: macOS 10.15.2
      CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
      Memory: 4.69 GB / 32.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 12.14.1 - /var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/T/yarn--1580150374542-0.30379921037702373/node
      Yarn: 1.18.0 - /var/folders/8v/nt6q98150ss138rdc78htqxr0000gn/T/yarn--1580150374542-0.30379921037702373/yarn
      npm: 6.13.2 - ~/.nvm/versions/node/v12.14.1/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.6010548
      Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
```

## Description

I'm trying to upgrade react-native, and having some problems.  I'm not sure if it's the root cause or not, but I notice that `npm` is being used to install my dependencies, even though I'm in a yarn workspace environment.  I see that there's a `preferYarn` option in the `PackageManager` (https://github.com/react-native-community/cli/blob/935ad660f146a3ce1d5ca25427d9f5a758220bfd/packages/cli/src/tools/packageManager.ts#L49), but this doesn't seem to actually be used anywhere in the upgrade code.  Is this intentional?

**Comment by thymikee** [comment]
Do you have `yarn.lock` present in your project? If the `preferYarn` options is not passed to package manager (like in this case, because we should be able to infer it), this is used:

https://github.com/react-native-community/cli/blob/6ce799f59b7fec9f82058901820ead75a7ca5555/packages/cli/src/tools/yarn.ts#L45-L47

Can you hook into this code and see what's happening?

**Comment by IanVS** [comment]
I do have a `yarn.lock`, but as I mentioned, I'm using yarn workspaces, so the lockfile lives at my project root, but my mobile code is in `projRoot/client/mobile`, and _that_ is where `isProjectUsingYarn` is looking for a lock file.  It doesn't find it (because it's actually two directories up), so it uses npm instead.

**Comment by IanVS** [comment]
It looks like this was probably fixed by https://github.com/react-native-community/cli/pull/768 for 3.x and above.  So once I get on RN 0.61 I should be fine.  It would be nice to have this fix in older versions, but I'm guessing that's not really easy to backport, so I'll close out the issue.

**Comment by thymikee** [comment]
Awesome, thanks for the followup :)
