### ISSUE TITLE
Using private template with cli

### ISSUE THREAD

**Issue by lucianomlima** [react-native-community/cli#927]
## Ask your Question

Hello guys. Is there a way to use private package as template?
I'm trying several ways to make this work but have no success.
I'm trying with github package registry, but fails in the download step.

I'm try to add the registry URL in `.npmrc`, in `.yarnrc`, but doesn't work.
Any advices?

**Comment by thymikee** [comment]
Using `.yarnrc` in the directory your run command from should work:
```yml
registry "https://registry.yarnpkg.com"
"@your-org:registry" "https://artifactory.yourorg.com/artifactory/api/npm/"
```

**Comment by lucianomlima** [comment]
Doesn't work. I try this with .npmrc and .yarnrc. Both files only works to get the first code, get error when try to download the template.

**Comment by thymikee** [comment]
Um, add the config file to your template then.

**Comment by lucianomlima** [comment]
> Um, add the config file to your template then, it's gonna be copied as is.

I try this too

**Comment by thymikee** [comment]
You're right, that won't work. We'd have to introduce the registry flag passed to the npm/yarn. Reopening

**Comment by ThallyssonKlein** [comment]
is there any temporary solution while the feature is in development?

**Comment by MONTYYYYY** [comment]
Any temp solution for this?

**Comment by thymikee** [comment]
Still valid, anyone up for grabs? :)

**Comment by lucianomlima** [comment]
Is there a way to implements this? If yes, I can try code it.

**Comment by adamTrz** [comment]
Any help is welcomed @lucianomlima :)

**Comment by lucianomlima** [comment]
> Any help is welcomed @lucianomlima :)

I need some guidance, about this. I don't know where this can be implemented.
