### ISSUE TITLE
Add launcher category flag to `run-android`

### ISSUE THREAD

**Issue by IanVS** [react-native-community/cli#929]
## Describe the Feature
When launching my app, the main activity checks if the intent has a category of `android.intent.category.LAUNCHER`, and if so, changes some behavior.  Android studio includes `-c android.intent.category.LAUNCHER` in the call to `adb shell am start` automatically.  Is there any way to also send this flag when using `run-android`?  If not, do you think it could be added?

## Possible Implementations
Addition of a `--category` flag perhaps?  Or, maybe this should be the default behavior?  (it is default in android studio, after all). Or maybe there could be a more general flag for arbitrary adb flags?

## Related Issues
I couldn't find anything.

**Comment by thymikee** [comment]
What do you think @Krizzu @dratwas @ferrannp @dulmandakh?
