### ISSUE TITLE
Suggest to add ANDROID_HOME environment variable if no emulators are found

### ISSUE THREAD

**Issue by IanVS** [react-native-community/cli#930]
## Describe the Feature
It took me a while to figure out why `yarn react-native run-android` was not launching my app on my running emulator.  The only key was a message about adb not working correctly.  It might be nice to point to the https://facebook.github.io/react-native/docs/getting-started docs with instructions to add the environment variables listed there.

## Possible Implementations
Print out some helpful text when adb doesn't find any emulators, possibly after checking whether the environment variable and PATH are set as needed.

**Comment by thymikee** [comment]
You can now verify if ANDROID_HOME is set with `doctor` command. Should help in the future :)
