### ISSUE TITLE
Instruction for adding autolinking support to a RN library

### ISSUE THREAD

**Issue by SaeedZhiany** [react-native-community/cli#932]
## Ask your Question

Some RN libraries have been migrated to support RN v0.60+ (migrate to androidx, etc...) but they missing autolinking support. is there any documented step-by-step instruction about how it should be added to an RN Library?

**Comment by grabbou** [comment]
Check this out: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#what-do-i-need-to-have-in-my-package-to-make-it-work.

Improvements to our documentation are always welcome. In this case, please send a pull request.
