### ISSUE TITLE
Updating the cli?

### ISSUE THREAD

**Issue by mahyali** [react-native-community/cli#933]
https://github.com/react-native-community/cli#updating-the-cli

I tried following this guide to upgrade our cli to "3.0.5-alpha.0".  We have a lock file but I can't get the version to change. Also am using RN version 0.61.5 if that helps.

**Comment by grabbou** [comment]
Have you tried doing this? https://github.com/react-native-community/cli/releases/tag/v3.0.5-alpha.0

**Comment by grabbou** [comment]
CC: @thecodrr @thymikee - the instructions in the readme that @mahyali is referring to are really confusing to me as well. Was there any reason to not recommend using `Yarn resolutions` instead?

**Comment by httol** [comment]
I think this issue shoule be noticed by react-native-community, the guidlines not works as decribed !
