### ISSUE TITLE
Adding fonts to ios(current way is fine) and android(res/font/) project.

### ISSUE THREAD

**Issue by shubhnik** [react-native-community/cli#944]
I have a react native library, which has a fonts folder `fonts/`. Is there a way when a consumer project installs the library then the fonts are linked to consumer native ios project and added to `res/font` of the consumer native Andriod project. My react native library doesn't have any native code, I just want fonts to be added to the consumer project. Is this possible?

**Comment by davidwico** [comment]
Facing the same issue right now, I need to auto-link fonts from my custom component library. Any solutions? Project without any native (android/ios) code.
