### ISSUE TITLE
CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by OguzhanKazak** [react-native-community/cli#945]
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
    Memory: 6.53 GB / 15.91 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.10.3 - C:\Users\oguzhan.kazak\AppData\Roaming\npm\npm.CMD
  SDKs:
    Android SDK:
      API Levels: 23, 25, 28
      Build Tools: 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.6010548
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Projects\TerminalMobil\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 154

* What went wrong:
A problem occurred evaluating script.
> Cannot run program "C:\Projects\TerminalMobil\node_modules\@react-native-community\cli\build\bin.js": CreateProcess error=193, %1 is not a valid Win32 application

react-native run-android throws this error.

**Comment by thymikee** [comment]
Do you have a repro maybe? I haven't seen an error like this here yet. Maybe your node_modules are corrupted? Please try to remove them and `yarn install` again (I suggest using yarn, because npm produces undeterministic node_modules).

**Comment by draggie** [comment]
I also have this error, it occured quite recently after some packages like camera were added.
package-lock and node_modules removed and installed again, no change.

**Comment by mjaydeep01** [comment]
I am facing the same issue.

**Comment by OguzhanKazak** [comment]
this solution may be helpful, but it didn't work out for me: https://stackoverflow.com/questions/58952564/error-unable-to-determine-the-current-character-it-is-not-a-string-number-ar

**Comment by Waqas-Jani** [comment]
i have the same issue @OguzhanKazak  . anyone solve this?

**Comment by OguzhanKazak** [comment]
I solved it with replacing android folder, package.json and package-lock.json files with working ones.
 Problem is probably about @react-native-community/cli-platform-android

**Comment by Waqas-Jani** [comment]
i don't have package-lock.json file

**Comment by ngregrichardson** [comment]
@OguzhanKazak Can you explain a bit more? What do you mean by "working ones"?

**Comment by OguzhanKazak** [comment]
We are working on that project with my friend. So i copied and pasted android + package.json's from him.

**Comment by amduffy19** [comment]
I'm having the same issue.

**Comment by sclavijo93** [comment]
same problem here in a fresh react native app

**Comment by grabbou** [comment]
This sounds like a serious problem, we're going to look into it first thing in the morning.

**Comment by JeanPSF** [comment]
Problem started again 5 hours ago.

**Comment by aldrichdev** [comment]
> 
> 
> I think the lasted version (0.61.0) is the problem I created a new react native app using 0.60.0 and I tested in the emulator without errors.
> 
> react-native init AwesomeProject --version 0.60.0

This made the build succeed, but when the app opens on my connected Android phone I get:

```
console error: React Native version mismatch. 

Javascript version: 0.61.5
Native version: 0.60.0
```

**Comment by nikhilbatta** [comment]
Im having the same problem and dont know how to fix it.

**Comment by sclavijo93** [comment]
Hi @nikhilbatta , check this https://github.com/react-native-community/cli/issues/965#issuecomment-586011638

**Comment by nikhilbatta** [comment]
@sclavijo93 I tried this just now, and im still getting the same error.

**Comment by amduffy19** [comment]
@sclavijo93 thanks, that worked!

**Comment by amduffy19** [comment]
However I'm now getting another error from the same library, `Error: ENOENT: no such file or directory, open 'app\build\intermediates\merged_manifests\debug\AndroidManifest.xml'`. Seems to be an issue with 3.1.1: https://stackoverflow.com/questions/60218063/no-such-file-or-directory-open-app-build-intermediates-merged-manifests-debug

**Comment by sclavijo93** [comment]
@amduffy19  Did you try downgrading @react-native-community to 2.9.0 ?

**Comment by amduffy19** [comment]
@sclavijo93 I'm trying to but having trouble getting it to downgrade due to my version of react-native I think. Working on it...

**Comment by sclavijo93** [comment]
@amduffy19  Try removing the line '@react-native-community/cli-platform-android....' from `dependencies` in the package.json then follow this https://github.com/react-native-community/cli/issues/965#issuecomment-586056786

**Comment by amduffy19** [comment]
@sclavijo93 Thanks but still not working :( Trying to downgrade react-native to 0.60.0 now...

**Comment by amduffy19** [comment]
That worked, thanks!

**Comment by grabbou** [comment]
Wish this issue was closed 7 days ago and I didn't see it. It was a good heads up. Anyway, this is fixed with latest CLI, so just re-install your node_modules.
