### ISSUE TITLE
Cannot invoke method getErrorStream() on null object react-native (linux)

### ISSUE THREAD

**Issue by ashishfeels** [react-native-community/cli#947]
## Environment
System:
    OS: Linux 5.3 Manjaro Linux undefined
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 230.50 MB / 7.63 GB
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 10.16.3 - ~/n/bin/node
    npm: 6.13.6 - ~/n/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.4 => 0.61.4 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-rename: 2.4.1

## Description

Anyone have faced an issue while Gradle sync in Android Studio :
`ERROR: Cannot invoke method getErrorStream() on null object react-native`
CLI works fine 
on android studio gives the following error log: https://hastebin.com/cilutesafu.cs

OS: Linux (manjaro)
Android Studio: v3.5

## Reproducible Demo
Open Project in Android Studio and do Sync Gradle

**Comment by thymikee** [comment]
Can you try https://github.com/react-native-community/cli/releases/tag/v3.0.5-alpha.1? Instructions how to use it inside

**Comment by ashishfeels** [comment]
surely will try and come back. I'm using npm tough

**Comment by Andarius** [comment]
Is this solution working for existing projects ? I face the same issue.

**Comment by ashishfeels** [comment]
yes @Andarius you can give it a try you have to use both :

` "@react-native-community/cli": "3.0.5-alpha.1",
   "@react-native-community/cli-platform-android": "3.0.5-alpha.1",`
for android and this if for ios
`"@react-native-community/cli-platform-ios": "3.0.5-alpha.1"`

**Comment by Andarius** [comment]
I did change the **package.json** with the given resolutions, but the error changed from `ERROR: Cannot invoke method getErrorStream() on null object react-native` to what I mentioned above.
If I roll back, removing the resolutions, `npx react-native run-android` works again.

**Comment by ashishfeels** [comment]
for me the above solution did work. maybe you missed something

**Comment by Andarius** [comment]
Weirdly, after rolling back, Android Studio Build works.... I just get another error `Cannot resolve symbol 'OutputFile'` which does not beak the build, so must be unrelated.

**Comment by Kimleng11122** [comment]
ERROR Message : Cannot invoke method isEmpty() on null object

**Comment by jensonjohn001** [comment]
> ERROR Message : Cannot invoke method isEmpty() on null object

+1 

FAILURE: Build failed with an exception.

* Where:
Script '...../YwaitTV/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 275

* What went wrong:
A problem occurred evaluating script.
> Cannot invoke method isEmpty() on null object

**Comment by Flam3rboy** [comment]
@Kimleng11122 duplicate of #1489
