### ISSUE TITLE
4.0.0 feedback

### ISSUE THREAD

**Issue by Jarred-Sumner** [react-native-community/cli#949]
I just upgraded to 4.0.0!

I really like this:
> To reload the app press "r"

That's very helpful. Thank you.

I also like that `react-native run-ios` shares the cache with Xcode. I stopped using `react-native run-ios` for awhile because the behavior was different than Xcode (it opened in a very old iPhone simulator) but this fixes that, and it feels fast.

I like the timestamps in the logs, but I wish it somehow knew the width of the window & hid the timestamps when there isn't space (or rendered a shorter version):
![image](https://user-images.githubusercontent.com/709451/74100879-45139200-4ae8-11ea-8382-5b36da6f240b.png)

Nice work with 4.0.0.

**Comment by thymikee** [comment]
Thanks for your feedback, really appreciate this! 

For the timestamps in the logs, I assume this is `start` command, right? Feel free to open an issue in Metro, or check the configuration, maybe some option is there already :)
