### ISSUE TITLE
Better Xcode error formatting

### ISSUE THREAD

**Issue by NoemiRozpara** [react-native-community/cli#950]
## Describe the Feature

In some cases when `react-native run-ios` fails, after the error I get too long output (sample visible on the attached screenshot). The most content is full file paths. Final output is so big, I can't scroll to the main error message. Increased buffer size to the maximum memory limit, but it wasn't enough.

## Possible Implementations

I can see 2 possible solutions: 
1. Move the main error to the end of the output, so it's always accessible
2. Omit this part of the output by default, show it when some flag was used, e.g. `react-native run-ios --full-log`

<img width="1020" alt="Zrzut ekranu 2020-02-10 o 20 24 49" src="https://user-images.githubusercontent.com/27765703/74153564-7e144980-4c43-11ea-9485-655666b0efe4.png">

**Comment by thymikee** [comment]
We have `--verbose` already, so could use that instead of `--full-log` but definitely agree we should do something to simplify the output. Thanks for the report!

**Comment by Esemesek** [comment]
This is something that is really tricky as `Xcode` command-line utility outputs all kinds of things that we usually don't need. One of the workarounds would be to pipe the output to `less` or to some file and then grep the error line.

We are using all kinds of 3rd party utilities that have limited customizability - maybe we should create error log files like `yarn` does? Having full output for all errors in `.react-native-cli-timestamp.txt` would be so useful for debugging and improving error tracking - we could just ask peeps to import those files to `pastebin` and link them in issues.

cc. @thymikee @grabbou wdyt?

**Comment by thymikee** [comment]
Supporting logging errors to files could be handy. We'd need to decide if we go Yarn way (.log file in the repo) or Flow-like (logs in tmp dir)
