### ISSUE TITLE
Do not warn on manually linked modules when autolinking disabled

### ISSUE THREAD

**Issue by grabbou** [react-native-community/cli#952]
Had a chat with @janicduplessis and he correctly pointed out that it's not easy to remove warnings even if you do not use autolinking. We should detect the presence and warn if turned on... or, go lazy and only run this path when the function is present in Pod / Gradle files.

**Comment by thymikee** [comment]
Warnings are getting removed alongside with rnpm in this PR: https://github.com/react-native-community/cli/pull/1043

**Comment by janicduplessis** [comment]
@thymikee This issue is about warning when not using autolinking I think, not the ones about deprecated rnpm config.

**Comment by thymikee** [comment]
Oh right, forgot we have another warning for that!
