### ISSUE TITLE
ReactNative:Running 'undefined config' command failed.

### ISSUE THREAD

**Issue by Chukwudi4** [react-native-community/cli#955]
## Environment

$ react-native --version
react-native-cli: 2.0.1
react-native: 0.59.10

$ react-native info
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
      Memory: 1.94 GB / 7.84 GB
    Binaries:
      Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.5429.30.34.5452501

## Description

$ react-native run-android
info Starting JS server...
info Building and installing the app on the device (cd android && gradlew.bat app:installDebug)...
Starting a Gradle Daemon (subsequent builds will be faster)
:ReactNative:Running 'undefined config' command failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Dell\Documents\workspace\gallery\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 154

* What went wrong:
A problem occurred evaluating script.
> Cannot run program "undefined": CreateProcess error=2, The system cannot find the file specified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 30s
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.

I have tried 
1. npm install
2. to delete the project and clone it again

**Comment by thymikee** [comment]
Please remove the global `react-native-cli`, it's no longer necessary.

**Comment by Chukwudi4** [comment]
> 
> 
> Please remove the global `react-native-cli`, it's no longer necessary.

$ react-native run-android
bash: /c/Users/Dell/AppData/Roaming/npm/react-native: Permission denied

after removing global react-native-cli using npm uninstall -g react-native-cli

**Comment by thymikee** [comment]
You also need to remove global `react-native`. Geez, we need to add that to doctor and warn users. cc @lucasbento

**Comment by lucasbento** [comment]
Created #957 for this.
