### ISSUE TITLE
Add health check for globally installed `react-native` in `doctor`

### ISSUE THREAD

**Issue by lucasbento** [react-native-community/cli#957]
## Describe the Feature

We see a lot of issues such as #955 where problems are caused because `react-native` and/or `react-native-cli` are installed globally, would be nice to have a health check to identify and remove them.

## Possible Implementations

Something like [is-installed-globally](https://github.com/sindresorhus/is-installed-globally) but for specific packages, [the implementation is pretty simple](https://github.com/sindresorhus/is-installed-globally/blob/master/index.js) so we can work on top of that.

**Comment by thymikee** [comment]
Great, thanks!

**Comment by Esemesek** [comment]
I'm on it C:

**Comment by lucasbento** [comment]
@thymikee: I was just thinking about this, it would be nice to also identify in `react-native` that the CLI was in a global path if the user tried to do `react-native <command>`, right?

**Comment by thymikee** [comment]
Yep
