### ISSUE TITLE
Migrate to leven to find the closest match for an unknown command

### ISSUE THREAD

**Issue by jamesgeorge007** [react-native-community/cli#959]
## Describe the Feature

As of now [didyoumean.js](https://github.com/dcporter/didyoumean.js/) matching engine is used to suggest matching commands if the user mistypes. But it is not longer actively maintained. Instead I would suggest switching over to [leven](https://github.com/sindresorhus/leven) which is the fastest JS implementation of the Levenshtein distance algorithm.

## Possible Implementations
`leven` returns the distance between 2 strings which can be made use of to find the exact match.

## Related Issues
N/A

**Comment by jamesgeorge007** [comment]
I would be happy to shoot a PR :+1:

**Comment by thymikee** [comment]
Awesome, go for it!
