### ISSUE TITLE
Add verbose logging to all commands

### ISSUE THREAD

**Issue by Esemesek** [react-native-community/cli#96]
Add `--verbose` flag to enable `DEBUG` log level.
Logger unification and implementation is tracked in #95

**Comment by matt-block** [comment]
Is anyone working on this? If not, I'd like to give it a try 😄

**Comment by thymikee** [comment]
@matt-block afaik nobody works on this currently. Feel free to grab it! :)

**Comment by lucasbento** [comment]
Can we close this? it was done in #239 I believe.

**Comment by matt-block** [comment]
It's been implemented but many commands of the CLI still don't have any debug level log messages.

Maybe we should track those as a list in a dedicated issue and close this 🤔

**Comment by lucasbento** [comment]
@matt-block I second this :)

**Comment by thymikee** [comment]
Who's willing to make a list of commands that have `logger.debug` calls and ones that don't? :)

**Comment by matei-radu** [comment]
@thymikee I can do that. Should I create a new issue for this?

**Comment by thymikee** [comment]
Nah, let's add this list here and I can keep it updated :)

**Comment by theweavrs** [comment]
@thymikee what's the status of this?

**Comment by thymikee** [comment]
Debug logging is still not present in every command. We need to compile a list and let people work on it

**Comment by maciejsimka** [comment]
OK, so here's the list of commands, with the ones having `logger.debug` calls checked.

- [ ] `start`
- [ ] `bundle`
- [ ] `ram-bundle`
- [x] `link`
- [x] `unlink`
- [ ] `install`
- [ ] `uninstall`
- [x] `upgrade`
- [ ] `info`
- [ ] `config`
- [x] `init`
- [ ] `log-ios`
- [x] `run-ios`
- [ ] `log-android`
- [x] `run-android`

**Comment by Esemesek** [comment]
In addition to @maciejsimka list:
- `log-android` and `log-ios` are using `logkitty` to log device logs. We don't need verbose logging there, because they are verbose by default.
- `info` and `config` are very basic and verbose logging there isn't necessary
- `install` and `uninstall` have verbose logging when `linking` happens - I think we don't need more logging there

**Comment by Naturalclar** [comment]
are there any additional logging required for this issue?
the unchecked options are `bundle` and `ram-bundle`, which both leads to `buildBundle` which has loggings.

**Comment by Esemesek** [comment]
@Naturalclar it seems like this issue should be closed. C:
