### ISSUE TITLE
auto linking local module.

### ISSUE THREAD

**Issue by mohankoppuravuri** [react-native-community/cli#962]
## How to update react-native-config.js file dependency entry, in order to autolink a local folder. 
In react-native-community/cli/autolinking.md, they mentioned to update it.
When I run the command 'react-native config', it just prints the content. Can you provide the steps modify it.

**Comment by thymikee** [comment]
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-autolink-a-local-library
