### ISSUE TITLE
Delete apk from emulator or phone if new apk cannot be installed ?

### ISSUE THREAD

**Issue by roshangm1** [react-native-community/cli#970]
## Describe the Feature
When performing react-native run-android, if the same app already exists but with no compatibility, just uninstall the app automatically and install the new app instead of throwing error and requiring manual intervention.

**Comment by szymonrybczak** [comment]
Hm, I tried reproducing this and I cannot replicate this. I believe that this was fixed on Android side. Please feel free to comment if this issue still exists.
