### ISSUE TITLE
Question: is it possible to know when the application is started or reloaded?

### ISSUE THREAD

**Issue by artyorsh** [react-native-community/cli#972]
## Ask your Question

Hi! 

As far as I understand, React Native CLI starts Metro Bundler on `start` command.
I would like to know if it is possible to configure hooks or listeners to know when the application is started or (and) reloaded. Could it be possibly done with `metro.config.js` or `react-native.config.js`?

We're working on UI library and this is needed for us to launch a node script that will perform a job during the build process.

Sorry if it is not the right place for asking

**Comment by artyorsh** [comment]
Seels like [metro.reporter](https://facebook.github.io/metro/docs/en/configuration#reporter) is a good option for this

**Comment by grabbou** [comment]
Yes, that is a way to go. You can pass a path to your custom reporter via terminal flag of `start` command.
