### ISSUE TITLE
Help !! running the App 

### ISSUE THREAD

**Issue by reejarejin** [react-native-community/cli#974]
............
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening clientApp.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/*****/Desktop/clientApp/ios/build/clientApp

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: /Users/*******/Desktop/clientApp/ios/Pods/Target Support Files/Pods-clientApp/Pods-clientApp.debug.xcconfig: unable to open file (in target "clientApp" in project "clientApp") (in target 'clientApp')

Build system information
error: /Users/*****/Desktop/clientApp/ios/Pods/Target Support Files/Pods-clientApp/Pods-clientApp.debug.xcconfig: unable to open file (in target "clientApp" in project "clientApp") (in target 'clientApp')

Build system information
error: /Users/********/Desktop/clientApp/ios/Pods/Target Support Files/Pods-clientApp/Pods-clientApp.debug.xcconfig: unable to open file (in target "clientApp" in project "clientApp") (in target 'clientApp')

Build system information
error: /Users/*******/Desktop/clientApp/ios/Pods/Target Support Files/Pods-clientApp/Pods-clientApp.debug.xcconfig: unable to open file (in target "clientApp" in project "clientApp") (in target 'clientApp')

** BUILD FAILED **

**Comment by thymikee** [comment]
I'm sorry but there's too little information. Please come up with a reproduction we could investigate.
