### ISSUE TITLE
[Feature request] run-ios supports mac catalyst target

### ISSUE THREAD

**Issue by robertying** [react-native-community/cli#998]
## Describe the Feature
Mac Catalyst has already been available for React Native projects since 0.62-rc.

Now I believe we can only build the app using Xcode. Running `react-native run-ios` with `--device` flag does not work, since CLI cannot find any iOS devices.

It would be great if CLI can start to accept Mac device names, such as `My Mac` or the device's name, so we can use command line to invoke the build process.

## Possible Implementations
Update CLI to allow Mac as the target device.

I may be able to look into this and create a pull request when free.

## Related Issues
https://github.com/react-native-community/discussions-and-proposals/issues/131

**Comment by grabbou** [comment]
Great idea. I believe it has to do with the way we get devices from the underlying Xcode script. I haven't looked at it yet, but my idea would be to check whether it returns Mac devices and if not, whether we can pass it a flag to do so. Alternatively, just get Mac devices the other way as a fallback.
